import { useMutation, useQuery } from "@tanstack/react-query";
import { CalendarClock, LockKeyhole, ScrollText, ShieldCheck } from "lucide-react";
import GameLayout from "@/components/layout/GameLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Event = { id: string; type: string; summary: string; createdAt: number };
type Protection = { protection: { vacationMode: boolean; pptActive: boolean; pptUntil: number; raidCooldownRemainingSeconds: number; covertAttemptsInLastHour: number }; rules: { attackCooldownMinutes: number; covertSaturationLimit: number } };
type Events = { events: Event[]; count: number };

export default function StargateOperations() {
  const protection = useQuery<Protection>({ queryKey: ["/api/stargate/protection"], queryFn: async () => (await apiRequest("GET", "/api/stargate/protection")).json() });
  const events = useQuery<Events>({ queryKey: ["/api/stargate/events"], queryFn: async () => (await apiRequest("GET", "/api/stargate/events")).json() });
  const toggle = useMutation({ mutationFn: async (enabled: boolean) => (await apiRequest("POST", "/api/stargate/protection/vacation", { enabled })).json(), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/stargate/protection"] }) });
  if (!protection.data || !events.data) return <GameLayout><div className="p-8 font-rajdhani text-slate-300">Synchronizing operations security...</div></GameLayout>;
  const status = protection.data.protection;
  return <GameLayout><div className="sd-win-command space-y-6 pb-10"><section className="sd-win-window rounded-2xl border border-blue-400/45 bg-[linear-gradient(135deg,rgba(7,28,61,0.95),rgba(20,92,168,0.92))] p-6"><div className="flex items-center gap-2 text-cyan-200"><ShieldCheck className="h-5 w-5" /><span className="font-mono text-xs uppercase tracking-[0.28em]">Operational Integrity Console</span></div><h1 className="mt-2 font-orbitron text-3xl font-bold text-white">Protection & Operations</h1><p className="mt-2 font-rajdhani text-blue-100">Monitor protection status, control vacation mode, review action cooldowns, and inspect every persisted system event.</p></section><section className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><Card className="sd-win-window border-blue-300/70 bg-white/90"><CardHeader><CardTitle className="font-orbitron">Protection State</CardTitle><CardDescription>Protection is enforced before strategic actions become publicly competitive.</CardDescription></CardHeader><CardContent className="space-y-4"><Status icon={CalendarClock} label="Vacation Mode" value={status.vacationMode ? "Enabled" : "Disabled"} /><Status icon={LockKeyhole} label="Player Protection" value={status.pptActive ? "Active" : "Inactive"} /><Status icon={ShieldCheck} label="Raid Cooldown" value={`${status.raidCooldownRemainingSeconds}s remaining`} /><Status icon={ScrollText} label="Covert Attempts" value={`${status.covertAttemptsInLastHour}/${protection.data.rules.covertSaturationLimit} per hour`} /><Button disabled={toggle.isPending} variant={status.vacationMode ? "outline" : "default"} onClick={() => toggle.mutate(!status.vacationMode)}>{status.vacationMode ? "Disable Vacation Mode" : "Enable Vacation Mode"}</Button></CardContent></Card><Card className="sd-win-window border-blue-300/70 bg-white/90"><CardHeader><CardTitle className="font-orbitron">Event & Report Stream</CardTitle><CardDescription>{events.data.count} retained strategic system events.</CardDescription></CardHeader><CardContent><div className="space-y-3">{events.data.events.length ? events.data.events.map((event) => <div key={event.id} className="rounded-xl border border-blue-100 bg-blue-50/60 p-3"><div className="flex justify-between gap-3"><div className="font-semibold text-slate-800">{event.summary}</div><div className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}</div></div><div className="mt-1 font-mono text-xs text-blue-700">{event.type}</div></div>) : <div className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">No system events recorded. Submit strategic orders to populate the operational log.</div>}</div></CardContent></Card></section></div></GameLayout>;
}
function Status({ icon: Icon, label, value }: { icon: typeof ShieldCheck; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-lg bg-blue-50 p-3"><Icon className="h-5 w-5 text-blue-700" /><div><div className="text-xs text-slate-500">{label}</div><div className="font-semibold text-slate-800">{value}</div></div></div>; }
