import React, { useState } from 'react';
import {
  Scroll,
  Plus,
  Search,
  Filter,
  Download,
  Calendar,
  Globe,
  Zap,
  Crown,
  Swords,
  ShieldAlert,
  Sparkles,
  CheckCircle2,
  X,
  Copy,
  Check,
  Tag,
  Trash2,
  Layers,
  FileText,
  Clock,
  User,
  Compass,
} from 'lucide-react';
import {
  EmpireHistoryEvent,
  EmpireHistoryCategory,
  EmpireHistorySignificance,
  EmpireHistoryImpact,
} from '../../../types';
import {
  getAllEmpireHistoryEvents,
  saveCustomHistoryEvent,
  deleteCustomHistoryEvent,
} from '../../../data/empireHistoryData';
import { sound } from '../../../sound';

interface AdminEmpireHistoryTabProps {
  adminUsername?: string;
}

export const AdminEmpireHistoryTab: React.FC<AdminEmpireHistoryTabProps> = ({
  adminUsername = 'SystemsRoot_Admin',
}) => {
  const [eventsList, setEventsList] = useState<EmpireHistoryEvent[]>(getAllEmpireHistoryEvents);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [categoryFilter, setCategoryFilter] = useState<string>('all');
  const [significanceFilter, setSignificanceFilter] = useState<string>('all');
  const [selectedEvent, setSelectedEvent] = useState<EmpireHistoryEvent | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // Form State for Log New Historical Event
  const [showAddModal, setShowAddModal] = useState<boolean>(false);
  const [newTitle, setNewTitle] = useState<string>('');
  const [newCategory, setNewCategory] = useState<EmpireHistoryCategory>('colony_establishment');
  const [newSignificance, setNewSignificance] = useState<EmpireHistorySignificance>('major');
  const [newStardate, setNewStardate] = useState<string>(`SD-${new Date().toISOString().slice(0, 10)}-X01`);
  const [newCoordinates, setNewCoordinates] = useState<string>('[1:204:6]');
  const [newDescription, setNewDescription] = useState<string>('');
  const [newTagsInput, setNewTagsInput] = useState<string>('Colony, Sector Conquest, Imperial');
  const [impactList, setImpactList] = useState<EmpireHistoryImpact[]>([
    { label: 'Territory Gained', value: '1 Planet' },
    { label: 'Resource Yield', value: '+10,000 / Turn' },
  ]);

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(label);
    sound.play('confirm');
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleAddImpactRow = () => {
    setImpactList([...impactList, { label: 'Metric', value: '+10%' }]);
  };

  const handleRemoveImpactRow = (index: number) => {
    setImpactList(impactList.filter((_, i) => i !== index));
  };

  const handleUpdateImpactRow = (index: number, key: 'label' | 'value', val: string) => {
    const updated = [...impactList];
    updated[index][key] = val;
    setImpactList(updated);
  };

  const handleCreateEvent = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim() || !newDescription.trim()) return;

    const parsedTags = newTagsInput
      .split(',')
      .map((t) => t.trim())
      .filter((t) => t.length > 0);

    const newEvt: EmpireHistoryEvent = {
      id: `hist_custom_${Date.now()}`,
      timestamp: new Date().toISOString(),
      stardate: newStardate.trim() || `SD-${Date.now()}`,
      title: newTitle.trim(),
      category: newCategory,
      significance: newSignificance,
      rulerName: adminUsername,
      rulerRole: 'Systems Root Admin',
      coordinates: newCoordinates.trim() || undefined,
      description: newDescription.trim(),
      impacts: impactList.filter((i) => i.label.trim() && i.value.trim()),
      tags: parsedTags.length > 0 ? parsedTags : ['Admin Log'],
      isCustomAdminEntry: true,
    };

    saveCustomHistoryEvent(newEvt);
    setEventsList([newEvt, ...eventsList]);
    setSelectedEvent(newEvt);
    setNewTitle('');
    setNewDescription('');
    setShowAddModal(false);
    sound.play('confirm');
  };

  const handleDeleteEvent = (id: string) => {
    sound.play('warning');
    deleteCustomHistoryEvent(id);
    setEventsList(eventsList.filter((e) => e.id !== id));
    if (selectedEvent?.id === id) {
      setSelectedEvent(null);
    }
  };

  const handleExportJSON = () => {
    sound.play('confirm');
    const jsonStr = JSON.stringify(eventsList, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `empire_history_chronicle_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    sound.play('confirm');
    let md = `# Imperial Empire History Chronicle\n\n`;
    md += `*Generated by Sovereign Admin Systems (${adminUsername}) on ${new Date().toUTCString()}*\n\n`;
    md += `---\n\n`;

    filteredEvents.forEach((evt) => {
      md += `### ${evt.stardate} — ${evt.title}\n`;
      md += `**Category**: ${evt.category.toUpperCase()} | **Significance**: ${evt.significance.toUpperCase()}\n`;
      if (evt.coordinates) md += `**Coordinates**: \`${evt.coordinates}\`\n`;
      md += `**Recorded By**: ${evt.rulerName} (${evt.rulerRole || 'Ruler'})\n\n`;
      md += `${evt.description}\n\n`;
      if (evt.impacts.length > 0) {
        md += `**Key Historical Impacts**:\n`;
        evt.impacts.forEach((imp) => {
          md += `- **${imp.label}**: ${imp.value}\n`;
        });
        md += `\n`;
      }
      md += `---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `empire_history_chronicle_${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Filter Logic
  const filteredEvents = eventsList.filter((evt) => {
    const matchesCategory = categoryFilter === 'all' || evt.category === categoryFilter;
    const matchesSignificance = significanceFilter === 'all' || evt.significance === significanceFilter;
    const q = searchQuery.toLowerCase().trim();
    const matchesQuery =
      !q ||
      evt.title.toLowerCase().includes(q) ||
      evt.description.toLowerCase().includes(q) ||
      evt.rulerName.toLowerCase().includes(q) ||
      evt.stardate.toLowerCase().includes(q) ||
      (evt.coordinates && evt.coordinates.toLowerCase().includes(q)) ||
      evt.tags.some((t) => t.toLowerCase().includes(q));

    return matchesCategory && matchesSignificance && matchesQuery;
  });

  const getCategoryIcon = (cat: EmpireHistoryCategory) => {
    switch (cat) {
      case 'colony_establishment':
        return <Globe className="w-4 h-4 text-emerald-400" />;
      case 'tech_breakthrough':
        return <Zap className="w-4 h-4 text-sky-400" />;
      case 'imperial_decree':
        return <Crown className="w-4 h-4 text-amber-400" />;
      case 'galactic_battle':
        return <Swords className="w-4 h-4 text-red-400" />;
      case 'admin_directive':
        return <ShieldAlert className="w-4 h-4 text-purple-400" />;
      case 'ascension_milestone':
        return <Sparkles className="w-4 h-4 text-yellow-300" />;
      default:
        return <Scroll className="w-4 h-4 text-slate-400" />;
    }
  };

  const getCategoryLabel = (cat: EmpireHistoryCategory) => {
    switch (cat) {
      case 'colony_establishment':
        return 'Colony Establishment';
      case 'tech_breakthrough':
        return 'Tech Breakthrough';
      case 'imperial_decree':
        return 'Imperial Decree';
      case 'galactic_battle':
        return 'Galactic Battle';
      case 'admin_directive':
        return 'Admin Directive';
      case 'ascension_milestone':
        return 'Ascension Milestone';
      default:
        return 'Chronicle Entry';
    }
  };

  const getSignificanceBadge = (sig: EmpireHistorySignificance) => {
    switch (sig) {
      case 'epoch_defining':
        return (
          <span className="px-2 py-0.5 bg-amber-500/20 border border-amber-500/40 text-amber-300 font-bold uppercase text-[9px]">
            EPOCH-DEFINING
          </span>
        );
      case 'major':
        return (
          <span className="px-2 py-0.5 bg-sky-500/20 border border-sky-500/40 text-sky-300 font-bold uppercase text-[9px]">
            MAJOR EVENT
          </span>
        );
      default:
        return (
          <span className="px-2 py-0.5 bg-slate-800 border border-slate-700 text-slate-400 font-bold uppercase text-[9px]">
            ROUTINE RECORD
          </span>
        );
    }
  };

  // Metrics Summary
  const countColonies = eventsList.filter((e) => e.category === 'colony_establishment').length;
  const countTechs = eventsList.filter((e) => e.category === 'tech_breakthrough').length;
  const countDecrees = eventsList.filter((e) => e.category === 'imperial_decree').length;
  const countBattles = eventsList.filter((e) => e.category === 'galactic_battle').length;

  return (
    <div className="space-y-6 font-mono text-slate-100" id="admin-empire-history-view">
      {/* Header Banner */}
      <div className="p-5 bg-slate-900 border-2 border-slate-700 shadow-xl flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2 py-0.5 bg-amber-500/20 border border-amber-500/40 text-amber-300 text-[10px] font-bold uppercase tracking-widest">
              SOVEREIGN HISTORICAL MATRIX
            </span>
            <span className="text-slate-400 text-xs">Logged by {adminUsername}</span>
          </div>
          <h2 className="text-xl font-black text-white uppercase flex items-center gap-2">
            <Scroll className="w-6 h-6 text-amber-400" />
            <span>Empire History & Historical Chronicle Systems</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1 max-w-3xl leading-relaxed">
            Complete scrollable archive of major empire-wide milestones: colonial world establishments, quantum technological breakthroughs, past imperial crown decrees, and pivotal space combats across stardates.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2 shrink-0">
          <button
            onClick={() => {
              sound.play('click');
              setShowAddModal(true);
            }}
            className="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold uppercase text-xs transition-all flex items-center gap-2 cursor-pointer shadow-md"
          >
            <Plus className="w-4 h-4" />
            <span>Log Historical Event</span>
          </button>

          <button
            onClick={handleExportJSON}
            className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-600 font-bold uppercase text-xs transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-sky-400" />
            <span>JSON</span>
          </button>

          <button
            onClick={handleExportMarkdown}
            className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-600 font-bold uppercase text-xs transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <FileText className="w-3.5 h-3.5 text-amber-400" />
            <span>Markdown Log</span>
          </button>
        </div>
      </div>

      {/* Overview Stat Counters (Unboxed Clean Metadata Layout) */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="p-3 bg-slate-950 border border-slate-800">
          <div className="text-[10px] text-slate-500 uppercase font-bold flex items-center gap-1.5">
            <Globe className="w-3.5 h-3.5 text-emerald-400" />
            <span>Colonies Established</span>
          </div>
          <div className="text-lg font-black text-emerald-400 tabular-nums mt-0.5">{countColonies} Worlds</div>
        </div>

        <div className="p-3 bg-slate-950 border border-slate-800">
          <div className="text-[10px] text-slate-500 uppercase font-bold flex items-center gap-1.5">
            <Zap className="w-3.5 h-3.5 text-sky-400" />
            <span>Tech Breakthroughs</span>
          </div>
          <div className="text-lg font-black text-sky-400 tabular-nums mt-0.5">{countTechs} Unlocked</div>
        </div>

        <div className="p-3 bg-slate-950 border border-slate-800">
          <div className="text-[10px] text-slate-500 uppercase font-bold flex items-center gap-1.5">
            <Crown className="w-3.5 h-3.5 text-amber-400" />
            <span>Imperial Decrees</span>
          </div>
          <div className="text-lg font-black text-amber-400 tabular-nums mt-0.5">{countDecrees} Issued</div>
        </div>

        <div className="p-3 bg-slate-950 border border-slate-800">
          <div className="text-[10px] text-slate-500 uppercase font-bold flex items-center gap-1.5">
            <Swords className="w-3.5 h-3.5 text-red-400" />
            <span>Space Encounters</span>
          </div>
          <div className="text-lg font-black text-red-400 tabular-nums mt-0.5">{countBattles} Victories</div>
        </div>
      </div>

      {/* Search & Filter Controls Bar */}
      <div className="p-4 bg-slate-950 border border-slate-800 space-y-3">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {/* Search Bar */}
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by title, stardate, ruler, coords, tag..."
              className="w-full bg-slate-900 border border-slate-700 pl-9 pr-3 py-1.5 text-xs text-slate-100 placeholder-slate-500 focus:border-amber-500 outline-none"
            />
          </div>

          {/* Category Filter */}
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-slate-500 shrink-0" />
            <select
              value={categoryFilter}
              onChange={(e) => {
                sound.play('click');
                setCategoryFilter(e.target.value);
              }}
              className="w-full bg-slate-900 border border-slate-700 px-3 py-1.5 text-xs text-slate-100 focus:border-amber-500 outline-none cursor-pointer"
            >
              <option value="all">All Categories ({eventsList.length})</option>
              <option value="colony_establishment">Colony Establishments ({countColonies})</option>
              <option value="tech_breakthrough">Tech Breakthroughs ({countTechs})</option>
              <option value="imperial_decree">Imperial Decrees ({countDecrees})</option>
              <option value="galactic_battle">Galactic Battles ({countBattles})</option>
              <option value="admin_directive">Admin Directives</option>
              <option value="ascension_milestone">Ascension Milestones</option>
            </select>
          </div>

          {/* Significance Filter */}
          <div className="flex items-center gap-2">
            <Layers className="w-4 h-4 text-slate-500 shrink-0" />
            <select
              value={significanceFilter}
              onChange={(e) => {
                sound.play('click');
                setSignificanceFilter(e.target.value);
              }}
              className="w-full bg-slate-900 border border-slate-700 px-3 py-1.5 text-xs text-slate-100 focus:border-amber-500 outline-none cursor-pointer"
            >
              <option value="all">All Significance Levels</option>
              <option value="epoch_defining">Epoch-Defining Only</option>
              <option value="major">Major Events Only</option>
              <option value="routine">Routine Records Only</option>
            </select>
          </div>
        </div>

        {/* Clean Filter Chips (Functional Button Controls) */}
        <div className="flex items-center gap-2 pt-1 overflow-x-auto text-xs">
          <span className="text-[10px] text-slate-500 uppercase font-bold shrink-0">Quick Filter:</span>
          {[
            { id: 'all', label: 'All Records' },
            { id: 'colony_establishment', label: '🌍 Colony' },
            { id: 'tech_breakthrough', label: '⚡ Tech' },
            { id: 'imperial_decree', label: '👑 Decrees' },
            { id: 'galactic_battle', label: '⚔️ Battles' },
            { id: 'admin_directive', label: '🛡️ Admin' },
          ].map((tab) => {
            const isActive = categoryFilter === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => {
                  sound.play('click');
                  setCategoryFilter(tab.id);
                }}
                className={`px-3 py-1 text-xs font-bold transition-all cursor-pointer whitespace-nowrap shrink-0 ${
                  isActive
                    ? 'bg-amber-500 text-slate-950 shadow-sm'
                    : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
                }`}
              >
                {tab.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Scrollable Timeline Log */}
      <div className="p-5 bg-slate-950 border border-slate-800 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2 text-slate-300">
            <Scroll className="w-4 h-4 text-amber-400" />
            <span className="font-extrabold uppercase text-xs">
              Chronicle Event Stream ({filteredEvents.length} Matched Entries)
            </span>
          </div>

          <span className="text-[10px] text-slate-500">
            Ordered by Stardate Recency
          </span>
        </div>

        {filteredEvents.length === 0 ? (
          <div className="p-12 text-center text-slate-500 space-y-2 border border-dashed border-slate-800">
            <Scroll className="w-8 h-8 mx-auto text-slate-600" />
            <p className="text-xs font-bold uppercase">No historical chronicle events match filter criteria.</p>
            <p className="text-[11px] text-slate-600">Try clearing your search query or selecting 'All Categories'.</p>
          </div>
        ) : (
          <div className="space-y-4 relative before:absolute before:left-6 before:top-3 before:bottom-3 before:w-0.5 before:bg-slate-800">
            {filteredEvents.map((evt) => {
              const isSelected = selectedEvent?.id === evt.id;
              return (
                <div
                  key={evt.id}
                  onClick={() => {
                    sound.play('click');
                    setSelectedEvent(evt);
                  }}
                  className={`relative pl-12 p-4 border transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-slate-900 border-amber-500/80 shadow-lg ring-1 ring-amber-500/30'
                      : 'bg-slate-900/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900'
                  }`}
                >
                  {/* Timeline Marker Icon */}
                  <div className="absolute left-3 top-4 w-6 h-6 rounded-full bg-slate-950 border border-slate-700 flex items-center justify-center shrink-0 z-10">
                    {getCategoryIcon(evt.category)}
                  </div>

                  {/* Top Metadata Line (Clean unboxed text with · separators) */}
                  <div className="flex flex-wrap items-center justify-between gap-2 text-[11px] mb-1.5">
                    <div className="flex items-center gap-2 text-slate-400">
                      <span className="font-bold text-amber-400 font-mono">{evt.stardate}</span>
                      <span aria-hidden="true">·</span>
                      <span className="text-slate-300 font-bold">{getCategoryLabel(evt.category)}</span>
                      {evt.coordinates && (
                        <>
                          <span aria-hidden="true">·</span>
                          <span className="text-sky-300 font-bold">{evt.coordinates}</span>
                        </>
                      )}
                      <span aria-hidden="true">·</span>
                      <span className="text-slate-400 flex items-center gap-1">
                        <User className="w-3 h-3 text-slate-500" />
                        {evt.rulerName}
                      </span>
                    </div>

                    <div className="flex items-center gap-2">
                      {getSignificanceBadge(evt.significance)}
                      {evt.isCustomAdminEntry && (
                        <span className="px-1.5 py-0.5 bg-purple-500/20 text-purple-300 border border-purple-500/40 text-[9px] uppercase font-bold">
                          Admin Injected
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Title & Description */}
                  <h3 className="text-sm font-bold text-white mb-1">{evt.title}</h3>
                  <p className="text-xs text-slate-300 leading-relaxed mb-3">{evt.description}</p>

                  {/* Impact Highlights Grid */}
                  {evt.impacts && evt.impacts.length > 0 && (
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 p-2.5 bg-slate-950 border border-slate-800/80 mb-3 text-[11px]">
                      {evt.impacts.map((imp, idx) => (
                        <div key={idx} className="flex items-center justify-between gap-1">
                          <span className="text-slate-500">{imp.label}:</span>
                          <span className="text-emerald-400 font-bold font-mono">{imp.value}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Bottom Tags & Controls */}
                  <div className="flex items-center justify-between text-[10px]">
                    <div className="flex flex-wrap items-center gap-1.5">
                      {evt.tags.map((tag, tIdx) => (
                        <span key={tIdx} className="text-slate-500 text-[10px]">
                          #{tag}
                        </span>
                      ))}
                    </div>

                    {evt.isCustomAdminEntry && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDeleteEvent(evt.id);
                        }}
                        className="text-red-400 hover:text-red-300 flex items-center gap-1 text-[10px] cursor-pointer"
                      >
                        <Trash2 className="w-3 h-3" />
                        <span>Delete Record</span>
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Selected Event Detail Inspection Modal */}
      {selectedEvent && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="w-full max-w-2xl bg-slate-900 border-2 border-slate-700 text-slate-100 shadow-2xl overflow-hidden font-mono text-xs">
            <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                {getCategoryIcon(selectedEvent.category)}
                <span className="font-bold text-white uppercase text-sm">{selectedEvent.title}</span>
              </div>
              <button
                onClick={() => {
                  sound.play('click');
                  setSelectedEvent(null);
                }}
                className="p-1 bg-slate-800 text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
              <div className="p-3 bg-slate-950 border border-slate-800 flex flex-wrap items-center justify-between gap-2 text-[11px]">
                <div>Stardate: <strong className="text-amber-400">{selectedEvent.stardate}</strong></div>
                <div>Category: <strong className="text-sky-300">{getCategoryLabel(selectedEvent.category)}</strong></div>
                {selectedEvent.coordinates && <div>Location: <strong className="text-emerald-400">{selectedEvent.coordinates}</strong></div>}
                <div>Recorded By: <strong className="text-slate-200">{selectedEvent.rulerName}</strong></div>
              </div>

              <div>
                <label className="text-[10px] text-slate-500 font-bold uppercase block mb-1">Historical Account:</label>
                <p className="text-xs text-slate-200 leading-relaxed bg-slate-950 p-3 border border-slate-800">
                  {selectedEvent.description}
                </p>
              </div>

              {selectedEvent.impacts.length > 0 && (
                <div>
                  <label className="text-[10px] text-slate-500 font-bold uppercase block mb-1">Impact Metrics:</label>
                  <div className="grid grid-cols-2 gap-2">
                    {selectedEvent.impacts.map((imp, idx) => (
                      <div key={idx} className="p-2 bg-slate-950 border border-slate-800 flex justify-between">
                        <span className="text-slate-400">{imp.label}</span>
                        <span className="text-emerald-400 font-bold">{imp.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex justify-between items-center pt-2 border-t border-slate-800 text-[10px]">
                <span className="text-slate-500">Timestamp: {new Date(selectedEvent.timestamp).toUTCString()}</span>
                <button
                  onClick={() => handleCopy(JSON.stringify(selectedEvent, null, 2), 'modal-json')}
                  className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-600 flex items-center gap-1.5 cursor-pointer"
                >
                  {copiedKey === 'modal-json' ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                  <span>{copiedKey === 'modal-json' ? 'Copied JSON' : 'Copy Event JSON'}</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Log New Historical Event Modal (Admin Logger) */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="w-full max-w-2xl bg-slate-900 border-2 border-slate-700 text-slate-100 shadow-2xl overflow-hidden font-mono text-xs">
            <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Plus className="w-5 h-5 text-emerald-400" />
                <h3 className="font-black text-white uppercase text-sm">Log New Historical Empire Event</h3>
              </div>
              <button
                onClick={() => {
                  sound.play('click');
                  setShowAddModal(false);
                }}
                className="p-1 bg-slate-800 text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateEvent} className="p-6 space-y-4 max-h-[80vh] overflow-y-auto">
              <div>
                <label className="text-[10px] text-slate-400 block mb-1">Event Title *</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  required
                  placeholder="e.g. Conquest of Sector 884 & Subspace Nexus Deployment"
                  className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div>
                  <label className="text-[10px] text-slate-400 block mb-1">Category</label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value as EmpireHistoryCategory)}
                    className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                  >
                    <option value="colony_establishment">Colony Establishment</option>
                    <option value="tech_breakthrough">Tech Breakthrough</option>
                    <option value="imperial_decree">Imperial Decree</option>
                    <option value="galactic_battle">Galactic Battle</option>
                    <option value="admin_directive">Admin Directive</option>
                    <option value="ascension_milestone">Ascension Milestone</option>
                  </select>
                </div>

                <div>
                  <label className="text-[10px] text-slate-400 block mb-1">Significance Level</label>
                  <select
                    value={newSignificance}
                    onChange={(e) => setNewSignificance(e.target.value as EmpireHistorySignificance)}
                    className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                  >
                    <option value="epoch_defining">Epoch-Defining</option>
                    <option value="major">Major Event</option>
                    <option value="routine">Routine Record</option>
                  </select>
                </div>

                <div>
                  <label className="text-[10px] text-slate-400 block mb-1">Stardate Identifier</label>
                  <input
                    type="text"
                    value={newStardate}
                    onChange={(e) => setNewStardate(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="text-[10px] text-slate-400 block mb-1">Sector Coordinates (Optional)</label>
                <input
                  type="text"
                  value={newCoordinates}
                  onChange={(e) => setNewCoordinates(e.target.value)}
                  placeholder="e.g. [1:204:6]"
                  className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                />
              </div>

              <div>
                <label className="text-[10px] text-slate-400 block mb-1">Event Chronicle Description *</label>
                <textarea
                  rows={4}
                  value={newDescription}
                  onChange={(e) => setNewDescription(e.target.value)}
                  required
                  placeholder="Provide a detailed historical account of the event, strategy employed, or decree enacted..."
                  className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                />
              </div>

              {/* Impact Metric Rows */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-[10px] text-slate-400 uppercase font-bold">Historical Impact Metrics:</label>
                  <button
                    type="button"
                    onClick={handleAddImpactRow}
                    className="text-[10px] text-emerald-400 hover:text-emerald-300 flex items-center gap-1 cursor-pointer"
                  >
                    <Plus className="w-3 h-3" />
                    <span>Add Metric Row</span>
                  </button>
                </div>

                <div className="space-y-2">
                  {impactList.map((imp, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <input
                        type="text"
                        value={imp.label}
                        onChange={(e) => handleUpdateImpactRow(idx, 'label', e.target.value)}
                        placeholder="Label (e.g. Territory)"
                        className="w-1/2 bg-slate-950 border border-slate-700 p-1.5 text-xs text-white outline-none"
                      />
                      <input
                        type="text"
                        value={imp.value}
                        onChange={(e) => handleUpdateImpactRow(idx, 'value', e.target.value)}
                        placeholder="Value (e.g. +15 Worlds)"
                        className="w-1/2 bg-slate-950 border border-slate-700 p-1.5 text-xs text-white outline-none"
                      />
                      <button
                        type="button"
                        onClick={() => handleRemoveImpactRow(idx)}
                        className="p-1.5 text-red-400 hover:bg-slate-800 cursor-pointer"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <label className="text-[10px] text-slate-400 block mb-1">Tags (Comma Separated)</label>
                <input
                  type="text"
                  value={newTagsInput}
                  onChange={(e) => setNewTagsInput(e.target.value)}
                  placeholder="Colony, Sector Conquest, Imperial"
                  className="w-full bg-slate-950 border border-slate-700 p-2 text-xs text-white focus:border-amber-500 outline-none"
                />
              </div>

              <button
                type="submit"
                className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold uppercase transition-all flex items-center justify-center gap-2 cursor-pointer shadow-lg"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>Save to Historical Chronicle</span>
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
