export type AnomalyRarity = "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic";
export type AnomalyStatus = "dormant" | "active" | "collapsed" | "unstable" | "sealed";
export type AnomalyType = "wormhole" | "rift" | "void_portal" | "temporal裂隙" | "nexus" | "gate" | "abyss" | "shard" | "mirror" | "echo";
export type AnomalyRewardType = "resources" | "research" | "technology" | "artifact" | "experience" | "fleet" | "dark_matter" | "relic" | "blueprint";

export interface DimensionalAnomaly {
  id: string;
  name: string;
  description: string;
  type: AnomalyType;
  rarity: AnomalyRarity;
  status: AnomalyStatus;
  dangerLevel: number;
  recommendedPower: number;
  maxExplorers: number;
  respawnTimeHours: number;
  entryCost: { metal?: number; crystal?: number; deuterium?: number; darkMatter?: number };
  rewards: AnomalyReward[];
  lore: string;
  effects: AnomalyEffect[];
  region: string;
}

export interface AnomalyReward {
  type: AnomalyRewardType;
  name: string;
  amount: number;
  chance: number;
}

export interface AnomalyEffect {
  type: string;
  value: number;
  description: string;
}

export const DIMENSIONAL_ANOMALIES: DimensionalAnomaly[] = [
  // === REGION: Core Systems (1-15) ===
  { id: "dg-001", name: "Fading Wormhole Alpha", description: "A weak but stable wormhole near the home system. Perfect for beginners.", type: "wormhole", rarity: "common", status: "dormant", dangerLevel: 1, recommendedPower: 100, maxExplorers: 20, respawnTimeHours: 2, entryCost: { metal: 500, crystal: 200 }, rewards: [{ type: "resources", name: "Mixed Resources", amount: 2000, chance: 0.9 }, { type: "experience", name: "Exploration XP", amount: 50, chance: 1 }], lore: "The first wormhole catalogued by the Stellar Cartography Institute. Stability is surprisingly consistent.", effects: [], region: "Core" },
  { id: "dg-002", name: "Crystalline Rift", description: "A rift pulsing with raw crystal energy. Rich in rare minerals.", type: "rift", rarity: "uncommon", status: "dormant", dangerLevel: 3, recommendedPower: 300, maxExplorers: 15, respawnTimeHours: 4, entryCost: { metal: 800, crystal: 400 }, rewards: [{ type: "resources", name: "Crystal Cluster", amount: 5000, chance: 0.85 }, { type: "artifact", name: "Crystal Shard", amount: 1, chance: 0.15 }], lore: "Said to be the tears of a dying god, these crystals hum with an otherworldly resonance.", effects: [{ type: "crystalBonus", value: 0.1, description: "+10% Crystal yield during exploration" }], region: "Core" },
  { id: "dg-003", name: "Quantum Echo Chamber", description: "Echoes of past battles ripple through this dimension. Valuable tactical data.", type: "echo", rarity: "uncommon", status: "dormant", dangerLevel: 4, recommendedPower: 400, maxExplorers: 12, respawnTimeHours: 6, entryCost: { metal: 1000, crystal: 500 }, rewards: [{ type: "research", name: "Tactical Data", amount: 300, chance: 0.8 }, { type: "technology", name: "Combat Protocol Fragment", amount: 1, chance: 0.1 }], lore: "Temporal echoes preserve moments of intense conflict. Study them carefully.", effects: [], region: "Core" },
  { id: "dg-004", name: "Void Pocket Sigma", description: "A pocket of compressed void energy. Dangerous but rewarding.", type: "void_portal", rarity: "rare", status: "dormant", dangerLevel: 6, recommendedPower: 800, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 2000, crystal: 1000, deuterium: 500 }, rewards: [{ type: "resources", name: "Void Essence", amount: 3000, chance: 0.7 }, { type: "dark_matter", name: "Dark Matter", amount: 25, chance: 0.5 }, { type: "artifact", name: "Void Fragment", amount: 1, chance: 0.2 }], lore: "Void pockets are tears in spacetime that compress matter into exotic forms.", effects: [{ type: "dangerBonus", value: 0.15, description: "+15% danger but +15% reward" }], region: "Core" },
  { id: "dg-005", name: "Temporal Rift Prime", description: "The largest temporal rift in the Core. Time flows differently here.", type: "temporal裂隙", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1000, maxExplorers: 8, respawnTimeHours: 12, entryCost: { metal: 3000, crystal: 1500, deuterium: 800 }, rewards: [{ type: "research", name: "Temporal Research Data", amount: 800, chance: 0.75 }, { type: "technology", name: "Chroniton Theory", amount: 1, chance: 0.2 }, { type: "experience", name: "Temporal XP", amount: 200, chance: 1 }], lore: "Time dilation zones where minutes can equal years. The research potential is immense.", effects: [{ type: "timeWarp", value: 2, description: "2x research speed while exploring" }], region: "Core" },
  { id: "dg-006", name: "Nexus Gateway Epsilon", description: "A nexus point connecting multiple dimensions. Highly strategic.", type: "nexus", rarity: "epic", status: "dormant", dangerLevel: 8, recommendedPower: 1500, maxExplorers: 6, respawnTimeHours: 16, entryCost: { metal: 5000, crystal: 3000, deuterium: 1500 }, rewards: [{ type: "technology", name: "Nexus Navigation Data", amount: 1, chance: 0.6 }, { type: "relic", name: "Nexus Key", amount: 1, chance: 0.3 }, { type: "dark_matter", name: "Dark Matter", amount: 50, chance: 0.4 }], lore: "Nexus points are the crossroads of dimensions. Control one, and you control the flow.", effects: [{ type: "multiDimension", value: 3, description: "Access 3 dimensional paths" }], region: "Core" },
  { id: "dg-007", name: "Shattered Gate Fragment", description: "Remains of an ancient gate. The technology could be reverse-engineered.", type: "gate", rarity: "uncommon", status: "collapsed", dangerLevel: 2, recommendedPower: 200, maxExplorers: 25, respawnTimeHours: 3, entryCost: { metal: 600, crystal: 300 }, rewards: [{ type: "blueprint", name: "Gate Blueprint Fragment", amount: 1, chance: 0.25 }, { type: "resources", name: "Ancient Materials", amount: 1500, chance: 0.8 }], lore: "The Ancients built gates that spanned galaxies. Their fragments still hold power.", effects: [], region: "Core" },
  { id: "dg-008", name: "Abyssal Deep", description: "An abyss that seems to have no bottom. What lurks below?", type: "abyss", rarity: "rare", status: "unstable", dangerLevel: 9, recommendedPower: 2000, maxExplorers: 5, respawnTimeHours: 20, entryCost: { metal: 4000, crystal: 2000, deuterium: 1000 }, rewards: [{ type: "artifact", name: "Abyssal Relic", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 75, chance: 0.5 }, { type: "fleet", name: "Lost Fleet Coordinates", amount: 1, chance: 0.15 }], lore: "Sensors detect no bottom. Some say it connects to the space between dimensions.", effects: [{ type: "fogOfWar", value: 1, description: "Reduced sensor range during exploration" }], region: "Core" },
  { id: "dg-009", name: "Mirror Dimension Gate", description: "A gate leading to a mirror image of our universe.", type: "mirror", rarity: "epic", status: "active", dangerLevel: 8, recommendedPower: 1800, maxExplorers: 6, respawnTimeHours: 24, entryCost: { metal: 6000, crystal: 3500, deuterium: 2000 }, rewards: [{ type: "technology", name: "Mirror Physics Data", amount: 1, chance: 0.5 }, { type: "relic", name: "Mirror Shard", amount: 1, chance: 0.35 }, { type: "experience", name: "Dimensional XP", amount: 500, chance: 1 }], lore: "In the mirror dimension, everything is reversed. Even the laws of physics.", effects: [{ type: "mirrorBonus", value: 0.2, description: "+20% all rewards in mirror dimension" }], region: "Core" },
  { id: "dg-010", name: "Wormhole Cluster Delta", description: "Multiple interconnected wormholes. Navigate carefully.", type: "wormhole", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 900, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2500, crystal: 1200, deuterium: 600 }, rewards: [{ type: "resources", name: "Multi-Dimensional Resources", amount: 8000, chance: 0.8 }, { type: "research", name: "Wormhole Navigation Data", amount: 500, chance: 0.6 }], lore: "Wormhole clusters are gravitational anomalies that link multiple points in spacetime.", effects: [{ type: "wormholeHop", value: 3, description: "Can hop between 3 connected wormholes" }], region: "Core" },
  { id: "dg-011", name: "Energy Siphon Rift", description: "A rift that siphons energy from nearby ships. Risky but profitable.", type: "rift", rarity: "uncommon", status: "active", dangerLevel: 5, recommendedPower: 500, maxExplorers: 12, respawnTimeHours: 5, entryCost: { metal: 1200, crystal: 600, deuterium: 300 }, rewards: [{ type: "resources", name: "Siphoned Energy", amount: 4000, chance: 0.75 }, { type: "dark_matter", name: "Dark Matter", amount: 10, chance: 0.3 }], lore: "These rifts feed on nearby energy sources. Enter at your own risk.", effects: [{ type: "energyDrain", value: 0.05, description: "-5% fleet energy per turn in range" }], region: "Core" },
  { id: "dg-012", name: "Ancient Observatory Portal", description: "A portal to an ancient observation post. The data within is priceless.", type: "gate", rarity: "epic", status: "sealed", dangerLevel: 7, recommendedPower: 1200, maxExplorers: 8, respawnTimeHours: 30, entryCost: { metal: 4500, crystal: 2500, deuterium: 1200 }, rewards: [{ type: "technology", name: "Ancient Star Charts", amount: 1, chance: 0.65 }, { type: "relic", name: "Observatory Lens", amount: 1, chance: 0.25 }, { type: "research", name: "Astronomical Data", amount: 1000, chance: 0.8 }], lore: "The Ancients mapped the entire galaxy from this single vantage point.", effects: [{ type: "scannerBoost", value: 0.3, description: "+30% scanner range for 24h" }], region: "Core" },
  { id: "dg-013", name: "Plasma Vein Anomaly", description: "A vein of pure plasma energy flowing between dimensions.", type: "shard", rarity: "common", status: "active", dangerLevel: 2, recommendedPower: 250, maxExplorers: 18, respawnTimeHours: 3, entryCost: { metal: 700, crystal: 350 }, rewards: [{ type: "resources", name: "Plasma Core", amount: 2500, chance: 0.85 }, { type: "experience", name: "Energy XP", amount: 40, chance: 1 }], lore: "Plasma veins are the circulatory system of the cosmos.", effects: [], region: "Core" },
  { id: "dg-014", name: "Dimensional Lock Gate", description: "A heavily locked gate. Requires significant resources to open.", type: "gate", rarity: "legendary", status: "sealed", dangerLevel: 10, recommendedPower: 3000, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 10000, crystal: 6000, deuterium: 3000, darkMatter: 100 }, rewards: [{ type: "technology", name: "Dimensional Lock Theory", amount: 1, chance: 0.7 }, { type: "relic", name: "Master Key", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 200, chance: 0.6 }], lore: "Only the most advanced empires can afford to breach these locks.", effects: [{ type: "techUnlock", value: 1, description: "Unlocks advanced dimensional technology" }], region: "Core" },
  { id: "dg-015", name: "Resonance Echo Field", description: "A field of resonating echoes. The harmonics reveal hidden truths.", type: "echo", rarity: "uncommon", status: "active", dangerLevel: 3, recommendedPower: 350, maxExplorers: 14, respawnTimeHours: 4, entryCost: { metal: 900, crystal: 450 }, rewards: [{ type: "research", name: "Resonance Data", amount: 400, chance: 0.75 }, { type: "experience", name: "Harmonic XP", amount: 60, chance: 1 }], lore: "Every sound in the universe leaves an echo. Listen closely.", effects: [{ type: "researchBonus", value: 0.05, description: "+5% research speed for 12h" }], region: "Core" },

  // === REGION: Outer Rim (16-30) ===
  { id: "dg-016", name: "Rim Wormhole Kappa", description: "A wormhole on the edge of explored space. Unknown what lies beyond.", type: "wormhole", rarity: "uncommon", status: "dormant", dangerLevel: 5, recommendedPower: 600, maxExplorers: 12, respawnTimeHours: 6, entryCost: { metal: 1500, crystal: 800, deuterium: 400 }, rewards: [{ type: "resources", name: "Rim Resources", amount: 4500, chance: 0.8 }, { type: "research", name: "Frontier Data", amount: 350, chance: 0.6 }], lore: "The outer rim hides secrets that the core systems have long forgotten.", effects: [], region: "Outer Rim" },
  { id: "dg-017", name: "Void Shard Cluster", description: "A cluster of void shards radiating dark energy.", type: "shard", rarity: "rare", status: "unstable", dangerLevel: 7, recommendedPower: 1100, maxExplorers: 8, respawnTimeHours: 10, entryCost: { metal: 2800, crystal: 1400, deuterium: 700 }, rewards: [{ type: "dark_matter", name: "Void Shards", amount: 40, chance: 0.6 }, { type: "artifact", name: "Void Crystal", amount: 1, chance: 0.25 }, { type: "resources", name: "Dark Energy", amount: 5000, chance: 0.7 }], lore: "Void shards are remnants of collapsed dimensions. Handle with extreme care.", effects: [{ type: "darkResonance", value: 0.1, description: "+10% dark matter yield" }], region: "Outer Rim" },
  { id: "dg-018", name: "Collapsed Nexus Zeta", description: "A nexus that collapsed long ago. Its debris holds great power.", type: "nexus", rarity: "rare", status: "collapsed", dangerLevel: 6, recommendedPower: 900, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 2200, crystal: 1100, deuterium: 550 }, rewards: [{ type: "technology", name: "Nexus Engineering Data", amount: 1, chance: 0.35 }, { type: "resources", name: "Nexus Debris", amount: 6000, chance: 0.8 }, { type: "blueprint", name: "Nexus Stabilizer", amount: 1, chance: 0.15 }], lore: "Collapsed nexuses scatter dimensional energy across lightyears.", effects: [{ type: "debrisField", value: 1, description: "Salvage bonus from debris" }], region: "Outer Rim" },
  { id: "dg-019", name: "Temporal Cascade Gate", description: "A gate where time cascades forward and backward unpredictably.", type: "temporal裂隙", rarity: "epic", status: "unstable", dangerLevel: 9, recommendedPower: 2200, maxExplorers: 5, respawnTimeHours: 20, entryCost: { metal: 5500, crystal: 3000, deuterium: 1500 }, rewards: [{ type: "research", name: "Temporal Cascade Data", amount: 1200, chance: 0.7 }, { type: "technology", name: "Time Manipulation Theory", amount: 1, chance: 0.3 }, { type: "relic", name: "Temporal Crystal", amount: 1, chance: 0.2 }], lore: "Temporal cascades are the universe's way of correcting paradoxes.", effects: [{ type: "timeRift", value: 0.1, description: "10% chance to skip build time" }], region: "Outer Rim" },
  { id: "dg-020", name: "Graviton Well", description: "A gravitational anomaly that bends light and space itself.", type: "abyss", rarity: "rare", status: "active", dangerLevel: 8, recommendedPower: 1600, maxExplorers: 6, respawnTimeHours: 14, entryCost: { metal: 3500, crystal: 2000, deuterium: 1000 }, rewards: [{ type: "resources", name: "Graviton Energy", amount: 7000, chance: 0.75 }, { type: "artifact", name: "Graviton Lens", amount: 1, chance: 0.2 }, { type: "dark_matter", name: "Dark Matter", amount: 35, chance: 0.4 }], lore: "Graviton wells warp spacetime so severely that light itself cannot escape.", effects: [{ type: "gravityWarp", value: 0.15, description: "+15% resource extraction in area" }], region: "Outer Rim" },
  { id: "dg-021", name: "Psionic Resonance Rift", description: "A rift that responds to thought. The mentally strong will prosper.", type: "rift", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1300, maxExplorers: 8, respawnTimeHours: 16, entryCost: { metal: 3000, crystal: 1800, deuterium: 900 }, rewards: [{ type: "research", name: "Psionic Research", amount: 900, chance: 0.7 }, { type: "technology", name: "Psionic Amplifier", amount: 1, chance: 0.25 }, { type: "experience", name: "Psionic XP", amount: 300, chance: 1 }], lore: "Psionic rifts amplify mental energy. Those who can channel it gain immense power.", effects: [{ type: "psionicBoost", value: 0.2, description: "+20% research speed with psionic focus" }], region: "Outer Rim" },
  { id: "dg-022", name: "Dark Matter Vein", description: "A concentrated vein of dark matter flowing through subspace.", type: "void_portal", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 800, maxExplorers: 10, respawnTimeHours: 12, entryCost: { metal: 2000, crystal: 1000, deuterium: 500 }, rewards: [{ type: "dark_matter", name: "Dark Matter", amount: 60, chance: 0.7 }, { type: "resources", name: "Subspace Energy", amount: 4000, chance: 0.75 }], lore: "Dark matter veins are the hidden arteries of the cosmos.", effects: [{ type: "darkHarvest", value: 0.1, description: "+10% dark matter collection" }], region: "Outer Rim" },
  { id: "dg-023", name: "Wormhole Nursery", description: "Where new wormholes are born. Unstable but full of potential.", type: "wormhole", rarity: "uncommon", status: "unstable", dangerLevel: 4, recommendedPower: 450, maxExplorers: 15, respawnTimeHours: 5, entryCost: { metal: 1100, crystal: 550, deuterium: 275 }, rewards: [{ type: "research", name: "Wormhole Genesis Data", amount: 350, chance: 0.7 }, { type: "resources", name: "Spacetime Residue", amount: 3000, chance: 0.8 }], lore: "Wormhole nurseries are where the universe creates new shortcuts through space.", effects: [], region: "Outer Rim" },
  { id: "dg-024", name: "Chrono-Static Field", description: "A field of frozen time. Extracting its energy is extremely profitable.", type: "temporal裂隙", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1000, maxExplorers: 8, respawnTimeHours: 10, entryCost: { metal: 2500, crystal: 1250, deuterium: 625 }, rewards: [{ type: "resources", name: "Chrono Energy", amount: 6000, chance: 0.75 }, { type: "artifact", name: "Time Fragment", amount: 1, chance: 0.2 }, { type: "research", name: "Chrono Research", amount: 600, chance: 0.6 }], lore: "Frozen time pockets hold energy that can accelerate or decelerate any process.", effects: [{ type: "timeFreeze", value: 0.08, description: "8% chance to freeze enemy cooldowns" }], region: "Outer Rim" },
  { id: "dg-025", name: "Dimensional Bleed", description: "Where two dimensions overlap. Reality becomes thin and malleable.", type: "rift", rarity: "uncommon", status: "active", dangerLevel: 5, recommendedPower: 550, maxExplorers: 12, respawnTimeHours: 6, entryCost: { metal: 1300, crystal: 650, deuterium: 325 }, rewards: [{ type: "resources", name: "Bleed Energy", amount: 3500, chance: 0.8 }, { type: "experience", name: "Dimensional XP", amount: 80, chance: 1 }], lore: "Dimensional bleeds are where reality becomes a suggestion rather than a rule.", effects: [{ type: "realityBend", value: 0.05, description: "5% chance for random resource bonus" }], region: "Outer Rim" },
  { id: "dg-026", name: "Null Space Pocket", description: "A pocket of absolute nothing. Even light cannot exist here.", type: "void_portal", rarity: "epic", status: "sealed", dangerLevel: 10, recommendedPower: 2500, maxExplorers: 4, respawnTimeHours: 36, entryCost: { metal: 8000, crystal: 4500, deuterium: 2200 }, rewards: [{ type: "technology", name: "Null Space Theory", amount: 1, chance: 0.6 }, { type: "dark_matter", name: "Pure Dark Matter", amount: 100, chance: 0.5 }, { type: "relic", name: "Void Core", amount: 1, chance: 0.3 }], lore: "Null space is where dimensions cancel out. The energy released is immense.", effects: [{ type: "nullEnergy", value: 0.25, description: "+25% energy weapon damage" }], region: "Outer Rim" },
  { id: "dg-027", name: "Stellar Nursery Gate", description: "A gate to a stellar nursery where stars are born.", type: "gate", rarity: "rare", status: "active", dangerLevel: 5, recommendedPower: 700, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 1800, crystal: 900, deuterium: 450 }, rewards: [{ type: "resources", name: "Stellar Material", amount: 5500, chance: 0.85 }, { type: "research", name: "Stellar Formation Data", amount: 450, chance: 0.6 }], lore: "Stellar nurseries are where the universe creates its most powerful energy sources.", effects: [{ type: "stellarBonus", value: 0.1, description: "+10% energy production" }], region: "Outer Rim" },
  { id: "dg-028", name: "Quantum Entanglement Rift", description: "A rift where quantum entanglement occurs at macro scale.", type: "rift", rarity: "uncommon", status: "active", dangerLevel: 4, recommendedPower: 400, maxExplorers: 14, respawnTimeHours: 4, entryCost: { metal: 1000, crystal: 500, deuterium: 250 }, rewards: [{ type: "research", name: "Quantum Entanglement Data", amount: 300, chance: 0.7 }, { type: "technology", name: "Quantum Comm Fragment", amount: 1, chance: 0.1 }], lore: "Quantum entanglement at macro scale allows instantaneous communication across vast distances.", effects: [], region: "Outer Rim" },
  { id: "dg-029", name: "Magnetic Monopole Field", description: "A field generated by hypothetical magnetic monopoles.", type: "shard", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 850, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2100, crystal: 1050, deuterium: 525 }, rewards: [{ type: "artifact", name: "Monopole Magnet", amount: 1, chance: 0.3 }, { type: "resources", name: "Magnetic Energy", amount: 5000, chance: 0.8 }, { type: "blueprint", name: "Monopole Shield", amount: 1, chance: 0.1 }], lore: "Magnetic monopoles were once theoretical. This field proves they exist.", effects: [{ type: "shieldBoost", value: 0.1, description: "+10% shield effectiveness" }], region: "Outer Rim" },
  { id: "dg-030", name: "Dimensional Anchor Point", description: "A point where dimensions are anchored. Destabilizing it could be catastrophic.", type: "nexus", rarity: "legendary", status: "sealed", dangerLevel: 10, recommendedPower: 3500, maxExplorers: 3, respawnTimeHours: 72, entryCost: { metal: 12000, crystal: 8000, deuterium: 4000, darkMatter: 200 }, rewards: [{ type: "technology", name: "Dimensional Stabilizer", amount: 1, chance: 0.7 }, { type: "relic", name: "Anchor Crystal", amount: 1, chance: 0.5 }, { type: "dark_matter", name: "Dark Matter", amount: 300, chance: 0.6 }], lore: "Dimensional anchors prevent realities from merging. Tamper at your own risk.", effects: [{ type: "dimensionLock", value: 1, description: "Stabilizes all active anomalies for 48h" }], region: "Outer Rim" },

  // === REGION: Deep Space (31-50) ===
  { id: "dg-031", name: "Abyssal Maw", description: "A consuming void that devours everything nearby.", type: "abyss", rarity: "epic", status: "active", dangerLevel: 9, recommendedPower: 2000, maxExplorers: 5, respawnTimeHours: 24, entryCost: { metal: 5000, crystal: 2500, deuterium: 1250 }, rewards: [{ type: "dark_matter", name: "Consumed Matter", amount: 80, chance: 0.6 }, { type: "artifact", name: "Maw Core", amount: 1, chance: 0.25 }, { type: "resources", name: "Devoured Resources", amount: 10000, chance: 0.7 }], lore: "The Abyssal Maw consumes all that enters. Only the bravest dare approach.", effects: [{ type: "consumeEffect", value: 0.1, description: "10% chance to consume enemy fleet in range" }], region: "Deep Space" },
  { id: "dg-032", name: "Wormhole Network Hub", description: "The central hub of a wormhole network. Navigate to any connected system.", type: "wormhole", rarity: "legendary", status: "active", dangerLevel: 8, recommendedPower: 2500, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 8000, crystal: 4000, deuterium: 2000 }, rewards: [{ type: "technology", name: "Network Navigation Key", amount: 1, chance: 0.6 }, { type: "relic", name: "Hub Crystal", amount: 1, chance: 0.35 }, { type: "experience", name: "Network XP", amount: 800, chance: 1 }], lore: "Wormhole network hubs are the internet of the cosmos.", effects: [{ type: "networkAccess", value: 5, description: "Access 5 additional wormhole destinations" }], region: "Deep Space" },
  { id: "dg-033", name: "Temporal Prison", description: "A prison where time moves infinitely slowly. What's trapped inside?", type: "temporal裂隙", rarity: "epic", status: "sealed", dangerLevel: 8, recommendedPower: 1800, maxExplorers: 6, respawnTimeHours: 30, entryCost: { metal: 5500, crystal: 3000, deuterium: 1500 }, rewards: [{ type: "technology", name: "Temporal Containment Data", amount: 1, chance: 0.5 }, { type: "relic", name: "Time Prison Key", amount: 1, chance: 0.3 }, { type: "dark_matter", name: "Frozen Time", amount: 50, chance: 0.4 }], lore: "Temporal prisons hold entities that cannot be destroyed, only contained.", effects: [{ type: "timeDilation", value: 0.2, description: "20% reduced enemy movement speed in area" }], region: "Deep Space" },
  { id: "dg-034", name: "Dark Energy Cascade", description: "A cascade of dark energy that could power an entire empire.", type: "void_portal", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1200, maxExplorers: 8, respawnTimeHours: 14, entryCost: { metal: 3000, crystal: 1500, deuterium: 750 }, rewards: [{ type: "resources", name: "Dark Energy Reserve", amount: 8000, chance: 0.8 }, { type: "dark_matter", name: "Dark Matter", amount: 45, chance: 0.5 }], lore: "Dark energy cascades are the universe's most potent power source.", effects: [{ type: "energySurge", value: 0.15, description: "+15% energy production for 24h" }], region: "Deep Space" },
  { id: "dg-035", name: "Nebula Gate Sigma", description: "A gate hidden within a dense nebula. The gas masks its true nature.", type: "gate", rarity: "rare", status: "dormant", dangerLevel: 6, recommendedPower: 900, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2500, crystal: 1250, deuterium: 625 }, rewards: [{ type: "resources", name: "Nebula Materials", amount: 6000, chance: 0.85 }, { type: "research", name: "Nebula Composition Data", amount: 500, chance: 0.6 }], lore: "Nebula gates are the universe's best-kept secrets, hidden in plain sight.", effects: [{ type: "nebulaCover", value: 0.2, description: "+20% stealth in nebula systems" }], region: "Deep Space" },
  { id: "dg-036", name: "Psionic Storm Rift", description: "A rift generating constant psionic storms. Mental fortitude required.", type: "rift", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1100, maxExplorers: 8, respawnTimeHours: 12, entryCost: { metal: 2800, crystal: 1400, deuterium: 700 }, rewards: [{ type: "research", name: "Psionic Storm Data", amount: 700, chance: 0.7 }, { type: "artifact", name: "Storm Core", amount: 1, chance: 0.2 }, { type: "experience", name: "Psionic XP", amount: 250, chance: 1 }], lore: "Psionic storms can shatter minds. Only the strongest survive.", effects: [{ type: "psionicDefense", value: 0.15, description: "+15% psionic resistance" }], region: "Deep Space" },
  { id: "dg-037", name: "Crystalline Labyrinth", description: "A maze of crystal formations that shifts and changes.", type: "shard", rarity: "epic", status: "active", dangerLevel: 8, recommendedPower: 1600, maxExplorers: 6, respawnTimeHours: 20, entryCost: { metal: 4500, crystal: 2500, deuterium: 1250 }, rewards: [{ type: "artifact", name: "Labyrinth Crystal", amount: 1, chance: 0.4 }, { type: "resources", name: "Crystal Essence", amount: 8000, chance: 0.8 }, { type: "blueprint", name: "Crystal Armor", amount: 1, chance: 0.15 }], lore: "The Crystalline Labyrinth changes its layout every cycle. Mapping it is nearly impossible.", effects: [{ type: "crystalMaze", value: 0.2, description: "+20% crystal yield but maze navigation required" }], region: "Deep Space" },
  { id: "dg-038", name: "Void Whispers", description: "Mysterious whispers emanate from this void. Those who listen gain knowledge.", type: "void_portal", rarity: "uncommon", status: "active", dangerLevel: 4, recommendedPower: 450, maxExplorers: 14, respawnTimeHours: 5, entryCost: { metal: 1100, crystal: 550, deuterium: 275 }, rewards: [{ type: "research", name: "Whispered Secrets", amount: 400, chance: 0.75 }, { type: "experience", name: "Insight XP", amount: 100, chance: 1 }], lore: "The void whispers to those who listen. Some say it knows the future.", effects: [{ type: "whisperInsight", value: 0.08, description: "+8% research speed" }], region: "Deep Space" },
  { id: "dg-039", name: "Antimatter Geyser", description: "A geyser of antimatter erupting from subspace.", type: "shard", rarity: "rare", status: "unstable", dangerLevel: 8, recommendedPower: 1500, maxExplorers: 6, respawnTimeHours: 14, entryCost: { metal: 3500, crystal: 1750, deuterium: 875 }, rewards: [{ type: "resources", name: "Antimatter", amount: 6000, chance: 0.75 }, { type: "artifact", name: "Antimatter Core", amount: 1, chance: 0.2 }, { type: "dark_matter", name: "Dark Matter", amount: 30, chance: 0.35 }], lore: "Antimatter geysers are incredibly dangerous but yield the most potent fuel.", effects: [{ type: "antimatterBoost", value: 0.2, description: "+20% weapon damage for 12h" }], region: "Deep Space" },
  { id: "dg-040", name: "Dimensional Fold", description: "A fold in spacetime that creates a shortcut between distant points.", type: "rift", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1300, maxExplorers: 8, respawnTimeHours: 16, entryCost: { metal: 3200, crystal: 1600, deuterium: 800 }, rewards: [{ type: "technology", name: "Fold Navigation Data", amount: 1, chance: 0.5 }, { type: "resources", name: "Fold Energy", amount: 7000, chance: 0.8 }, { type: "experience", name: "Fold XP", amount: 350, chance: 1 }], lore: "Dimensional folds are the universe's way of connecting distant points.", effects: [{ type: "foldTravel", value: 0.3, description: "+30% fleet speed through folds" }], region: "Deep Space" },
  { id: "dg-041", name: "Gravity Wave Anomaly", description: "Concentrated gravity waves that can crush or propel.", type: "abyss", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1000, maxExplorers: 8, respawnTimeHours: 12, entryCost: { metal: 2600, crystal: 1300, deuterium: 650 }, rewards: [{ type: "resources", name: "Gravity Energy", amount: 5500, chance: 0.8 }, { type: "artifact", name: "Gravity Lens", amount: 1, chance: 0.2 }, { type: "research", name: "Gravity Wave Data", amount: 500, chance: 0.6 }], lore: "Gravity waves propagate through dimensions, carrying immense energy.", effects: [{ type: "gravityControl", value: 0.12, description: "+12% mining efficiency" }], region: "Deep Space" },
  { id: "dg-042", name: "Phase Shift Gate", description: "A gate that shifts between dimensions at regular intervals.", type: "gate", rarity: "rare", status: "unstable", dangerLevel: 6, recommendedPower: 850, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 2000, crystal: 1000, deuterium: 500 }, rewards: [{ type: "technology", name: "Phase Shift Theory", amount: 1, chance: 0.35 }, { type: "resources", name: "Phase Energy", amount: 5000, chance: 0.8 }, { type: "blueprint", name: "Phase Cloak", amount: 1, chance: 0.1 }], lore: "Phase shift gates exist in multiple dimensions simultaneously.", effects: [{ type: "phaseShift", value: 0.15, description: "+15% dodge chance" }], region: "Deep Space" },
  { id: "dg-043", name: "Quantum Foam Pool", description: "A pool of quantum foam where reality is still forming.", type: "rift", rarity: "uncommon", status: "active", dangerLevel: 3, recommendedPower: 350, maxExplorers: 16, respawnTimeHours: 4, entryCost: { metal: 900, crystal: 450, deuterium: 225 }, rewards: [{ type: "research", name: "Quantum Foam Data", amount: 300, chance: 0.75 }, { type: "resources", name: "Quantum Residue", amount: 2500, chance: 0.8 }], lore: "Quantum foam is the fabric of reality at its most fundamental level.", effects: [], region: "Deep Space" },
  { id: "dg-044", name: "Dimensional Storm", description: "A storm of dimensional energy tearing through space.", type: "temporal裂隙", rarity: "epic", status: "active", dangerLevel: 9, recommendedPower: 2000, maxExplorers: 5, respawnTimeHours: 24, entryCost: { metal: 5000, crystal: 2500, deuterium: 1250 }, rewards: [{ type: "technology", name: "Storm Navigation Data", amount: 1, chance: 0.55 }, { type: "dark_matter", name: "Storm Essence", amount: 60, chance: 0.5 }, { type: "relic", name: "Storm Core", amount: 1, chance: 0.25 }], lore: "Dimensional storms are the universe's tantrums. Ride them and emerge stronger.", effects: [{ type: "stormRide", value: 0.2, description: "+20% all stats during storm" }], region: "Deep Space" },
  { id: "dg-045", name: "Echo of Creation", description: "An echo from the moment the universe was born. Incomprehensible power.", type: "echo", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 5000, maxExplorers: 2, respawnTimeHours: 120, entryCost: { metal: 15000, crystal: 10000, deuterium: 5000, darkMatter: 300 }, rewards: [{ type: "technology", name: "Creation Theory", amount: 1, chance: 0.8 }, { type: "relic", name: "Creation Fragment", amount: 1, chance: 0.6 }, { type: "dark_matter", name: "Primordial Matter", amount: 500, chance: 0.7 }], lore: "The Echo of Creation is the oldest sound in the universe. It still reverberates.", effects: [{ type: "creationPower", value: 0.3, description: "+30% all empire stats permanently" }], region: "Deep Space" },
  { id: "dg-046", name: "Plasma Conduit", description: "A conduit of pure plasma energy cutting through dimensions.", type: "shard", rarity: "uncommon", status: "active", dangerLevel: 4, recommendedPower: 400, maxExplorers: 14, respawnTimeHours: 4, entryCost: { metal: 1000, crystal: 500, deuterium: 250 }, rewards: [{ type: "resources", name: "Plasma Energy", amount: 3500, chance: 0.85 }, { type: "experience", name: "Energy XP", amount: 70, chance: 1 }], lore: "Plasma conduits are the power lines of the cosmos.", effects: [{ type: "plasmaFlow", value: 0.08, description: "+8% energy production" }], region: "Deep Space" },
  { id: "dg-047", name: "Singularity Rift", description: "A rift near a microscopic singularity. Infinite density, infinite potential.", type: "rift", rarity: "legendary", status: "unstable", dangerLevel: 10, recommendedPower: 3000, maxExplorers: 3, respawnTimeHours: 48, entryCost: { metal: 9000, crystal: 5000, deuterium: 2500 }, rewards: [{ type: "technology", name: "Singularity Physics", amount: 1, chance: 0.7 }, { type: "relic", name: "Singularity Core", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 150, chance: 0.6 }], lore: "Near a singularity, the laws of physics break down entirely.", effects: [{ type: "singularityPower", value: 0.25, description: "+25% all production but -10% build speed" }], region: "Deep Space" },
  { id: "dg-048", name: "Memory Fragment Pool", description: "A pool of memories from a destroyed civilization.", type: "echo", rarity: "rare", status: "active", dangerLevel: 5, recommendedPower: 700, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 1800, crystal: 900, deuterium: 450 }, rewards: [{ type: "research", name: "Ancient Knowledge", amount: 600, chance: 0.75 }, { type: "technology", name: "Lost Technology Fragment", amount: 1, chance: 0.2 }, { type: "experience", name: "Wisdom XP", amount: 200, chance: 1 }], lore: "Memory pools preserve the last thoughts of entire civilizations.", effects: [{ type: "memoryRecall", value: 0.1, description: "+10% research speed" }], region: "Deep Space" },
  { id: "dg-049", name: "Dimensional Barrier", description: "The barrier between dimensions. Breaking it requires immense power.", type: "gate", rarity: "legendary", status: "sealed", dangerLevel: 9, recommendedPower: 2800, maxExplorers: 4, respawnTimeHours: 60, entryCost: { metal: 10000, crystal: 6000, deuterium: 3000 }, rewards: [{ type: "technology", name: "Barrier Breach Theory", amount: 1, chance: 0.65 }, { type: "relic", name: "Barrier Shard", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 120, chance: 0.5 }], lore: "Dimensional barriers keep realities separate. Breach them, and anything is possible.", effects: [{ type: "barrierBreak", value: 0.2, description: "+20% dimensional technology efficiency" }], region: "Deep Space" },
  { id: "dg-050", name: "Void Titan Remnant", description: "The remains of a Void Titan. Its power still lingers.", type: "abyss", rarity: "mythic", status: "active", dangerLevel: 10, recommendedPower: 4000, maxExplorers: 3, respawnTimeHours: 96, entryCost: { metal: 12000, crystal: 8000, deuterium: 4000, darkMatter: 250 }, rewards: [{ type: "technology", name: "Void Titan Schematics", amount: 1, chance: 0.7 }, { type: "relic", name: "Titan Core", amount: 1, chance: 0.5 }, { type: "fleet", name: "Titan Blueprint", amount: 1, chance: 0.3 }], lore: "Void Titans were the largest entities ever to exist. Their remnants hold immense power.", effects: [{ type: "titanLegacy", value: 0.3, description: "+30% fleet power" }], region: "Deep Space" },

  // === REGION: Exotic Space (51-70) ===
  { id: "dg-051", name: "Antimatter Nebula Gate", description: "A gate to a nebula made entirely of antimatter.", type: "gate", rarity: "epic", status: "active", dangerLevel: 8, recommendedPower: 1800, maxExplorers: 6, respawnTimeHours: 24, entryCost: { metal: 5500, crystal: 3000, deuterium: 1500 }, rewards: [{ type: "resources", name: "Antimatter Reserve", amount: 8000, chance: 0.8 }, { type: "dark_matter", name: "Dark Matter", amount: 55, chance: 0.45 }], lore: "Antimatter nebulae are the universe's most dangerous power sources.", effects: [{ type: "antimatterField", value: 0.15, description: "+15% weapon damage" }], region: "Exotic Space" },
  { id: "dg-052", name: "Quantum Superposition Rift", description: "A rift existing in multiple states simultaneously.", type: "rift", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 850, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2000, crystal: 1000, deuterium: 500 }, rewards: [{ type: "research", name: "Superposition Data", amount: 550, chance: 0.7 }, { type: "technology", name: "Quantum Computer Fragment", amount: 1, chance: 0.15 }], lore: "Quantum superposition allows things to exist in all states at once.", effects: [{ type: "superposition", value: 0.1, description: "+10% research speed" }], region: "Exotic Space" },
  { id: "dg-053", name: "Dark Energy Fountain", description: "A fountain of pure dark energy erupting from the void.", type: "void_portal", rarity: "rare", status: "active", dangerLevel: 7, recommendedPower: 1100, maxExplorers: 8, respawnTimeHours: 12, entryCost: { metal: 2800, crystal: 1400, deuterium: 700 }, rewards: [{ type: "resources", name: "Dark Energy", amount: 7000, chance: 0.8 }, { type: "dark_matter", name: "Dark Matter", amount: 40, chance: 0.45 }], lore: "Dark energy fountains are the universe's most abundant power source.", effects: [{ type: "darkFountain", value: 0.12, description: "+12% energy production" }], region: "Exotic Space" },
  { id: "dg-054", name: "Temporal Echo Chamber", description: "A chamber where temporal echoes are amplified and preserved.", type: "echo", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1400, maxExplorers: 7, respawnTimeHours: 18, entryCost: { metal: 4000, crystal: 2000, deuterium: 1000 }, rewards: [{ type: "research", name: "Temporal Echo Data", amount: 900, chance: 0.75 }, { type: "relic", name: "Temporal Echo Crystal", amount: 1, chance: 0.25 }], lore: "Echo chambers preserve moments in time. Study them to unlock the past.", effects: [{ type: "temporalEcho", value: 0.15, description: "+15% research speed" }], region: "Exotic Space" },
  { id: "dg-055", name: "Gravitational Lens Gate", description: "A gate hidden behind a gravitational lens. The distortion hides its true nature.", type: "gate", rarity: "rare", status: "dormant", dangerLevel: 5, recommendedPower: 700, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 1800, crystal: 900, deuterium: 450 }, rewards: [{ type: "technology", name: "Gravitational Lensing Data", amount: 1, chance: 0.3 }, { type: "resources", name: "Lensed Energy", amount: 5500, chance: 0.8 }], lore: "Gravitational lenses bend light, hiding gates in plain sight.", effects: [{ type: "lensVision", value: 0.2, description: "+20% scanner range" }], region: "Exotic Space" },
  { id: "dg-056", name: "Void Crystal Garden", description: "A garden of crystals growing in the void. Each crystal holds unique properties.", type: "shard", rarity: "epic", status: "active", dangerLevel: 6, recommendedPower: 1000, maxExplorers: 8, respawnTimeHours: 14, entryCost: { metal: 2500, crystal: 1250, deuterium: 625 }, rewards: [{ type: "artifact", name: "Void Crystal", amount: 1, chance: 0.4 }, { type: "resources", name: "Crystal Essence", amount: 6000, chance: 0.85 }, { type: "blueprint", name: "Crystal Growth Catalyst", amount: 1, chance: 0.12 }], lore: "Void crystals grow in absolute zero. Each one is a unique work of nature.", effects: [{ type: "crystalGrowth", value: 0.15, description: "+15% crystal production" }], region: "Exotic Space" },
  { id: "dg-057", name: "Dimensional Vortex", description: "A vortex pulling matter from multiple dimensions.", type: "rift", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 2500, maxExplorers: 4, respawnTimeHours: 36, entryCost: { metal: 7000, crystal: 3500, deuterium: 1750 }, rewards: [{ type: "technology", name: "Vortex Navigation Theory", amount: 1, chance: 0.6 }, { type: "relic", name: "Vortex Core", amount: 1, chance: 0.35 }, { type: "dark_matter", name: "Dark Matter", amount: 80, chance: 0.5 }], lore: "Dimensional vortices are the universe's washing machines, mixing everything together.", effects: [{ type: "vortexMix", value: 0.2, description: "+20% resource diversity" }], region: "Exotic Space" },
  { id: "dg-058", name: "Stellar Forge Gate", description: "A gate to a stellar forge where stars are manufactured.", type: "gate", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1300, maxExplorers: 7, respawnTimeHours: 20, entryCost: { metal: 3500, crystal: 1750, deuterium: 875 }, rewards: [{ type: "technology", name: "Stellar Forge Blueprints", amount: 1, chance: 0.5 }, { type: "resources", name: "Stellar Material", amount: 7000, chance: 0.85 }], lore: "Stellar forges create stars. The energy required is beyond comprehension.", effects: [{ type: "stellarForge", value: 0.18, description: "+18% production speed" }], region: "Exotic Space" },
  { id: "dg-059", name: "Quantum Entanglement Hub", description: "The central hub of a quantum entanglement network.", type: "nexus", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 900, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2200, crystal: 1100, deuterium: 550 }, rewards: [{ type: "technology", name: "Entanglement Hub Access", amount: 1, chance: 0.4 }, { type: "research", name: "Entanglement Data", amount: 500, chance: 0.7 }], lore: "Quantum entanglement hubs allow instantaneous communication across the galaxy.", effects: [{ type: "entanglement", value: 0.15, description: "+15% communication speed" }], region: "Exotic Space" },
  { id: "dg-060", name: "Dark Matter Storm", description: "A storm of dark matter tearing through dimensions.", type: "void_portal", rarity: "epic", status: "unstable", dangerLevel: 8, recommendedPower: 1700, maxExplorers: 6, respawnTimeHours: 22, entryCost: { metal: 4800, crystal: 2400, deuterium: 1200 }, rewards: [{ type: "dark_matter", name: "Dark Matter Storm Essence", amount: 70, chance: 0.6 }, { type: "resources", name: "Storm Energy", amount: 8000, chance: 0.8 }], lore: "Dark matter storms are the universe's most powerful energy sources.", effects: [{ type: "darkStorm", value: 0.2, description: "+20% dark matter yield during storm" }], region: "Exotic Space" },
  { id: "dg-061", name: "Temporal Paradox Zone", description: "A zone where cause and effect are reversed.", type: "temporal裂隙", rarity: "epic", status: "active", dangerLevel: 8, recommendedPower: 1600, maxExplorers: 6, respawnTimeHours: 20, entryCost: { metal: 4500, crystal: 2250, deuterium: 1125 }, rewards: [{ type: "research", name: "Paradox Resolution Data", amount: 800, chance: 0.7 }, { type: "relic", name: "Paradox Crystal", amount: 1, chance: 0.25 }, { type: "experience", name: "Paradox XP", amount: 400, chance: 1 }], lore: "In paradox zones, effects precede causes. Understanding them requires deep thought.", effects: [{ type: "paradoxResolve", value: 0.15, description: "+15% research speed" }], region: "Exotic Space" },
  { id: "dg-062", name: "Nebula Core Gate", description: "A gate at the heart of a nebula. The core holds immense energy.", type: "gate", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 850, maxExplorers: 10, respawnTimeHours: 10, entryCost: { metal: 2100, crystal: 1050, deuterium: 525 }, rewards: [{ type: "resources", name: "Nebula Core Energy", amount: 6500, chance: 0.85 }, { type: "research", name: "Nebula Core Data", amount: 450, chance: 0.6 }], lore: "Nebula cores are the birthplaces of stars and the graves of civilizations.", effects: [{ type: "nebulaCore", value: 0.12, description: "+12% energy production" }], region: "Exotic Space" },
  { id: "dg-063", name: "Void Echo Network", description: "A network of void echoes connecting distant parts of space.", type: "echo", rarity: "rare", status: "active", dangerLevel: 5, recommendedPower: 700, maxExplorers: 10, respawnTimeHours: 8, entryCost: { metal: 1800, crystal: 900, deuterium: 450 }, rewards: [{ type: "research", name: "Void Echo Data", amount: 500, chance: 0.7 }, { type: "technology", name: "Echo Navigation", amount: 1, chance: 0.2 }], lore: "Void echoes travel faster than light, connecting the universe's hidden pathways.", effects: [{ type: "echoNetwork", value: 0.1, description: "+10% communication range" }], region: "Exotic Space" },
  { id: "dg-064", name: "Crystalline Dimension", description: "An entire dimension made of crystal. The resources are limitless.", type: "shard", rarity: "legendary", status: "active", dangerLevel: 8, recommendedPower: 2000, maxExplorers: 5, respawnTimeHours: 30, entryCost: { metal: 6000, crystal: 3000, deuterium: 1500 }, rewards: [{ type: "resources", name: "Crystal Dimension Essence", amount: 12000, chance: 0.85 }, { type: "artifact", name: "Dimension Crystal", amount: 1, chance: 0.35 }, { type: "blueprint", name: "Crystal Growth Accelerator", amount: 1, chance: 0.2 }], lore: "The Crystalline Dimension is a world where everything is made of living crystal.", effects: [{ type: "crystalDimension", value: 0.25, description: "+25% crystal production" }], region: "Exotic Space" },
  { id: "dg-065", name: "Dimensional Stabilizer", description: "A device that stabilizes dimensional rifts. Extremely valuable.", type: "nexus", rarity: "legendary", status: "sealed", dangerLevel: 8, recommendedPower: 2200, maxExplorers: 5, respawnTimeHours: 40, entryCost: { metal: 7000, crystal: 3500, deuterium: 1750 }, rewards: [{ type: "technology", name: "Stabilizer Technology", amount: 1, chance: 0.7 }, { type: "relic", name: "Stabilizer Core", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 90, chance: 0.5 }], lore: "Dimensional stabilizers are the universe's safety nets.", effects: [{ type: "dimensionStabilize", value: 0.2, description: "+20% anomaly stability" }], region: "Exotic Space" },
  { id: "dg-066", name: "Quantum Foam Abyss", description: "An abyss filled with quantum foam. Reality is barely held together.", type: "abyss", rarity: "epic", status: "active", dangerLevel: 9, recommendedPower: 2000, maxExplorers: 5, respawnTimeHours: 24, entryCost: { metal: 5000, crystal: 2500, deuterium: 1250 }, rewards: [{ type: "technology", name: "Quantum Foam Theory", amount: 1, chance: 0.55 }, { type: "dark_matter", name: "Quantum Dark Matter", amount: 65, chance: 0.5 }, { type: "relic", name: "Foam Crystal", amount: 1, chance: 0.3 }], lore: "Quantum foam is the foundation of reality. Study it to reshape the universe.", effects: [{ type: "quantumFoam", value: 0.18, description: "+18% all research" }], region: "Exotic Space" },
  { id: "dg-067", name: "Temporal Acceleration Gate", description: "A gate that accelerates time within. Perfect for rapid research.", type: "temporal裂隙", rarity: "rare", status: "active", dangerLevel: 6, recommendedPower: 900, maxExplorers: 8, respawnTimeHours: 12, entryCost: { metal: 2400, crystal: 1200, deuterium: 600 }, rewards: [{ type: "research", name: "Accelerated Research", amount: 700, chance: 0.8 }, { type: "experience", name: "Acceleration XP", amount: 250, chance: 1 }], lore: "Temporal acceleration gates compress time, allowing rapid progress.", effects: [{ type: "timeAccel", value: 0.25, description: "+25% research speed" }], region: "Exotic Space" },
  { id: "dg-068", name: "Dark Energy Vortex", description: "A vortex of dark energy spiraling into a singularity.", type: "void_portal", rarity: "epic", status: "active", dangerLevel: 8, recommendedPower: 1700, maxExplorers: 6, respawnTimeHours: 20, entryCost: { metal: 4500, crystal: 2250, deuterium: 1125 }, rewards: [{ type: "dark_matter", name: "Dark Energy Core", amount: 75, chance: 0.55 }, { type: "resources", name: "Vortex Energy", amount: 9000, chance: 0.8 }], lore: "Dark energy vortices are the universe's most powerful whirlpools.", effects: [{ type: "darkVortex", value: 0.18, description: "+18% dark energy production" }], region: "Exotic Space" },
  { id: "dg-069", name: "Gravitational Singularity Gate", description: "A gate hidden within a gravitational singularity.", type: "gate", rarity: "legendary", status: "sealed", dangerLevel: 10, recommendedPower: 3500, maxExplorers: 3, respawnTimeHours: 72, entryCost: { metal: 11000, crystal: 7000, deuterium: 3500 }, rewards: [{ type: "technology", name: "Singularity Gate Theory", amount: 1, chance: 0.65 }, { type: "relic", name: "Singularity Gate Key", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 200, chance: 0.6 }], lore: "Gravitational singularity gates are the universe's most powerful doorways.", effects: [{ type: "singularityGate", value: 0.3, description: "+30% all production" }], region: "Exotic Space" },
  { id: "dg-070", name: "Dimensional Nexus Prime", description: "The primary nexus connecting all dimensions. The most strategic location.", type: "nexus", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 5000, maxExplorers: 2, respawnTimeHours: 168, entryCost: { metal: 20000, crystal: 12000, deuterium: 6000, darkMatter: 500 }, rewards: [{ type: "technology", name: "Nexus Prime Control", amount: 1, chance: 0.8 }, { type: "relic", name: "Prime Nexus Core", amount: 1, chance: 0.6 }, { type: "dark_matter", name: "Dark Matter", amount: 500, chance: 0.7 }], lore: "Dimensional Nexus Prime is the crossroads of all realities. Control it, and you control everything.", effects: [{ type: "nexusPrime", value: 0.35, description: "+35% all empire stats" }], region: "Exotic Space" },

  // === REGION: Unknown Space (71-90) ===
  { id: "dg-071", name: "Void of Unmaking", description: "A void that unmakes everything it touches. Pure entropy.", type: "abyss", rarity: "mythic", status: "active", dangerLevel: 10, recommendedPower: 4000, maxExplorers: 2, respawnTimeHours: 120, entryCost: { metal: 15000, crystal: 10000, deuterium: 5000, darkMatter: 300 }, rewards: [{ type: "technology", name: "Entropy Theory", amount: 1, chance: 0.7 }, { type: "relic", name: "Entropy Core", amount: 1, chance: 0.5 }, { type: "dark_matter", name: "Pure Entropy", amount: 400, chance: 0.6 }], lore: "The Void of Unmaking is where the universe goes to die.", effects: [{ type: "entropyPower", value: 0.3, description: "+30% all stats but -15% build speed" }], region: "Unknown Space" },
  { id: "dg-072", name: "Creation Rift", description: "A rift where new matter is spontaneously created.", type: "rift", rarity: "legendary", status: "active", dangerLevel: 8, recommendedPower: 2500, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 8000, crystal: 4000, deuterium: 2000 }, rewards: [{ type: "resources", name: "Created Matter", amount: 15000, chance: 0.85 }, { type: "technology", name: "Matter Creation Theory", amount: 1, chance: 0.5 }], lore: "Creation rifts are where the universe writes new chapters.", effects: [{ type: "creationRift", value: 0.25, description: "+25% resource production" }], region: "Unknown Space" },
  { id: "dg-073", name: "Temporal Convergence", description: "Where all timelines converge into a single moment.", type: "temporal裂隙", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 4500, maxExplorers: 2, respawnTimeHours: 144, entryCost: { metal: 18000, crystal: 11000, deuterium: 5500, darkMatter: 400 }, rewards: [{ type: "technology", name: "Timeline Convergence Theory", amount: 1, chance: 0.75 }, { type: "relic", name: "Convergence Crystal", amount: 1, chance: 0.55 }, { type: "dark_matter", name: "Temporal Dark Matter", amount: 350, chance: 0.65 }], lore: "Temporal convergence is where past, present, and future become one.", effects: [{ type: "temporalConverge", value: 0.35, description: "+35% research speed" }], region: "Unknown Space" },
  { id: "dg-074", name: "Void Gate Omega", description: "The final void gate. Beyond lies the unknown.", type: "gate", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 4000, maxExplorers: 3, respawnTimeHours: 120, entryCost: { metal: 16000, crystal: 10000, deuterium: 5000, darkMatter: 350 }, rewards: [{ type: "technology", name: "Omega Gate Access", amount: 1, chance: 0.7 }, { type: "relic", name: "Omega Key", amount: 1, chance: 0.5 }, { type: "fleet", name: "Omega Fleet Blueprint", amount: 1, chance: 0.25 }], lore: "Void Gate Omega is the gateway to the furthest reaches of existence.", effects: [{ type: "omegaGate", value: 0.35, description: "+35% all empire capabilities" }], region: "Unknown Space" },
  { id: "dg-075", name: "Dark Matter Nexus", description: "The central nexus of all dark matter in the universe.", type: "nexus", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 3000, maxExplorers: 3, respawnTimeHours: 60, entryCost: { metal: 10000, crystal: 6000, deuterium: 3000 }, rewards: [{ type: "dark_matter", name: "Dark Matter Core", amount: 200, chance: 0.7 }, { type: "technology", name: "Dark Matter Nexus Theory", amount: 1, chance: 0.55 }], lore: "The Dark Matter Nexus is where all dark matter flows converge.", effects: [{ type: "darkNexus", value: 0.3, description: "+30% dark matter production" }], region: "Unknown Space" },
  { id: "dg-076", name: "Reality Shatter Zone", description: "A zone where reality itself has shattered into fragments.", type: "rift", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 2800, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 9000, crystal: 5000, deuterium: 2500 }, rewards: [{ type: "relic", name: "Reality Fragment", amount: 1, chance: 0.45 }, { type: "technology", name: "Reality Reconstruction Theory", amount: 1, chance: 0.5 }, { type: "dark_matter", name: "Dark Matter", amount: 100, chance: 0.55 }], lore: "Reality shatter zones are where the universe's code has been corrupted.", effects: [{ type: "realityShatter", value: 0.2, description: "+20% all stats but random effects" }], region: "Unknown Space" },
  { id: "dg-077", name: "Void Walker's Path", description: "The path walked by Void Walkers. Only the worthy may pass.", type: "void_portal", rarity: "legendary", status: "sealed", dangerLevel: 9, recommendedPower: 2800, maxExplorers: 3, respawnTimeHours: 60, entryCost: { metal: 9500, crystal: 5500, deuterium: 2750 }, rewards: [{ type: "technology", name: "Void Walking Theory", amount: 1, chance: 0.6 }, { type: "relic", name: "Void Walker's Mark", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 120, chance: 0.5 }], lore: "The Void Walker's Path tests all who enter. Only the strongest survive.", effects: [{ type: "voidWalker", value: 0.25, description: "+25% all combat stats" }], region: "Unknown Space" },
  { id: "dg-078", name: "Singularity Forge", description: "A forge powered by a singularity. Creates the most powerful weapons.", type: "shard", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 2700, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 8500, crystal: 4500, deuterium: 2250 }, rewards: [{ type: "blueprint", name: "Singularity Weapon Blueprint", amount: 1, chance: 0.4 }, { type: "technology", name: "Singularity Forge Theory", amount: 1, chance: 0.55 }, { type: "relic", name: "Forge Core", amount: 1, chance: 0.35 }], lore: "Singularity forges create weapons that can pierce dimensional barriers.", effects: [{ type: "singularityForge", value: 0.2, description: "+20% weapon damage" }], region: "Unknown Space" },
  { id: "dg-079", name: "Temporal Echoes of War", description: "Echoes of ancient battles still reverberate through time.", type: "echo", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1400, maxExplorers: 7, respawnTimeHours: 16, entryCost: { metal: 3500, crystal: 1750, deuterium: 875 }, rewards: [{ type: "research", name: "Ancient Battle Tactics", amount: 800, chance: 0.75 }, { type: "technology", name: "War Echo Analysis", amount: 1, chance: 0.25 }], lore: "War echoes preserve the tactics of civilizations long dead.", effects: [{ type: "warEcho", value: 0.15, description: "+15% combat effectiveness" }], region: "Unknown Space" },
  { id: "dg-080", name: "Dimensional Barrier Breach", description: "A breach in the dimensional barrier. Things are coming through.", type: "gate", rarity: "mythic", status: "active", dangerLevel: 10, recommendedPower: 4000, maxExplorers: 2, respawnTimeHours: 96, entryCost: { metal: 14000, crystal: 9000, deuterium: 4500, darkMatter: 300 }, rewards: [{ type: "technology", name: "Barrier Breach Mastery", amount: 1, chance: 0.7 }, { type: "relic", name: "Breach Shard", amount: 1, chance: 0.5 }, { type: "dark_matter", name: "Dimensional Dark Matter", amount: 250, chance: 0.6 }], lore: "Barrier breaches are where dimensions collide. The energy released is unimaginable.", effects: [{ type: "barrierBreach", value: 0.35, description: "+35% all stats" }], region: "Unknown Space" },
  { id: "dg-081", name: "Void Essence Pool", description: "A pool of pure void essence. The most concentrated form of dark energy.", type: "void_portal", rarity: "epic", status: "active", dangerLevel: 7, recommendedPower: 1300, maxExplorers: 7, respawnTimeHours: 16, entryCost: { metal: 3200, crystal: 1600, deuterium: 800 }, rewards: [{ type: "dark_matter", name: "Void Essence", amount: 55, chance: 0.6 }, { type: "resources", name: "Concentrated Dark Energy", amount: 7000, chance: 0.8 }], lore: "Void essence pools are the most concentrated form of dark energy in the universe.", effects: [{ type: "voidEssence", value: 0.15, description: "+15% dark energy production" }], region: "Unknown Space" },
  { id: "dg-082", name: "Quantum Entanglement Storm", description: "A storm of quantum entanglement events. Reality becomes uncertain.", type: "rift", rarity: "epic", status: "unstable", dangerLevel: 8, recommendedPower: 1600, maxExplorers: 6, respawnTimeHours: 20, entryCost: { metal: 4200, crystal: 2100, deuterium: 1050 }, rewards: [{ type: "research", name: "Entanglement Storm Data", amount: 750, chance: 0.7 }, { type: "technology", name: "Quantum Storm Navigation", amount: 1, chance: 0.3 }], lore: "Quantum entanglement storms make reality uncertain. Embrace the chaos.", effects: [{ type: "quantumStorm", value: 0.18, description: "+18% research speed during storm" }], region: "Unknown Space" },
  { id: "dg-083", name: "Temporal Paradox Engine", description: "An engine that harnesses temporal paradoxes for energy.", type: "temporal裂隙", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 2500, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 7500, crystal: 3750, deuterium: 1875 }, rewards: [{ type: "technology", name: "Paradox Engine Theory", amount: 1, chance: 0.6 }, { type: "relic", name: "Paradox Engine Core", amount: 1, chance: 0.4 }, { type: "dark_matter", name: "Dark Matter", amount: 80, chance: 0.5 }], lore: "Paradox engines turn impossible contradictions into usable energy.", effects: [{ type: "paradoxEngine", value: 0.2, description: "+20% energy production" }], region: "Unknown Space" },
  { id: "dg-084", name: "Dark Energy Cascade Prime", description: "The primary dark energy cascade. The most powerful energy source known.", type: "void_portal", rarity: "legendary", status: "active", dangerLevel: 9, recommendedPower: 2800, maxExplorers: 4, respawnTimeHours: 48, entryCost: { metal: 9000, crystal: 5000, deuterium: 2500 }, rewards: [{ type: "resources", name: "Dark Energy Prime", amount: 12000, chance: 0.85 }, { type: "dark_matter", name: "Dark Matter", amount: 100, chance: 0.55 }], lore: "Dark Energy Cascade Prime is the universe's most powerful energy source.", effects: [{ type: "darkCascadePrime", value: 0.25, description: "+25% energy production" }], region: "Unknown Space" },
  { id: "dg-085", name: "Dimensional Rift Storm", description: "A storm of dimensional rifts tearing through reality.", type: "rift", rarity: "mythic", status: "active", dangerLevel: 10, recommendedPower: 4000, maxExplorers: 2, respawnTimeHours: 120, entryCost: { metal: 15000, crystal: 10000, deuterium: 5000, darkMatter: 350 }, rewards: [{ type: "technology", name: "Rift Storm Mastery", amount: 1, chance: 0.7 }, { type: "relic", name: "Rift Storm Core", amount: 1, chance: 0.5 }, { type: "dark_matter", name: "Rift Dark Matter", amount: 300, chance: 0.6 }], lore: "Dimensional rift storms reshape reality itself. Only the most advanced can survive.", effects: [{ type: "riftStorm", value: 0.35, description: "+35% all stats during storm" }], region: "Unknown Space" },
  { id: "dg-086", name: "Void Gate Origin", description: "The origin point of all void gates. The first doorway.", type: "gate", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 4500, maxExplorers: 2, respawnTimeHours: 168, entryCost: { metal: 20000, crystal: 12000, deuterium: 6000, darkMatter: 500 }, rewards: [{ type: "technology", name: "Origin Gate Theory", amount: 1, chance: 0.75 }, { type: "relic", name: "Origin Key", amount: 1, chance: 0.55 }, { type: "fleet", name: "Origin Fleet Blueprint", amount: 1, chance: 0.3 }], lore: "The Void Gate Origin is where all dimensional travel began.", effects: [{ type: "originGate", value: 0.4, description: "+40% all empire capabilities" }], region: "Unknown Space" },
  { id: "dg-087", name: "Reality Anchor Point", description: "A point where reality is anchored. Destabilize it to reshape the universe.", type: "nexus", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 5000, maxExplorers: 2, respawnTimeHours: 168, entryCost: { metal: 22000, crystal: 14000, deuterium: 7000, darkMatter: 600 }, rewards: [{ type: "technology", name: "Reality Anchoring Theory", amount: 1, chance: 0.8 }, { type: "relic", name: "Reality Anchor", amount: 1, chance: 0.6 }, { type: "dark_matter", name: "Reality Dark Matter", amount: 500, chance: 0.7 }], lore: "Reality anchor points hold the universe together. Control one, and you control reality itself.", effects: [{ type: "realityAnchor", value: 0.4, description: "+40% all empire stats" }], region: "Unknown Space" },
  { id: "dg-088", name: "Void of Creation", description: "The void where the universe was born. Pure potential.", type: "abyss", rarity: "mythic", status: "active", dangerLevel: 10, recommendedPower: 4500, maxExplorers: 2, respawnTimeHours: 144, entryCost: { metal: 18000, crystal: 11000, deuterium: 5500, darkMatter: 450 }, rewards: [{ type: "technology", name: "Creation Mastery", amount: 1, chance: 0.75 }, { type: "relic", name: "Creation Core", amount: 1, chance: 0.55 }, { type: "dark_matter", name: "Primordial Dark Matter", amount: 400, chance: 0.65 }], lore: "The Void of Creation is where everything began. The power within is limitless.", effects: [{ type: "creationVoid", value: 0.4, description: "+40% all production and research" }], region: "Unknown Space" },
  { id: "dg-089", name: "Dimensional Convergence Nexus", description: "Where all dimensions converge into a single point of infinite energy.", type: "nexus", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 5000, maxExplorers: 2, respawnTimeHours: 168, entryCost: { metal: 25000, crystal: 15000, deuterium: 7500, darkMatter: 700 }, rewards: [{ type: "technology", name: "Convergence Mastery", amount: 1, chance: 0.8 }, { type: "relic", name: "Convergence Core", amount: 1, chance: 0.6 }, { type: "dark_matter", name: "Convergence Dark Matter", amount: 600, chance: 0.7 }], lore: "The Dimensional Convergence Nexus is the most powerful point in the universe.", effects: [{ type: "convergenceNexus", value: 0.45, description: "+45% all empire stats" }], region: "Unknown Space" },
  { id: "dg-090", name: "The Final Gate", description: "The last gate. Beyond lies the answer to everything.", type: "gate", rarity: "mythic", status: "sealed", dangerLevel: 10, recommendedPower: 5000, maxExplorers: 1, respawnTimeHours: 336, entryCost: { metal: 30000, crystal: 20000, deuterium: 10000, darkMatter: 1000 }, rewards: [{ type: "technology", name: "Final Gate Theory", amount: 1, chance: 0.9 }, { type: "relic", name: "The Answer", amount: 1, chance: 0.7 }, { type: "dark_matter", name: "Ultimate Dark Matter", amount: 1000, chance: 0.8 }], lore: "The Final Gate is the last doorway. Beyond it lies the ultimate truth of the universe.", effects: [{ type: "finalGate", value: 0.5, description: "+50% all empire stats permanently" }], region: "Unknown Space" },
];

export const ANOMALY_REGIONS = ["Core", "Outer Rim", "Deep Space", "Exotic Space", "Unknown Space"] as const;

export const ANOMALY_RARITY_COLORS: Record<AnomalyRarity, string> = {
  common: "text-gray-400",
  uncommon: "text-green-400",
  rare: "text-blue-400",
  epic: "text-purple-400",
  legendary: "text-amber-400",
  mythic: "text-red-500",
};

export const ANOMALY_RARITY_BG: Record<AnomalyRarity, string> = {
  common: "bg-gray-500/10 border-gray-500/30",
  uncommon: "bg-green-500/10 border-green-500/30",
  rare: "bg-blue-500/10 border-blue-500/30",
  epic: "bg-purple-500/10 border-purple-500/30",
  legendary: "bg-amber-500/10 border-amber-500/30",
  mythic: "bg-red-500/10 border-red-500/30",
};

export function getAnomaliesByRegion(region: string): DimensionalAnomaly[] {
  return DIMENSIONAL_ANOMALIES.filter((a) => a.region === region);
}

export function getAnomaliesByRarity(rarity: AnomalyRarity): DimensionalAnomaly[] {
  return DIMENSIONAL_ANOMALIES.filter((a) => a.rarity === rarity);
}

export function getAnomalyById(id: string): DimensionalAnomaly | undefined {
  return DIMENSIONAL_ANOMALIES.find((a) => a.id === id);
}

export function getAnomalyStats() {
  const regions = ANOMALY_REGIONS.map((r) => ({ region: r, count: getAnomaliesByRegion(r).length }));
  const rarities = (["common", "uncommon", "rare", "epic", "legendary", "mythic"] as AnomalyRarity[]).map((r) => ({ rarity: r, count: getAnomaliesByRarity(r).length }));
  return { total: DIMENSIONAL_ANOMALIES.length, regions, rarities };
}
