export type RealmTier = "Sovereign" | "Dominion" | "Ascendant" | "Warfront" | "Prosperity" | "Industrial" | "Strike" | "Shadow" | "Endgame";
export type ServerRegion = "nexus-alpha" | "cygnus-eu" | "orion-apac" | "lyra-sa" | "draco-me" | "phoenix-af" | "vega-au" | "sirius-in" | "polaris-an";
export type RealmStatus = "live" | "new" | "full" | "locked";
export type RealmBonusType = "research" | "production" | "defense" | "economy" | "military" | "espionage" | "colonization" | "diplomacy";

export interface RealmBonus {
  type: RealmBonusType;
  value: number;
  label: string;
}

export interface RealmDef {
  id: string;
  name: string;
  tier: RealmTier;
  tierNumber: number;
  universe: string;
  universeDescription: string;
  server: ServerRegion;
  serverLabel: string;
  status: RealmStatus;
  icon: string;
  bannerGradient: string;
  accentColor: string;
  textColor: string;
  borderColor: string;
  glowColor: string;
  population: string;
  populationCount: number;
  onlinePlayers: number;
  totalEmpires: number;
  avgPower: number;
  description: string;
  lore: string;
  bonuses: RealmBonus[];
  features: string[];
  restrictions: string[];
  recommendedFor: string[];
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "Veteran";
  startResources: {
    credits: number;
    minerals: number;
    energy: number;
    alloys: number;
    research: number;
    influence: number;
  };
  specialMechanic: string;
  seasonalEvent: string;
  maxAllianceSize: number;
  galaxySize: "Small" | "Medium" | "Large" | "Massive";
  speedMultiplier: number;
}

export const SERVER_INFO: Record<ServerRegion, { name: string; region: string; latency: string; status: "healthy" | "degraded" | "offline"; uptime: string }> = {
  "nexus-alpha": { name: "Nexus Alpha", region: "US East (Virginia)", latency: "~20ms", status: "healthy", uptime: "99.97%" },
  "cygnus-eu": { name: "Cygnus", region: "EU West (Frankfurt)", latency: "~35ms", status: "healthy", uptime: "99.94%" },
  "orion-apac": { name: "Orion", region: "APAC (Singapore)", latency: "~45ms", status: "healthy", uptime: "99.91%" },
  "lyra-sa": { name: "Lyra", region: "SA East (São Paulo)", latency: "~120ms", status: "healthy", uptime: "99.88%" },
  "draco-me": { name: "Draco", region: "ME (Bahrain)", latency: "~90ms", status: "healthy", uptime: "99.85%" },
  "phoenix-af": { name: "Phoenix", region: "AF (Cape Town)", latency: "~150ms", status: "healthy", uptime: "99.82%" },
  "vega-au": { name: "Vega", region: "OCE (Sydney)", latency: "~80ms", status: "healthy", uptime: "99.91%" },
  "sirius-in": { name: "Sirius", region: "IN (Mumbai)", latency: "~65ms", status: "healthy", uptime: "99.87%" },
  "polaris-an": { name: "Polaris", region: "AN (Antarctica Relay)", latency: "~200ms", status: "healthy", uptime: "99.79%" },
};

export const REALMS: RealmDef[] = [
  {
    id: "realm-01",
    name: "Asgard Prime",
    tier: "Sovereign",
    tierNumber: 1,
    universe: "Nexus Crown",
    universeDescription: "The apex cluster of the known galaxy",
    server: "nexus-alpha",
    serverLabel: "Nexus Alpha (US)",
    status: "live",
    icon: "👑",
    bannerGradient: "from-yellow-500 via-amber-500 to-orange-600",
    accentColor: "#f59e0b",
    textColor: "text-amber-400",
    borderColor: "border-amber-500/40",
    glowColor: "shadow-[0_0_30px_rgba(245,158,11,0.2)]",
    population: "14.2M",
    populationCount: 14200000,
    onlinePlayers: 487000,
    totalEmpires: 128400,
    avgPower: 847000,
    description: "The crown jewel of the galactic order. Asgard Prime is the seat of supreme command, where the most powerful empires vie for dominion over the known universe.",
    lore: "Founded at the dawn of the galactic age, Asgard Prime has been the crucible where legends are forged. Its councils shape the fate of billions, and its fleets patrol the most contested corridors of space.",
    bonuses: [
      { type: "diplomacy", value: 15, label: "+15% Diplomacy" },
      { type: "production", value: 10, label: "+10% Production" },
    ],
    features: ["Apex Fleet Command", "Galactic Council Access", "Prestige Diplomacy", "Crown World Events"],
    restrictions: ["Minimum 500K power to enter", "Monthly maintenance tax +20%"],
    recommendedFor: ["Diplomacy mains", "Alliance leaders", "Endgame players"],
    difficulty: "Veteran",
    startResources: { credits: 50000, minerals: 30000, energy: 20000, alloys: 15000, research: 10000, influence: 5000 },
    specialMechanic: "Crown Authority — Hold the Throne to receive +25% to all production and unique Crown Edicts.",
    seasonalEvent: "War of Crowns — Quarterly empire-vs-empire tournament for control of the Crown World.",
    maxAllianceSize: 40,
    galaxySize: "Massive",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-02",
    name: "Midgard Frontier",
    tier: "Dominion",
    tierNumber: 2,
    universe: "Nexus Crown",
    universeDescription: "The apex cluster of the known galaxy",
    server: "nexus-alpha",
    serverLabel: "Nexus Alpha (US)",
    status: "live",
    icon: "🌍",
    bannerGradient: "from-green-500 via-emerald-500 to-teal-600",
    accentColor: "#10b981",
    textColor: "text-emerald-400",
    borderColor: "border-emerald-500/40",
    glowColor: "shadow-[0_0_30px_rgba(16,185,129,0.2)]",
    population: "11.8M",
    populationCount: 11800000,
    onlinePlayers: 412000,
    totalEmpires: 105200,
    avgPower: 623000,
    description: "The heartland of expansion and opportunity. Midgard Frontier rewards balanced empire-building with generous colonization bonuses and thriving trade networks.",
    lore: "Once a scattered collection of frontier worlds, Midgard has unified under a banner of cooperative growth. Its worlds bloom with diverse populations and its trade routes span the sector.",
    bonuses: [
      { type: "colonization", value: 20, label: "+20% Colonization" },
      { type: "economy", value: 10, label: "+10% Economy" },
    ],
    features: ["Colonial Expansion Bonus", "Trade Route Mastery", "Population Growth +25%", "Frontier Markets"],
    restrictions: [],
    recommendedFor: ["New players", "Economy builders", "Expansion specialists"],
    difficulty: "Beginner",
    startResources: { credits: 40000, minerals: 40000, energy: 25000, alloys: 10000, research: 8000, influence: 3000 },
    specialMechanic: "Frontier Spirit — Each new colony provides a stacking +2% bonus to all resource production for 30 days.",
    seasonalEvent: "Gold Rush — Limited-time resource spikes appear across the frontier, rewarding fast expansion.",
    maxAllianceSize: 35,
    galaxySize: "Large",
    speedMultiplier: 1.1,
  },
  {
    id: "realm-03",
    name: "Alfheim Radiant",
    tier: "Ascendant",
    tierNumber: 3,
    universe: "Aurora Reach",
    universeDescription: "A luminous region of scientific discovery",
    server: "cygnus-eu",
    serverLabel: "Cygnus (EU)",
    status: "live",
    icon: "🔬",
    bannerGradient: "from-blue-500 via-cyan-500 to-sky-600",
    accentColor: "#06b6d4",
    textColor: "text-cyan-400",
    borderColor: "border-cyan-500/40",
    glowColor: "shadow-[0_0_30px_rgba(6,182,212,0.2)]",
    population: "9.4M",
    populationCount: 9400000,
    onlinePlayers: 315000,
    totalEmpires: 82100,
    avgPower: 534000,
    description: "The intellectual capital of the galaxy. Alfheim Radiant accelerates all research and unlocks unique technologies unavailable elsewhere.",
    lore: "Alfheim's ancient precursor libraries hold secrets that accelerate scientific progress by decades. Empires here pioneer breakthroughs that reshape galactic civilization.",
    bonuses: [
      { type: "research", value: 25, label: "+25% Research" },
    ],
    features: ["Accelerated Research", "Unique Tech Trees", "Lab Synergy Bonuses", "Science Council"],
    restrictions: ["Military production -10%"],
    recommendedFor: ["Tech rushers", "Research specialists", "Science Victory seekers"],
    difficulty: "Intermediate",
    startResources: { credits: 35000, minerals: 25000, energy: 30000, alloys: 8000, research: 20000, influence: 4000 },
    specialMechanic: "Resonance Fields — Research buildings produce 50% more when adjacent to other research buildings.",
    seasonalEvent: "Technological Singularity — A precursor artifact activates, doubling all research for 72 hours.",
    maxAllianceSize: 30,
    galaxySize: "Medium",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-04",
    name: "Jotunheim Bastion",
    tier: "Warfront",
    tierNumber: 4,
    universe: "Aurora Reach",
    universeDescription: "A luminous region of scientific discovery",
    server: "cygnus-eu",
    serverLabel: "Cygnus (EU)",
    status: "live",
    icon: "⚔️",
    bannerGradient: "from-red-500 via-orange-500 to-amber-600",
    accentColor: "#ef4444",
    textColor: "text-red-400",
    borderColor: "border-red-500/40",
    glowColor: "shadow-[0_0_30px_rgba(239,68,68,0.2)]",
    population: "8.9M",
    populationCount: 8900000,
    onlinePlayers: 298000,
    totalEmpires: 76400,
    avgPower: 712000,
    description: "The militarized frontier where only the strongest survive. Jotunheim Bastion amplifies defense and assault capabilities for total war doctrine.",
    lore: "Born from centuries of border conflict, Jotunheim's worlds are fortified citadels. Its shipyards produce warships of unmatched durability, and its commanders are feared across the sector.",
    bonuses: [
      { type: "defense", value: 20, label: "+20% Defense" },
      { type: "military", value: 15, label: "+15% Military" },
    ],
    features: ["Fortress World Bonus", "Shipyard Speed +30%", "Defense Grid Supreme", "Warlord Council"],
    restrictions: ["Research speed -15%"],
    recommendedFor: ["PvP players", "Defense builders", "Fleet commanders"],
    difficulty: "Advanced",
    startResources: { credits: 30000, minerals: 35000, energy: 20000, alloys: 25000, research: 5000, influence: 3000 },
    specialMechanic: "Iron Wall — Defensive structures have +40% HP and repair 2x faster after combat.",
    seasonalEvent: "Siege of Jotunheim — Massive AI armada attacks all border systems, rewarding defenders with exclusive blueprints.",
    maxAllianceSize: 45,
    galaxySize: "Large",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-05",
    name: "Vanaheim Bloom",
    tier: "Prosperity",
    tierNumber: 5,
    universe: "Verdant Expanse",
    universeDescription: "A lush region of abundant natural resources",
    server: "orion-apac",
    serverLabel: "Orion (APAC)",
    status: "live",
    icon: "💰",
    bannerGradient: "from-emerald-400 via-teal-500 to-cyan-600",
    accentColor: "#34d399",
    textColor: "text-emerald-400",
    borderColor: "border-emerald-400/40",
    glowColor: "shadow-[0_0_30px_rgba(52,211,153,0.2)]",
    population: "10.6M",
    populationCount: 10600000,
    onlinePlayers: 378000,
    totalEmpires: 94300,
    avgPower: 489000,
    description: "The wealthiest realm in the galaxy. Vanaheim Bloom offers unparalleled resource generation and economic supremacy for trade-focused empires.",
    lore: "Vanaheim's verdant worlds produce rare minerals and bio-resources found nowhere else. Its merchant princes trade across all realms, and its banks underwrite galactic commerce.",
    bonuses: [
      { type: "economy", value: 25, label: "+25% Economy" },
      { type: "production", value: 10, label: "+10% Production" },
    ],
    features: ["Resource Surge Events", "Trade Route Mastery", "Market Fee -50%", "Merchant Guilds"],
    restrictions: ["Fleet capacity -10%"],
    recommendedFor: ["Economy mains", "Trade empires", "Passive builders"],
    difficulty: "Intermediate",
    startResources: { credits: 60000, minerals: 50000, energy: 30000, alloys: 12000, research: 7000, influence: 4000 },
    specialMechanic: "Bloom Cycle — Every 48 hours, resource production doubles for 6 hours across all colonies.",
    seasonalEvent: "Harvest Festival — Double resource drops from all planetary events for one week.",
    maxAllianceSize: 30,
    galaxySize: "Medium",
    speedMultiplier: 1.2,
  },
  {
    id: "realm-06",
    name: "Svartalf Forge",
    tier: "Industrial",
    tierNumber: 6,
    universe: "Celestial Arc",
    universeDescription: "A mysterious arc of precursor worlds and ancient technology",
    server: "phoenix-af",
    serverLabel: "Phoenix (AF)",
    status: "live",
    icon: "🔨",
    bannerGradient: "from-slate-400 via-zinc-500 to-neutral-600",
    accentColor: "#a1a1aa",
    textColor: "text-zinc-400",
    borderColor: "border-zinc-500/40",
    glowColor: "shadow-[0_0_30px_rgba(161,161,170,0.2)]",
    population: "7.7M",
    populationCount: 7700000,
    onlinePlayers: 256000,
    totalEmpires: 67800,
    avgPower: 598000,
    description: "The industrial backbone of the galaxy. Svartalf Forge excels in shipbuilding, blueprint mastery, and producing elite hull components.",
    lore: "Svartalf's foundries burn with plasma fires visible from orbit. Its engineers craft vessels and weapons that set the standard for galactic military hardware.",
    bonuses: [
      { type: "production", value: 25, label: "+25% Production" },
      { type: "military", value: 10, label: "+10% Military" },
    ],
    features: ["Shipyard Speed +50%", "Blueprint Mastery", "Alloy Production +40%", "Forge World Bonus"],
    restrictions: ["Research cost +10%"],
    recommendedFor: ["Ship builders", "Industrialists", "Blueprint collectors"],
    difficulty: "Intermediate",
    startResources: { credits: 25000, minerals: 60000, energy: 25000, alloys: 30000, research: 6000, influence: 2500 },
    specialMechanic: "Forge Mastery — Ship construction costs -20% and build speed +30% for all vessels.",
    seasonalEvent: "Grand Forge — Players compete to build the most ships in 48 hours, with top builders earning legendary blueprints.",
    maxAllianceSize: 35,
    galaxySize: "Medium",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-07",
    name: "Muspel Pyre",
    tier: "Strike",
    tierNumber: 7,
    universe: "Crimson Verge",
    universeDescription: "A volatile frontier of constant conflict",
    server: "lyra-sa",
    serverLabel: "Lyra (SA)",
    status: "live",
    icon: "🔥",
    bannerGradient: "from-orange-500 via-red-500 to-rose-600",
    accentColor: "#f97316",
    textColor: "text-orange-400",
    borderColor: "border-orange-500/40",
    glowColor: "shadow-[0_0_30px_rgba(249,115,22,0.2)]",
    population: "6.3M",
    populationCount: 6300000,
    onlinePlayers: 234000,
    totalEmpires: 58900,
    avgPower: 678000,
    description: "The burning crucible of galactic warfare. Muspel Pyre rewards aggressive expansion, raiding, and total fleet superiority.",
    lore: "Muspel's worlds orbit unstable stars, and its people are forged in the fires of constant conflict. Only the aggressive thrive here — the timid are consumed.",
    bonuses: [
      { type: "military", value: 25, label: "+25% Military" },
      { type: "production", value: 10, label: "+10% Production" },
    ],
    features: ["Raid Bonus +30%", "Fleet Speed +20%", "Pillage Rewards", "Warlord Rank System"],
    restrictions: ["Defense structures -20% effectiveness", "Alliance size capped at 25"],
    recommendedFor: ["PvP raiders", "Aggressive players", "Fleet combat specialists"],
    difficulty: "Advanced",
    startResources: { credits: 30000, minerals: 25000, energy: 20000, alloys: 20000, research: 5000, influence: 2000 },
    specialMechanic: "Inferno Rage — Winning battles grants stacking +5% fleet attack bonus (max +50%) that decays over time.",
    seasonalEvent: "Inferno War — All shields are disabled for 24 hours, turning the realm into a kill-or-be-killed free-for-all.",
    maxAllianceSize: 25,
    galaxySize: "Small",
    speedMultiplier: 1.3,
  },
  {
    id: "realm-08",
    name: "Niflheim Veil",
    tier: "Shadow",
    tierNumber: 8,
    universe: "Void Walker",
    universeDescription: "A shadowy expanse of hidden routes and unseen dangers",
    server: "vega-au",
    serverLabel: "Vega (OCE)",
    status: "live",
    icon: "🌑",
    bannerGradient: "from-purple-500 via-violet-500 to-indigo-600",
    accentColor: "#a855f7",
    textColor: "text-purple-400",
    borderColor: "border-purple-500/40",
    glowColor: "shadow-[0_0_30px_rgba(168,85,247,0.2)]",
    population: "5.8M",
    populationCount: 5800000,
    onlinePlayers: 198000,
    totalEmpires: 51200,
    avgPower: 512000,
    description: "The unseen hand of galactic politics. Niflheim Veil is the realm of spies, saboteurs, and shadow emperors who rule from the darkness.",
    lore: "Hidden within dense nebulae, Niflheim's worlds are shrouded in perpetual twilight. Its intelligence networks span the galaxy, and its agents move unseen between empires.",
    bonuses: [
      { type: "espionage", value: 30, label: "+30% Espionage" },
      { type: "diplomacy", value: 10, label: "+10% Diplomacy" },
    ],
    features: ["Spy Network Supreme", "Intel Gathering +40%", "Sabotage Mastery", "Shadow Council"],
    restrictions: ["Fleet visibility -20%", "Public intel -30%"],
    recommendedFor: ["Espionage mains", "Spy enthusiasts", "Information warfare"],
    difficulty: "Advanced",
    startResources: { credits: 35000, minerals: 20000, energy: 25000, alloys: 10000, research: 15000, influence: 8000 },
    specialMechanic: "Veil of Shadows — Espionage actions cost 30% less and have +25% success rate. Assassination missions unlock at lower empire levels.",
    seasonalEvent: "Shadow Games — Espionage point leaderboard with exclusive spy-themed cosmetics and agent skins.",
    maxAllianceSize: 20,
    galaxySize: "Small",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-09",
    name: "Hel Nexus",
    tier: "Endgame",
    tierNumber: 9,
    universe: "Oblivion Gate",
    universeDescription: "The bleeding edge of galactic collapse",
    server: "draco-me",
    serverLabel: "Draco (ME)",
    status: "live",
    icon: "💀",
    bannerGradient: "from-rose-500 via-pink-500 to-fuchsia-600",
    accentColor: "#f43f5e",
    textColor: "text-rose-400",
    borderColor: "border-rose-500/40",
    glowColor: "shadow-[0_0_30px_rgba(244,63,94,0.2)]",
    population: "4.9M",
    populationCount: 4900000,
    onlinePlayers: 167000,
    totalEmpires: 42800,
    avgPower: 923000,
    description: "The ultimate proving ground. Hel Nexus is reserved for veteran empires seeking the apex of power through ascension loops and cosmic mastery.",
    lore: "At the edge of galactic collapse, Hel Nexus exists in a state of perpetual entropy. Only the most advanced empires can survive here, where the laws of physics bend and reality fractures.",
    bonuses: [
      { type: "production", value: 15, label: "+15% Production" },
      { type: "research", value: 15, label: "+15% Research" },
      { type: "military", value: 15, label: "+15% Military" },
    ],
    features: ["Ascension Loops", "Reality Warping", "Omega Technologies", "Nexus Collapse Events"],
    restrictions: ["Minimum 2M power to enter", "No new accounts", "Permanent death mode optional"],
    recommendedFor: ["Veteran players", "Ascension chasers", "Hardcore gamers"],
    difficulty: "Veteran",
    startResources: { credits: 80000, minerals: 60000, energy: 50000, alloys: 40000, research: 30000, influence: 10000 },
    specialMechanic: "Entropy Surge — Every 72 hours, a random system undergoes an entropy event, reshaping the map and creating new opportunities.",
    seasonalEvent: "Nexus Collapse — The galaxy map partially resets every season, forcing empires to re-expand and re-fortify.",
    maxAllianceSize: 20,
    galaxySize: "Small",
    speedMultiplier: 1.5,
  },
  {
    id: "realm-10",
    name: "Verdant Oasis",
    tier: "Prosperity",
    tierNumber: 5,
    universe: "Verdant Expanse",
    universeDescription: "A lush region of abundant natural resources",
    server: "orion-apac",
    serverLabel: "Orion (APAC)",
    status: "live",
    icon: "🌿",
    bannerGradient: "from-emerald-400 via-green-500 to-teal-600",
    accentColor: "#34d399",
    textColor: "text-emerald-400",
    borderColor: "border-emerald-400/40",
    glowColor: "shadow-[0_0_30px_rgba(52,211,153,0.2)]",
    population: "8.2M",
    populationCount: 8200000,
    onlinePlayers: 280000,
    totalEmpires: 72000,
    avgPower: 380000,
    description: "A tranquil haven for growers and builders. Verdant Oasis offers abundant fertile worlds and unmatched agricultural output for peaceful expansion.",
    lore: "The Verdant Oasis sector was once a forgotten agricultural hub, rediscovered by settlers seeking refuge from the endless wars. Its worlds now produce food and resources that sustain entire fleets.",
    bonuses: [
      { type: "economy", value: 20, label: "+20% Economy" },
      { type: "colonization", value: 15, label: "+15% Colonization" },
    ],
    features: ["Fertile World Bonus", "Harvest Cycles", "Resource Prospecting", "Agricultural Guilds"],
    restrictions: [],
    recommendedFor: ["New players", "Farmers", "Casual builders"],
    difficulty: "Beginner",
    startResources: { credits: 45000, minerals: 45000, energy: 25000, alloys: 10000, research: 7000, influence: 3000 },
    specialMechanic: "Verdant Cycle — Farms and food production buildings produce +100% resources during peak growth cycles that trigger every 48 hours.",
    seasonalEvent: "Bloom Festival — Double crop yields across all agricultural worlds for one week, with exclusive decorative rewards.",
    maxAllianceSize: 35,
    galaxySize: "Large",
    speedMultiplier: 1.2,
  },
  {
    id: "realm-11",
    name: "Crimson Front",
    tier: "Strike",
    tierNumber: 7,
    universe: "Crimson Verge",
    universeDescription: "A volatile frontier of constant conflict",
    server: "lyra-sa",
    serverLabel: "Lyra (SA)",
    status: "live",
    icon: "⚡",
    bannerGradient: "from-orange-500 via-red-500 to-rose-600",
    accentColor: "#f97316",
    textColor: "text-orange-400",
    borderColor: "border-orange-500/40",
    glowColor: "shadow-[0_0_30px_rgba(249,115,22,0.2)]",
    population: "5.5M",
    populationCount: 5500000,
    onlinePlayers: 210000,
    totalEmpires: 52000,
    avgPower: 650000,
    description: "The frontline of galactic warfare. Crimson Front rewards fortified positions and coordinated assaults with powerful defensive bonuses.",
    lore: "Carved from a war-torn nebula, the Crimson Front is a perpetual battlefield where empires test their military might. Its chokepoints are littered with the wreckage of countless fleets.",
    bonuses: [
      { type: "defense", value: 20, label: "+20% Defense" },
      { type: "military", value: 15, label: "+15% Military" },
    ],
    features: ["Fortification Bonus", "Frontline Resupply", "Starbase Overcharge", "War Asset Recycling"],
    restrictions: ["Research speed -15%", "Alliance size capped at 25"],
    recommendedFor: ["PvP fighters", "Defense specialists", "Frontline commanders"],
    difficulty: "Advanced",
    startResources: { credits: 25000, minerals: 30000, energy: 20000, alloys: 25000, research: 5000, influence: 2000 },
    specialMechanic: "Frontline Fortifications — All defensive structures gain +30% HP and deal +20% damage to attacking fleets.",
    seasonalEvent: "Crimson Tide — Territory control event where empires fight for control of strategic chokepoints for exclusive war assets.",
    maxAllianceSize: 25,
    galaxySize: "Small",
    speedMultiplier: 1.3,
  },
  {
    id: "realm-12",
    name: "Oblivion Gate",
    tier: "Endgame",
    tierNumber: 9,
    universe: "Oblivion Gate",
    universeDescription: "The bleeding edge of galactic collapse",
    server: "draco-me",
    serverLabel: "Draco (ME)",
    status: "live",
    icon: "🕳️",
    bannerGradient: "from-rose-500 via-pink-500 to-fuchsia-600",
    accentColor: "#f43f5e",
    textColor: "text-rose-400",
    borderColor: "border-rose-500/40",
    glowColor: "shadow-[0_0_30px_rgba(244,63,94,0.2)]",
    population: "4.5M",
    populationCount: 4500000,
    onlinePlayers: 150000,
    totalEmpires: 40000,
    avgPower: 890000,
    description: "The ultimate gamble for the fearless. Oblivion Gate offers unparalleled rewards at the edge of annihilation, where every victory could be your last.",
    lore: "At the heart of the Oblivion Gate universe lies a phenomenon that defies comprehension — a tear in reality that grants immense power to those who dare approach it. Only the brave or the foolish enter.",
    bonuses: [
      { type: "military", value: 20, label: "+20% Military" },
      { type: "production", value: 15, label: "+15% Production" },
    ],
    features: ["Reality Rifts", "Omega Loot Drops", "Cataclysm Events", "Gate World Access"],
    restrictions: ["Minimum 1.5M power to enter", "No new accounts", "Permanent death mode optional"],
    recommendedFor: ["Veteran players", "Risk-takers", "Power gamers"],
    difficulty: "Veteran",
    startResources: { credits: 75000, minerals: 55000, energy: 45000, alloys: 35000, research: 25000, influence: 8000 },
    specialMechanic: "Oblivion's Gambit — Every combat has a 10% chance to trigger a cataclysmic event that damages both attacker and defender but yields triple salvage rewards.",
    seasonalEvent: "Gate Collapse — Systems near the Oblivion Gate periodically destabilize, creating rare resource deposits and high-value target zones.",
    maxAllianceSize: 20,
    galaxySize: "Small",
    speedMultiplier: 1.5,
  },
  {
    id: "realm-13",
    name: "Arc Prime",
    tier: "Ascendant",
    tierNumber: 3,
    universe: "Celestial Arc",
    universeDescription: "A mysterious arc of precursor worlds and ancient technology",
    server: "phoenix-af",
    serverLabel: "Phoenix (AF)",
    status: "live",
    icon: "🏛️",
    bannerGradient: "from-blue-500 via-cyan-500 to-sky-600",
    accentColor: "#06b6d4",
    textColor: "text-cyan-400",
    borderColor: "border-cyan-500/40",
    glowColor: "shadow-[0_0_30px_rgba(6,182,212,0.2)]",
    population: "6.5M",
    populationCount: 6500000,
    onlinePlayers: 240000,
    totalEmpires: 58000,
    avgPower: 480000,
    description: "The gateway to a forgotten era. Arc Prime brims with precursor relics and ancient technologies waiting to be deciphered by bold explorers.",
    lore: "The Celestial Arc is strewn with the remnants of a civilization that vanished eons ago. Arc Prime sits at the center of this archaeological wonderland, where each excavation rewrites galactic history.",
    bonuses: [
      { type: "research", value: 20, label: "+20% Research" },
      { type: "colonization", value: 10, label: "+10% Colonization" },
    ],
    features: ["Precursor Relic Hunting", "Ancient Tech Reverse Engineering", "Archaeology Expeditions", "Arc World Access"],
    restrictions: ["Military production -10%"],
    recommendedFor: ["Explorers", "Archaeology enthusiasts", "Tech collectors"],
    difficulty: "Intermediate",
    startResources: { credits: 35000, minerals: 25000, energy: 30000, alloys: 8000, research: 22000, influence: 4000 },
    specialMechanic: "Precursor Relics — Scanning ancient ruins has a 15% chance to unlock unique technologies not available anywhere else in the galaxy.",
    seasonalEvent: "Arc Expedition — Cooperative exploration event to uncover the secrets of the Celestial Arc, with exclusive precursor-themed rewards.",
    maxAllianceSize: 30,
    galaxySize: "Medium",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-14",
    name: "Void Gate",
    tier: "Shadow",
    tierNumber: 8,
    universe: "Void Walker",
    universeDescription: "A shadowy expanse of hidden routes and unseen dangers",
    server: "vega-au",
    serverLabel: "Vega (OCE)",
    status: "live",
    icon: "🌀",
    bannerGradient: "from-purple-500 via-violet-500 to-indigo-600",
    accentColor: "#a855f7",
    textColor: "text-purple-400",
    borderColor: "border-purple-500/40",
    glowColor: "shadow-[0_0_30px_rgba(168,85,247,0.2)]",
    population: "5.2M",
    populationCount: 5200000,
    onlinePlayers: 185000,
    totalEmpires: 48000,
    avgPower: 540000,
    description: "The crossroads of shadow and intrigue. Void Gate offers unparalleled opportunities for covert operations and information warfare.",
    lore: "The Void Walker expanse is crisscrossed by unstable wormholes and hidden passages known only to the most daring navigators. Void Gate serves as the hub for all who trade in secrets.",
    bonuses: [
      { type: "espionage", value: 25, label: "+25% Espionage" },
      { type: "diplomacy", value: 15, label: "+15% Diplomacy" },
    ],
    features: ["Wormhole Navigation", "Covert Operations Hub", "Intel Exchange", "Shadow Markets"],
    restrictions: ["Fleet visibility -20%", "Public intel -30%"],
    recommendedFor: ["Espionage mains", "Spy enthusiasts", "Information warfare"],
    difficulty: "Advanced",
    startResources: { credits: 30000, minerals: 20000, energy: 25000, alloys: 10000, research: 15000, influence: 8000 },
    specialMechanic: "Void Passage — Stealth fleets gain +50% speed and can pass through hostile territory completely undetected.",
    seasonalEvent: "Void Incursion — Sabotage missions yield triple rewards for 48 hours, with exclusive agent unlockables.",
    maxAllianceSize: 20,
    galaxySize: "Small",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-15",
    name: "Iron Bastion",
    tier: "Warfront",
    tierNumber: 4,
    universe: "Iron Dominion",
    universeDescription: "A heavily fortified region of military-industrial supremacy",
    server: "sirius-in",
    serverLabel: "Sirius (IN)",
    status: "live",
    icon: "🛡️",
    bannerGradient: "from-red-500 via-orange-500 to-amber-600",
    accentColor: "#ef4444",
    textColor: "text-red-400",
    borderColor: "border-red-500/40",
    glowColor: "shadow-[0_0_30px_rgba(239,68,68,0.2)]",
    population: "6.0M",
    populationCount: 6000000,
    onlinePlayers: 225000,
    totalEmpires: 55000,
    avgPower: 680000,
    description: "The unbreachable fortress of the Iron Dominion. Iron Bastion is optimized for defense, with reinforced stations and impenetrable planetary shields.",
    lore: "The Iron Dominion was forged in the crucible of endless war. Iron Bastion represents the pinnacle of their military engineering — a fortress sector that has never fallen to invasion.",
    bonuses: [
      { type: "defense", value: 25, label: "+25% Defense" },
      { type: "military", value: 10, label: "+10% Military" },
    ],
    features: ["Fortress World Bonus", "Shield Network Supreme", "Garrison Upkeep -30%", "War Council"],
    restrictions: ["Research speed -15%"],
    recommendedFor: ["PvP players", "Defense builders", "Fleet commanders"],
    difficulty: "Advanced",
    startResources: { credits: 30000, minerals: 35000, energy: 20000, alloys: 25000, research: 5000, influence: 3000 },
    specialMechanic: "Iron Fortress — Stations and defensive platforms cost 30% less, build 40% faster, and regenerate shields 2x faster after combat.",
    seasonalEvent: "Dominion War — Alliance-vs-alliance territory control event with exclusive fleet cosmetics and permanent sector bonuses.",
    maxAllianceSize: 45,
    galaxySize: "Large",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-16",
    name: "Iron Foundry",
    tier: "Industrial",
    tierNumber: 6,
    universe: "Iron Dominion",
    universeDescription: "A heavily fortified region of military-industrial supremacy",
    server: "sirius-in",
    serverLabel: "Sirius (IN)",
    status: "live",
    icon: "⚙️",
    bannerGradient: "from-slate-400 via-zinc-500 to-neutral-600",
    accentColor: "#a1a1aa",
    textColor: "text-zinc-400",
    borderColor: "border-zinc-500/40",
    glowColor: "shadow-[0_0_30px_rgba(161,161,170,0.2)]",
    population: "7.0M",
    populationCount: 7000000,
    onlinePlayers: 260000,
    totalEmpires: 65000,
    avgPower: 560000,
    description: "The industrial heart of the Iron Dominion. Iron Foundry churns out warships and war materiel at a pace unmatched across the galaxy.",
    lore: "Iron Foundry's orbital shipyards span entire gas giants, producing fleets that darken the skies. Its assembly lines never stop, and its forges are the envy of every warlord.",
    bonuses: [
      { type: "production", value: 25, label: "+25% Production" },
      { type: "military", value: 10, label: "+10% Military" },
    ],
    features: ["Shipyard Speed +50%", "Assembly Line Efficiency", "Alloy Refinement +40%", "Foundry World Bonus"],
    restrictions: ["Research cost +10%"],
    recommendedFor: ["Ship builders", "Industrialists", "Fleet producers"],
    difficulty: "Intermediate",
    startResources: { credits: 25000, minerals: 60000, energy: 25000, alloys: 30000, research: 6000, influence: 2500 },
    specialMechanic: "Foundry Efficiency — All ship construction costs -25% and build speed +40% in systems with orbital foundries.",
    seasonalEvent: "Grand Assembly — Build the most ships in a 72-hour window to win rare blueprints and exclusive ship skins.",
    maxAllianceSize: 35,
    galaxySize: "Medium",
    speedMultiplier: 1.0,
  },
  {
    id: "realm-17",
    name: "Eternal Frontier",
    tier: "Dominion",
    tierNumber: 2,
    universe: "Eternal Edge",
    universeDescription: "The untamed frontier of endless possibilities and discovery",
    server: "polaris-an",
    serverLabel: "Polaris (AN)",
    status: "live",
    icon: "🚀",
    bannerGradient: "from-green-500 via-emerald-500 to-teal-600",
    accentColor: "#10b981",
    textColor: "text-emerald-400",
    borderColor: "border-emerald-500/40",
    glowColor: "shadow-[0_0_30px_rgba(16,185,129,0.2)]",
    population: "9.0M",
    populationCount: 9000000,
    onlinePlayers: 300000,
    totalEmpires: 80000,
    avgPower: 350000,
    description: "The final frontier of galactic colonization. Eternal Frontier offers endless room for expansion and discovery beyond the known maps.",
    lore: "The Eternal Edge marks the boundary between charted space and the unknown. Settlers here are pioneers, pushing into uncharted systems where every planet holds the promise of a new beginning.",
    bonuses: [
      { type: "colonization", value: 25, label: "+25% Colonization" },
      { type: "economy", value: 10, label: "+10% Economy" },
    ],
    features: ["Colonial Expansion Bonus", "Uncharted Systems", "Pioneer Settlements", "Frontier Outposts"],
    restrictions: [],
    recommendedFor: ["New players", "Colonizers", "Expansionists"],
    difficulty: "Beginner",
    startResources: { credits: 40000, minerals: 45000, energy: 25000, alloys: 10000, research: 7000, influence: 3500 },
    specialMechanic: "Pioneer Spirit — First 10 colonies are established at half cost with +50% starting population and a free defensive garrison.",
    seasonalEvent: "Great Expansion — Territorial acquisition event with bonus influence rewards and exclusive frontier titles for claiming new systems.",
    maxAllianceSize: 35,
    galaxySize: "Large",
    speedMultiplier: 1.1,
  },
  {
    id: "realm-18",
    name: "Eternal Wilds",
    tier: "Prosperity",
    tierNumber: 5,
    universe: "Eternal Edge",
    universeDescription: "The untamed frontier of endless possibilities and discovery",
    server: "polaris-an",
    serverLabel: "Polaris (AN)",
    status: "live",
    icon: "🌲",
    bannerGradient: "from-emerald-400 via-teal-500 to-cyan-600",
    accentColor: "#34d399",
    textColor: "text-emerald-400",
    borderColor: "border-emerald-400/40",
    glowColor: "shadow-[0_0_30px_rgba(52,211,153,0.2)]",
    population: "8.0M",
    populationCount: 8000000,
    onlinePlayers: 270000,
    totalEmpires: 70000,
    avgPower: 420000,
    description: "A rugged wilderness of untapped resources. Eternal Wilds challenges survivors to thrive in the harshest conditions with the richest rewards.",
    lore: "The Eternal Wilds are a vast, untamed region where nature itself fights back against colonization. Only the most resourceful empires can tame these worlds and extract their incredible wealth.",
    bonuses: [
      { type: "economy", value: 20, label: "+20% Economy" },
      { type: "production", value: 15, label: "+15% Production" },
    ],
    features: ["Wild Resource Nodes", "Survival Camps", "Expedition Rewards", "Natural Defenses"],
    restrictions: ["No trade routes with other realms"],
    recommendedFor: ["Survivalists", "Solo players", "Resource gatherers"],
    difficulty: "Intermediate",
    startResources: { credits: 30000, minerals: 35000, energy: 35000, alloys: 15000, research: 8000, influence: 2000 },
    specialMechanic: "Wild Harvest — All resource gathering actions yield +50% more, but hostile NPC fleets are 2x more aggressive and spawn more frequently.",
    seasonalEvent: "Wild Storm — Periodic environmental hazards sweep the galaxy, destroying unprotected outposts but revealing rare resource nodes and ancient ruins.",
    maxAllianceSize: 30,
    galaxySize: "Large",
    speedMultiplier: 1.2,
  },
];

export function getRealmById(id: string): RealmDef | undefined {
  return REALMS.find((r) => r.id === id);
}

export function getRealmsByServer(server: ServerRegion): RealmDef[] {
  return REALMS.filter((r) => r.server === server);
}

export function getRealmsByDifficulty(difficulty: RealmDef["difficulty"]): RealmDef[] {
  return REALMS.filter((r) => r.difficulty === difficulty);
}

export function getTotalPopulation(): string {
  const total = REALMS.reduce((sum, r) => sum + r.populationCount, 0);
  if (total >= 1_000_000_000) return `${(total / 1_000_000_000).toFixed(1)}B`;
  if (total >= 1_000_000) return `${(total / 1_000_000).toFixed(1)}M`;
  return total.toLocaleString();
}

export function getTotalOnlinePlayers(): number {
  return REALMS.reduce((sum, r) => sum + r.onlinePlayers, 0);
}

export function getTotalEmpires(): number {
  return REALMS.reduce((sum, r) => sum + r.totalEmpires, 0);
}
