import type { OgameCatalogEntryDefinition } from "./ogameCatalogConfig";

/**
 * Extended OGame ships from UniEngine (IDs 216-224)
 * Ships beyond the standard OGame 202-215 range.
 * Includes: orbital_station, mega_cargo_ship, annihilator,
 * space_shuttle, space_carrier, hadron_bomber,
 * plasmic_ship, proton_destroyer, disintegrating_ship
 */
export const UNIVERSE_EXTENDED_SHIPS: OgameCatalogEntryDefinition[] = [
  {
    id: "orbitalStation",
    categoryId: "fleet",
    entryType: "ship",
    name: "Orbital Station",
    description: "Stationary orbital defense platform with powerful laser and plasma armaments.",
    baseCost: { metal: 2500000, crystal: 3500000, deuterium: 1000000 },
    baseTimeSeconds: 6000,
    growthFactor: 1,
    prerequisites: { shipyard: 8, plasmaTech: 12, armourTech: 6, shieldingTech: 10, laserTech: 12, computerTech: 10 },
    stats: { attack: 100000, shield: 60000, hull: 2500000, speed: 0, cargo: 0 },
  },
  {
    id: "megaCargoShip",
    categoryId: "fleet",
    entryType: "ship",
    name: "Mega Cargo Ship",
    description: "Ultra-heavy transport with massive cargo capacity for bulk logistics.",
    baseCost: { metal: 25000, crystal: 25000, deuterium: 10000 },
    baseTimeSeconds: 800,
    growthFactor: 1,
    prerequisites: { shipyard: 8, naniteFactory: 1, hyperspaceDrive: 6, shieldingTech: 5 },
    stats: { attack: 5, shield: 40, hull: 24000, speed: 17500, cargo: 125000 },
  },
  {
    id: "annihilatorShip",
    categoryId: "fleet",
    entryType: "ship",
    name: "Annihilator",
    description: "Devastating super-ship armed with antimatter technology.",
    baseCost: { metal: 6000000, crystal: 3500000, deuterium: 3500000 },
    baseTimeSeconds: 15000,
    growthFactor: 1,
    prerequisites: { shipyard: 15, hyperspaceDrive: 7, armourTech: 12, shieldingTech: 6, computerTech: 12 },
    stats: { attack: 400000, shield: 70000, hull: 6500000, speed: 12000, cargo: 1500 },
  },
  {
    id: "spaceShuttle",
    categoryId: "fleet",
    entryType: "ship",
    name: "Space Shuttle",
    description: "Light courier vessel for rapid personnel and small cargo transport.",
    baseCost: { metal: 5000, crystal: 10000, deuterium: 5000 },
    baseTimeSeconds: 200,
    growthFactor: 1,
    prerequisites: { shipyard: 4, combustionDrive: 4, armourTech: 4 },
    stats: { attack: 1, shield: 1, hull: 2000, speed: 15000, cargo: 50 },
  },
  {
    id: "spaceCarrier",
    categoryId: "fleet",
    entryType: "ship",
    name: "Space Carrier",
    description: "Capital carrier vessel designed to transport and deploy fighter squadrons.",
    baseCost: { metal: 5000000, crystal: 2000000, deuterium: 1000000 },
    baseTimeSeconds: 12000,
    growthFactor: 1,
    prerequisites: { shipyard: 16, hyperspaceDrive: 10, armourTech: 15, combustionDrive: 8, computerTech: 15, ionTech: 12 },
    stats: { attack: 2000, shield: 30000, hull: 1500000, speed: 4000, cargo: 5000 },
  },
  {
    id: "hadronBomber",
    categoryId: "fleet",
    entryType: "ship",
    name: "Hadron Bomber",
    description: "Advanced bomber using hadron projectile technology for planetary siege.",
    baseCost: { metal: 2500000, crystal: 3500000, deuterium: 4500000 },
    baseTimeSeconds: 9000,
    growthFactor: 1,
    prerequisites: { shipyard: 10, hyperspaceDrive: 10, energyTech: 16 },
    stats: { attack: 35000, shield: 5000, hull: 400000, speed: 4500, cargo: 4000 },
  },
  {
    id: "plasmicShip",
    categoryId: "fleet",
    entryType: "ship",
    name: "Plasmic Ship",
    description: "Experimental vessel wielding concentrated plasma energy beams.",
    baseCost: { metal: 5000000, crystal: 3000000, deuterium: 4000000 },
    baseTimeSeconds: 11000,
    growthFactor: 1,
    prerequisites: { shipyard: 18, hyperspaceDrive: 12, plasmaTech: 18 },
    stats: { attack: 47500, shield: 10000, hull: 800000, speed: 7500, cargo: 8500 },
  },
  {
    id: "protonDestroyer",
    categoryId: "fleet",
    entryType: "ship",
    name: "Proton Destroyer",
    description: "Anti-capital siege vessel firing focused proton warheads.",
    baseCost: { metal: 4500000, crystal: 5500000, deuterium: 6000000 },
    baseTimeSeconds: 13000,
    growthFactor: 1,
    prerequisites: { shipyard: 20, hyperspaceDrive: 9, armourTech: 15 },
    stats: { attack: 440000, shield: 20000, hull: 1000000, speed: 1500, cargo: 7500 },
  },
  {
    id: "disintegratingShip",
    categoryId: "fleet",
    entryType: "ship",
    name: "Disintegrating Ship",
    description: "Ultimate doomsday weapon armed with disintegration beam technology.",
    baseCost: { metal: 6500000, crystal: 8000000, deuterium: 10000000 },
    baseTimeSeconds: 20000,
    growthFactor: 1,
    prerequisites: { shipyard: 25, computerTech: 18, hyperspaceTech: 10, hyperspaceDrive: 15, armourTech: 20, energyTech: 22 },
    stats: { attack: 500000, shield: 50000, hull: 3000000, speed: 1250, cargo: 14000 },
  },
];

export const UNIVERSE_EXTENDED_SHIP_MAP: Record<string, OgameCatalogEntryDefinition> =
  Object.fromEntries(UNIVERSE_EXTENDED_SHIPS.map((entry) => [entry.id, entry]));
