import { ImperialDecree, AdminWorldModifier, AdminServerSettings } from './types';

export const INITIAL_IMPERIAL_DECREES: ImperialDecree[] = [
  {
    id: 'decree_crown_sovereign',
    title: 'Crown of the Stellar Sovereign',
    codename: 'IMPERIUM-SUPREME-01',
    category: 'divine',
    description: 'Invokes the divine mandate of the Galactic Emperor. All empire resource yields, mining speed, fleet velocity, and research throughput receive an imperial sovereign blessing.',
    effectSummary: '+50% All Production, +25% Fleet Speed, +35% Research Output',
    multiplier: 1.5,
    active: true,
    costDarkMatter: 0,
    icon: '👑',
    durationMinutes: 1440,
    activatedAt: new Date().toISOString(),
  },
  {
    id: 'decree_golden_synthesis',
    title: 'Golden Age of Synthesis',
    codename: 'SYNTHESIS-SURGE-02',
    category: 'economic',
    description: 'Edict mandating 24/7 planetary automated nanofoundry overdrive. Metal refineries, crystal synthesizers, and heavy deuterium centrifuges operate at emergency maximum output.',
    effectSummary: '+100% Metal, Crystal & Deuterium Natural Income',
    multiplier: 2.0,
    active: false,
    costDarkMatter: 500,
    icon: '💎',
    durationMinutes: 360,
  },
  {
    id: 'decree_martial_blitz',
    title: 'Martial Law & Armada Blitz',
    codename: 'DREADNOUGHT-EXPEDITE-03',
    category: 'military',
    description: 'Mobilizes all orbital drydocks, military academies, and planetary defense batteries into emergency planetary defense readiness.',
    effectSummary: '+40% Fleet & Planetary Attack Power, -50% Shipyard Build Times',
    multiplier: 1.4,
    active: false,
    costDarkMatter: 750,
    icon: '⚔️',
    durationMinutes: 180,
  },
  {
    id: 'decree_hyperlane_supercharge',
    title: 'Hyperlane Quantum Supercharge',
    codename: 'WARP-OVERDRIVE-04',
    category: 'expansion',
    description: 'Injects dark matter antimatter catalysts into the sector hyperlane conduits, slashing expedition travel times and doubling discovery loot.',
    effectSummary: '+100% Fleet Warp Speed, +50% Expedition Artifact & Resource Drops',
    multiplier: 2.0,
    active: false,
    costDarkMatter: 600,
    icon: '🚀',
    durationMinutes: 240,
  },
  {
    id: 'decree_tritium_fusion',
    title: 'Stargate Tritium Fusion Edict',
    codename: 'STARGATE-RESONANCE-05',
    category: 'science',
    description: 'Orders the Galactic Stargate Guild to open ultra-stable supergate wormhole tunnels, enabling free interstellar jumps and maximum research compute sharing.',
    effectSummary: '-50% Stargate Tritium Costs, +60% Lab Research Speed',
    multiplier: 1.6,
    active: false,
    costDarkMatter: 800,
    icon: '🌌',
    durationMinutes: 300,
  },
  {
    id: 'decree_cosmic_sanctuary',
    title: 'Pax Galactica Peace Sanctuary',
    codename: 'SANCTUARY-CEASEFIRE-06',
    category: 'divine',
    description: 'Declares an imperial holy truce across all colonized solar systems. Hostile covert sabotage and pirate incursions are temporarily neutralized.',
    effectSummary: '+100% Defense Shielding, Covert Sabotage Immune, +20% Bank Vault Interest',
    multiplier: 2.0,
    active: false,
    costDarkMatter: 1000,
    icon: '🛡️',
    durationMinutes: 720,
  },
];

export const INITIAL_WORLD_MODIFIERS: AdminWorldModifier[] = [
  {
    id: 'mod_global_speed',
    name: 'Galactic Universe Speed',
    description: 'Master server tick multiplier governing fleet travel, expedition timers, and construction rates.',
    category: 'speed',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.25,
    max: 10.0,
    step: 0.25,
    unit: 'x',
  },
  {
    id: 'mod_resource_rate',
    name: 'Resource Production Yield',
    description: 'Global resource production multiplier across all metal mines, crystal synthetics, and deuterium extractors.',
    category: 'production',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.5,
    max: 20.0,
    step: 0.5,
    unit: 'x',
  },
  {
    id: 'mod_research_speed',
    name: 'Scientific Research Rate',
    description: 'Global laboratory throughput multiplier accelerating technology breakthroughs and blueprint mastering.',
    category: 'speed',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.5,
    max: 10.0,
    step: 0.5,
    unit: 'x',
  },
  {
    id: 'mod_shipyard_rate',
    name: 'Orbital Shipyard Drydock Speed',
    description: 'Construction velocity modifier for combat vessels, defense cannons, and stellar megastructures.',
    category: 'speed',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.5,
    max: 10.0,
    step: 0.5,
    unit: 'x',
  },
  {
    id: 'mod_combat_intensity',
    name: 'Fleet Combat Lethality',
    description: 'Damage output and deflector penetration scaling during simulated and live fleet engagements.',
    category: 'combat',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.5,
    max: 5.0,
    step: 0.25,
    unit: 'x',
  },
  {
    id: 'mod_bank_interest',
    name: 'Imperial Bank Vault Interest',
    description: 'Accrual multiplier on treasury deposits stored in the planetary vault per cron cycle.',
    category: 'economy',
    multiplier: 1.0,
    defaultValue: 1.0,
    min: 0.0,
    max: 5.0,
    step: 0.25,
    unit: 'x',
  },
];

export const DEFAULT_ADMIN_SETTINGS: AdminServerSettings = {
  serverName: 'Universe Alpha Realm #01 (US-East)',
  realmState: 'online',
  godModeEnabled: false,
  instantBuildsEnabled: false,
  freeDarkMatterMode: false,
  pvpEnabled: true,
  globalBroadcastMessage: 'Crown of the Emperor is active. Imperial Decrees are in effect.',
  globalBroadcastActive: true,
  turnTickMultiplier: 1.0,
};
