import {
  Race,
  Government,
  PlayerProfile,
  PlayerResources,
  Technology,
  WeaponType,
  PlayerWeapon,
  TargetRealm,
  MothershipModule,
  PlanetColony,
  MarketOrder,
  MercenaryContract,
  RankingEntry,
  Alliance,
  GameMessage,
} from './types';
import { CONVERT_NPC_RACES_TO_TARGET_REALMS } from './stargateNpcRacesData';
import { EXPANDED_TECHNOLOGIES } from './data/expandedTechnologiesData';

export const RACES: Race[] = [
  {
    id: 'tauri',
    name: "Tau'ri",
    bonusLabel: 'Attack bonus (+25%)',
    bonusPercent: 25,
    bankName: 'Alpha Site Vault',
    attackModifier: 1.25,
    defenseModifier: 1.0,
    incomeModifier: 1.0,
    covertModifier: 1.0,
    description: 'Humanity from Earth. Tenacious combat doctrine and adaptive reverse-engineered technologies.',
  },
  {
    id: 'asgard',
    name: 'Asgard',
    bonusLabel: 'Defense bonus (+25%)',
    bonusPercent: 25,
    bankName: 'Planetary Vault',
    attackModifier: 1.0,
    defenseModifier: 1.25,
    incomeModifier: 1.0,
    covertModifier: 1.0,
    description: 'Ancient, benevolent protectors possessing formidable shield grids and neutronium armor.',
  },
  {
    id: 'goauld',
    name: "Goa'uld",
    bonusLabel: 'Income bonus (+25%)',
    bonusPercent: 25,
    bankName: 'Secret Temple',
    attackModifier: 1.0,
    defenseModifier: 1.0,
    incomeModifier: 1.25,
    covertModifier: 1.0,
    description: 'Parasitic feudal overlords commanding vast slave labor and relentless Naquadah extraction.',
  },
  {
    id: 'replicator',
    name: 'Replicator',
    bonusLabel: 'Covert bonus (+25%)',
    bonusPercent: 25,
    bankName: 'Time Chamber',
    attackModifier: 1.0,
    defenseModifier: 1.0,
    incomeModifier: 1.0,
    covertModifier: 1.25,
    description: 'Self-replicating nanite swarms. Masters of subversion, assimilation, and unseen sabotage.',
  },
  {
    id: 'tollan',
    name: 'Tollan',
    bonusLabel: 'Technological Mastery (+20%)',
    bonusPercent: 20,
    bankName: 'Curia Archive',
    attackModifier: 1.1,
    defenseModifier: 1.1,
    incomeModifier: 1.1,
    covertModifier: 1.1,
    description: 'An advanced pacifist society with impenetrable phase-shifting planetary defense cannons.',
  },
];

export const GOVERNMENTS: Government[] = [
  {
    id: 'democracy',
    name: 'Representative Democratic Federation',
    tagline: 'Sovereignty vested in elected planetary senates and free citizen charters',
    description: 'Free citizen assembly promoting trade, economic prosperity, colonial expansion, and diplomatic pacts across civilized sectors.',
    icon: '🏛️',
    ideology: 'Egalitarian Federalism & Free Enterprise',
    economyModifier: 1.30,
    researchModifier: 1.10,
    militaryModifier: 0.85,
    defenseModifier: 1.05,
    colonyModifier: 1.25,
    fleetModifier: 0.90,
    metalMineModifier: 1.15,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.10,
    reputationModifier: 1.30,
    gloryModifier: 1.05,
    subspaceSpeedModifier: 1.05,
    specialPerk: 'Colonial Expansion Bill: +2 Max Colony slots, civil population morale never drops below 80%, and trade income +20%.',
    uniqueShipClass: 'Federation Diplomatic Flagship',
    colorTheme: 'blue',
    strengths: ['+30% Trade & Banking Economy', '+25% Colony Capacity & Growth', '+30% Galactic Diplomatic Standing'],
    weaknesses: ['-15% Fleet Offensive Firepower', '-10% Fleet Maintenance Readiness'],
    edicts: [
      {
        id: 'fed_trade_bill',
        name: 'Interstellar Commerce Accord',
        description: 'Subsidize civilian trade lanes to surge market trade profits.',
        effect: '+20% Trade Market Profits & Bank Interest',
        cost: '15,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'fed_research_grant',
        name: 'Open Academy Grant',
        description: 'Allocate federal grants to universities and civilian research laboratories.',
        effect: '+15% Scientific Research Speed',
        cost: '25,000 Metal, 10,000 Crystal',
        durationHours: 24,
      },
      {
        id: 'fed_defense_pact',
        name: 'Sovereign Defense Resolution',
        description: 'Rally civilian volunteers and planetary militia into static defenses.',
        effect: '+20% Planetary Shield Harmonics',
        cost: '20,000 Deuterium',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'junta',
    name: 'Military Command Stratocracy',
    tagline: 'All resources subordinated to the Supreme War Council and Armada Shipyards',
    description: 'Stratified command structure focusing supreme authority on martial dominance, rapid fleet production, and unyielding orbital firepower.',
    icon: '⚔️',
    ideology: 'Martial Autocracy & Total Mobilization',
    economyModifier: 0.85,
    researchModifier: 1.00,
    militaryModifier: 1.35,
    defenseModifier: 1.20,
    colonyModifier: 0.90,
    fleetModifier: 1.30,
    metalMineModifier: 1.10,
    crystalMineModifier: 0.95,
    deutMineModifier: 1.25,
    reputationModifier: 0.80,
    gloryModifier: 1.35,
    subspaceSpeedModifier: 1.15,
    specialPerk: 'Total War Economy: Capital warships build 30% faster, and all armada ships gain +10% Rapid Fire rating.',
    uniqueShipClass: 'Dreadnought Command Battleship',
    colorTheme: 'red',
    strengths: ['+35% Fleet Offensive Firepower', '+30% Orbital Shipyard Assembly Speed', '+35% Battle Glory Point Yield'],
    weaknesses: ['-15% Civilian Economic Output', '-10% Colony Expansion & Diplomacy'],
    edicts: [
      {
        id: 'junta_mobilization',
        name: 'General Fleet Mobilization',
        description: 'Requisition industrial factories directly into military shipyards.',
        effect: '+25% Shipyard Assembly Rate',
        cost: '30,000 Metal, 10,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'junta_drills',
        name: 'Live-Fire Subspace Maneuvers',
        description: 'Conduct high-intensity plasma artillery drills across combat task forces.',
        effect: '+15% Fleet Weapon Damage & Critical Hit Rate',
        cost: '25,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'junta_garrison',
        name: 'Martial Defense Garrison',
        description: 'Fortify planetary installations with heavy garrison Gauss emplacements.',
        effect: '+30% Ground Invasion Resistance',
        cost: '35,000 Metal, 15,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'technocracy',
    name: 'Scientific Cybernetic Directorate',
    tagline: 'Governance guided by logic, synthetic computation, and quantum discovery',
    description: 'Led by supreme research councils prioritizing rapid technological breakthroughs, hyperspace propulsion, and energy deflector physics.',
    icon: '🧪',
    ideology: 'Rational Empiricism & Cybernetic Automation',
    economyModifier: 1.05,
    researchModifier: 1.40,
    militaryModifier: 1.00,
    defenseModifier: 1.15,
    colonyModifier: 1.05,
    fleetModifier: 1.15,
    metalMineModifier: 1.00,
    crystalMineModifier: 1.30,
    deutMineModifier: 1.35,
    reputationModifier: 1.10,
    gloryModifier: 1.10,
    subspaceSpeedModifier: 1.25,
    specialPerk: 'Quantum Supercomputing Matrix: Technology labs upgrade 40% faster; Espionage probes operate with +2 stealth tiers.',
    uniqueShipClass: 'Tachyon Quantum Science Cruiser',
    colorTheme: 'teal',
    strengths: ['+40% Scientific Research Velocity', '+35% Deuterium Synthesizer Output', '+25% Subspace Engine Speed'],
    weaknesses: ['Standard Raw Troop Infantry Morale', 'High Deuterium Energy Demands'],
    edicts: [
      {
        id: 'tech_overclock',
        name: 'Core Quantum Overclock',
        description: 'Push tachyon processors to maximum thermal limits to accelerate ongoing research.',
        effect: '+25% Technology Research Speed',
        cost: '20,000 Crystal, 20,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'tech_probe_stealth',
        name: 'Subspace Cloaking Calibration',
        description: 'Align sensor cloaks on all espionage recon craft to bypass planetary radars.',
        effect: '+35% Espionage Probe Stealth Penetration',
        cost: '15,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'tech_nanite_boost',
        name: 'Nanite Assembly Protocol',
        description: 'Deploy molecular constructor nanites across orbital infrastructure.',
        effect: '-20% Construction Duration for Facilities',
        cost: '30,000 Crystal, 15,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'empire',
    name: 'Feudal Imperial Autocracy',
    tagline: 'Divine decree of the High Emperor enforced by planetary Dukes and Grand Moffs',
    description: 'Centralized dynastic dominion ruling through planetary governors, extracting heavy tribute from conquered worlds to forge sovereign capital flagships.',
    icon: '👑',
    ideology: 'Imperial Hegemony & Feudal Tribute',
    economyModifier: 1.20,
    researchModifier: 0.90,
    militaryModifier: 1.20,
    defenseModifier: 1.15,
    colonyModifier: 1.15,
    fleetModifier: 1.10,
    metalMineModifier: 1.30,
    crystalMineModifier: 1.15,
    deutMineModifier: 1.05,
    reputationModifier: 0.90,
    gloryModifier: 1.25,
    subspaceSpeedModifier: 1.05,
    specialPerk: 'Imperial Vassal Tithes: Secondary colonies pay +25% mineral tribute to homeworld; Capital flagships receive +20% hull integrity.',
    uniqueShipClass: 'Imperial Sovereign Super-Dreadnought',
    colorTheme: 'amber',
    strengths: ['+30% Metal Mine Heavy Extraction', '+20% Capital Ship Armor & Hull', '+25% Plunder Yield from Raids'],
    weaknesses: ['-10% Innovation & Lab Speed', 'Colonies Require Strong Governors'],
    edicts: [
      {
        id: 'emp_tithe',
        name: 'Imperial Tribute Tithe',
        description: 'Command provincial lords to deliver heavy ore convoys to the imperial throne.',
        effect: '+20% Metal and Crystal Harvest Yield',
        cost: '10,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'emp_grand_fleet',
        name: 'Emperor\'s Iron Guard',
        description: 'Anoint elite praetorian guard vessels with heavy reinforced durasteel plating.',
        effect: '+20% Hull Integrity for Cruisers and Battleships',
        cost: '40,000 Metal, 15,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'emp_coronation',
        name: 'Sovereign Coronation Decrees',
        description: 'Host imperial pageants and martial parades across all sector worlds.',
        effect: '+25% Empire Glory and Honor Rating',
        cost: '25,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'guild',
    name: 'Corporate Merchant Syndicate',
    tagline: 'Prosperity dictated by trade monopolies, privateers, and banking cartels',
    description: 'Mercantile oligarchy powered by trade monopolies, interstellar banking conglomerates, dark matter speculation, and private mercenary fleet contractors.',
    icon: '💎',
    ideology: 'Plutocratic Capitalism & Hyper-Commerce',
    economyModifier: 1.45,
    researchModifier: 1.05,
    militaryModifier: 0.85,
    defenseModifier: 0.90,
    colonyModifier: 1.20,
    fleetModifier: 1.20,
    metalMineModifier: 1.20,
    crystalMineModifier: 1.25,
    deutMineModifier: 1.15,
    reputationModifier: 1.20,
    gloryModifier: 1.00,
    subspaceSpeedModifier: 1.20,
    specialPerk: 'Mercantile Cargo Logistics: Cargo freighters carry +50% payload; Bank deposits earn +35% interest; Store procurement discount -15%.',
    uniqueShipClass: 'Armored Merchant Mega-Freighter',
    colorTheme: 'emerald',
    strengths: ['+45% Economic & Banking Wealth', '+50% Cargo Capacity on Transports', '+35% Bank Compound Interest'],
    weaknesses: ['-15% Standing Military Morale', '-10% Static Defensive Fortifications'],
    edicts: [
      {
        id: 'guild_monopoly',
        name: 'Corporate Monopoly Charter',
        description: 'Secure exclusive trade concessions across neighboring galaxy nodes.',
        effect: '+30% Imperial Bank Daily Interest',
        cost: '30,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'guild_privateer',
        name: 'Letters of Marque',
        description: 'Hire licensed privateer flotillas to intercept rogue trade routes.',
        effect: '+25% Resource Plunder Capacity for Transports',
        cost: '20,000 Naquadah, 10,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'guild_subsidies',
        name: 'Shipyard Tax Havens',
        description: 'Grant tax incentives to private shipbuilders to slash procurement costs.',
        effect: '-15% Ship Construction Resource Costs',
        cost: '25,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'theocracy',
    name: 'Theocratic Holy Dominion',
    tagline: 'Devoted faithful guided by divine prophecies of ascension and sacred relics',
    description: 'Led by the High Ecclesiarchy and Zealot Priests who inspire total devotion, transforming planetary defenses and armadas into fanatical crusade engines.',
    icon: '☀️',
    ideology: 'Religious Fervor & Ascended Zealotry',
    economyModifier: 1.10,
    researchModifier: 0.80,
    militaryModifier: 1.25,
    defenseModifier: 1.35,
    colonyModifier: 1.10,
    fleetModifier: 1.10,
    metalMineModifier: 1.05,
    crystalMineModifier: 1.10,
    deutMineModifier: 1.25,
    reputationModifier: 0.85,
    gloryModifier: 1.60,
    subspaceSpeedModifier: 1.10,
    specialPerk: 'Sacred Martyrdom Wards: Planetary defenses gain +35% shield absorption; Glory point gains increased by +60% across all operations.',
    uniqueShipClass: 'Holy Inquisitor Temple Warship',
    colorTheme: 'yellow',
    strengths: ['+35% Planetary Iris Defense Strength', '+60% Imperial Glory Point Generation', '+25% Crusade Weapon Power'],
    weaknesses: ['-20% Secular Scientific Innovation', 'Strict Heresy Laws Impede Diplomacy'],
    edicts: [
      {
        id: 'theo_crusade',
        name: 'Proclamation of Holy Crusade',
        description: 'Sanctify armada weapons with blessed plasma coils to purge rival realms.',
        effect: '+25% Fleet Damage against Alien & Hostile Empires',
        cost: '20,000 Naquadah, 15,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'theo_iris_ward',
        name: 'Sanctified Iris Deflector Field',
        description: 'Imbue orbital defense stations with high-frequency energy wards.',
        effect: '+30% Defense Shield Regeneration Rate',
        cost: '25,000 Crystal, 15,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'theo_pilgrimage',
        name: 'Great Ascended Pilgrimage',
        description: 'Summon billions of faithful pilgrims to imperial cathedral worlds.',
        effect: '+50% Glory Points Gained for 24 Hours',
        cost: '25,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'hive',
    name: 'Cybernetic Hive Matrix',
    tagline: 'Synthetic swarm consciousness operating with absolute mathematical unity',
    description: 'An interconnected synthetic neural network where trillions of worker drones operate in flawless cohesion, eliminating civil unrest and maximizing automation.',
    icon: '🤖',
    ideology: 'Synthetic Gestalt & Overmind Logic',
    economyModifier: 1.25,
    researchModifier: 1.20,
    militaryModifier: 1.15,
    defenseModifier: 1.10,
    colonyModifier: 1.30,
    fleetModifier: 1.15,
    metalMineModifier: 1.25,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.20,
    reputationModifier: 0.60,
    gloryModifier: 0.90,
    subspaceSpeedModifier: 1.15,
    specialPerk: 'Gestalt Overmind Synchronization: Zero civil unrest across all colonies; Solar and Fusion power plants yield +30% energy output.',
    uniqueShipClass: 'Bio-Mechanical Swarm Hive-Carrier',
    colorTheme: 'purple',
    strengths: ['+30% Energy Output from Power Plants', '+30% Drone Colony Expansion', '+25% Automated Mine Extraction'],
    weaknesses: ['-40% Diplomatic Reputation with Biologicals', 'Alien to Traditional Trade'],
    edicts: [
      {
        id: 'hive_overclock',
        name: 'Overclock Drone Subroutines',
        description: 'Reroute secondary computational cycles directly into planetary mining bores.',
        effect: '+25% Mine Ore Extraction Speed',
        cost: '20,000 Deuterium',
        durationHours: 24,
      },
      {
        id: 'hive_swarm_link',
        name: 'Neural Swarm Link',
        description: 'Synchronize warship navigation telemetry into a unified swarm array.',
        effect: '+20% Fleet Evasion & Shield Regeneration',
        cost: '20,000 Crystal, 10,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'hive_debris_sweep',
        name: 'Automated Debris Harvester Cycle',
        description: 'Deploy swarms of sub-light robotic scavengers to salvage destroyed armadas.',
        effect: '+30% Debris Field Recovery Yield',
        cost: '15,000 Metal, 10,000 Deuterium',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'anarchy',
    name: 'Anarcho-Syndicalist Free Collective',
    tagline: 'Decentralized workers councils, partisan raiders, and autonomous frontier communes',
    description: 'A revolutionary confederation of self-governing star systems, relying on guerrilla warfare, low fleet maintenance, sabotage, and total resistance to tyranny.',
    icon: '🏴',
    ideology: 'Libertarian Socialism & Guerrilla Resistance',
    economyModifier: 1.10,
    researchModifier: 1.10,
    militaryModifier: 1.10,
    defenseModifier: 1.25,
    colonyModifier: 1.20,
    fleetModifier: 1.25,
    metalMineModifier: 1.10,
    crystalMineModifier: 1.10,
    deutMineModifier: 1.10,
    reputationModifier: 0.95,
    gloryModifier: 1.15,
    subspaceSpeedModifier: 1.30,
    specialPerk: 'Guerrilla Partisan Network: Fleet fuel consumption reduced by -40%; Sabotage missions gain +35% success chance; Immune to enemy espionage probe reveals.',
    uniqueShipClass: 'Stealth Guerrilla Raider Frigate',
    colorTheme: 'zinc',
    strengths: ['-40% Fleet Fuel Consumption', '+35% Sabotage & Infiltration Success', '+30% Subspace Fleet Transit Speed'],
    weaknesses: ['-15% Heavy Capital Ship Armor', 'Decentralized Command Lacks Heavy Tithes'],
    edicts: [
      {
        id: 'anarchy_partisan_cells',
        name: 'Partisan Defense Cells',
        description: 'Equip planetary civilian militias with shoulder-fired plasma anti-air rockets.',
        effect: '+35% Defense against Orbital Bombardment',
        cost: '20,000 Metal, 5,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'anarchy_sabotage',
        name: 'Decentralized Sabotage Wave',
        description: 'Deploy covert partisan infiltrators to disrupt enemy staging worlds.',
        effect: '+30% Sabotage Mission Success Rating',
        cost: '15,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'anarchy_open_source',
        name: 'Open-Source Scientific Commons',
        description: 'Abolish proprietary patents, freely broadcasting technology blueprints.',
        effect: '+15% Research Speed & Free Tech Unlocks',
        cost: '15,000 Crystal',
        durationHours: 24,
      },
    ],
  },
  {
    id: 'aristocracy',
    name: 'Oligarchic Aristocratic Directorate',
    tagline: 'Ancient bloodlines, grand councils of dynasties, and peerless flagship admirals',
    description: 'An elite patrician high council where ancestral noble houses pool tremendous fortunes to field peerless commanders, luxury cruisers, and shadow intelligence networks.',
    icon: '⚜️',
    ideology: 'Patrician Nobility & Dynastic Hegemony',
    economyModifier: 1.15,
    researchModifier: 1.15,
    militaryModifier: 1.20,
    defenseModifier: 1.10,
    colonyModifier: 1.05,
    fleetModifier: 1.25,
    metalMineModifier: 1.10,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.15,
    reputationModifier: 1.40,
    gloryModifier: 1.40,
    subspaceSpeedModifier: 1.10,
    specialPerk: 'Noble Commander Heraldry: All assigned High Officers and Commanders grant +25% stronger aura bonuses; +15% Critical Strike chance in fleet battles.',
    uniqueShipClass: 'Patrician Aristocratic Grand Flagship',
    colorTheme: 'indigo',
    strengths: ['+25% Commander Officer Stat Buffs', '+40% Diplomatic Reputation & Prestige', '+15% Fleet Critical Strike Chance'],
    weaknesses: ['-15% Common Worker Mine Productivity', 'High Courtly Maintenance Costs'],
    edicts: [
      {
        id: 'arist_officer_commission',
        name: 'Patrician Officer Commission',
        description: 'Appoint high-born nobles as commodores, granting bonus tactical command acumen.',
        effect: '+25% Commander XP Gain and Aura Multipliers',
        cost: '25,000 Naquadah',
        durationHours: 24,
      },
      {
        id: 'arist_diplomatic_envoy',
        name: 'Grand Diplomatic Embassy',
        description: 'Send luxurious heralds with ancient relics to foreign galactic courts.',
        effect: '+35% Galactic Reputation and NPC Realm Favor',
        cost: '20,000 Naquadah, 10,000 Crystal',
        durationHours: 24,
      },
      {
        id: 'arist_noble_treasury',
        name: 'House Heritage Reliquary',
        description: 'Open ancestral subterranean vaults to reward victorious battle task forces.',
        effect: '+30% Glory Points on All Combat Victories',
        cost: '30,000 Metal, 15,000 Naquadah',
        durationHours: 24,
      },
    ],
  },
];

export const INITIAL_PROFILE: PlayerProfile = {
  id: 'usr-1',
  username: 'demo',
  displayName: 'Commander Tanang',
  race: 'tauri',
  governmentId: 'junta',
  rankName: 'Commander',
  rankLevel: 3,
  glory: 1250,
  reputation: 680,
  defconLevel: 0,
  vacationUntil: null,
  ascended: false,
  lastTurnAt: new Date().toISOString(),
};

export const INITIAL_RESOURCES: PlayerResources = {
  credits: 500000,
  naquadah: 125000,
  bankedNaquadah: 500000,
  attackTurns: 48,
  untrainedUnits: 1600,
  miners: 650,
  lifers: 150,
  unitProduction: 12,
  attackUnits: 850,
  defenseUnits: 1200,
  spies: 160,
  antiSpies: 140,
  superUnits: 25,
  metal: 85000,
  crystal: 54000,
  deuterium: 28000,
  food: 42000,
  maxFood: 250000,
  water: 58000,
  maxWater: 300000,
  totalPopulation: 14000000,
  energy: 450,
  maxEnergy: 600,
  gateTokens: 25,
  dimensionalTokens: 12,
  raidTokens: 6,
};

export const INITIAL_TECHNOLOGIES: Technology[] = [
  ...EXPANDED_TECHNOLOGIES,
  {
    id: 'tech-1',
    key: 'tech_offense_plasma',
    name: 'Plasma Discharge Cannons',
    category: 'offense',
    subClass: 'Energy Projectiles',
    techType: 'Plasma Emitter',
    subType: 'Ionized Stream',
    tier: 1,
    tierTitle: 'Tier I - Planetary Frontier',
    baseCost: 25000,
    costGrowth: 1.35,
    level: 2,
    maxLevel: 50,
    description: 'High-energy ionized gas weapon arrays that burn through opposing starship plating.',
    stats: {
      primaryStat: { name: 'Energy DPS', value: 310, unit: 'MW' },
      subStats: [
        { name: 'Armor Melt', value: 18, unit: '%' },
        { name: 'Crit Surge', value: 8, unit: '%' },
        { name: 'Fire Rate', value: 160, unit: 'RPM' },
        { name: 'Heat Efficiency', value: 75, unit: '%' },
      ],
    },
    effectsSummary: 'Increases offense combat multiplier by +15% per level.',
    powerRating: 200,
  },
  {
    id: 'tech-2',
    key: 'tech_offense_tachyon',
    name: 'Tachyon Lance Systems',
    category: 'offense',
    subClass: 'Particle & Tachyon Beams',
    techType: 'Tachyon Lance',
    subType: 'Coherent Stream',
    tier: 2,
    tierTitle: 'Tier II - Orbital Hegemony',
    baseCost: 65000,
    costGrowth: 1.45,
    level: 1,
    maxLevel: 45,
    description: 'Faster-than-light particle beams capable of piercing defensive fields.',
    stats: {
      primaryStat: { name: 'Beam Penetration', value: 550, unit: 'TeV' },
      subStats: [
        { name: 'Shield Bypass', value: 20, unit: '%' },
        { name: 'Effective Range', value: 100, unit: 'k-km' },
        { name: 'Sustained Burn', value: 5, unit: 's' },
        { name: 'Coherence Index', value: 85, unit: '%' },
      ],
    },
    effectsSummary: 'Increases offense combat multiplier by +15% per level.',
    powerRating: 320,
  },
  {
    id: 'tech-3',
    key: 'tech_defense_shield',
    name: 'Asgard Bubble Shields',
    category: 'defense',
    subClass: 'Force Fields & Phased Barriers',
    techType: 'Deflector Screen',
    subType: 'Harmonic Shield',
    tier: 2,
    tierTitle: 'Tier II - Orbital Hegemony',
    baseCost: 30000,
    costGrowth: 1.35,
    level: 3,
    maxLevel: 45,
    description: 'Multi-phased energy barriers absorbing both kinetic and energy-based orbital bombardments.',
    stats: {
      primaryStat: { name: 'Shield Capacity', value: 480, unit: 'MW' },
      subStats: [
        { name: 'Recharge Rate', unit: 'MW/s', value: 30 },
        { name: 'Beam Dissipation', unit: '%', value: 35 },
        { name: 'Kinetic Deflect', unit: '%', value: 28 },
        { name: 'Power Upkeep', unit: 'EU', value: 75 },
      ],
    },
    effectsSummary: 'Increases defense combat multiplier by +15% per level.',
    powerRating: 280,
  },
  {
    id: 'tech-4',
    key: 'tech_defense_armor',
    name: 'Trinium Hull Reinforcement',
    category: 'defense',
    subClass: 'Composite Armor & Plating',
    techType: 'Alloy Bulkhead',
    subType: 'Reinforced Hull',
    tier: 2,
    tierTitle: 'Tier II - Orbital Hegemony',
    baseCost: 45000,
    costGrowth: 1.4,
    level: 2,
    maxLevel: 45,
    description: 'Layered trinium-neutronium alloy armor plates protecting vital planetary bunkers.',
    stats: {
      primaryStat: { name: 'Armor Durability', value: 620, unit: 'EHP' },
      subStats: [
        { name: 'Explosive Resist', unit: '%', value: 30 },
        { name: 'Kinetic Hardening', unit: '%', value: 32 },
        { name: 'Spall Suppression', unit: '%', value: 42 },
        { name: 'Mass Penalty', unit: '%', value: 15 },
      ],
    },
    effectsSummary: 'Increases defense combat multiplier by +15% per level.',
    powerRating: 300,
  },
  {
    id: 'tech-5',
    key: 'tech_covert_cloak',
    name: 'Stealth Phase Generators',
    category: 'covert',
    subClass: 'Phase Cloaking & Optical Camouflage',
    techType: 'Cloaking Device',
    subType: 'Phase Shift',
    tier: 2,
    tierTitle: 'Tier II - Orbital Hegemony',
    baseCost: 20000,
    costGrowth: 1.3,
    level: 2,
    maxLevel: 45,
    description: 'Phase cloaking devices rendering infiltrators invisible to standard sensor sweeps.',
    stats: {
      primaryStat: { name: 'Stealth Rating', value: 410, unit: 'IDX' },
      subStats: [
        { name: 'Visual Invisibility', unit: '%', value: 70 },
        { name: 'Thermal Baffle', unit: '%', value: 50 },
        { name: 'Decloak Speed', unit: 's', value: 6.5 },
        { name: 'Cloak Power Drain', unit: 'MW', value: 100 },
      ],
    },
    effectsSummary: 'Increases covert combat multiplier by +15% per level.',
    powerRating: 240,
  },
  {
    id: 'tech-6',
    key: 'tech_anti_sensors',
    name: 'Subspace Tachyonic Sweepers',
    category: 'anti-covert',
    subClass: 'Tachyon Sensor Arrays',
    techType: 'Tachyon Dish',
    subType: 'Wide-Band Sweep',
    tier: 2,
    tierTitle: 'Tier II - Orbital Hegemony',
    baseCost: 22000,
    costGrowth: 1.32,
    level: 2,
    maxLevel: 45,
    description: 'Deep-band subspace radar networks intercepting enemy espionage probes.',
    stats: {
      primaryStat: { name: 'Scan Resolution', value: 380, unit: 'AU' },
      subStats: [
        { name: 'Stealth Penetration', unit: '%', value: 42 },
        { name: 'Scan Range', unit: 'AU', value: 11 },
        { name: 'Ghost Rejection', unit: '%', value: 51 },
        { name: 'Tracking Precision', unit: '%', value: 67 },
      ],
    },
    effectsSummary: 'Increases anti-covert detection multiplier by +15% per level.',
    powerRating: 250,
  },
];

export const WEAPON_TYPES: WeaponType[] = [
  // ==================== 1. WEAPONS (SMALL ARMS) ====================
  {
    id: 'wpn-m4a1',
    name: 'M4A1 Tactical Assault Carbine',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Small Arms',
    tier: 1,
    power: 28,
    attack: 28,
    defense: 8,
    price: 650,
    crewReq: 1,
    upkeep: 5,
    mass: '3.4 kg',
    range: '500 m',
    specSummary: '5.56×45mm NATO, 850 RPM, Selective Fire, Picatinny Rail',
    doctrine: 'Standard Infantry Doctrine',
    description: 'Standard-issue frontline service carbine offering dependable semi-auto and burst fire across varied theater engagements.',
    maxDurability: 100,
  },
  {
    id: 'wpn-scarh',
    name: 'SCAR-H 7.62mm Battle Rifle',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Small Arms',
    tier: 2,
    power: 52,
    attack: 52,
    defense: 14,
    price: 1450,
    crewReq: 1,
    upkeep: 10,
    mass: '3.72 kg',
    range: '800 m',
    specSummary: '7.62×51mm NATO, Heavy Gas Piston, High Kinetic Penetration',
    doctrine: 'Precision Fireteam Suppression',
    description: 'Hard-hitting 7.62 battle rifle engineered to penetrate medium body armor and light barriers at extended combat ranges.',
    maxDurability: 100,
  },
  {
    id: 'wpn-p90',
    name: 'FN P90 Personal Defense Weapon',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Small Arms',
    tier: 1,
    power: 34,
    attack: 34,
    defense: 12,
    price: 850,
    crewReq: 1,
    upkeep: 6,
    mass: '2.6 kg',
    range: '200 m',
    specSummary: '5.7×28mm AP, 50-round Translucent Mag, 900 RPM Bullpup',
    doctrine: 'Close-Quarters Stargate Incursion',
    description: 'Compact bullpup PDW favored by SG frontline strike teams for devastating armor-piercing close-quarters combat.',
    maxDurability: 100,
  },
  {
    id: 'wpn-barrett',
    name: 'Barrett M82A1 .50 BMG Anti-Materiel Rifle',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Small Arms',
    tier: 2,
    power: 95,
    attack: 95,
    defense: 25,
    price: 3200,
    crewReq: 2,
    upkeep: 25,
    mass: '14.0 kg',
    range: '1,800 m',
    specSummary: '.50 BMG (12.7×99mm), Semi-Auto Recoil Operated, Muzzle Brake',
    doctrine: 'Long-Range Anti-Materiel Interdiction',
    description: 'Heavy high-caliber rifle capable of neutralizing unarmored targets, sensor dishes, and light armored hulls at extreme distance.',
    maxDurability: 100,
  },
  {
    id: 'wpn-benelli',
    name: 'Benelli M4 Tactical Breaching Shotgun',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Small Arms',
    tier: 1,
    power: 32,
    attack: 32,
    defense: 16,
    price: 720,
    crewReq: 1,
    upkeep: 5,
    mass: '3.8 kg',
    range: '50 m',
    specSummary: '12-Gauge 3-inch Mag, Auto-Regulating Gas System (ARGO)',
    doctrine: 'Breach & Clear CQB',
    description: 'Combat shotgun designed for rapid stronghold entry, fortified trench clearing, and point-blank shock impact.',
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (CREW-SERVED & HEAVY) ====================
  {
    id: 'wpn-m240b',
    name: 'M240B General-Purpose Machine Gun',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Crew-Served',
    tier: 2,
    power: 75,
    attack: 75,
    defense: 35,
    price: 2400,
    crewReq: 2,
    upkeep: 18,
    mass: '12.5 kg',
    range: '1,100 m',
    specSummary: '7.62×51mm Belt-Fed, Sustained 650-950 RPM, Gas-Operated',
    doctrine: 'Sustained Fire Suppression',
    description: 'Heavy sustained-fire team weapon providing lethal area denial and pinning enemy skirmish lines down.',
    maxDurability: 100,
  },
  {
    id: 'wpn-m2hb',
    name: 'M2HB .50 Cal Heavy Machine Gun',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Crew-Served',
    tier: 2,
    power: 110,
    attack: 110,
    defense: 50,
    price: 3800,
    crewReq: 3,
    upkeep: 30,
    mass: '38.0 kg',
    range: '2,000 m',
    specSummary: '.50 Cal (12.7mm) Linked Belt, Heavy Air-Cooled Barrel',
    doctrine: 'Fortified Emplacement Defense',
    description: 'Legendary heavy machine gun delivering devastating kinetic fire against troop formations, light armor, and low-altitude aircraft.',
    maxDurability: 100,
  },
  {
    id: 'wpn-mk19',
    name: 'Mk 19 40mm Automatic Grenade Launcher',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Crew-Served',
    tier: 2,
    power: 135,
    attack: 135,
    defense: 45,
    price: 4600,
    crewReq: 3,
    upkeep: 35,
    mass: '35.3 kg',
    range: '1,500 m',
    specSummary: '40×53mm High-Velocity Grenades, 325-375 RPM Area Lethality',
    doctrine: 'High-Explosive Saturation',
    description: 'Crew-served weapon firing continuous salvos of dual-purpose high-explosive grenades that shatter infantry and light fortifications.',
    maxDurability: 100,
  },
  {
    id: 'wpn-tow',
    name: 'BGM-71 TOW Anti-Tank Guided Missile',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Crew-Served',
    tier: 3,
    power: 220,
    attack: 220,
    defense: 40,
    price: 7800,
    crewReq: 2,
    upkeep: 60,
    mass: '22.6 kg',
    range: '4,200 m',
    specSummary: 'Tandem Shaped-Charge Warhead, Optical SACLOS / Wireless Guidance',
    doctrine: 'Armor-Breaker Interdiction',
    description: 'Heavy guided missile system designed to defeat modern explosive reactive armor and eliminate enemy battle tanks.',
    maxDurability: 100,
  },
  {
    id: 'wpn-stinger',
    name: 'FIM-92 Stinger MANPADS Air Defense',
    category: 'Defense',
    itemType: 'weapon',
    subCategory: 'Crew-Served',
    tier: 2,
    power: 140,
    attack: 140,
    defense: 85,
    price: 4900,
    crewReq: 2,
    upkeep: 40,
    mass: '15.2 kg',
    range: '4,800 m',
    specSummary: 'Dual-Color IR/UV Seeker, Supersonic Proximity Hit-to-Kill',
    doctrine: 'Low-Altitude Airspace Denial',
    description: 'Man-portable anti-air missile creating a lethal perimeter against attack gunships, low-flying strike craft, and recon drones.',
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (ARTILLERY & ROCKETS) ====================
  {
    id: 'wpn-m777',
    name: 'M777 155mm Lightweight Towed Howitzer',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Artillery & Rockets',
    tier: 3,
    power: 260,
    attack: 260,
    defense: 60,
    price: 9200,
    crewReq: 5,
    upkeep: 80,
    mass: '4,200 kg',
    range: '30-40 km',
    specSummary: '155mm Caliber, GPS Precision Guided Shells (Excalibur Compatible)',
    doctrine: 'Indirect Fires & Counter-Battery',
    description: 'Digital fire-control titanium howitzer providing devastating pinpoint strikes across regional battlefronts.',
    maxDurability: 100,
  },
  {
    id: 'wpn-paladin',
    name: 'M109A7 Paladin 155mm Self-Propelled Howitzer',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Artillery & Rockets',
    tier: 3,
    power: 340,
    attack: 340,
    defense: 120,
    price: 14500,
    crewReq: 4,
    upkeep: 120,
    mass: '35,000 kg',
    range: '30 km',
    specSummary: 'Tracked Chassis, 60-second Shoot-and-Scoot, Automated Rammer',
    doctrine: 'Mobile Heavy Artillery Barrage',
    description: 'Tracked armored howitzer capable of firing rapid coordinated salvos before relocating to evade counter-battery retaliation.',
    maxDurability: 100,
  },
  {
    id: 'wpn-himars',
    name: 'M142 HIMARS Precision Rocket Artillery',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Artillery & Rockets',
    tier: 4,
    power: 520,
    attack: 520,
    defense: 90,
    price: 23000,
    crewReq: 3,
    upkeep: 180,
    mass: '16,200 kg',
    range: '70-300 km',
    specSummary: '6× GMLRS / 1× ATACMS, GPS/INS Inertial Precision Guidance',
    doctrine: 'Strategic Deep Strike Interdiction',
    description: 'High-mobility truck-mounted rocket launcher delivering precision-guided warheads to demolish command centers and ammunition depots.',
    maxDurability: 100,
  },
  {
    id: 'wpn-heavy-mlrs',
    name: 'Tornado-S 300mm Heavy Guided MLRS',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Artillery & Rockets',
    tier: 4,
    power: 610,
    attack: 610,
    defense: 80,
    price: 27500,
    crewReq: 4,
    upkeep: 220,
    mass: '43,000 kg',
    range: '120 km',
    specSummary: '12× 300mm Long-Range Rocket Tubes, Cluster & Thermobaric Options',
    doctrine: 'Area Saturation Bombardment',
    description: 'Heavy multi-rocket complex saturating entire defensive grids with devastating thermobaric salvo volleys.',
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (AIR DEFENSE & NAVAL) ====================
  {
    id: 'wpn-phalanx',
    name: 'Phalanx 20mm Block 1B CIWS',
    category: 'Defense',
    itemType: 'weapon',
    subCategory: 'Air Defense & Naval',
    tier: 3,
    power: 280,
    attack: 180,
    defense: 280,
    price: 11500,
    crewReq: 2,
    upkeep: 90,
    mass: '6,200 kg',
    range: '3,500 m',
    specSummary: '20mm M61A1 Vulcan, 4,500 RPM, Autonomous Ku-Band Radar & FLIR',
    doctrine: 'Point-Defense Anti-Missile Ring',
    description: 'Autonomous rapid-fire Gatling cannon shredding incoming cruise missiles, drones, and guided artillery projectiles.',
    maxDurability: 100,
  },
  {
    id: 'wpn-patriot',
    name: 'MIM-104 Patriot PAC-3 MSE SAM Battery',
    category: 'Defense',
    itemType: 'weapon',
    subCategory: 'Air Defense & Naval',
    tier: 4,
    power: 540,
    attack: 210,
    defense: 540,
    price: 29000,
    crewReq: 4,
    upkeep: 240,
    mass: '900 kg per missile',
    range: '60-160 km',
    specSummary: 'Active Ka-Band Millimeter Wave Radar, Hit-to-Kill Kinetic Interceptor',
    doctrine: 'Theater Ballistic & Air Defense',
    description: 'Premier integrated air defense missile system defending territory against high-performance aircraft and ballistic missiles.',
    maxDurability: 100,
  },
  {
    id: 'wpn-mk45',
    name: 'Mk 45 Mod 4 5-inch 62-Caliber Naval Gun',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Air Defense & Naval',
    tier: 3,
    power: 310,
    attack: 310,
    defense: 140,
    price: 13800,
    crewReq: 3,
    upkeep: 110,
    mass: '24,000 kg',
    range: '36 km',
    specSummary: '127mm Automated Turret, 16-20 RPM, Extended-Range Munitions',
    doctrine: 'Naval Surface Fire Support',
    description: 'Automated naval cannon delivering heavy bombardment onto coastal defense positions and enemy flotillas.',
    maxDurability: 100,
  },
  {
    id: 'wpn-harpoon',
    name: 'RGM-84 Harpoon Anti-Ship Cruise Missile',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Air Defense & Naval',
    tier: 3,
    power: 390,
    attack: 390,
    defense: 60,
    price: 16500,
    crewReq: 2,
    upkeep: 130,
    mass: '690 kg',
    range: '140 km',
    specSummary: 'Sea-Skimming Radar-Guided Cruise Missile, 221 kg High Explosive',
    doctrine: 'Over-the-Horizon Surface Strike',
    description: 'Long-range anti-ship missile skimming just above wave tops to evade detection before slamming into enemy warship hulls.',
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (EXOTIC ENERGY & STARGATE) ====================
  {
    id: 'wpn-1',
    name: "Zat'nik'tel Arrays",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Exotic Energy Weapon',
    tier: 2,
    power: 65,
    attack: 65,
    defense: 20,
    price: 1200,
    crewReq: 1,
    upkeep: 8,
    mass: '1.2 kg',
    range: '150 m',
    specSummary: 'Coherent Bio-Electric Particle Beam, Stun to Disintegration Modes',
    doctrine: 'Alien Technology Integration',
    description: "Handheld Goa'uld energy weapon firing electrical discharge pulses capable of stunning, neutralizing, or disintegrating organic targets.",
    maxDurability: 100,
  },
  {
    id: 'wpn-2',
    name: 'Heavy Staff Cannons',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Exotic Energy Weapon',
    tier: 3,
    power: 160,
    attack: 160,
    defense: 45,
    price: 4500,
    crewReq: 2,
    upkeep: 30,
    mass: '45.0 kg',
    range: '1,200 m',
    specSummary: 'Liquid Naquadah Plasma Chamber, Twin-Mounted Heavy Emplacement',
    doctrine: 'Heavy Assault Siege Warfare',
    description: 'Emplacement-mounted plasma artillery powered by liquid Naquadah, delivering scorching superheated plasma bursts.',
    maxDurability: 100,
  },
  {
    id: 'wpn-3',
    name: 'Ancient Drone Launchers',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Exotic Energy Weapon',
    tier: 5,
    power: 580,
    attack: 580,
    defense: 120,
    price: 19500,
    crewReq: 1,
    upkeep: 150,
    mass: 'Autonomous Swarm Pod',
    range: 'Orbital & Atmospheric',
    specSummary: 'Self-Guided Squid Drones, Phase-Shield Penetration Warheads',
    doctrine: 'Ancient Weapon Platform Dominance',
    description: 'Autonomous bio-neural squid-shaped kinetic projectiles capable of bypassing shields and burrowing through capital warship hulls.',
    maxDurability: 100,
  },
  {
    id: 'wpn-asgard-beam',
    name: 'Asgard Plasma Beam Arrays',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Exotic Energy Weapon',
    tier: 5,
    power: 850,
    attack: 850,
    defense: 220,
    price: 38000,
    crewReq: 3,
    upkeep: 280,
    mass: 'Capital Core Mounting',
    range: 'Deep Space & Sub-Orbital',
    specSummary: 'High-Energy Blue Ion-Plasma Lance, Core Reactor Linked',
    doctrine: 'Capital Dreadnought Annihilation',
    description: 'The pinnacle of Asgard engineering: focused energy lances capable of slicing through Ori and Goauld mothership hulls in consecutive pulses.',
    maxDurability: 100,
  },
  {
    id: 'wpn-ori-beam',
    name: 'Ori Heavy Satellite Energy Cannon',
    category: 'Offense',
    itemType: 'weapon',
    subCategory: 'Exotic Energy Weapon',
    tier: 5,
    power: 1150,
    attack: 1150,
    defense: 300,
    price: 65000,
    crewReq: 0,
    upkeep: 420,
    mass: 'Orbital Superstructure',
    range: 'Interplanetary Beam Radius',
    specSummary: 'Trans-Dimensional Focal Lens, Celestial Origin Power Source',
    doctrine: 'Absolute Planetary Dominance',
    description: 'Orbital siege cannon channeling immense divine celestial energy, capable of destroying shielded capital ships with a single direct blast.',
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (INFANTRY BODY ARMOR) ====================
  {
    id: 'arm-kevlar',
    name: 'Lightweight Kevlar Vest & ACH Helmet',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Infantry Body Armor',
    tier: 1,
    power: 35,
    attack: 0,
    defense: 35,
    price: 750,
    crewReq: 1,
    upkeep: 4,
    mass: '4.8 kg',
    specSummary: 'NIJ Level IIIA Aramid Kevlar, Advanced Combat Helmet with NVG Mount',
    doctrine: 'Standard Soldier Protection',
    description: 'Standard tactical soft armor providing shrapnel dispersion and stopping handgun rounds and indirect blast fragments.',
    maxDurability: 100,
  },
  {
    id: 'arm-ceramic-plate',
    name: 'Level IV Ceramic Ballistic Strike Plates',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Infantry Body Armor',
    tier: 2,
    power: 85,
    attack: 0,
    defense: 85,
    price: 2100,
    crewReq: 1,
    upkeep: 10,
    mass: '7.2 kg',
    specSummary: 'Boron Carbide Ceramic + Ultra-High Molecular Weight Polyethylene',
    doctrine: 'High-Threat Tactical Breaching',
    description: 'Hard armor inserts rated to stop multiple high-velocity 7.62mm armor-piercing rifle rounds in heavy frontline firefights.',
    maxDurability: 100,
  },
  {
    id: 'arm-eod-juggernaut',
    name: 'Heavy EOD Juggernaut Blast Armor Suit',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Infantry Body Armor',
    tier: 3,
    power: 180,
    attack: 15,
    defense: 180,
    price: 6200,
    crewReq: 1,
    upkeep: 25,
    mass: '28.0 kg',
    specSummary: 'Nomex/Kevlar Multi-Layered Overpressure Blast Suit, Integrated Cooling',
    doctrine: 'Fortified Breaching & Demolitions',
    description: 'Full-body armored carapace engineered to withstand point-blank explosive detonations, high-yield blast waves, and heavy shrapnel.',
    maxDurability: 100,
  },
  {
    id: 'arm-exoskeleton',
    name: 'Powered Tactical Exoskeleton Harness',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Infantry Body Armor',
    tier: 4,
    power: 340,
    attack: 45,
    defense: 340,
    price: 14500,
    crewReq: 1,
    upkeep: 65,
    mass: '32.0 kg',
    specSummary: 'Hydraulic-Pneumatic Motorized Frame, Kinetic Load Dispenser, Titanium Plating',
    doctrine: 'Super-Soldier Urban Assault',
    description: 'Motorized combat exoskeleton multiplying soldier physical load capacity while supporting thick composite titanium armor shells.',
    maxDurability: 100,
  },
  {
    id: 'arm-trinium-nano',
    name: 'Trinium-Weave Nano-Composite Combat Suit',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Infantry Body Armor',
    tier: 5,
    power: 620,
    attack: 75,
    defense: 620,
    price: 32000,
    crewReq: 1,
    upkeep: 120,
    mass: '9.5 kg',
    specSummary: 'Self-Repairing Carbon Nanotubes & Off-World Trinium Alloy Weave',
    doctrine: 'Ancient Commando Infiltration',
    description: 'Ultra-lightweight off-world armor utilizing trinium alloy nanofilaments that dissipate kinetic strikes and absorb energy beam impacts.',
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (COMBAT VEHICLES & TANKS) ====================
  {
    id: 'arm-hmmwv',
    name: 'HMMWV Up-Armored Recon Vehicle',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 1,
    power: 55,
    attack: 20,
    defense: 55,
    price: 1800,
    crewReq: 4,
    upkeep: 15,
    mass: '5,400 kg',
    specSummary: 'Fragment-Resistant Armor Package, Run-Flat Tires, Roof Turret Ring',
    doctrine: 'Light Mobile Reconnaissance',
    description: 'All-terrain 4x4 combat utility vehicle fitted with perimeter armor plating to safeguard patrol squads against ambush attacks.',
    maxDurability: 100,
  },
  {
    id: 'arm-stryker',
    name: 'Stryker 8×8 Armored Personnel Carrier',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 2,
    power: 145,
    attack: 45,
    defense: 145,
    price: 5400,
    crewReq: 2,
    upkeep: 35,
    mass: '18,200 kg',
    specSummary: 'High-Hardness Steel Ceramic Composite Hull, Slat Anti-RPG Cage',
    doctrine: 'Rapid Infantry Deployment',
    description: 'Fast wheeled combat carrier delivering mechanized infantry squads directly into hostile sectors under protective armor.',
    maxDurability: 100,
  },
  {
    id: 'arm-jltv',
    name: 'Oshkosh JLTV Mine-Resistant Protected Carrier',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 2,
    power: 175,
    attack: 35,
    defense: 175,
    price: 6800,
    crewReq: 4,
    upkeep: 40,
    mass: '10,200 kg',
    specSummary: 'V-Shaped Deflector Blast Hull, Core 1085 Smart Armor System',
    doctrine: 'Anti-IED Ambush Survival',
    description: 'Rugged tactical carrier designed with a V-shaped blast-deflection undercarriage to protect crews from heavy mines and roadside IEDs.',
    maxDurability: 100,
  },
  {
    id: 'arm-bradley',
    name: 'M2A4 Bradley Infantry Fighting Vehicle',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 3,
    power: 280,
    attack: 115,
    defense: 280,
    price: 11800,
    crewReq: 3,
    upkeep: 75,
    mass: '27,600 kg',
    specSummary: 'Aluminum/Steel Spaced Laminate + ERA Tiles, 25mm Bushmaster + TOW',
    doctrine: 'Mechanized Infantry Assault',
    description: 'Heavily armed and armored tracked fighting vehicle that suppresses enemy strongpoints while protecting mechanized infantry.',
    maxDurability: 100,
  },
  {
    id: 'arm-abrams',
    name: 'M1A2 Abrams SEPv3 Main Battle Tank',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 4,
    power: 590,
    attack: 280,
    defense: 590,
    price: 27000,
    crewReq: 4,
    upkeep: 160,
    mass: '66,800 kg',
    specSummary: 'Depleted Uranium Composite Chobham Armor + Trophy Active Protection',
    doctrine: 'Heavy Armored Breakthrough',
    description: 'Supreme heavy main battle tank combining depleted uranium composite armor with an impenetrable 120mm smoothbore cannon.',
    maxDurability: 100,
  },
  {
    id: 'arm-leopard2',
    name: 'Leopard 2A7+ Heavy Main Battle Tank',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Armored Vehicles & Tanks',
    tier: 4,
    power: 620,
    attack: 270,
    defense: 620,
    price: 28500,
    crewReq: 4,
    upkeep: 170,
    mass: '67,500 kg',
    specSummary: 'Modular 360-Degree Composite Armor, Rheinmetall 120mm L/55 Cannon',
    doctrine: 'Sovereign Defense Bastion',
    description: 'Advanced European battle tank armored with cutting-edge 360-degree modular passive plating designed for full-spectrum warfare.',
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (HARDENED HULL PLATING & SUPPORT) ====================
  {
    id: 'arm-m88a2',
    name: 'M88A2 Hercules Armored Recovery Vehicle',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Hardened Hull Plating',
    tier: 2,
    power: 125,
    attack: 10,
    defense: 125,
    price: 4200,
    crewReq: 3,
    upkeep: 25,
    mass: '63,500 kg',
    specSummary: 'Heavy Cast Armor Hull, 35-ton Boom Crane & 140,000-lb Winch',
    doctrine: 'Battlefield Damage Recovery',
    description: 'Armored juggernaut engineered to recover disabled tanks under direct enemy fire and repair combat hulls in the field.',
    maxDurability: 100,
  },
  {
    id: 'arm-era-kits',
    name: 'Explosive Reactive Armor (ERA) Modular Kits',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Hardened Hull Plating',
    tier: 2,
    power: 110,
    attack: 0,
    defense: 110,
    price: 3600,
    crewReq: 0,
    upkeep: 15,
    mass: '1,200 kg per set',
    specSummary: 'Explosive Sandwich Counter-Jet Tiles against Shaped-Charge Jets',
    doctrine: 'Layered Vehicle Hardening',
    description: 'Interlocking explosive tiles that detonate outward on impact to disrupt shaped-charge anti-tank missiles before they pierce the hull.',
    maxDurability: 100,
  },
  {
    id: 'arm-sloped-trinium',
    name: 'Dreadnought Sloped Trinium Plating',
    category: 'Defense',
    itemType: 'armor',
    subCategory: 'Hardened Hull Plating',
    tier: 5,
    power: 780,
    attack: 50,
    defense: 780,
    price: 42000,
    crewReq: 0,
    upkeep: 190,
    mass: 'Bulkhead Plating Alloy',
    specSummary: 'Extruded Trinium-Neutronium Alloy Composite with Thermal Dampening',
    doctrine: 'Capital Ship Orbital Hardening',
    description: 'Massive sloped hull armor forged from pure trinium and neutronium alloys, deflecting orbital bombardment strikes and kinetic slug impacts.',
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (PERSONAL FORCE FIELDS & DEFLECTORS) ====================
  {
    id: 'shd-riot-ballistic',
    name: 'Polycarbonate Tactical Ballistic Shield',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Personal Deflector',
    tier: 1,
    power: 30,
    attack: 0,
    defense: 30,
    price: 650,
    crewReq: 1,
    upkeep: 2,
    mass: '6.5 kg',
    specSummary: 'Multi-Layered Ballistic Polycarbonate & Level III Ceramic Viewport',
    doctrine: 'Riot Control & Breaching Pointman',
    description: 'Handheld tactical shield deployed by frontline breachers to deflect shrapnel, shotgun blasts, and small arms fire.',
    maxDurability: 100,
  },
  {
    id: 'shd-carbon-barrier',
    name: 'Carbon-Nanotube Deployable Kinetic Barrier',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Personal Deflector',
    tier: 2,
    power: 75,
    attack: 0,
    defense: 75,
    price: 1950,
    crewReq: 1,
    upkeep: 8,
    mass: '12.0 kg',
    specSummary: 'Rapid-Expansion Nanotube Accordion Screen with Ground Anchors',
    doctrine: 'Field Fortification & Cover',
    description: 'Portable barrier expanding into a hardened barricade capable of stopping heavy machine gun fire and grenade blasts.',
    maxDurability: 100,
  },
  {
    id: 'shd-portable-emp',
    name: 'Portable Electromagnetic Deflector Screen',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Personal Deflector',
    tier: 3,
    power: 160,
    attack: 0,
    defense: 160,
    price: 5400,
    crewReq: 1,
    upkeep: 20,
    mass: '18.0 kg',
    specSummary: 'Pulsed Magnetodynamic Deflector, 450 kJ Capacitor Bank',
    doctrine: 'Anti-Energy Projectile Defense',
    description: 'Backpack-mounted energy projector that generates a localized magnetic field to curve and dissipate inbound plasma discharges.',
    maxDurability: 100,
  },
  {
    id: 'shd-ribbon',
    name: "Goa'uld Personal Ribbon Force Shield",
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Personal Deflector',
    tier: 3,
    power: 230,
    attack: 20,
    defense: 230,
    price: 8200,
    crewReq: 1,
    upkeep: 35,
    mass: '0.8 kg Gauntlet',
    specSummary: 'Subspace Kinetic Dissipation Sphere, Mental Interface Trigger',
    doctrine: 'Elite Commander Ward',
    description: 'Wrist-mounted device generating an instantaneous protective force sphere that stops high-velocity bullets and staff blast projectiles.',
    maxDurability: 100,
  },
  {
    id: 'shd-ancient-personal',
    name: 'Ancient Personal Phase Barrier',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Personal Deflector',
    tier: 4,
    power: 420,
    attack: 0,
    defense: 420,
    price: 18000,
    crewReq: 1,
    upkeep: 60,
    mass: '0.3 kg Amulet',
    specSummary: 'Sub-Atomic Phase-Shift Envelope, Zero-Point Energy Powered',
    doctrine: 'Untouchable Sovereign Protection',
    description: 'Miniaturized Ancient device encasing the bearer in a form-fitting phase-shifted energy envelope impenetrable to conventional attacks.',
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (TACTICAL & VEHICLE DEFLECTORS) ====================
  {
    id: 'shd-trophy-aps',
    name: 'Trophy Active Protection Countermeasure System',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Tactical Field Barrier',
    tier: 3,
    power: 210,
    attack: 30,
    defense: 210,
    price: 7600,
    crewReq: 0,
    upkeep: 35,
    mass: '850 kg',
    specSummary: '360° Radar Detection, MEFP Explosive Counter-Munition Interception',
    doctrine: 'Vehicle Point-Defense Ring',
    description: 'Hard-kill active defense system detecting incoming rockets and missiles in milliseconds and obliterating them before impact.',
    maxDurability: 100,
  },
  {
    id: 'shd-reactive-particle',
    name: 'Directed-Energy Reactive Particle Shield',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Tactical Field Barrier',
    tier: 4,
    power: 380,
    attack: 0,
    defense: 380,
    price: 15500,
    crewReq: 2,
    upkeep: 70,
    mass: '2,400 kg',
    specSummary: 'Harmonic Magnetic Pinch Field, High-Frequency Coherent Ion Curtain',
    doctrine: 'Tactical Emplacement Shielding',
    description: 'Mobile generator projecting an iridescent ionized particle curtain over tactical vehicle columns and field command bunkers.',
    maxDurability: 100,
  },
  {
    id: 'shd-subspace-disruption',
    name: 'Subspace Disruption Force Field',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Tactical Field Barrier',
    tier: 4,
    power: 540,
    attack: 40,
    defense: 540,
    price: 24000,
    crewReq: 2,
    upkeep: 110,
    mass: '5,100 kg',
    specSummary: 'Subspace Distortion Emitter, 1.2 GW Continuous Output',
    doctrine: 'Advanced Area Inviolability',
    description: 'High-yield distortion generator that bends incoming kinetic shells and lasers into local subspace folds, neutralizing their momentum.',
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (PLANETARY & ORBITAL AEGIS) ====================
  {
    id: 'wpn-4',
    name: 'Perimeter Defense Turrets',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Planetary & Orbital Shield',
    tier: 2,
    power: 75,
    attack: 25,
    defense: 75,
    price: 1400,
    crewReq: 1,
    upkeep: 15,
    mass: 'Fixed Installation',
    specSummary: 'Automated Dual-Barreled 40mm Rotary Kinetic Turrets',
    doctrine: 'Base Perimeter Security',
    description: 'Hardened perimeter turrets providing automatic scanning and interdiction of unauthorized incursions.',
    maxDurability: 100,
  },
  {
    id: 'wpn-5',
    name: 'Ion Phase Cannon Arrays',
    category: 'Defense',
    itemType: 'weapon',
    subCategory: 'Planetary & Orbital Shield',
    tier: 3,
    power: 180,
    attack: 80,
    defense: 180,
    price: 5200,
    crewReq: 3,
    upkeep: 45,
    mass: 'Surface-to-Orbit Complex',
    specSummary: 'Planetary Ground-to-Orbit Ionized Particle Batteries',
    doctrine: 'Surface-to-Orbit Defense',
    description: 'Heavy surface installations capable of firing coherent ion beams into low orbit to repel invasion fleets.',
    maxDurability: 100,
  },
  {
    id: 'wpn-6',
    name: 'Tollan Planetary Defense Cannon',
    category: 'Defense',
    itemType: 'weapon',
    subCategory: 'Planetary & Orbital Shield',
    tier: 5,
    power: 520,
    attack: 250,
    defense: 520,
    price: 18500,
    crewReq: 2,
    upkeep: 140,
    mass: 'Deep-Core Anchored',
    specSummary: 'Phase Disruption Orbital Ion Cannon, Autonomous Targeting',
    doctrine: 'Planetary Neutralization Grid',
    description: 'Legendary Tollan orbital defense battery firing phased energy bolts that bypass standard shields to disintegrate motherships.',
    maxDurability: 100,
  },
  {
    id: 'shd-asgard-bubble',
    name: 'Asgard Multi-Phased Bubble Shield Matrix',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Planetary & Orbital Shield',
    tier: 5,
    power: 880,
    attack: 0,
    defense: 880,
    price: 39000,
    crewReq: 0,
    upkeep: 210,
    mass: 'Orbital Emitter Network',
    specSummary: 'Multi-Phased Variable Harmonic Energy Sphere, 4.8 Terawatt Absorption',
    doctrine: 'Sovereign Colony Sanctuary',
    description: 'Supreme energy barrier covering entire planetary cities in an impenetrable cyan bubble that absorbs both nuclear and plasma bombardment.',
    maxDurability: 100,
  },
  {
    id: 'shd-atlantis-grid',
    name: 'Atlantis Subspace Shield & Cloaking Grid',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Planetary & Orbital Shield',
    tier: 5,
    power: 1450,
    attack: 0,
    defense: 1450,
    price: 82000,
    crewReq: 0,
    upkeep: 350,
    mass: 'City-Ship Superstructure Grid',
    specSummary: 'Zero-Point Energy Powered Phase Distortion & Complete Optical Cloaking',
    doctrine: 'Ancient City-Ship Inviolability',
    description: 'The pinnacle of Ancient shield science: a city-scale energy dome capable of withstanding ocean depths and fleet bombardments.',
    maxDurability: 100,
  },
  {
    id: 'shd-ori-barrier',
    name: 'Ori Trans-Dimensional Celestial Barrier',
    category: 'Defense',
    itemType: 'shield',
    subCategory: 'Planetary & Orbital Shield',
    tier: 5,
    power: 1950,
    attack: 80,
    defense: 1950,
    price: 125000,
    crewReq: 0,
    upkeep: 480,
    mass: 'Divine Resonance Conduit',
    specSummary: 'Higher-Dimensional Energy Shunt, Near-Zero Thermal Transfer',
    doctrine: 'Celestial Origin Ward',
    description: 'Trans-dimensional energy barrier channeled from Ascended planes, shunting all incoming attacks directly into parallel dimensional voids.',
    maxDurability: 100,
  },
];

export const INITIAL_PLAYER_WEAPONS: PlayerWeapon[] = [
  { id: 'pw-1', weaponTypeId: 'wpn-1', quantity: 240, durability: 95 },
  { id: 'pw-2', weaponTypeId: 'wpn-2', quantity: 85, durability: 88 },
  { id: 'pw-3', weaponTypeId: 'wpn-4', quantity: 310, durability: 92 },
  { id: 'pw-4', weaponTypeId: 'wpn-5', quantity: 70, durability: 80 },
  { id: 'pw-5', weaponTypeId: 'wpn-m4a1', quantity: 180, durability: 96 },
  { id: 'pw-6', weaponTypeId: 'arm-kevlar', quantity: 140, durability: 90 },
  { id: 'pw-7', weaponTypeId: 'arm-ceramic-plate', quantity: 55, durability: 94 },
  { id: 'pw-8', weaponTypeId: 'arm-hmmwv', quantity: 18, durability: 85 },
  { id: 'pw-9', weaponTypeId: 'shd-riot-ballistic', quantity: 95, durability: 92 },
  { id: 'pw-10', weaponTypeId: 'shd-portable-emp', quantity: 25, durability: 88 },
];

const BASE_TARGET_REALMS: TargetRealm[] = [
  {
    id: 'tgt-1',
    commanderName: 'Lord Apophis',
    race: "Goa'uld",
    rank: 'High System Lord',
    score: 94200,
    estimatedUnits: 1450,
    estimatedNaquadah: 280000,
    isProtected: false,
    defenseLevel: 3,
    antiCovertLevel: 2,
  },
  {
    id: 'tgt-2',
    commanderName: 'Baal Syndicate',
    race: "Goa'uld",
    rank: 'Underlord',
    score: 76500,
    estimatedUnits: 980,
    estimatedNaquadah: 195000,
    isProtected: false,
    defenseLevel: 2,
    antiCovertLevel: 3,
  },
  {
    id: 'tgt-3',
    commanderName: 'Replicator Hive Block 4',
    race: 'Replicator',
    rank: 'Nanite Swarm',
    score: 112000,
    estimatedUnits: 2100,
    estimatedNaquadah: 420000,
    isProtected: false,
    defenseLevel: 4,
    antiCovertLevel: 4,
  },
  {
    id: 'tgt-4',
    commanderName: 'Lucian Outpost Bravo',
    race: "Tau'ri Outlaw",
    rank: 'Raider',
    score: 41000,
    estimatedUnits: 550,
    estimatedNaquadah: 85000,
    isProtected: false,
    defenseLevel: 1,
    antiCovertLevel: 1,
  },
  {
    id: 'tgt-5',
    commanderName: 'Anubis Dread Fleet',
    race: "Goa'uld Ascended",
    rank: 'Supreme Overlord',
    score: 185000,
    estimatedUnits: 3400,
    estimatedNaquadah: 890000,
    isProtected: true,
    defenseLevel: 5,
    antiCovertLevel: 5,
  },
];

export const TARGET_REALMS: TargetRealm[] = [
  ...BASE_TARGET_REALMS,
  ...CONVERT_NPC_RACES_TO_TARGET_REALMS(),
];

export const INITIAL_MOTHERSHIP_MODULES: MothershipModule[] = [
  { key: 'hull', name: 'Neutronium Reinforced Hull', level: 3, baseCost: 40000, benefit: '+1,500 Hull Integrity' },
  { key: 'volley_bays', name: 'Rapid Volley Weapon Bays', level: 2, baseCost: 35000, benefit: '+250 Strike Volley Power' },
  { key: 'shields', name: 'Phase Shift Shield Matrix', level: 3, baseCost: 45000, benefit: '+1,800 Shield Capacity' },
  { key: 'hangars', name: 'Fighter Hangars (F-302 Wings)', level: 2, baseCost: 30000, benefit: '+12 Interceptor Squadrons' },
  { key: 'scanners', name: 'Subspace Sensor Array', level: 2, baseCost: 28000, benefit: '+2 Sector Recon Range' },
  { key: 'jump_drive', name: 'Hyperdrive Engine Core', level: 1, baseCost: 60000, benefit: '-15% Travel Turn Consumption' },
];

export const INITIAL_PLANETS: PlanetColony[] = [
  {
    id: 'pl-homeworld',
    name: 'Homeworld Earth (Tau\'ri Command)',
    coordinate: '1:204:8',
    biome: 'Temperate Continental',
    level: 5,
    incomeBonus: 35000,
    defenseBonus: 65000,
    maintenanceCost: 10750,
    moonName: 'Luna Prime',
    jumpGateLevel: 2,
    isHomeworld: true,
    fieldsUsed: 84,
    fieldsMax: 188,
    temperature: '+18°C',
    diameterKm: 12742,
    hasMoon: true,
    metalProductionRate: 48500,
    crystalProductionRate: 29400,
    deuteriumProductionRate: 18200,
    naquadahProductionRate: 35000,
    energyProductionRate: 850,
    specialization: 'homeworld',
    governor: 'General George Hammond',
    taxPolicy: 'balanced',
    foodStockpile: 35000,
    foodCapacity: 100000,
    foodProductionRate: 14200,
    foodConsumptionRate: 8200,
    waterStockpile: 48000,
    waterCapacity: 120000,
    waterProductionRate: 18500,
    waterConsumptionRate: 10000,
    population: {
      total: 14000000,
      growthRatePerHour: 24500,
      housingCapacity: 22000000,
      happiness: 90,
      unrest: 10,
      strata: {
        farmers: 2400000,
        hydrologists: 2400000,
        miners: 2800000,
        industrialWorkers: 2600000,
        scientists: 1400000,
        administrators: 800000,
        militaryRecruits: 1600000,
      },
      livingStandard: 'utopian',
      rationingLevel: 'abundant',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 12,
      bioFarms: 8,
      geneticCropLabs: 5,
      deepAquiferPumps: 14,
      moistureCondensers: 10,
      desalinationPlants: 9,
      subsurfaceCisterns: 12,
      atmosphereScrubbers: 8,
    },
    hazards: [
      {
        id: 'hzd-earth-1',
        name: 'Industrial Smog & Atmospheric Carbon Accumulation',
        type: 'acid_rain',
        severity: 'low',
        icon: '🌧️',
        effectDescription: 'Atmospheric particulates reduce natural crop yields by 5% and increase water filtration loads.',
        habitabilityPenalty: 5,
        popGrowthPenalty: 4,
        waterContaminationPercent: 6,
        isMitigated: true,
        mitigationProjectName: 'Planetary Geo-Scrubber Array',
      },
      {
        id: 'hzd-earth-2',
        name: 'Pacific Tectonic Rim Subduction Fault',
        type: 'tectonic_fault',
        severity: 'moderate',
        icon: '🌋',
        effectDescription: 'Seismic tremors cause sporadic power grid disruptions and reduce building stability.',
        habitabilityPenalty: 8,
        popGrowthPenalty: 6,
        waterContaminationPercent: 4,
        isMitigated: false,
        mitigationProjectName: 'Seismic Dampener Grid Installation',
        mitigationCost: { metal: 45000, crystal: 30000, deuterium: 10000, naquadah: 15000 },
      },
    ],
    plunge: {
      plungeIndex: 8,
      stage: 'stable',
      trend: 'stable',
      reasons: ['Abundant food & clean aquifer water surpluses', 'High planetary happiness index'],
      activeCrises: [],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl0',
          name: 'Emergency Food & Aquifer Water Relief Airdrop',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained urban sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-welfare-stimulus-pl0',
          name: 'Imperial Welfare Subsidies & Citizens Stimulus',
          category: 'welfare',
          description: 'Disburse 25,000 Naquadah and credits to subsidize healthcare and colonial living standards.',
          cost: { naquadah: 25000, credits: 500 },
          plungeReduction: 15,
          happinessBonus: 14,
          cooldownMinutes: 30,
        },
        {
          id: 'int-peacekeeper-patrol-pl0',
          name: 'Colonial Peacekeeper & SGC Security Mobilization',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 8,
      shipyard: 10,
      researchLab: 12,
      allianceDepot: 3,
      missileSilo: 6,
      naniteFactory: 4,
      terraformer: 2,
    },
    mines: {
      metalMine: 24,
      crystalMine: 20,
      deuteriumSynthesizer: 18,
      solarPlant: 22,
      fusionReactor: 12,
      naquadahCoreTap: 16,
    },
    defenses: {
      rocketLauncher: 850,
      lightLaser: 420,
      heavyLaser: 180,
      gaussCannon: 65,
      ionCannon: 40,
      plasmaTurret: 18,
      smallShieldDome: true,
      largeShieldDome: true,
      antiBallisticMissiles: 45,
      interplanetaryMissiles: 15,
    },
    lunarBase: {
      level: 4,
      sensorPhalanxLevel: 5,
      jumpGateLevel: 2,
      moonFieldsUsed: 12,
      moonFieldsMax: 25,
    },
  },
  {
    id: 'pl-1',
    name: 'P3X-984 (Alpha Site)',
    coordinate: '1:12:4',
    biome: 'Mountainous Subterranean',
    level: 4,
    incomeBonus: 18500,
    defenseBonus: 32000,
    maintenanceCost: 13560,
    moonName: 'Orbit Station Alpha',
    jumpGateLevel: 2,
    fieldsUsed: 52,
    fieldsMax: 165,
    temperature: '+4°C',
    diameterKm: 11200,
    hasMoon: true,
    metalProductionRate: 28000,
    crystalProductionRate: 19500,
    deuteriumProductionRate: 12400,
    naquadahProductionRate: 22000,
    energyProductionRate: 520,
    specialization: 'fortress',
    governor: 'Colonel Jack O\'Neill',
    taxPolicy: 'balanced',
    foodStockpile: 18000,
    foodCapacity: 60000,
    foodProductionRate: 6800,
    foodConsumptionRate: 4500,
    waterStockpile: 22000,
    waterCapacity: 75000,
    waterProductionRate: 9200,
    waterConsumptionRate: 5200,
    population: {
      total: 2400000,
      growthRatePerHour: 5800,
      housingCapacity: 4500000,
      happiness: 82,
      unrest: 16,
      strata: {
        farmers: 350000,
        hydrologists: 400000,
        miners: 650000,
        industrialWorkers: 400000,
        scientists: 250000,
        administrators: 100000,
        militaryRecruits: 250000,
      },
      livingStandard: 'decent',
      rationingLevel: 'abundant',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 6,
      bioFarms: 4,
      geneticCropLabs: 2,
      deepAquiferPumps: 8,
      moistureCondensers: 6,
      desalinationPlants: 4,
      subsurfaceCisterns: 7,
      atmosphereScrubbers: 5,
    },
    hazards: [
      {
        id: 'hzd-alpha-1',
        name: 'Sub-Zero Cryo Frost & Mountain Blizzards',
        type: 'cryo_frost',
        severity: 'moderate',
        icon: '❄️',
        effectDescription: 'Frigid mountain temperatures increase surface power consumption by 15% and slow exterior facility expansion.',
        habitabilityPenalty: 12,
        popGrowthPenalty: 10,
        waterContaminationPercent: 2,
        isMitigated: true,
        mitigationProjectName: 'Subterranean Thermal Tap Vents',
      },
    ],
    plunge: {
      plungeIndex: 14,
      stage: 'stable',
      trend: 'stable',
      reasons: ['Secure subterranean bunker complex', 'Stable food and geothermal water reserves'],
      activeCrises: [],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl1',
          name: 'Emergency Food & Aquifer Water Relief Airdrop',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
      ],
    },
    facilities: {
      roboticsFactory: 5,
      shipyard: 6,
      researchLab: 8,
      allianceDepot: 2,
      missileSilo: 4,
      naniteFactory: 2,
      terraformer: 0,
    },
    mines: {
      metalMine: 18,
      crystalMine: 15,
      deuteriumSynthesizer: 14,
      solarPlant: 16,
      fusionReactor: 8,
      naquadahCoreTap: 12,
    },
    defenses: {
      rocketLauncher: 320,
      lightLaser: 150,
      heavyLaser: 60,
      gaussCannon: 24,
      ionCannon: 15,
      plasmaTurret: 6,
      smallShieldDome: true,
      largeShieldDome: false,
      antiBallisticMissiles: 20,
      interplanetaryMissiles: 5,
    },
    lunarBase: {
      level: 2,
      sensorPhalanxLevel: 3,
      jumpGateLevel: 1,
      moonFieldsUsed: 6,
      moonFieldsMax: 15,
    },
  },
  {
    id: 'pl-2',
    name: 'Chulak Stronghold',
    coordinate: '1:44:8',
    biome: 'Arid Plains',
    level: 2,
    incomeBonus: 10500,
    defenseBonus: 18500,
    maintenanceCost: 5950,
    moonName: 'Chulak Moon',
    jumpGateLevel: 1,
    fieldsUsed: 38,
    fieldsMax: 142,
    temperature: '+32°C',
    diameterKm: 9800,
    hasMoon: true,
    metalProductionRate: 19000,
    crystalProductionRate: 12000,
    deuteriumProductionRate: 8500,
    naquadahProductionRate: 14000,
    energyProductionRate: 380,
    specialization: 'industrial',
    governor: 'Master Bra\'tac',
    taxPolicy: 'balanced',
    foodStockpile: 9000,
    foodCapacity: 40000,
    foodProductionRate: 4100,
    foodConsumptionRate: 3800,
    waterStockpile: 8500,
    waterCapacity: 45000,
    waterProductionRate: 3900,
    waterConsumptionRate: 4200,
    population: {
      total: 1900000,
      growthRatePerHour: 2200,
      housingCapacity: 3000000,
      happiness: 64,
      unrest: 34,
      strata: {
        farmers: 280000,
        hydrologists: 220000,
        miners: 500000,
        industrialWorkers: 350000,
        scientists: 120000,
        administrators: 80000,
        militaryRecruits: 350000,
      },
      livingStandard: 'basic',
      rationingLevel: 'standard',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 4,
      bioFarms: 3,
      geneticCropLabs: 1,
      deepAquiferPumps: 4,
      moistureCondensers: 3,
      desalinationPlants: 2,
      subsurfaceCisterns: 4,
      atmosphereScrubbers: 3,
    },
    hazards: [
      {
        id: 'hzd-chulak-1',
        name: 'Solar Flare Radiation Burst & Atmospheric Thinning',
        type: 'solar_flare',
        severity: 'high',
        icon: '☀️',
        effectDescription: 'Unfiltered solar radiation bleaches surface farmlands and increases water evaporation rates.',
        habitabilityPenalty: 22,
        popGrowthPenalty: 18,
        waterContaminationPercent: 14,
        isMitigated: false,
        mitigationProjectName: 'Planetary Magnetic Deflector Array',
        mitigationCost: { metal: 60000, crystal: 45000, deuterium: 20000, naquadah: 25000 },
      },
      {
        id: 'hzd-chulak-2',
        name: 'Arid Duststorms & Seasonal Drought',
        type: 'toxic_spore',
        severity: 'moderate',
        icon: '🌪️',
        effectDescription: 'Violent particulate storms clog surface moisture condensers.',
        habitabilityPenalty: 12,
        popGrowthPenalty: 10,
        waterContaminationPercent: 8,
        isMitigated: false,
        mitigationProjectName: 'Sealed Dome Electro-Filtration Grids',
        mitigationCost: { metal: 35000, crystal: 20000, deuterium: 10000, naquadah: 8000 },
      },
    ],
    plunge: {
      plungeIndex: 38,
      stage: 'stressed',
      trend: 'deteriorating',
      reasons: ['Net negative water production (-300/h deficit)', 'Active unmitigated solar radiation storms', 'Mounting civil unrest among warrior castes'],
      activeCrises: ['Impending Aquifer Depletion Crisis', 'Solar Radiation Sickness Flare'],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl2',
          name: 'Emergency Food & Aquifer Water Relief Airdrop',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-peacekeeper-patrol-pl2',
          name: 'Colonial Peacekeeper & SGC Security Mobilization',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 4,
      shipyard: 4,
      researchLab: 4,
      allianceDepot: 1,
      missileSilo: 2,
      naniteFactory: 1,
      terraformer: 0,
    },
    mines: {
      metalMine: 14,
      crystalMine: 12,
      deuteriumSynthesizer: 10,
      solarPlant: 12,
      fusionReactor: 5,
      naquadahCoreTap: 8,
    },
    defenses: {
      rocketLauncher: 180,
      lightLaser: 80,
      heavyLaser: 30,
      gaussCannon: 12,
      ionCannon: 8,
      plasmaTurret: 2,
      smallShieldDome: true,
      largeShieldDome: false,
      antiBallisticMissiles: 10,
      interplanetaryMissiles: 0,
    },
    lunarBase: {
      level: 1,
      sensorPhalanxLevel: 2,
      jumpGateLevel: 1,
      moonFieldsUsed: 4,
      moonFieldsMax: 12,
    },
  },
  {
    id: 'pl-3',
    name: 'Abydos Naquadah Outpost',
    coordinate: '2:5:3',
    biome: 'Desert Dunes',
    level: 3,
    incomeBonus: 22000,
    defenseBonus: 12000,
    maintenanceCost: 7490,
    moonName: 'Tebet-1',
    jumpGateLevel: 1,
    fieldsUsed: 44,
    fieldsMax: 155,
    temperature: '+58°C',
    diameterKm: 10500,
    hasMoon: true,
    metalProductionRate: 15000,
    crystalProductionRate: 34000,
    deuteriumProductionRate: 6000,
    naquadahProductionRate: 48000,
    energyProductionRate: 420,
    specialization: 'mining',
    governor: 'Kasuf Elder',
    taxPolicy: 'extractive',
    foodStockpile: 6000,
    foodCapacity: 30000,
    foodProductionRate: 2200,
    foodConsumptionRate: 3100,
    waterStockpile: 5000,
    waterCapacity: 35000,
    waterProductionRate: 2400,
    waterConsumptionRate: 3500,
    population: {
      total: 1700000,
      growthRatePerHour: -450,
      housingCapacity: 2500000,
      happiness: 45,
      unrest: 56,
      strata: {
        farmers: 180000,
        hydrologists: 190000,
        miners: 850000,
        industrialWorkers: 220000,
        scientists: 80000,
        administrators: 60000,
        militaryRecruits: 120000,
      },
      livingStandard: 'impoverished',
      rationingLevel: 'strict_rationing',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 3,
      bioFarms: 2,
      geneticCropLabs: 0,
      deepAquiferPumps: 3,
      moistureCondensers: 2,
      desalinationPlants: 1,
      subsurfaceCisterns: 3,
      atmosphereScrubbers: 2,
    },
    hazards: [
      {
        id: 'hzd-abydos-1',
        name: 'Extreme Dune Hyperthermia (+58°C Surface Heat)',
        type: 'solar_flare',
        severity: 'high',
        icon: '🔥',
        effectDescription: 'Scorching daytime temperatures cause rapid water reservoir evaporation and worker heat exhaustion.',
        habitabilityPenalty: 28,
        popGrowthPenalty: 24,
        waterContaminationPercent: 20,
        isMitigated: false,
        mitigationProjectName: 'Sub-Sand Cooling Duct Complex',
        mitigationCost: { metal: 50000, crystal: 35000, deuterium: 15000, naquadah: 20000 },
      },
      {
        id: 'hzd-abydos-2',
        name: 'Shifting Silica Dune Migration',
        type: 'tectonic_fault',
        severity: 'moderate',
        icon: '🏜️',
        effectDescription: 'Mega sand waves bury perimeter mining roads and damage heavy extraction rigs.',
        habitabilityPenalty: 14,
        popGrowthPenalty: 12,
        waterContaminationPercent: 5,
        isMitigated: false,
        mitigationProjectName: 'Subsurface Dune Anchoring Anchors',
        mitigationCost: { metal: 30000, crystal: 15000, deuterium: 5000, naquadah: 10000 },
      },
    ],
    plunge: {
      plungeIndex: 58,
      stage: 'severe_crisis',
      trend: 'deteriorating',
      reasons: ['Dual Food (-900/h) and Water (-1,100/h) deficits', 'Extractive colonial tax policy causing worker fatigue', 'Extreme desert temperatures depleting moisture reserves'],
      activeCrises: ['Severe Famine Risk Alert', 'Impoverished Miner Labor Strike', 'Rapid Aquifer Desiccation'],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl3',
          name: 'Emergency Food & Aquifer Water Relief Airdrop',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-welfare-stimulus-pl3',
          name: 'Imperial Welfare Subsidies & Citizens Stimulus',
          category: 'welfare',
          description: 'Disburse 25,000 Naquadah and credits to subsidize healthcare and colonial living standards.',
          cost: { naquadah: 25000, credits: 500 },
          plungeReduction: 15,
          happinessBonus: 14,
          cooldownMinutes: 30,
        },
        {
          id: 'int-peacekeeper-patrol-pl3',
          name: 'Colonial Peacekeeper & SGC Security Mobilization',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 3,
      shipyard: 3,
      researchLab: 5,
      allianceDepot: 1,
      missileSilo: 3,
      naniteFactory: 1,
      terraformer: 0,
    },
    mines: {
      metalMine: 12,
      crystalMine: 22,
      deuteriumSynthesizer: 8,
      solarPlant: 18,
      fusionReactor: 4,
      naquadahCoreTap: 20,
    },
    defenses: {
      rocketLauncher: 120,
      lightLaser: 60,
      heavyLaser: 20,
      gaussCannon: 8,
      ionCannon: 5,
      plasmaTurret: 2,
      smallShieldDome: false,
      largeShieldDome: false,
      antiBallisticMissiles: 8,
      interplanetaryMissiles: 0,
    },
    lunarBase: {
      level: 1,
      sensorPhalanxLevel: 1,
      jumpGateLevel: 1,
      moonFieldsUsed: 3,
      moonFieldsMax: 10,
    },
  },
];

export const INITIAL_MARKET_ORDERS: MarketOrder[] = [
  { id: 'mkt-1', sellerName: 'Rebel Jaffa Cartel', resourceType: 'naquadah', quantity: 250000, pricePerUnit: 1.0, totalCost: 250000 },
  { id: 'mkt-2', sellerName: 'Free Asgard Guild', resourceType: 'super-weapon', quantity: 15, pricePerUnit: 14000, totalCost: 210000 },
  { id: 'mkt-3', sellerName: 'Tok\'ra Logistics', resourceType: 'energy-core', quantity: 5, pricePerUnit: 48000, totalCost: 240000 },
];

export const MERCENARY_CONTRACTS: MercenaryContract[] = [
  {
    id: 'merc-1',
    name: 'Free Jaffa Assault Cadre',
    type: 'infantry',
    attackPower: 120,
    defensePower: 80,
    cost: 18000,
    upkeepPerTurn: 450,
    available: 12,
  },
  {
    id: 'merc-2',
    name: 'Kull Warrior Biomechanical Unit',
    type: 'heavy',
    attackPower: 350,
    defensePower: 300,
    cost: 55000,
    upkeepPerTurn: 1200,
    available: 4,
  },
  {
    id: 'merc-3',
    name: 'Tok\'ra Symbiote Infiltrators',
    type: 'infiltrator',
    attackPower: 60,
    defensePower: 50,
    cost: 28000,
    upkeepPerTurn: 600,
    available: 8,
  },
];

export const INITIAL_RANKINGS: RankingEntry[] = [
  { rank: 1, commanderName: 'Supreme Commander Thor', race: 'Asgard', overallScore: 245000, attackScore: 190000, defenseScore: 310000, covertScore: 180000, mothershipScore: 300000, glory: 4800 },
  { rank: 2, commanderName: 'Anubis Dread Fleet', race: "Goa'uld", overallScore: 212000, attackScore: 230000, defenseScore: 220000, covertScore: 205000, mothershipScore: 193000, glory: 3900 },
  { rank: 3, commanderName: 'Commander Tanang (You)', race: "Tau'ri", overallScore: 168500, attackScore: 175000, defenseScore: 182000, covertScore: 142000, mothershipScore: 175000, glory: 1250 },
  { rank: 4, commanderName: 'Lord Apophis', race: "Goa'uld", overallScore: 142000, attackScore: 155000, defenseScore: 140000, covertScore: 132000, mothershipScore: 141000, glory: 1100 },
  { rank: 5, commanderName: 'Replicator Queen 01', race: 'Replicator', overallScore: 139000, attackScore: 125000, defenseScore: 130000, covertScore: 210000, mothershipScore: 91000, glory: 980 },
  { rank: 6, commanderName: 'Baal Syndicate', race: "Goa'uld", overallScore: 118000, attackScore: 110000, defenseScore: 125000, covertScore: 135000, mothershipScore: 102000, glory: 820 },
  { rank: 7, commanderName: 'Bra\'tac Free Council', race: 'Jaffa', overallScore: 95000, attackScore: 102000, defenseScore: 98000, covertScore: 78000, mothershipScore: 102000, glory: 690 },
];

export const INITIAL_ALLIANCES: Alliance[] = [
  { id: 'all-1', name: 'Tau\'ri Defense Coalition', tag: '[TDC]', leader: 'Commander Tanang', membersCount: 14, treasury: 1850000, isOpen: true },
  { id: 'all-2', name: 'System Lords High Court', tag: '[SL]', leader: 'Lord Apophis', membersCount: 22, treasury: 4500000, isOpen: false },
  { id: 'all-3', name: 'Asgard Protected Planets Alliance', tag: '[APPA]', leader: 'Supreme Commander Thor', membersCount: 8, treasury: 6200000, isOpen: true },
];

export const INITIAL_MESSAGES: GameMessage[] = [
  {
    id: 'msg-1',
    sender: 'Supreme Commander Thor',
    recipient: 'Commander Tanang',
    subject: 'Asgard Shield Upgrades Dispatched',
    body: 'Greetings, Commander. We have observed heightened Replicator activity in Sector 4. High-frequency shield modulators have been transferred to your armory reserves. Maintain vigilance.',
    timestamp: '14 minutes ago',
    read: false,
  },
  {
    id: 'msg-2',
    sender: 'SGC High Command',
    recipient: 'Commander Tanang',
    subject: 'Turn Settlement & Naquadah Logistics',
    body: 'Commander, the off-world mining teams on P3X-984 reported 100% extraction efficiency. Verify your bank vault allocation to prevent overflow losses during upcoming turn cycles.',
    timestamp: '1 hour ago',
    read: true,
  },
];
