import {
  HyperspaceDriveTech,
  SubspaceJumpGate,
  WormholeAnomaly,
  MothershipTitanClass,
  MothershipTacticalAbility,
} from './types';

export const HYPERSPACE_DRIVES: HyperspaceDriveTech[] = [
  {
    id: 'drive_combustion',
    name: 'Chemical Combustion Drive',
    tier: 1,
    speedMultiplier: 1.0,
    fuelEfficiency: 1.0,
    deuteriumCostPerHour: 50,
    description: 'High-thrust chemical reaction rockets utilized for small freighters, light fighters, and orbital probes.',
    level: 8,
  },
  {
    id: 'drive_impulse',
    name: 'Sub-Light Impulse Drive',
    tier: 2,
    speedMultiplier: 2.2,
    fuelEfficiency: 1.4,
    deuteriumCostPerHour: 120,
    description: 'Relativistic ion-plasma propulsion bending local space-time slightly to achieve 20% speed of light. Powers Cruisers & Heavy Transports.',
    level: 6,
  },
  {
    id: 'drive_hyperspace',
    name: 'FTL Hyperspace Drive',
    tier: 3,
    speedMultiplier: 4.5,
    fuelEfficiency: 2.0,
    deuteriumCostPerHour: 280,
    description: 'Subspace field generator allowing vessels to slip into higher hyperspace dimensions to travel light-years in minutes. Powers Battleships, Bombers & Destroyers.',
    level: 5,
  },
  {
    id: 'drive_tachyon',
    name: 'Tachyon Quantum Fold Engine',
    tier: 4,
    speedMultiplier: 8.0,
    fuelEfficiency: 3.2,
    deuteriumCostPerHour: 550,
    description: 'Harnesses superluminal tachyon particles to fold two distant points in space-time into instantaneous contact. Powers Battlecruisers & Ripstars.',
    level: 3,
  },
  {
    id: 'drive_slipstream',
    name: 'Intergalactic Subspace Slipstream Core',
    tier: 5,
    speedMultiplier: 15.0,
    fuelEfficiency: 5.0,
    deuteriumCostPerHour: 1100,
    description: 'Pierces through the fabric of subspace corridors to traverse entire galactic clusters with zero relativistic dilation. Powers Capital Flagships.',
    level: 2,
  },
];

export const INITIAL_JUMP_GATES: SubspaceJumpGate[] = [
  {
    id: 'gate-1',
    name: 'Lunar Alpha → Phalanx Beta Relay',
    originMoon: 'Lunar Alpha [1:234:4]',
    destinationMoon: 'Phalanx Beta [2:112:8]',
    chargePercentage: 100,
    ready: true,
    cooldownSeconds: 0,
  },
  {
    id: 'gate-2',
    name: 'Phalanx Beta → Orion Deep Anchor',
    originMoon: 'Phalanx Beta [2:112:8]',
    destinationMoon: 'Orion Deep [3:400:15]',
    chargePercentage: 74,
    ready: false,
    cooldownSeconds: 156,
  },
  {
    id: 'gate-3',
    name: 'Deep Space Stargate Super-Conduit',
    originMoon: 'Lunar Alpha [1:234:4]',
    destinationMoon: 'Pegasus Sanctuary [5:50:3]',
    chargePercentage: 100,
    ready: true,
    cooldownSeconds: 0,
  },
];

export const WORMHOLE_ANOMALIES: WormholeAnomaly[] = [
  {
    id: 'wormhole-alpha',
    name: 'Gravitational Rift Alpha-7',
    stability: 'stable',
    destinationSector: 'Sector 89: Ancient Forerunner Vaults',
    dangerRating: 'low',
    rewardPotential: 'High (Dark Matter Caches & Rare Alloys)',
    durationSeconds: 1800,
  },
  {
    id: 'wormhole-beta',
    name: 'Chronal Distortion Void',
    stability: 'fluctuating',
    destinationSector: 'Unknown Quadrant: Derelict Alien Graveyard',
    dangerRating: 'moderate',
    rewardPotential: 'Extreme (Lost Capital Blueprints & Precursor Relics)',
    durationSeconds: 940,
  },
  {
    id: 'wormhole-gamma',
    name: 'Singularity Breach Zero',
    stability: 'critical',
    destinationSector: 'Temporal Nexus: Dark Energy Wells',
    dangerRating: 'extreme',
    rewardPotential: 'Cosmic (10,000+ Dark Matter & Titan Cores)',
    durationSeconds: 320,
  },
];

export const MOTHERSHIP_TITAN_CLASSES: MothershipTitanClass[] = [
  {
    id: 'class_dreadnought',
    name: 'Sovereign-Class Dreadnought',
    hullType: 'dreadnought',
    hullHp: 1500000,
    shieldHp: 950000,
    firepower: 480000,
    energyCore: 12000,
    hangarSlots: 8,
    flagshipBonus: '+20% Fleet Broadside Volley Damage',
    description: 'Heavy armor-clad capital command ship engineered with multi-axis railguns and forward torpedo tubes.',
  },
  {
    id: 'class_titan',
    name: 'O\'Neill-Class Asgard Titan',
    hullType: 'titan',
    hullHp: 3200000,
    shieldHp: 2800000,
    firepower: 950000,
    energyCore: 25000,
    hangarSlots: 14,
    flagshipBonus: '+40% Fleet Energy Shields & Fast Regeneration',
    description: 'Constructed from refined neutronium-trinium alloys. Armed with high-output ion pulse cannons and phased defensive barriers.',
  },
  {
    id: 'class_colossus',
    name: 'Apophis Sun-Crusher Colossus',
    hullType: 'colossus',
    hullHp: 5500000,
    shieldHp: 3500000,
    firepower: 1850000,
    energyCore: 40000,
    hangarSlots: 20,
    flagshipBonus: '+50% Orbital Bombardment & Defense Penetration',
    description: 'Titanic pyramid-structured war temple housing a planetary spinal cannon capable of shattering crustal defenses.',
  },
  {
    id: 'class_world_eater',
    name: 'Leviathan Star-Eater Ark',
    hullType: 'world_eater',
    hullHp: 9000000,
    shieldHp: 6500000,
    firepower: 3200000,
    energyCore: 80000,
    hangarSlots: 32,
    flagshipBonus: 'Recycles 50% of all destroyed ships directly into fuel & nanites during combat',
    description: 'A mobile stellar fortress that captures cosmic matter and fuels ongoing fleet sieges across galaxies.',
  },
];

export const MOTHERSHIP_TACTICAL_ABILITIES: MothershipTacticalAbility[] = [
  {
    id: 'ability_orbital_beam',
    name: 'Spinal Titan Beam Lance',
    energyCost: 1500,
    cooldownSeconds: 60,
    remainingCooldown: 0,
    icon: '⚡',
    description: 'Discharges an antimatter focused ray across target orbital coordinates, inflicting devastating structural damage.',
    effectType: 'bombardment',
  },
  {
    id: 'ability_shield_overcharge',
    name: 'Quantum Barrier Overdrive',
    energyCost: 1200,
    cooldownSeconds: 45,
    remainingCooldown: 0,
    icon: '🛡️',
    description: 'Overcharges shield harmonics to absorb 100% incoming laser and kinetic fire for the next 30 seconds.',
    effectType: 'shield_overcharge',
  },
  {
    id: 'ability_warp_jump',
    name: 'Emergency Subspace Micro-Jump',
    energyCost: 2000,
    cooldownSeconds: 90,
    remainingCooldown: 0,
    icon: '🌀',
    description: 'Folds space to instantaneously reposition the mothership and escort flotilla away from lethal ambushes.',
    effectType: 'warp_jump',
  },
  {
    id: 'ability_sensor_sweep',
    name: 'Tachyon Hyper-Sensor Pulse',
    energyCost: 800,
    cooldownSeconds: 30,
    remainingCooldown: 0,
    icon: '📡',
    description: 'Sends out an ultra-wide sensor pulse revealing all hostile fleets in flight across 5 neighboring solar systems.',
    effectType: 'sensor_sweep',
  },
  {
    id: 'ability_fleet_aura',
    name: 'Supreme Command Fleet Aura',
    energyCost: 1000,
    cooldownSeconds: 60,
    remainingCooldown: 0,
    icon: '👑',
    description: 'Transmits tactical target telemetry to all escorted ships, boosting friendly fleet weapon accuracy and fire rate by 35%.',
    effectType: 'fleet_aura',
  },
];
