import { OGameServer, SolarSystemSlot, ACSAttackGroup, MissileSiloData } from './types';

export const OGAME_SERVERS: OGameServer[] = [
  {
    id: 'uni-1',
    name: 'Universe 1 (Classic)',
    type: 'classic',
    speedMultiplier: 1,
    fleetSpeedMultiplier: 1,
    debrisFieldPercent: 30,
    playersOnline: 1420,
    galaxiesCount: 9,
    systemsPerGalaxy: 499,
    acsEnabled: true,
    defensesToDebris: false,
    status: 'recommended',
    description: 'The definitive standard Game experience. Balanced economy, strategic fleetsaving, and classic 30% debris fields.',
  },
  {
    id: 'uni-electra',
    name: 'Universe Electra (War)',
    type: 'war',
    speedMultiplier: 5,
    fleetSpeedMultiplier: 4,
    debrisFieldPercent: 70,
    playersOnline: 2150,
    galaxiesCount: 9,
    systemsPerGalaxy: 499,
    acsEnabled: true,
    defensesToDebris: true,
    status: 'hardcore',
    description: 'Aggressive universe where 70% of fleet and defense wreckage creates massive debris fields. High-stakes PvP warfare.',
  },
  {
    id: 'uni-quantum',
    name: 'Universe Quantum (Speed & Hyper-Raid)',
    type: 'speed',
    speedMultiplier: 10,
    fleetSpeedMultiplier: 8,
    debrisFieldPercent: 80,
    playersOnline: 3400,
    galaxiesCount: 9,
    systemsPerGalaxy: 499,
    acsEnabled: true,
    defensesToDebris: false,
    status: 'active',
    description: 'Maximum velocity simulation. Instantaneous fleet jumps, 10x resource ticks, and fast-paced interstellar expansion.',
  },
  {
    id: 'uni-pegasus',
    name: 'Universe Pegasus (Economy & Peace)',
    type: 'eco',
    speedMultiplier: 4,
    fleetSpeedMultiplier: 1,
    debrisFieldPercent: 30,
    playersOnline: 980,
    galaxiesCount: 6,
    systemsPerGalaxy: 400,
    acsEnabled: false,
    defensesToDebris: false,
    status: 'recommended',
    description: '4x Mining & Construction rate with calm 1x fleet transit. Perfect for industrial builders, mega-science, and peaceful expansion.',
  },
];

export const INITIAL_SOLAR_SYSTEM_SLOTS: SolarSystemSlot[] = [
  {
    slotNumber: 1,
    type: 'planet',
    planetName: 'Vulcan Forge Prime',
    planetClass: 'Class B (Molten)',
    planetDiameterKm: 4800,
    temperatureMin: 220,
    temperatureMax: 650,
    playerName: 'Warlord Pyros',
    playerRank: 42,
    allianceTag: '[SOLAR]',
    playerStatus: 'active',
    hasMoon: false,
    debrisField: { metal: 45000, crystal: 28000 },
  },
  {
    slotNumber: 2,
    type: 'planet',
    planetName: 'Helios Infernal',
    planetClass: 'Class Y (Toxic Acid)',
    planetDiameterKm: 6100,
    temperatureMin: 180,
    temperatureMax: 490,
    playerName: 'Baron Karr',
    playerRank: 89,
    allianceTag: '[WAR]',
    playerStatus: 'inactive',
    hasMoon: false,
    debrisField: { metal: 12000, crystal: 8500 },
  },
  {
    slotNumber: 3,
    type: 'planet',
    planetName: 'Caelum Outpost',
    planetClass: 'Class H (Desert)',
    planetDiameterKm: 8900,
    temperatureMin: 40,
    temperatureMax: 110,
    playerName: 'Miner Frank',
    playerRank: 154,
    allianceTag: '[MINE]',
    playerStatus: 'active',
    hasMoon: true,
    moonName: 'Caelum Minor',
    moonDiameterKm: 1800,
    debrisField: undefined,
  },
  {
    slotNumber: 4,
    type: 'planet',
    planetName: 'Terra Nova (Your Colony)',
    planetClass: 'Class M (Continental)',
    planetDiameterKm: 12800,
    temperatureMin: -5,
    temperatureMax: 35,
    playerName: 'Commander Tanang',
    playerRank: 3,
    allianceTag: '[TAURI]',
    playerStatus: 'active',
    hasMoon: true,
    moonName: 'Lunar Alpha',
    moonDiameterKm: 3400,
    debrisField: undefined,
  },
  {
    slotNumber: 5,
    type: 'planet',
    planetName: 'Aethelgard Prime',
    planetClass: 'Class M (Terrestrial)',
    planetDiameterKm: 13400,
    temperatureMin: 0,
    temperatureMax: 40,
    playerName: 'Emperor Vane',
    playerRank: 7,
    allianceTag: '[VOID]',
    playerStatus: 'active',
    hasMoon: true,
    moonName: 'Aethel Phalanx',
    moonDiameterKm: 2900,
    debrisField: { metal: 180000, crystal: 95000 },
  },
  {
    slotNumber: 6,
    type: 'empty',
  },
  {
    slotNumber: 7,
    type: 'planet',
    planetName: 'Zephyr Arcadia',
    planetClass: 'Class O (Oceanic)',
    planetDiameterKm: 14200,
    temperatureMin: 15,
    temperatureMax: 50,
    playerName: 'Admiral Marina',
    playerRank: 64,
    allianceTag: '[DEEP]',
    playerStatus: 'vacation',
    hasMoon: false,
    debrisField: undefined,
  },
  {
    slotNumber: 8,
    type: 'planet',
    planetName: 'Sovereign Nexus',
    planetClass: 'Class G (Crystalline)',
    planetDiameterKm: 11900,
    temperatureMin: -15,
    temperatureMax: 25,
    playerName: 'Archon Replicus',
    playerRank: 14,
    allianceTag: '[NEXUS]',
    playerStatus: 'strong',
    hasMoon: true,
    moonName: 'Nexus Eye',
    moonDiameterKm: 4100,
    debrisField: { metal: 320000, crystal: 210000 },
  },
  {
    slotNumber: 9,
    type: 'empty',
  },
  {
    slotNumber: 10,
    type: 'planet',
    planetName: 'Hyperion Deep',
    planetClass: 'Class I (Gas Giant)',
    planetDiameterKm: 110000,
    temperatureMin: -90,
    temperatureMax: -20,
    playerName: 'Governor Geryon',
    playerRank: 112,
    allianceTag: '[SOLAR]',
    playerStatus: 'active',
    hasMoon: true,
    moonName: 'Geryon IV',
    moonDiameterKm: 2200,
    debrisField: { metal: 25000, crystal: 14000 },
  },
  {
    slotNumber: 11,
    type: 'empty',
  },
  {
    slotNumber: 12,
    type: 'planet',
    planetName: 'Cryo Boreas',
    planetClass: 'Class P (Glaciated)',
    planetDiameterKm: 9800,
    temperatureMin: -140,
    temperatureMax: -60,
    playerName: 'Frost King',
    playerRank: 201,
    allianceTag: '[ICE]',
    playerStatus: 'inactive',
    hasMoon: false,
    debrisField: { metal: 65000, crystal: 40000 },
  },
  {
    slotNumber: 13,
    type: 'empty',
  },
  {
    slotNumber: 14,
    type: 'planet',
    planetName: 'Deuterium Abyss',
    planetClass: 'Class W (Cryo-Neptune)',
    planetDiameterKm: 45000,
    temperatureMin: -180,
    temperatureMax: -95,
    playerName: 'Fuel Syndicate',
    playerRank: 33,
    allianceTag: '[FUEL]',
    playerStatus: 'active',
    hasMoon: false,
    debrisField: undefined,
  },
  {
    slotNumber: 15,
    type: 'planet',
    planetName: 'Ultima Thule',
    planetClass: 'Class Z (Zero-Zone Void)',
    planetDiameterKm: 8500,
    temperatureMin: -240,
    temperatureMax: -190,
    playerName: 'Void Hermit',
    playerRank: 95,
    allianceTag: '[SOLO]',
    playerStatus: 'noob',
    hasMoon: true,
    moonName: 'Ghost Shard',
    moonDiameterKm: 1100,
    debrisField: { metal: 80000, crystal: 50000 },
  },
];

export const INITIAL_ACS_GROUPS: ACSAttackGroup[] = [
  {
    id: 'acs-1',
    missionName: 'Operation Eclipse Strike',
    targetCoord: '[1:234:8] Nexus Eye Moon',
    leadCommander: 'Commander Tanang',
    members: ['Commander Tanang', 'Thor (Asgard)', 'Jacob Carter (Tok\'ra)'],
    totalShips: 2450,
    arrivalSeconds: 142,
    status: 'in_flight',
  },
  {
    id: 'acs-2',
    missionName: 'Defensive Fleet Garrison: Moon Alpha',
    targetCoord: '[1:234:4] Lunar Alpha',
    leadCommander: 'General O\'Neill',
    members: ['General O\'Neill', 'Bra\'tac of Chulak'],
    totalShips: 1200,
    arrivalSeconds: 48,
    status: 'coordinating',
  },
];

export const INITIAL_MISSILE_SILO: MissileSiloData = {
  level: 4,
  ipmCount: 15,
  abmCount: 20,
  maxCapacity: 40,
  rangeSystems: 12,
};
