import {
  OGameTechnology,
  OGameFacility,
  OGameShip,
  OGameDefense,
  FleetFormation,
  FleetFormationPreset,
  MegastructureProject,
  ExpeditionLog,
  ExpeditionMission,
} from './types';

// =========================================================================
// 1. OGAME MASTER RESEARCH LIBRARY & TECH TREE
// =========================================================================
export const OGAME_TECHNOLOGIES: OGameTechnology[] = [
  // --- ECONOMICS & MINING BRANCH ---
  {
    id: 'basic_engineering',
    name: 'Basic Engineering',
    branch: 'economics',
    category: 'materials',
    description: 'Foundational civil and planetary engineering principles enabling industrial infrastructure.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 200, crystal: 100, deuterium: 0, energy: 10 },
    costMultiplier: 1.5,
    baseTimeSeconds: 15,
    prerequisites: [],
    effects: [
      { type: 'production_boost', label: 'Construction Speed', valuePerLevel: 5, unit: '%' },
    ],
    unlockTargets: ['Metal Mine Lv 2', 'Robotics Factory'],
  },
  {
    id: 'mineral_processing',
    name: 'Mineral Processing',
    branch: 'economics',
    category: 'mining',
    description: 'Advanced separation and refining of raw geological ores into high-purity structural ingots.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 400, crystal: 200, deuterium: 50, energy: 20 },
    costMultiplier: 1.6,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'basic_engineering', name: 'Basic Engineering', requiredLevel: 1 }],
    effects: [
      { type: 'production_boost', label: 'Metal Mine Output', valuePerLevel: 6, unit: '%' },
    ],
    unlockTargets: ['Metal Refinery', 'Deep Core Mining'],
  },
  {
    id: 'deep_core_mining',
    name: 'Deep Core Mining',
    branch: 'economics',
    category: 'mining',
    description: 'Pressurized tectonic drilling into planetary mantles to extract dense heavy elements.',
    level: 0,
    maxLevel: 40,
    baseCost: { metal: 1200, crystal: 800, deuterium: 300, energy: 50 },
    costMultiplier: 1.7,
    baseTimeSeconds: 50,
    prerequisites: [{ type: 'tech', id: 'mineral_processing', name: 'Mineral Processing', requiredLevel: 2 }],
    effects: [
      { type: 'production_boost', label: 'Mantle Ore Yield', valuePerLevel: 8, unit: '%' },
    ],
    unlockTargets: ['Rare Mineral Extractor', 'Heavy Asteroid Harvester'],
  },
  {
    id: 'asteroid_mining',
    name: 'Asteroid Mining Tech',
    branch: 'economics',
    category: 'mining',
    description: 'Automated tractor arrays and orbital smelting drones for deep space belt prospecting.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 2500, deuterium: 1200, energy: 100 },
    costMultiplier: 1.75,
    baseTimeSeconds: 90,
    prerequisites: [
      { type: 'tech', id: 'deep_core_mining', name: 'Deep Core Mining', requiredLevel: 3 },
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 2 },
    ],
    effects: [
      { type: 'production_boost', label: 'Off-World Extraction', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Asteroid Harvester Ship', 'Stellar Mining'],
  },

  // --- ENERGY BRANCH ---
  {
    id: 'energy_science',
    name: 'Energy Science',
    branch: 'science',
    category: 'energy',
    description: 'Universal theory of high-density electromagnetic conversion and capacitor storage.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 0, crystal: 800, deuterium: 400, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 20,
    prerequisites: [],
    effects: [
      { type: 'energy_boost', label: 'Power Grid Efficiency', valuePerLevel: 4, unit: '%' },
    ],
    unlockTargets: ['Solar Energy', 'Fusion Energy', 'Laser Technology'],
  },
  {
    id: 'solar_energy',
    name: 'Solar Energy Tech',
    branch: 'science',
    category: 'energy',
    description: 'High-efficiency photovoltaic nanocoatings that maximize orbital and surface solar flux capture.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 300, crystal: 500, deuterium: 100, energy: 0 },
    costMultiplier: 1.55,
    baseTimeSeconds: 30,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 1 }],
    effects: [
      { type: 'energy_boost', label: 'Solar Plant Generation', valuePerLevel: 7, unit: '%' },
    ],
    unlockTargets: ['Solar Satellites', 'Stellar Power Collector'],
  },
  {
    id: 'fusion_energy',
    name: 'Fusion Energy',
    branch: 'science',
    category: 'energy',
    description: 'Magnetic confinement of Deuterium-Tritium plasma generating immense continuous megawatts.',
    level: 0,
    maxLevel: 40,
    baseCost: { metal: 1600, crystal: 1400, deuterium: 1000, energy: 0 },
    costMultiplier: 1.65,
    baseTimeSeconds: 60,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 3 }],
    effects: [
      { type: 'energy_boost', label: 'Fusion Reactor Output', valuePerLevel: 12, unit: '%' },
    ],
    unlockTargets: ['Fusion Reactor', 'Fusion Drive', 'Cruiser Class'],
  },
  {
    id: 'antimatter_tech',
    name: 'Antimatter Tech',
    branch: 'advanced_science',
    category: 'energy',
    description: 'Subatomic particle collision and Penning-trap containment of positrons and antiprotons.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 8000, crystal: 12000, deuterium: 9000, energy: 500 },
    costMultiplier: 1.8,
    baseTimeSeconds: 160,
    prerequisites: [
      { type: 'tech', id: 'fusion_energy', name: 'Fusion Energy', requiredLevel: 5 },
      { type: 'tech', id: 'quantum_computing', name: 'Quantum Computing', requiredLevel: 3 },
    ],
    effects: [
      { type: 'energy_boost', label: 'Antimatter Output', valuePerLevel: 18, unit: '%' },
      { type: 'weapon_boost', label: 'Antimatter Beam Damage', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Antimatter Reactor', 'Antimatter Torpedoes', 'Dreadnought'],
  },
  {
    id: 'zero_point_energy',
    name: 'Zero Point Energy',
    branch: 'endgame',
    category: 'energy',
    description: 'Extraction of vacuum quantum fluctuations from localized sub-space manifolds (ZPM equivalent).',
    level: 0,
    maxLevel: 20,
    baseCost: { metal: 50000, crystal: 80000, deuterium: 60000, energy: 2000 },
    costMultiplier: 2.0,
    baseTimeSeconds: 360,
    prerequisites: [
      { type: 'tech', id: 'antimatter_tech', name: 'Antimatter Tech', requiredLevel: 6 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Dimensional Propulsion', requiredLevel: 4 },
    ],
    effects: [
      { type: 'energy_boost', label: 'Empire Power Surplus', valuePerLevel: 25, unit: '%' },
    ],
    unlockTargets: ['Zero Point Reactor', 'Titan Super-Capital', 'Dyson Sphere'],
  },

  // --- SCIENCE & COMPUTING BRANCH ---
  {
    id: 'computer_technology',
    name: 'Computer Technology',
    branch: 'science',
    category: 'computing',
    description: 'Distributed command networks capable of orchestrating remote interstellar fleets and orbital grids.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 0, crystal: 400, deuterium: 600, energy: 10 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [],
    effects: [
      { type: 'fleet_slot', label: 'Active Fleet Slots', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Fleet Command', 'Automated Shipyard', 'Advanced Computers'],
  },
  {
    id: 'quantum_computing',
    name: 'Quantum Computing',
    branch: 'advanced_science',
    category: 'computing',
    description: 'Entangled q-bit logic gates executing millions of orbital flight vectors simultaneously.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 2000, crystal: 4500, deuterium: 3000, energy: 50 },
    costMultiplier: 1.7,
    baseTimeSeconds: 80,
    prerequisites: [{ type: 'tech', id: 'computer_technology', name: 'Computer Technology', requiredLevel: 5 }],
    effects: [
      { type: 'research_speed', label: 'Research Lab Speed', valuePerLevel: 8, unit: '%' },
      { type: 'fleet_slot', label: 'Advanced Fleet Slots', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Artificial Intelligence', 'Quantum Shields', 'Planetary Computer'],
  },
  {
    id: 'artificial_intelligence',
    name: 'Artificial Intelligence',
    branch: 'advanced_science',
    category: 'ai',
    description: 'Sentient tactical cores providing instantaneous real-time combat recalculation during space battles.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 6000, crystal: 10000, deuterium: 7500, energy: 120 },
    costMultiplier: 1.8,
    baseTimeSeconds: 140,
    prerequisites: [{ type: 'tech', id: 'quantum_computing', name: 'Quantum Computing', requiredLevel: 4 }],
    effects: [
      { type: 'weapon_boost', label: 'Autonomous Fleet Precision', valuePerLevel: 6, unit: '%' },
      { type: 'speed_boost', label: 'Drone Reaction Speed', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Autonomous Fleet Formations', 'Nanite Factory Lv 2'],
  },

  // --- PROPULSION BRANCH ---
  {
    id: 'chemical_propulsion',
    name: 'Chemical Propulsion',
    branch: 'military',
    category: 'propulsion',
    description: 'Liquid and solid hypergolic rocket propellants for surface-to-orbit boosters and light probes.',
    level: 1,
    maxLevel: 30,
    baseCost: { metal: 200, crystal: 400, deuterium: 200, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 20,
    prerequisites: [],
    effects: [
      { type: 'speed_boost', label: 'Cargo & Probe Speed', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Small Cargo', 'Espionage Probe', 'Light Fighter'],
  },
  {
    id: 'ion_propulsion',
    name: 'Ion Propulsion',
    branch: 'military',
    category: 'propulsion',
    description: 'Electrostatic acceleration of xenon ions delivering high specific impulse for patrol frigates.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 1000, crystal: 2000, deuterium: 800, energy: 30 },
    costMultiplier: 1.6,
    baseTimeSeconds: 45,
    prerequisites: [
      { type: 'tech', id: 'chemical_propulsion', name: 'Chemical Propulsion', requiredLevel: 2 },
      { type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 2 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Cruiser & Frigate Speed', valuePerLevel: 15, unit: '%' },
    ],
    unlockTargets: ['Heavy Fighter', 'Frigate', 'Cruiser', 'Heavy Recycler'],
  },
  {
    id: 'hyperspace_drive',
    name: 'Hyperspace Drive',
    branch: 'advanced_fleet',
    category: 'propulsion',
    description: 'Subspace field compression that tunnels ships into superluminal hyperspace corridors.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 8000, crystal: 15000, deuterium: 12000, energy: 200 },
    costMultiplier: 1.75,
    baseTimeSeconds: 150,
    prerequisites: [
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 4 },
      { type: 'tech', id: 'fusion_energy', name: 'Fusion Energy', requiredLevel: 4 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Capital Ship Subspace Speed', valuePerLevel: 20, unit: '%' },
    ],
    unlockTargets: ['Battleship', 'Battlecruiser', 'Carrier Class', 'Hyperspace Gate'],
  },
  {
    id: 'dimensional_propulsion',
    name: 'Dimensional Propulsion',
    branch: 'endgame',
    category: 'dimensional',
    description: 'Folding the cosmological metric to instantaneous phase-transition through extra-dimensional rifts.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 45000, crystal: 70000, deuterium: 50000, energy: 1500 },
    costMultiplier: 2.1,
    baseTimeSeconds: 320,
    prerequisites: [
      { type: 'tech', id: 'hyperspace_drive', name: 'Hyperspace Drive', requiredLevel: 6 },
      { type: 'tech', id: 'quantum_computing', name: 'Quantum Computing', requiredLevel: 6 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Universal Fleet Speed', valuePerLevel: 30, unit: '%' },
    ],
    unlockTargets: ['Titan Class Flagships', 'Wormhole Gateways', 'Galactic Jump'],
  },

  // --- WEAPONS BRANCH ---
  {
    id: 'kinetic_weapons',
    name: 'Kinetic Weapons',
    branch: 'military',
    category: 'weapons',
    description: 'Electromagnetic railguns and coilguns that fire dense depleted-uranium sabot rounds at orbital velocities.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 600, crystal: 200, deuterium: 0, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [],
    effects: [
      { type: 'weapon_boost', label: 'Kinetic Turret & Sabot Fire', valuePerLevel: 8, unit: '%' },
    ],
    unlockTargets: ['Defense Turret', 'Railgun Battery', 'Light Fighter Armament'],
  },
  {
    id: 'laser_technology',
    name: 'Laser Technology',
    branch: 'military',
    category: 'weapons',
    description: 'Coherent ultraviolet and X-ray laser emitters capable of burning through structural hull plating.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 1000, crystal: 800, deuterium: 200, energy: 40 },
    costMultiplier: 1.6,
    baseTimeSeconds: 40,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 2 }],
    effects: [
      { type: 'weapon_boost', label: 'Laser Cannon Intensity', valuePerLevel: 9, unit: '%' },
    ],
    unlockTargets: ['Light Laser', 'Heavy Laser', 'Cruiser Beam Battery'],
  },
  {
    id: 'plasma_technology',
    name: 'Plasma Technology',
    branch: 'military',
    category: 'weapons',
    description: 'Superheated magnetic fluid accelerated to 0.1c, detonating on contact with vaporizing kinetic power.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 3000, deuterium: 2000, energy: 100 },
    costMultiplier: 1.7,
    baseTimeSeconds: 85,
    prerequisites: [
      { type: 'tech', id: 'laser_technology', name: 'Laser Technology', requiredLevel: 4 },
      { type: 'tech', id: 'fusion_energy', name: 'Fusion Energy', requiredLevel: 3 },
    ],
    effects: [
      { type: 'weapon_boost', label: 'Plasma Cannon Power', valuePerLevel: 12, unit: '%' },
    ],
    unlockTargets: ['Plasma Cannon', 'Heavy Plasma Cannon', 'Battleship Batteries'],
  },

  // --- SHIELDS & DEFENSE BRANCH ---
  {
    id: 'shield_technology',
    name: 'Shield Technology',
    branch: 'military',
    category: 'shields',
    description: 'Localized gravitational deflectors and electromagnetic barrier emitters surrounding hulls.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 200, crystal: 600, deuterium: 300, energy: 50 },
    costMultiplier: 1.55,
    baseTimeSeconds: 30,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 2 }],
    effects: [
      { type: 'shield_boost', label: 'Fleet & Planetary Shield Points', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Small Shield Dome', 'Large Shield Dome', 'Cruiser Shields'],
  },
  {
    id: 'armor_technology',
    name: 'Armor Technology',
    branch: 'military',
    category: 'armor',
    description: 'Multi-layer composite alloys woven with carbon nanotubes to absorb structural kinetic impacts.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 800, crystal: 0, deuterium: 100, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'basic_engineering', name: 'Basic Engineering', requiredLevel: 2 }],
    effects: [
      { type: 'armor_boost', label: 'Ship Hull Structural HP', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Reinforced Hull Plating', 'Heavy Battleship Armor'],
  },
  {
    id: 'phase_shields',
    name: 'Phase Shielding',
    branch: 'advanced_science',
    category: 'shields',
    description: 'Frequency-shifting protective fields that phase enemy beam weapons harmlessly into subspace.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 6000, crystal: 12000, deuterium: 8000, energy: 300 },
    costMultiplier: 1.8,
    baseTimeSeconds: 150,
    prerequisites: [
      { type: 'tech', id: 'shield_technology', name: 'Shield Technology', requiredLevel: 5 },
      { type: 'tech', id: 'quantum_computing', name: 'Quantum Computing', requiredLevel: 3 },
    ],
    effects: [
      { type: 'shield_boost', label: 'Phase Deflection Rating', valuePerLevel: 15, unit: '%' },
    ],
    unlockTargets: ['Planetary Fortress Shield', 'Titan Shield Array'],
  },

  // --- ESPIONAGE & COLONIZATION ---
  {
    id: 'espionage_technology',
    name: 'Espionage Technology',
    branch: 'science',
    category: 'espionage',
    description: 'Sub-ether surveillance antennas, encrypted sensor sweeps, and stealth signal scramblers.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 100, crystal: 500, deuterium: 200, energy: 20 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'computer_technology', name: 'Computer Technology', requiredLevel: 1 }],
    effects: [
      { type: 'expedition_slot', label: 'Intel Depth & Cloak Detection', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Espionage Probe', 'Sensor Phalanx', 'Long Range Recon'],
  },
  {
    id: 'astrophysics',
    name: 'Astrophysics & Expeditions',
    branch: 'science',
    category: 'colonization',
    description: 'Orbital celestial mechanics enabling safe colony expeditions and deep-space anomaly exploration.',
    level: 1,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 8000, deuterium: 4000, energy: 100 },
    costMultiplier: 1.75,
    baseTimeSeconds: 120,
    prerequisites: [
      { type: 'tech', id: 'espionage_technology', name: 'Espionage Technology', requiredLevel: 3 },
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 3 },
    ],
    effects: [
      { type: 'expedition_slot', label: 'Simultaneous Expedition Slots', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Colony Ship', 'Deep Space Expeditions', 'Colony Ark'],
  },

  // --- MEGASTRUCTURES BRANCH ---
  {
    id: 'stellar_engineering',
    name: 'Stellar Engineering',
    branch: 'megastructures',
    category: 'megastructure',
    description: 'Mastery of macro-architectural gravity tethering to construct star-spanning artificial megastructures.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 100000, crystal: 150000, deuterium: 100000, energy: 5000 },
    costMultiplier: 2.2,
    baseTimeSeconds: 600,
    prerequisites: [
      { type: 'tech', id: 'zero_point_energy', name: 'Zero Point Energy', requiredLevel: 2 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Dimensional Propulsion', requiredLevel: 3 },
    ],
    effects: [
      { type: 'production_boost', label: 'Megastructure Construction Rate', valuePerLevel: 20, unit: '%' },
    ],
    unlockTargets: ['Dyson Swarm', 'Orbital Ring', 'Ringworld', 'Stellar Shipyard'],
  },
];

// =========================================================================
// 2. INDUSTRIAL FACILITIES & FACTORIES
// =========================================================================
export const OGAME_FACILITIES: OGameFacility[] = [
  // Resource Facilities
  {
    id: 'metal_mine',
    name: 'Metal Mine',
    category: 'resource',
    description: 'Deep mechanical excavations harvesting high-density iron, titanium, and trinium ore veins.',
    level: 3,
    maxLevel: 50,
    baseCost: { metal: 60, crystal: 15, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 10,
    productionPerLevel: { metal: 120 },
    bonusDescription: '+120 Metal / min per level',
    prerequisites: [],
  },
  {
    id: 'crystal_mine',
    name: 'Crystal Mine',
    category: 'resource',
    description: 'Subterranean laser quarrying of monocrystalline quartz and silicon matrices for electronics.',
    level: 2,
    maxLevel: 50,
    baseCost: { metal: 48, crystal: 24, deuterium: 0 },
    costMultiplier: 1.6,
    energyConsumptionPerLevel: 12,
    productionPerLevel: { crystal: 80 },
    bonusDescription: '+80 Crystal / min per level',
    prerequisites: [],
  },
  {
    id: 'deuterium_synthesizer',
    name: 'Deuterium Synthesizer',
    category: 'resource',
    description: 'Cryogenic centrifugal centrifuges distilling heavy hydrogen from ocean depths and atmospheric gas.',
    level: 1,
    maxLevel: 45,
    baseCost: { metal: 225, crystal: 75, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 20,
    productionPerLevel: { deuterium: 45 },
    bonusDescription: '+45 Deuterium / min per level',
    prerequisites: [],
  },

  // Power Plants
  {
    id: 'solar_plant',
    name: 'Solar Power Plant',
    category: 'resource',
    description: 'Expansive fields of concentrated photovoltaic mirrors delivering clean continuous base energy.',
    level: 4,
    maxLevel: 50,
    baseCost: { metal: 75, crystal: 30, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 0,
    productionPerLevel: { energy: 75 },
    bonusDescription: '+75 Energy generated per level',
    prerequisites: [],
  },
  {
    id: 'fusion_reactor',
    name: 'Fusion Reactor',
    category: 'resource',
    description: 'High-yield Deuterium-consuming magnetic bottle tokamak providing enormous emergency megawattage.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 900, crystal: 360, deuterium: 180 },
    costMultiplier: 1.8,
    energyConsumptionPerLevel: 0,
    productionPerLevel: { energy: 240, deuterium: -15 },
    bonusDescription: '+240 Energy (burns 15 Deuterium/min) per level',
    prerequisites: [
      { type: 'tech', id: 'fusion_energy', name: 'Fusion Energy', requiredLevel: 1 },
    ],
  },

  // Manufacturing & Industrial Complex
  {
    id: 'robotics_factory',
    name: 'Robotics Factory',
    category: 'manufacturing',
    description: 'Automated assembly servomotors and crane lines that speed up all surface facility construction.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 400, crystal: 120, deuterium: 200 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 5,
    bonusDescription: 'Reduces facility build duration by 10% per level',
    prerequisites: [
      { type: 'tech', id: 'basic_engineering', name: 'Basic Engineering', requiredLevel: 1 },
    ],
  },
  {
    id: 'nanite_factory',
    name: 'Nanite Factory',
    category: 'manufacturing',
    description: 'Microscopic molecular assembler swarms that halve the construction times of all ships, buildings, and defenses.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 20000, crystal: 40000, deuterium: 10000 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 50,
    bonusDescription: 'Halves all build times per level (-50% compound)',
    prerequisites: [
      { type: 'facility', id: 'robotics_factory', name: 'Robotics Factory', requiredLevel: 10 },
      { type: 'tech', id: 'computer_technology', name: 'Computer Technology', requiredLevel: 10 },
    ],
  },
  {
    id: 'shipyard_facility',
    name: 'Orbital Shipyard',
    category: 'manufacturing',
    description: 'Low-orbit zero-gravity scaffolding and dry docks capable of forging combat hulls and civilian haulers.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 400, crystal: 200, deuterium: 100 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 15,
    bonusDescription: 'Unlocks advanced ship classes and increases shipyard queue slots',
    prerequisites: [
      { type: 'facility', id: 'robotics_factory', name: 'Robotics Factory', requiredLevel: 2 },
    ],
  },
  {
    id: 'research_lab',
    name: 'Research Laboratory',
    category: 'infrastructure',
    description: 'Planetary science complex equipped with particle accelerators, quantum chambers, and superclusters.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 200, crystal: 400, deuterium: 200 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 20,
    bonusDescription: 'Increases research progression speed and unlocks advanced disciplines',
    prerequisites: [],
  },
];

// =========================================================================
// 3. SHIPYARD FLEET CATALOG (CIVILIAN, COMBAT, CARRIERS, CAPITAL)
// =========================================================================
export const OGAME_SHIPS: OGameShip[] = [
  // --- CIVILIAN SHIPS ---
  {
    id: 'small_cargo',
    name: 'Small Cargo Ship',
    category: 'civilian',
    description: 'Agile light logistics transport outfitted with chemical thrusters for raid resource hauling.',
    structure: 4000,
    shield: 10,
    weaponPower: 5,
    cargoCapacity: 5000,
    speed: 5000,
    fuelConsumption: 10,
    cost: { metal: 2000, crystal: 2000, deuterium: 0 },
    buildTimeSeconds: 15,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 2 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Chemical Propulsion', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 12,
  },
  {
    id: 'large_cargo',
    name: 'Large Cargo Ship',
    category: 'civilian',
    description: 'Massive heavy freighter with pressurized containers capable of moving planetary treasuries.',
    structure: 12000,
    shield: 25,
    weaponPower: 5,
    cargoCapacity: 25000,
    speed: 7500,
    fuelConsumption: 50,
    cost: { metal: 6000, crystal: 6000, deuterium: 0 },
    buildTimeSeconds: 35,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 4 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Chemical Propulsion', requiredLevel: 4 },
    ],
    rapidfireAgainst: {},
    quantity: 4,
  },
  {
    id: 'colony_ship',
    name: 'Colony Ship',
    category: 'civilian',
    description: 'Hermetically sealed biosphere transporter equipped with terraforming beacons and core infrastructure.',
    structure: 30000,
    shield: 100,
    weaponPower: 50,
    cargoCapacity: 7500,
    speed: 2500,
    fuelConsumption: 1000,
    cost: { metal: 10000, crystal: 20000, deuterium: 10000 },
    buildTimeSeconds: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 4 },
      { type: 'tech', id: 'astrophysics', name: 'Astrophysics & Expeditions', requiredLevel: 3 },
    ],
    rapidfireAgainst: {},
    quantity: 1,
  },
  {
    id: 'recycler',
    name: 'Recycler Vessel',
    category: 'civilian',
    description: 'Orbital tractor scrap-harvester capable of processing debris fields from catastrophic naval battles.',
    structure: 16000,
    shield: 10,
    weaponPower: 1,
    cargoCapacity: 20000,
    speed: 4000,
    fuelConsumption: 300,
    cost: { metal: 10000, crystal: 6000, deuterium: 2000 },
    buildTimeSeconds: 45,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 4 },
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 2,
  },
  {
    id: 'espionage_probe',
    name: 'Espionage Probe',
    category: 'civilian',
    description: 'Microminiaturized sensor drone fitted with high-overdrive ion thrusters and cloaked transmission arrays.',
    structure: 1000,
    shield: 0,
    weaponPower: 0,
    cargoCapacity: 5,
    speed: 100000,
    fuelConsumption: 1,
    cost: { metal: 0, crystal: 1000, deuterium: 0 },
    buildTimeSeconds: 5,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 3 },
      { type: 'tech', id: 'espionage_technology', name: 'Espionage Technology', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 15,
  },

  // --- COMBAT SHIPS ---
  {
    id: 'light_fighter',
    name: 'Light Fighter',
    category: 'combat',
    description: 'Inexpensive and nimble strike interceptor armed with dual kinetic cannons for swarm engagements.',
    structure: 4000,
    shield: 10,
    weaponPower: 50,
    cargoCapacity: 50,
    speed: 12500,
    fuelConsumption: 20,
    cost: { metal: 3000, crystal: 1000, deuterium: 0 },
    buildTimeSeconds: 20,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 1 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Chemical Propulsion', requiredLevel: 1 },
    ],
    rapidfireAgainst: { espionage_probe: 5 },
    quantity: 25,
  },
  {
    id: 'heavy_fighter',
    name: 'Heavy Fighter',
    category: 'combat',
    description: 'Armored multi-role superiority fighter sporting pulsed ion thrusters and high-energy laser cannons.',
    structure: 10000,
    shield: 25,
    weaponPower: 150,
    cargoCapacity: 100,
    speed: 10000,
    fuelConsumption: 75,
    cost: { metal: 6000, crystal: 4000, deuterium: 0 },
    buildTimeSeconds: 40,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 3 },
      { type: 'tech', id: 'armor_technology', name: 'Armor Technology', requiredLevel: 2 },
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 2 },
    ],
    rapidfireAgainst: { small_cargo: 3, espionage_probe: 5 },
    quantity: 10,
  },
  {
    id: 'cruiser',
    name: 'Cruiser',
    category: 'combat',
    description: 'Fast strike capital escort equipped with automated fire-control tracking that shreds light fighter wings.',
    structure: 27000,
    shield: 50,
    weaponPower: 400,
    cargoCapacity: 800,
    speed: 15000,
    fuelConsumption: 300,
    cost: { metal: 20000, crystal: 7000, deuterium: 2000 },
    buildTimeSeconds: 75,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 5 },
      { type: 'tech', id: 'ion_propulsion', name: 'Ion Propulsion', requiredLevel: 4 },
      { type: 'tech', id: 'heavy_laser', name: 'Laser Technology', requiredLevel: 3 },
    ],
    rapidfireAgainst: { light_fighter: 6, espionage_probe: 5, rocket_launcher: 10 },
    quantity: 6,
  },
  {
    id: 'battleship',
    name: 'Battleship',
    category: 'combat',
    description: 'Heavily armored core line-of-battle hull armed with broadside plasma batteries and deflector shield domes.',
    structure: 60000,
    shield: 200,
    weaponPower: 1000,
    cargoCapacity: 1500,
    speed: 10000,
    fuelConsumption: 500,
    cost: { metal: 45000, crystal: 15000, deuterium: 0 },
    buildTimeSeconds: 150,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 7 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Hyperspace Drive', requiredLevel: 4 },
    ],
    rapidfireAgainst: { espionage_probe: 5 },
    quantity: 2,
  },
  {
    id: 'battlecruiser',
    name: 'Battlecruiser',
    category: 'combat',
    description: 'High-speed hunter-killer specialized in decimating enemy cruiser lines and capital battleships.',
    structure: 70000,
    shield: 400,
    weaponPower: 700,
    cargoCapacity: 750,
    speed: 10000,
    fuelConsumption: 250,
    cost: { metal: 30000, crystal: 40000, deuterium: 15000 },
    buildTimeSeconds: 180,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 8 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Hyperspace Drive', requiredLevel: 5 },
      { type: 'tech', id: 'laser_technology', name: 'Laser Technology', requiredLevel: 6 },
    ],
    rapidfireAgainst: { espionage_probe: 5, small_cargo: 3, large_cargo: 3, heavy_fighter: 4, cruiser: 4, battleship: 7 },
    quantity: 1,
  },

  // --- CARRIER FLEET ---
  {
    id: 'fleet_carrier',
    name: 'Fleet Carrier',
    category: 'carrier',
    description: 'Sprawling capital hangar vessel supporting multiple fighter wings, repair bays, and drone swarms.',
    structure: 120000,
    shield: 600,
    weaponPower: 350,
    cargoCapacity: 3000,
    speed: 8000,
    fuelConsumption: 600,
    cost: { metal: 80000, crystal: 60000, deuterium: 25000 },
    buildTimeSeconds: 240,
    hangarCapacity: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 9 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Hyperspace Drive', requiredLevel: 6 },
      { type: 'tech', id: 'computer_technology', name: 'Computer Technology', requiredLevel: 8 },
    ],
    rapidfireAgainst: { light_fighter: 8, espionage_probe: 5 },
    quantity: 0,
  },

  // --- CAPITAL & TITANS ---
  {
    id: 'dreadnought',
    name: 'Dreadnought',
    category: 'capital',
    description: 'Monolithic warship armed with spinal relativistic cannons capable of glassing planetary defense sectors.',
    structure: 250000,
    shield: 1500,
    weaponPower: 3200,
    cargoCapacity: 5000,
    speed: 6000,
    fuelConsumption: 1200,
    cost: { metal: 150000, crystal: 100000, deuterium: 50000 },
    buildTimeSeconds: 400,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 10 },
      { type: 'tech', id: 'antimatter_tech', name: 'Antimatter Tech', requiredLevel: 3 },
      { type: 'tech', id: 'plasma_technology', name: 'Plasma Technology', requiredLevel: 5 },
    ],
    rapidfireAgainst: { cruiser: 7, battleship: 5, defense_turret: 15 },
    quantity: 0,
  },
  {
    id: 'titan_flagship',
    name: 'Titan Super-Flagship',
    category: 'capital',
    description: 'Endgame planetary superweapon. A 10-kilometer mobile fortress with planet-breaker tachyon lances.',
    structure: 1000000,
    shield: 8000,
    weaponPower: 15000,
    cargoCapacity: 20000,
    speed: 4000,
    fuelConsumption: 5000,
    cost: { metal: 800000, crystal: 500000, deuterium: 300000 },
    buildTimeSeconds: 900,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 12 },
      { type: 'tech', id: 'zero_point_energy', name: 'Zero Point Energy', requiredLevel: 2 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Dimensional Propulsion', requiredLevel: 2 },
    ],
    rapidfireAgainst: { battleship: 10, dreadnought: 4, light_fighter: 25, heavy_laser: 20 },
    quantity: 0,
  },
];

// =========================================================================
// 4. PLANETARY DEFENSE GRID (OGAME SPEC SECTION 22)
// =========================================================================
export const OGAME_DEFENSES: OGameDefense[] = [
  {
    id: 'rocket_launcher',
    name: 'Rocket Launcher Battery',
    category: 'kinetic',
    description: 'Simple surface silos launching salvos of unguided heat-seeking missiles against low-orbit bombers.',
    structure: 2000,
    shield: 20,
    weaponPower: 80,
    cost: { metal: 2000, crystal: 0, deuterium: 0 },
    buildTimeSeconds: 10,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 1 },
    ],
    quantity: 30,
  },
  {
    id: 'light_laser',
    name: 'Light Laser Emplacement',
    category: 'laser',
    description: 'Rapid-firing ruby-laser turrets that intercept light strike craft with pinpoint computer aim.',
    structure: 2000,
    shield: 25,
    weaponPower: 100,
    cost: { metal: 1500, crystal: 500, deuterium: 0 },
    buildTimeSeconds: 15,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 2 },
      { type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 1 },
      { type: 'tech', id: 'laser_technology', name: 'Laser Technology', requiredLevel: 1 },
    ],
    quantity: 15,
  },
  {
    id: 'heavy_laser',
    name: 'Heavy Laser Battery',
    category: 'laser',
    description: 'Armored subterranean pulsed X-ray lasers delivering devastating thermal puncturing to cruiser hulls.',
    structure: 8000,
    shield: 100,
    weaponPower: 250,
    cost: { metal: 6000, crystal: 2000, deuterium: 0 },
    buildTimeSeconds: 30,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 4 },
      { type: 'tech', id: 'energy_science', name: 'Energy Science', requiredLevel: 3 },
      { type: 'tech', id: 'laser_technology', name: 'Laser Technology', requiredLevel: 3 },
    ],
    quantity: 6,
  },
  {
    id: 'gauss_cannon',
    name: 'Gauss Cannon',
    category: 'kinetic',
    description: 'Massive magnetic accelerator tubes slinging several-ton hypervelocity rounds through dreadnought shields.',
    structure: 35000,
    shield: 200,
    weaponPower: 1100,
    cost: { metal: 20000, crystal: 15000, deuterium: 2000 },
    buildTimeSeconds: 60,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 6 },
      { type: 'tech', id: 'kinetic_weapons', name: 'Kinetic Weapons', requiredLevel: 5 },
      { type: 'tech', id: 'shield_technology', name: 'Shield Technology', requiredLevel: 3 },
    ],
    quantity: 2,
  },
  {
    id: 'plasma_turret',
    name: 'Heavy Plasma Turret',
    category: 'plasma',
    description: 'Apex planetary defense installation shooting superheated stellar plasma that melts entire ship sections.',
    structure: 100000,
    shield: 300,
    weaponPower: 3000,
    cost: { metal: 50000, crystal: 50000, deuterium: 30000 },
    buildTimeSeconds: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 8 },
      { type: 'tech', id: 'plasma_technology', name: 'Plasma Technology', requiredLevel: 5 },
    ],
    quantity: 1,
  },
  {
    id: 'small_shield_dome',
    name: 'Small Shield Dome',
    category: 'shield',
    description: 'Planetary energy hemisphere shielding the colony from orbital bombardment and incoming munitions.',
    structure: 20000,
    shield: 2000,
    weaponPower: 0,
    cost: { metal: 10000, crystal: 10000, deuterium: 0 },
    buildTimeSeconds: 60,
    maxBuildable: 1,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 1 },
      { type: 'tech', id: 'shield_technology', name: 'Shield Technology', requiredLevel: 2 },
    ],
    quantity: 1,
  },
  {
    id: 'large_shield_dome',
    name: 'Large Planetary Shield Dome',
    category: 'shield',
    description: 'High-density multi-phase planetary deflector grid that can absorb direct bombardment from capital fleets.',
    structure: 100000,
    shield: 10000,
    weaponPower: 0,
    cost: { metal: 50000, crystal: 50000, deuterium: 0 },
    buildTimeSeconds: 150,
    maxBuildable: 1,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Orbital Shipyard', requiredLevel: 6 },
      { type: 'tech', id: 'shield_technology', name: 'Shield Technology', requiredLevel: 6 },
    ],
    quantity: 0,
  },
];

// =========================================================================
// 5. FLEET FORMATIONS (SPEC SECTION 25)
// =========================================================================
export const FLEET_FORMATIONS: FleetFormation[] = [
  {
    id: 'standard',
    name: 'Standard Cruising Formation',
    description: 'Balanced fleet spacing with equal distribution of escorts and screen pickets.',
    attackModifier: 1.0,
    defenseModifier: 1.0,
    speedModifier: 1.0,
    flagshipProtection: 1.0,
  },
  {
    id: 'line',
    name: 'Line of Battle',
    description: 'Broadside alignment maximizing collective alpha-strike artillery on enemy center.',
    attackModifier: 1.25,
    defenseModifier: 0.9,
    speedModifier: 0.85,
    flagshipProtection: 1.1,
  },
  {
    id: 'wedge',
    name: 'Penetration Wedge',
    description: 'Spearhead configuration designed to pierce defensive screens and isolate hostiles.',
    attackModifier: 1.35,
    defenseModifier: 0.8,
    speedModifier: 1.15,
    flagshipProtection: 0.85,
  },
  {
    id: 'defensive',
    name: 'Defensive Perimeter Sphere',
    description: 'Interlocking deflector bubbles and overlapping anti-missile picket fire.',
    attackModifier: 0.85,
    defenseModifier: 1.35,
    speedModifier: 0.9,
    flagshipProtection: 1.5,
  },
  {
    id: 'assault',
    name: 'Swarm Assault',
    description: 'Dispersed multi-vector attacks by light combat craft to overwhelm target tracking.',
    attackModifier: 1.15,
    defenseModifier: 1.1,
    speedModifier: 1.2,
    flagshipProtection: 0.95,
  },
  {
    id: 'carrier',
    name: 'Carrier Task Force',
    description: 'Carriers secured at core while long-range bomber wings conduct standoff bombardment.',
    attackModifier: 1.2,
    defenseModifier: 1.2,
    speedModifier: 0.95,
    flagshipProtection: 1.6,
  },
];

// =========================================================================
// 6. MEGASTRUCTURE PROJECTS (SPEC SECTION 30)
// =========================================================================
export const MEGASTRUCTURE_PROJECTS: MegastructureProject[] = [
  {
    id: 'dyson_swarm',
    name: 'Dyson Swarm',
    subtitle: 'Stellar Energy Harvester',
    description: 'A dense cloud of millions of orbital mirrors orbiting the primary star, beaming gigawatts of pure solar flux.',
    icon: '☀️',
    currentStage: 0,
    totalStages: 3,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: '+50,000 Energy and +30% empire-wide resource production',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Stellar Engineering', requiredLevel: 1 },
      { type: 'tech', id: 'solar_energy', name: 'Solar Energy Tech', requiredLevel: 5 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Primary Mirror Ring',
        cost: { metal: 250000, crystal: 150000, deuterium: 50000 },
        durationSeconds: 180,
        completed: false,
        effectDescription: '+10,000 Energy',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Polar Orbital Collectors',
        cost: { metal: 500000, crystal: 300000, deuterium: 100000 },
        durationSeconds: 240,
        completed: false,
        effectDescription: '+25,000 Energy',
      },
      {
        stageNumber: 3,
        name: 'Stage III: Complete Stellar Swarm Grid',
        cost: { metal: 1000000, crystal: 600000, deuterium: 200000 },
        durationSeconds: 360,
        completed: false,
        effectDescription: '+50,000 Energy & +30% Mine Output',
      },
    ],
  },
  {
    id: 'orbital_ring',
    name: 'Colonial Orbital Ring',
    subtitle: 'Planetary Girdle Infrastructure',
    description: 'A solid circum-planetary megastructure encircling the planet, housing massive shipyards and defense platforms.',
    icon: '🪐',
    currentStage: 0,
    totalStages: 3,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: '+50% Planet Defense, +4 Shipyard Queue Slots, +25% Population Growth',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Stellar Engineering', requiredLevel: 2 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Space Elevator Anchors',
        cost: { metal: 300000, crystal: 200000, deuterium: 80000 },
        durationSeconds: 200,
        completed: false,
        effectDescription: '+15% Planet Defense & Logistics',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Orbital Girdle Spans',
        cost: { metal: 600000, crystal: 400000, deuterium: 150000 },
        durationSeconds: 300,
        completed: false,
        effectDescription: '+2 Shipyard Slots & +20% Population',
      },
      {
        stageNumber: 3,
        name: 'Stage III: Fortress Weapon Bastions',
        cost: { metal: 1200000, crystal: 800000, deuterium: 300000 },
        durationSeconds: 420,
        completed: false,
        effectDescription: 'Complete Orbital Ring Fortress Activation',
      },
    ],
  },
  {
    id: 'galactic_gateway',
    name: 'Galactic Jump Gateway',
    subtitle: 'Hyperspace Conduit Node',
    description: 'Artificial Einstein-Rosen wormhole bridge enabling zero-delay fleet relocation anywhere across the cosmos.',
    icon: '🌀',
    currentStage: 0,
    totalStages: 2,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: 'Instant fleet transit without fuel costs across all sectors',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Stellar Engineering', requiredLevel: 3 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Dimensional Propulsion', requiredLevel: 2 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Singularity Containment Ring',
        cost: { metal: 500000, crystal: 400000, deuterium: 250000 },
        durationSeconds: 240,
        completed: false,
        effectDescription: 'Initial Wormhole Resonance Calibrated',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Gateway Event Horizon Ignition',
        cost: { metal: 1000000, crystal: 800000, deuterium: 500000 },
        durationSeconds: 380,
        completed: false,
        effectDescription: 'Full Interstellar Fleet Relocation Operational',
      },
    ],
  },
];

// =========================================================================
// 7. EXPEDITION ENCOUNTER OUTCOMES & INITIAL LOGS
// =========================================================================
export const INITIAL_EXPEDITION_LOGS: ExpeditionLog[] = [
  {
    id: 'exp-1',
    timestamp: '11:15:02',
    sector: 'Sector 4:182:9',
    missionType: 'anomaly',
    status: 'triumph',
    narrative: 'Expedition fleet discovered a derelict Ancient automated cargo vessel drifting in stellar radiation. Salvaged intact ore stores.',
    loot: {
      metal: 35000,
      crystal: 22000,
      deuterium: 8000,
      naquadah: 15000,
    },
  },
  {
    id: 'exp-2',
    timestamp: '10:42:19',
    sector: 'Sector 8:091:4',
    missionType: 'relic_discovery',
    status: 'discovery',
    narrative: 'Sensors detected anomalous sub-space beacon on asteroid cluster. Excavated an intact Crystal Matrix Core relic.',
    loot: {
      crystal: 40000,
      relicName: 'Zero-Point Precursor Core',
    },
  },
  {
    id: 'exp-3',
    timestamp: '09:20:55',
    sector: 'Sector 2:310:1',
    missionType: 'exploration',
    status: 'triumph',
    narrative: 'Prospecting scan of untouched volcanic moon located rich surface veins of Deuterium ice and heavy metals.',
    loot: {
      metal: 18000,
      deuterium: 14000,
    },
  },
];

export const INITIAL_FLEET_PRESETS: FleetFormationPreset[] = [
  {
    id: 'preset_rapid_scout',
    name: 'Rapid Scout Escort',
    description: 'Light survey vanguard with balanced escort protection for deep-space recon & anomaly scanning.',
    formation: 'standard',
    composition: {
      espionage_probe: 5,
      small_cargo: 2,
      light_fighter: 5,
    },
    createdAt: 1700000000000,
    tags: ['expedition', 'custom'],
  },
  {
    id: 'preset_heavy_assault',
    name: 'Heavy Assault Armada',
    description: 'Line-of-battle fleet focused on overwhelming alpha-strike bombardment on planetary targets.',
    formation: 'line',
    composition: {
      battleship: 10,
      battlecruiser: 5,
      cruiser: 15,
      heavy_fighter: 25,
      light_fighter: 40,
    },
    createdAt: 1700000001000,
    tags: ['attack', 'custom'],
  },
  {
    id: 'preset_deep_salvage',
    name: 'Deep Space Mining Convoy',
    description: 'High-capacity cargo and recycler fleet protected by defensive sphere deflectors for derelict recovery.',
    formation: 'defensive',
    composition: {
      large_cargo: 10,
      small_cargo: 15,
      recycler: 5,
      espionage_probe: 3,
      cruiser: 4,
    },
    createdAt: 1700000002000,
    tags: ['expedition', 'custom'],
  },
  {
    id: 'preset_penetration_wedge',
    name: 'Orbital Penetration Spearhead',
    description: 'Wedge-formation heavy bombers and destroyers configured to smash through planetary shield grids.',
    formation: 'wedge',
    composition: {
      bomber: 8,
      destroyer: 6,
      cruiser: 12,
      heavy_fighter: 20,
    },
    createdAt: 1700000003000,
    tags: ['attack', 'custom'],
  },
  {
    id: 'preset_titan_armada',
    name: 'Titan Dreadnought Task Force',
    description: 'Capital-class strike group anchored by Titan flagships and dreadnoughts with carrier wing screens.',
    formation: 'carrier',
    composition: {
      titan_flagship: 1,
      dreadnought: 2,
      battleship: 6,
      carrier: 3,
      cruiser: 10,
      heavy_fighter: 30,
    },
    createdAt: 1700000004000,
    tags: ['attack', 'custom'],
  },
];

export const INITIAL_OGAME_TECHNOLOGIES: OGameTechnology[] = OGAME_TECHNOLOGIES;
export const INITIAL_OGAME_FACILITIES: OGameFacility[] = OGAME_FACILITIES;
export const INITIAL_OGAME_SHIPS: OGameShip[] = OGAME_SHIPS;
export const INITIAL_OGAME_DEFENSES: OGameDefense[] = OGAME_DEFENSES;
export const INITIAL_MEGASTRUCTURES: MegastructureProject[] = MEGASTRUCTURE_PROJECTS;
export const INITIAL_EXPEDITIONS: ExpeditionMission[] = [];
export const INITIAL_FLEET_FORMATION_PRESETS: FleetFormationPreset[] = INITIAL_FLEET_PRESETS;
