import {
  PlanetaryClassAZ,
  MoonClassAZ,
  PlanetarySizeScale,
  InterstellarCelestialObject,
  PlanetaryClassLetter,
} from './types';

// ==========================================
// COMPLETE PLANETARY CLASSIFICATION A TO Z
// ==========================================

export const PLANETARY_CLASSES_A_TO_Z: PlanetaryClassAZ[] = [
  {
    letter: 'A',
    className: 'Class A: Geothermal Primordial',
    typeCategory: 'Primordial Tectonic',
    scientificDesignation: 'GEO-PRIM-01',
    atmosphereComposition: 'Methane, Carbon Monoxide, Hydrogen Sulfide',
    surfaceComposition: 'Cooling Basalt, Silicate Slag, Thermal Fissures',
    temperatureRange: '150°C to 450°C',
    averageDiameterKm: 9800,
    sizeRating: 3,
    habitabilityScore: 8,
    metalMultiplier: 1.45,
    crystalMultiplier: 1.2,
    deuteriumMultiplier: 1.1,
    energyMultiplier: 1.8,
    description: 'Young proto-planetary bodies with continuous tectonic crust formation, radioactive isotope outgassing, and hydrothermal energy vents.',
    subClasses: ['Proto-Basaltic', 'Hydrothermal Rift', 'Mantle-Exposed Caldera'],
    subTypes: ['Early Archean Equivalent', 'Sub-Crustal Convection Cell'],
    colorHex: '#d97706',
  },
  {
    letter: 'B',
    className: 'Class B: Geomorteus Molten',
    typeCategory: 'Thermal Magmatic',
    scientificDesignation: 'PYRO-MORT-02',
    atmosphereComposition: 'Vaporized Silicates, Sodium Vapor, Carbon Dioxide',
    surfaceComposition: 'Liquid Silicate Magma Lakes, Pyroxene Lava Oceans',
    temperatureRange: '400°C to 1200°C',
    averageDiameterKm: 11200,
    sizeRating: 4,
    habitabilityScore: 0,
    metalMultiplier: 1.85,
    crystalMultiplier: 1.6,
    deuteriumMultiplier: 0.8,
    energyMultiplier: 2.2,
    description: 'Inhospitable worlds orbiting close to primary stars or experiencing extreme tidal kneading. Surface consists of glowing magma seas and iron rain.',
    subClasses: ['Lava Oceanic', 'Tidally Cooked Chthonian', 'Silicate Vapor Giant'],
    subTypes: ['Ultra-Short Period Super-Mercury', 'Sub-Coronal Magma Basin'],
    colorHex: '#dc2626',
  },
  {
    letter: 'C',
    className: 'Class C: Geoinactive Crystalline',
    typeCategory: 'Barren Silicate',
    scientificDesignation: 'LITH-CRYS-03',
    atmosphereComposition: 'Trace Argon, Helium, Solar Wind Exosphere',
    surfaceComposition: 'Quartz Sand Plains, Monocrystalline Crags, Silica Regolith',
    temperatureRange: '-80°C to 70°C',
    averageDiameterKm: 10400,
    sizeRating: 3,
    habitabilityScore: 22,
    metalMultiplier: 1.1,
    crystalMultiplier: 2.1,
    deuteriumMultiplier: 0.9,
    energyMultiplier: 1.15,
    description: 'Geologically dead silicate worlds covered in natural quartz lattice spires and crystalline dunes that reflect radar and solar radiation.',
    subClasses: ['Silica Monolith', 'Quartz Karst Plateaus', 'Piezoelectric Desert'],
    subTypes: ['High-Albedo Silicate', 'Impact-Fractured Crystalline'],
    colorHex: '#0ea5e9',
  },
  {
    letter: 'D',
    className: 'Class D: Asteroidal Regolith Dwarf',
    typeCategory: 'Airless Dwarf',
    scientificDesignation: 'ASTR-REG-04',
    atmosphereComposition: 'None (Vacuum)',
    surfaceComposition: 'Impact Regolith, Nickel-Iron Boulders, Carbonaceous Dust',
    temperatureRange: '-180°C to 120°C',
    averageDiameterKm: 4200,
    sizeRating: 1,
    habitabilityScore: 12,
    metalMultiplier: 1.6,
    crystalMultiplier: 1.3,
    deuteriumMultiplier: 0.5,
    energyMultiplier: 1.0,
    description: 'Low-mass dwarf planetoids with negligible gravity, heavy cratering, and pure exposed veins of strategic ores and heavy metals.',
    subClasses: ['Nickel-Iron Core Remnant', 'Chondritic Asteroid Basin', 'Carbonaceous Dwarf'],
    subTypes: ['Ceres-Class Planetesimal', 'Kirkwood Resonant Body'],
    colorHex: '#78716c',
  },
  {
    letter: 'E',
    className: 'Class E: Geoplastic Magma Oceanic',
    typeCategory: 'Viscous Mantle',
    scientificDesignation: 'PLAST-MAG-05',
    atmosphereComposition: 'Dense Nitrogen Dioxide, Carbon Dioxide, Sulfur Trioxide',
    surfaceComposition: 'Viscous Magmatic Sludge, Semi-Solid Crustal Rafts',
    temperatureRange: '280°C to 750°C',
    averageDiameterKm: 12400,
    sizeRating: 4,
    habitabilityScore: 5,
    metalMultiplier: 1.7,
    crystalMultiplier: 1.5,
    deuteriumMultiplier: 1.0,
    energyMultiplier: 1.95,
    description: 'Worlds where the crust never solidified into plates, drifting instead as shifting tectonic continents over a fluid viscous mantle.',
    subClasses: ['Semi-Solid Slag World', 'Viscous Basaltic Gyre', 'Pyroclastic Silt Plain'],
    subTypes: ['High-Viscosity Mantle Diapir', 'Continuous Thermal Inversion'],
    colorHex: '#ea580c',
  },
  {
    letter: 'F',
    className: 'Class F: Geometallic Iron World',
    typeCategory: 'Ferrous Metallic',
    scientificDesignation: 'MET-FERR-06',
    atmosphereComposition: 'Trace Oxygen, Carbon Dioxide, Metal Dust',
    surfaceComposition: 'Hematite, Magnetite, Metallic Iron Sand, Titanium Alloys',
    temperatureRange: '-20°C to 110°C',
    averageDiameterKm: 13800,
    sizeRating: 5,
    habitabilityScore: 35,
    metalMultiplier: 2.5,
    crystalMultiplier: 0.9,
    deuteriumMultiplier: 0.85,
    energyMultiplier: 1.3,
    description: 'High-density worlds with immense iron cores generating titanic magnetic shields. The primary planetary source of structural alloys across galaxies.',
    subClasses: ['Pure Magnetite Crust', 'Titanium Basin World', 'Heavy Siderite Core'],
    subTypes: ['Super-Mercury Ferrous Body', 'Stripped Silicate Mantle'],
    colorHex: '#64748b',
  },
  {
    letter: 'G',
    className: 'Class G: Geocrystalline Silicate Prism',
    typeCategory: 'Optic Crystalline',
    scientificDesignation: 'PRISM-CRYS-07',
    atmosphereComposition: 'Trace Neon, Xenon, Krypton, Argon',
    surfaceComposition: 'Corundum, Beryl, Topaz Shards, Optic Glass Valleys',
    temperatureRange: '-40°C to 85°C',
    averageDiameterKm: 11800,
    sizeRating: 4,
    habitabilityScore: 28,
    metalMultiplier: 1.0,
    crystalMultiplier: 2.6,
    deuteriumMultiplier: 1.0,
    energyMultiplier: 1.6,
    description: 'Rare worlds where tectonic crystallization resulted in surface jewel formations that channel and focus stellar light like colossal optical lasers.',
    subClasses: ['Corundum Ridge', 'Emerald Canyon', 'Piezo-Optical Salt Flat'],
    subTypes: ['Natural Laser Cavity Crust', 'Subsurface Diamond Mantle'],
    colorHex: '#06b6d4',
  },
  {
    letter: 'H',
    className: 'Class H: Desert Arid Hyper-Saline',
    typeCategory: 'Arid Dune',
    scientificDesignation: 'DES-SAL-08',
    atmosphereComposition: 'Nitrogen, Carbon Dioxide, Fine Silica Dust',
    surfaceComposition: 'Eolian Quartz Dunes, Evaporite Salt Flats, Iron Dust Reg',
    temperatureRange: '15°C to 95°C',
    averageDiameterKm: 12100,
    sizeRating: 4,
    habitabilityScore: 52,
    metalMultiplier: 1.25,
    crystalMultiplier: 1.4,
    deuteriumMultiplier: 0.6,
    energyMultiplier: 1.5,
    description: 'Sun-drenched desert worlds with dry atmospheric cycles, massive lithium and halite salt pans, and subterranean moisture basins.',
    subClasses: ['Great Dune Erg', 'Lithium Salt Sink', 'Badlands Canyons'],
    subTypes: ['Pre-Desertification Garden World', 'Tidally Heated Arid Zone'],
    colorHex: '#b45309',
  },
  {
    letter: 'I',
    className: 'Class I: Gas Supergiant Jovian Megaglobe',
    typeCategory: 'Gas Giant',
    scientificDesignation: 'JOV-MEGA-09',
    atmosphereComposition: 'Hydrogen (84%), Helium (14%), Trace Methane, Ammonia',
    surfaceComposition: 'None (Liquid Metallic Hydrogen Mantle, Dense Core)',
    temperatureRange: '-150°C to -30°C (Upper atmosphere)',
    averageDiameterKm: 142000,
    sizeRating: 9,
    habitabilityScore: 10,
    metalMultiplier: 0.4,
    crystalMultiplier: 0.5,
    deuteriumMultiplier: 3.2,
    energyMultiplier: 1.8,
    description: 'Enormous hydrogen-helium gas globes capable of sustaining dozens of moons and floating orbital skimmers harvesting billions of liters of Deuterium.',
    subClasses: ['Standard Jovian', 'Great Red Storm Supergiant', 'Banded Ammonia Giant'],
    subTypes: ['Sudarsky Class I Tropospheric Cloud', 'Fast-Rotator Flattened Pole'],
    colorHex: '#ca8a04',
  },
  {
    letter: 'J',
    className: 'Class J: Gas Jovian Helium-Rich Warm Giant',
    typeCategory: 'Warm Gas Giant',
    scientificDesignation: 'HELI-WARM-10',
    atmosphereComposition: 'Helium (35%), Hydrogen (60%), Sodium Vapor, Potassium',
    surfaceComposition: 'None (Supercritical Fluid Atmosphere)',
    temperatureRange: '120°C to 650°C',
    averageDiameterKm: 118000,
    sizeRating: 8,
    habitabilityScore: 15,
    metalMultiplier: 0.5,
    crystalMultiplier: 0.6,
    deuteriumMultiplier: 2.8,
    energyMultiplier: 2.4,
    description: 'Warm gas giants with glowing auroral arcs and deep atmospheric convection loops, providing pure fusion isotopes for hyperdrives.',
    subClasses: ['Cloudless Warm Jovian', 'Alkali-Rich Subgiant', 'Auroral Flare Giant'],
    subTypes: ['Sudarsky Class III Clear Troposphere', 'Helium-Enriched Fusion Reservoir'],
    colorHex: '#eab308',
  },
  {
    letter: 'K',
    className: 'Class K: Adaptable Arid Mars-Type World',
    typeCategory: 'Terraformable Arid',
    scientificDesignation: 'MARS-ADAP-11',
    atmosphereComposition: 'Carbon Dioxide (95%), Nitrogen (3%), Argon (1.6%)',
    surfaceComposition: 'Iron-Oxide Dust, Dry Ice Polar Caps, Ancient River Valleys',
    temperatureRange: '-85°C to 20°C',
    averageDiameterKm: 6800,
    sizeRating: 2,
    habitabilityScore: 68,
    metalMultiplier: 1.35,
    crystalMultiplier: 1.15,
    deuteriumMultiplier: 1.2,
    energyMultiplier: 1.1,
    description: 'Ancient, dormant terrestrial worlds primed for terraforming. Frozen subsurface water reservoirs and rich crustal minerals make colonization effortless.',
    subClasses: ['Rusty Oxide Plateau', 'Polar Cryo-Cap Basin', 'Fossil Delta World'],
    subTypes: ['Post-Hydrological Dead World', 'Low-Gravity Terraform Candidate'],
    colorHex: '#ef4444',
  },
  {
    letter: 'L',
    className: 'Class L: Marginal Habitable Pre-Vegetative',
    typeCategory: 'Pre-Biotic Continental',
    scientificDesignation: 'PRE-VEG-12',
    atmosphereComposition: 'Nitrogen (78%), Carbon Dioxide (15%), Oxygen (6%), Argon',
    surfaceComposition: 'Silicate Continents, Liquid Water Basins, Lichen Mats',
    temperatureRange: '-10°C to 45°C',
    averageDiameterKm: 12200,
    sizeRating: 4,
    habitabilityScore: 82,
    metalMultiplier: 1.05,
    crystalMultiplier: 1.05,
    deuteriumMultiplier: 1.15,
    energyMultiplier: 1.0,
    description: 'Worlds with primitive single-celled oceanic biospheres and rudimentary lichen mats on land. Humanoid breatheable with minimal filtration.',
    subClasses: ['Lichen Marsh Continental', 'Iron Bog Wetland', 'Algal Ocean Shallows'],
    subTypes: ['Proterozoic Atmosphere Model', 'Early Photosynthetic Bloom'],
    colorHex: '#84cc16',
  },
  {
    letter: 'M',
    className: 'Class M: Terrestrial Earth-Like Paradise',
    typeCategory: 'Garden Biosphere',
    scientificDesignation: 'TERR-GARD-13',
    atmosphereComposition: 'Nitrogen (77%), Oxygen (21%), Argon (1%), Carbon Dioxide (0.04%)',
    surfaceComposition: 'Liquid Oceans (71%), Continental Soil, Verdant Flora, Mountain Chains',
    temperatureRange: '-25°C to 40°C',
    averageDiameterKm: 12742,
    sizeRating: 4,
    habitabilityScore: 100,
    metalMultiplier: 1.0,
    crystalMultiplier: 1.0,
    deuteriumMultiplier: 1.0,
    energyMultiplier: 1.0,
    description: 'The golden standard of habitable celestial bodies. Rich ecosystems, balanced seasonal cycles, ideal gravity, and rapid population growth rates.',
    subClasses: ['Continental Archipelago', 'Temperate Forest Heartland', 'Tropical Pangaea'],
    subTypes: ['Prime Humanoid Garden', 'Geomagnetic Protected Biosphere'],
    colorHex: '#10b981',
  },
  {
    letter: 'N',
    className: 'Class N: Reducing Atmosphere Venusian Greenhouse',
    typeCategory: 'Super-Greenhouse',
    scientificDesignation: 'VEN-HYPER-14',
    atmosphereComposition: 'Carbon Dioxide (96.5%), Nitrogen (3.5%), Sulfuric Acid Clouds',
    surfaceComposition: 'Dense Basaltic Lava Plains, Crushed Pancake Domes',
    temperatureRange: '420°C to 480°C',
    averageDiameterKm: 12104,
    sizeRating: 4,
    habitabilityScore: 6,
    metalMultiplier: 1.4,
    crystalMultiplier: 1.3,
    deuteriumMultiplier: 0.7,
    energyMultiplier: 1.85,
    description: 'Runaway greenhouse planets with 90+ atmospheres of surface pressure. Acid cloud decks require floating aerostat cities and automated mining drills.',
    subClasses: ['Supercritical Caldera', 'Sulfuric Cloud Deck', 'Basalt Slag Plain'],
    subTypes: ['Runaway Vapor Trap', 'Crushing Surface Barosphere'],
    colorHex: '#f59e0b',
  },
  {
    letter: 'O',
    className: 'Class O: Pelagic Hyper-Oceanic World',
    typeCategory: 'Liquid Water World',
    scientificDesignation: 'AQUA-PELA-15',
    atmosphereComposition: 'Nitrogen (79%), Oxygen (20%), Water Vapor (1%)',
    surfaceComposition: 'Global Liquid Hydrosphere (100km depth), High-Pressure Ice VII Core',
    temperatureRange: '5°C to 38°C',
    averageDiameterKm: 14800,
    sizeRating: 5,
    habitabilityScore: 89,
    metalMultiplier: 0.7,
    crystalMultiplier: 1.35,
    deuteriumMultiplier: 2.1,
    energyMultiplier: 1.1,
    description: 'Global ocean planets without a single square kilometer of dry land. Vast floating arcologies harvest deuterium and abyssal thermal energy.',
    subClasses: ['Warm Pelagic Deep', 'Coral Atoll Shallows', 'Abyssal Trench Hydrosphere'],
    subTypes: ['Mantle-Separated Ice VII Hydrosphere', 'Floating Megacity Node'],
    colorHex: '#0284c7',
  },
  {
    letter: 'P',
    className: 'Class P: Glaciated Cryo World',
    typeCategory: 'Glacial Ice',
    scientificDesignation: 'CRYO-GLAC-16',
    atmosphereComposition: 'Nitrogen (85%), Carbon Dioxide, Methane',
    surfaceComposition: 'Kilometer-Thick Water & Nitrogen Glaciers, Tectonic Seracs',
    temperatureRange: '-160°C to -40°C',
    averageDiameterKm: 11400,
    sizeRating: 4,
    habitabilityScore: 48,
    metalMultiplier: 0.9,
    crystalMultiplier: 1.4,
    deuteriumMultiplier: 2.4,
    energyMultiplier: 0.75,
    description: 'Perpetually frozen ice globes locked in global snowball states. Vast subglacial freshwater oceans are heated by radioactive tectonic friction.',
    subClasses: ['Nitrogen Slush Glacier', 'Subglacial Ocean World', 'Ice Shield Tundra'],
    subTypes: ['Cryo-Volcanic Basin', 'Snowball Silicate Equilibrium'],
    colorHex: '#38bdf8',
  },
  {
    letter: 'Q',
    className: 'Class Q: Variable Chaotic Elliptical',
    typeCategory: 'Eccentric Climatic',
    scientificDesignation: 'ECC-CLIM-17',
    atmosphereComposition: 'Fluctuating Nitrogen, Carbon Monoxide, Seasonal Oxygen',
    surfaceComposition: 'Cyclic Thermal Fractures, Flash-Flooded Regolith, Flash-Frozen Basalt',
    temperatureRange: '-120°C to 180°C (Seasonal extremes)',
    averageDiameterKm: 10800,
    sizeRating: 3,
    habitabilityScore: 32,
    metalMultiplier: 1.3,
    crystalMultiplier: 1.45,
    deuteriumMultiplier: 1.3,
    energyMultiplier: 1.4,
    description: 'Worlds traversing high-eccentricity orbits around multi-star systems, plunging from freezing interstellar aphelion into blistering perihelion fire.',
    subClasses: ['Dual-Sun Elliptical', 'Flash-Season Basin', 'Thermal Fracture Globe'],
    subTypes: ['Chaotic Orbital Resonance', 'Phase-Changing Hydrosphere'],
    colorHex: '#a855f7',
  },
  {
    letter: 'R',
    className: 'Class R: Rogue Nomadic Void World',
    typeCategory: 'Steppenwolf Orphan',
    scientificDesignation: 'VOID-ROGU-18',
    atmosphereComposition: 'Frozen Dense Atmosphere Layer (Liquid Nitrogen Oceans)',
    surfaceComposition: 'Amorphous Ice Crust, Radioactive Basalt Core',
    temperatureRange: '-260°C to -210°C',
    averageDiameterKm: 13200,
    sizeRating: 5,
    habitabilityScore: 25,
    metalMultiplier: 1.2,
    crystalMultiplier: 1.5,
    deuteriumMultiplier: 2.6,
    energyMultiplier: 0.5,
    description: 'Orphaned planets ejected from their birth star systems, drifting through the dark void between galaxies. Heated solely by geothermal radioactive decay.',
    subClasses: ['Interstellar Drifter', 'Geothermal Pocket Haven', 'Frozen Air Void World'],
    subTypes: ['Galactic Halo Nomad', 'Zero-Insolation Silicate Core'],
    colorHex: '#475569',
  },
  {
    letter: 'S',
    className: 'Class S: Gas Ultragiant Sub-Brown Dwarf',
    typeCategory: 'Sub-Stellar Giant',
    scientificDesignation: 'SUB-STAR-19',
    atmosphereComposition: 'Hydrogen (75%), Helium (23%), Water Vapor Clouds, Iron Vapor',
    surfaceComposition: 'None (Liquid Metallic Core at 15 Million Atmospheres)',
    temperatureRange: '800°C to 1900°C',
    averageDiameterKm: 185000,
    sizeRating: 9,
    habitabilityScore: 12,
    metalMultiplier: 0.6,
    crystalMultiplier: 0.7,
    deuteriumMultiplier: 3.8,
    energyMultiplier: 2.8,
    description: 'Massive borderline planets at the threshold of nuclear ignition. Emits intense infrared heat and houses massive rings of diamond and platinum asteroid dust.',
    subClasses: ['Infrared Radiant Giant', 'Iron Rain Ultragiant', 'Deuterium Trap Supermassive'],
    subTypes: ['Sub-13 Jupiter Mass Limit', 'M-Type Spectral Borderline'],
    colorHex: '#f97316',
  },
  {
    letter: 'T',
    className: 'Class T: Brown Dwarf Thermonuclear Sub-Star',
    typeCategory: 'Lithium Burning',
    scientificDesignation: 'LITH-STAR-20',
    atmosphereComposition: 'Molecular Hydrogen, Helium, Methane, Water Vapor, Silicate Clouds',
    surfaceComposition: 'None (Degenerate Convective Plasma Mantle)',
    temperatureRange: '700°C to 2200°C',
    averageDiameterKm: 120000,
    sizeRating: 9,
    habitabilityScore: 15,
    metalMultiplier: 0.8,
    crystalMultiplier: 0.8,
    deuteriumMultiplier: 4.5,
    energyMultiplier: 3.5,
    description: 'Failed stars capable of sustaining deuterium fusion in their cores. Shines with dull magenta-crimson glow, radiating enormous energy to orbital station grids.',
    subClasses: ['Late T-Dwarf', 'Methane-Absorption Star-Planet', 'Plasma-Convective Anchor'],
    subTypes: ['T-Class Spectral Object', 'Deuterium Fusion Core'],
    colorHex: '#c026d3',
  },
  {
    letter: 'U',
    className: 'Class U: Fractured Shattered Planetary Remnant',
    typeCategory: 'Tidally Disrupted',
    scientificDesignation: 'FRAC-REMN-21',
    atmosphereComposition: 'Escaping Vapor Trail, Exposed Magma Gas',
    surfaceComposition: 'Floating Continental Chunks, Exposed Mantle Chasm, Asteroid Swarms',
    temperatureRange: '-100°C to 550°C',
    averageDiameterKm: 8200,
    sizeRating: 2,
    habitabilityScore: 18,
    metalMultiplier: 2.2,
    crystalMultiplier: 1.9,
    deuteriumMultiplier: 0.7,
    energyMultiplier: 1.6,
    description: 'Worlds caught inside Roche limits or struck by relativistic orbital strikes. Ripped into floating continental fragments with exposed zero-gravity mantle ore.',
    subClasses: ['Roche-Limit Shrapnel', 'Split-Hemisphere World', 'Orbital Debris Cluster'],
    subTypes: ['Gravitational Disruption Remnant', 'Exposed Core Fragment'],
    colorHex: '#9333ea',
  },
  {
    letter: 'V',
    className: 'Class V: Volcanic Sulfur Hyper-Active',
    typeCategory: 'Tidal Super-Io',
    scientificDesignation: 'IO-PYRO-22',
    atmosphereComposition: 'Sulfur Dioxide (90%), Hydrogen Sulfide, Sulfur Monoxide',
    surfaceComposition: 'Yellow Sulfur Calderas, Liquid Basalt Vents, Pyroclastic Ash Shields',
    temperatureRange: '180°C to 580°C',
    averageDiameterKm: 9900,
    sizeRating: 3,
    habitabilityScore: 14,
    metalMultiplier: 1.9,
    crystalMultiplier: 1.7,
    deuteriumMultiplier: 0.9,
    energyMultiplier: 2.3,
    description: 'Worlds experiencing continuous super-volcanic eruptions powered by tidal strain. 400km-high sulfur plumes coat the surface in heavy reactive compounds.',
    subClasses: ['Sulfur Plume Caldera', 'Basaltic Super-Io', 'Pele-Type Lava Fountain'],
    subTypes: ['Tidal Dissipation Crucible', 'Super-Hot Mineral Fumarole'],
    colorHex: '#e11d48',
  },
  {
    letter: 'W',
    className: 'Class W: Water-Ice Giant Cryo-Volcanic Neptune',
    typeCategory: 'Ice Giant',
    scientificDesignation: 'NEPT-ICE-23',
    atmosphereComposition: 'Hydrogen (80%), Helium (19%), Methane (1%)',
    surfaceComposition: 'Supercritical Slush Mantle (Water, Ammonia, Methane)',
    temperatureRange: '-210°C to -120°C',
    averageDiameterKm: 49500,
    sizeRating: 7,
    habitabilityScore: 28,
    metalMultiplier: 0.7,
    crystalMultiplier: 1.2,
    deuteriumMultiplier: 3.4,
    energyMultiplier: 1.2,
    description: 'Neptunian ice giants featuring blue methane cloud decks, fierce supersonic storms, and vast reservoirs of cryogenic fuel and exotic high-pressure ice.',
    subClasses: ['Methane Blue Giant', 'Cryo-Ammonia Slush World', 'Super-Neptune Core'],
    subTypes: ['Sudarsky Class IV Ice Giant', 'Diamond-Rain Deep Mantle'],
    colorHex: '#2563eb',
  },
  {
    letter: 'X',
    className: 'Class X: Xeno-Organic Living Biomorphic Biosphere',
    typeCategory: 'Living World Hive',
    scientificDesignation: 'XENO-ORGA-24',
    atmosphereComposition: 'Oxygen (23%), Nitrogen (71%), Spore Vapors, Pheromone Mist',
    surfaceComposition: 'Biomass Mycelial Mat, Calcified Chitin Shell Continents, Chlorophyll Oceans',
    temperatureRange: '18°C to 36°C',
    averageDiameterKm: 13100,
    sizeRating: 5,
    habitabilityScore: 92,
    metalMultiplier: 1.1,
    crystalMultiplier: 1.3,
    deuteriumMultiplier: 1.4,
    energyMultiplier: 1.7,
    description: 'Astonishing sentient worlds where the entire planetary crust functions as a unified biological neural organism. Cellular growth speeds up all local construction.',
    subClasses: ['Mycelial Hive World', 'Chitinous Shell Super-Organism', 'Bioluminescent Neuro-Ocean'],
    subTypes: ['Type-III Living Planet Entity', 'Bio-Synthesizing Crust Matrix'],
    colorHex: '#16a34a',
  },
  {
    letter: 'Y',
    className: 'Class Y: Demon Toxic Pyrolytic Acid',
    typeCategory: 'Corrosive Hellscape',
    scientificDesignation: 'TOX-DEMO-25',
    atmosphereComposition: 'Hydrofluoric Acid, Chlorine Gas, Carbon Monoxide, Mercury Vapor',
    surfaceComposition: 'Acid Slag Basins, Dissolved Silicate Slurry, Pyrolytic Tar Fields',
    temperatureRange: '350°C to 800°C',
    averageDiameterKm: 11600,
    sizeRating: 4,
    habitabilityScore: 2,
    metalMultiplier: 1.75,
    crystalMultiplier: 1.8,
    deuteriumMultiplier: 1.1,
    energyMultiplier: 2.1,
    description: 'Demon worlds swept by corrosive acid storms that dissolve unshielded steel within seconds. Contains ultra-rare caustic crystals valued in super-weapon manufacture.',
    subClasses: ['Chlorine Smog Cauldron', 'Hydrofluoric Acid Abyss', 'Mercury Mist Basin'],
    subTypes: ['Extreme Pyrolytic Dissolution', 'Corrosive Atmospheric Halogen'],
    colorHex: '#4ade80',
  },
  {
    letter: 'Z',
    className: 'Class Z: Zero-Zone Antimatter Rift & Temporal Void',
    typeCategory: 'Anomalous Void',
    scientificDesignation: 'ANOM-VOID-26',
    atmosphereComposition: 'Tachyon Particle Flux, Quantum Vacuum Field, Cherenkov Radiation',
    surfaceComposition: 'Metastable Antimatter Crystals, Chrono-Dilated Monoliths, Null-Mass Shards',
    temperatureRange: '-272°C to 1000°C (Quantum fluctuation)',
    averageDiameterKm: 14500,
    sizeRating: 5,
    habitabilityScore: 50,
    metalMultiplier: 2.0,
    crystalMultiplier: 3.0,
    deuteriumMultiplier: 3.0,
    energyMultiplier: 4.5,
    description: 'Mysterious anomalous worlds caught within subspace rifts or Ancient quantum experiments. Space-time fluctuates wildly, producing immense Dark Matter and Zero-Point power.',
    subClasses: ['Tachyon Event Horizon', 'Chrono-Stasis Void World', 'Antimatter Lattice Nexus'],
    subTypes: ['Zero-Point Quantum Rupture', 'Trans-Dimensional Anchor'],
    colorHex: '#6366f1',
  },
];

// ==========================================
// PLANETARY & MOON SIZES 1 TO 9
// ==========================================

export const PLANETARY_SIZE_SCALES: PlanetarySizeScale[] = [
  {
    sizeLevel: 1,
    label: 'Size 1: Micro-Planetesimal',
    category: 'Sub-Terrestrial Asteroid',
    fieldsRange: '40 - 65 Building Fields',
    diameterRangeKm: '2,500 - 4,500 km',
    massComparison: '0.05x - 0.15x Earth Mass',
    defenseSlots: 4,
    maxBuildingCapacity: 65,
    tacticalAdvantage: 'High orbital stealth, minimal sensor footprint, difficult to detect with standard radar.',
  },
  {
    sizeLevel: 2,
    label: 'Size 2: Sub-Dwarf Terrestrial',
    category: 'Low-Mass Planetoid',
    fieldsRange: '70 - 105 Building Fields',
    diameterRangeKm: '4,600 - 7,200 km',
    massComparison: '0.16x - 0.35x Earth Mass',
    defenseSlots: 8,
    maxBuildingCapacity: 105,
    tacticalAdvantage: 'Rapid sublight launch escape velocity; fast defensive missile launch reaction times.',
  },
  {
    sizeLevel: 3,
    label: 'Size 3: Minor Planetary Body',
    category: 'Intermediate Silicate',
    fieldsRange: '110 - 150 Building Fields',
    diameterRangeKm: '7,300 - 10,200 km',
    massComparison: '0.36x - 0.65x Earth Mass',
    defenseSlots: 12,
    maxBuildingCapacity: 150,
    tacticalAdvantage: 'Ideal balance for automated drone manufacturing and dedicated listening post relays.',
  },
  {
    sizeLevel: 4,
    label: 'Size 4: Standard Terrestrial',
    category: 'Full-Scale Terrestrial World',
    fieldsRange: '160 - 205 Building Fields',
    diameterRangeKm: '10,300 - 13,500 km',
    massComparison: '0.66x - 1.25x Earth Mass',
    defenseSlots: 16,
    maxBuildingCapacity: 205,
    tacticalAdvantage: 'Standard planetary baseline; full planetary shield dome capacity and balanced gravity.',
  },
  {
    sizeLevel: 5,
    label: 'Size 5: Medium Super-Terrestrial',
    category: 'Super-Earth Prime',
    fieldsRange: '210 - 260 Building Fields',
    diameterRangeKm: '13,600 - 18,000 km',
    massComparison: '1.26x - 2.50x Earth Mass',
    defenseSlots: 22,
    maxBuildingCapacity: 260,
    tacticalAdvantage: 'Strong magnetic dynamo protecting surface grids from solar flares and EMP attacks.',
  },
  {
    sizeLevel: 6,
    label: 'Size 6: Major Continental Super-Earth',
    category: 'Massive Terrestrial Core',
    fieldsRange: '265 - 320 Building Fields',
    diameterRangeKm: '18,100 - 25,000 km',
    massComparison: '2.51x - 4.50x Earth Mass',
    defenseSlots: 28,
    maxBuildingCapacity: 320,
    tacticalAdvantage: 'Can host dual orbital space elevator towers and deep underground nanite complexes.',
  },
  {
    sizeLevel: 7,
    label: 'Size 7: Massive Mega-Terrestrial',
    category: 'Mega-World / Mini-Neptune',
    fieldsRange: '325 - 390 Building Fields',
    diameterRangeKm: '25,100 - 45,000 km',
    massComparison: '4.51x - 9.00x Earth Mass',
    defenseSlots: 36,
    maxBuildingCapacity: 390,
    tacticalAdvantage: 'Titanic industrial capacity; can support orbital defense fortresses and fleet drydocks.',
  },
  {
    sizeLevel: 8,
    label: 'Size 8: Colossal Sub-Giant Core',
    category: 'Sub-Gas Giant World-Forge',
    fieldsRange: '395 - 480 Building Fields',
    diameterRangeKm: '45,100 - 80,000 km',
    massComparison: '9.01x - 25.0x Earth Mass',
    defenseSlots: 46,
    maxBuildingCapacity: 480,
    tacticalAdvantage: 'High planetary gravity wells trap passing debris and accelerate fleet hyperdrive jumps.',
  },
  {
    sizeLevel: 9,
    label: 'Size 9: Titanic Supermassive World / World-Forge',
    category: 'Supermassive World-Forge / Jovian Scale',
    fieldsRange: '490 - 650 Building Fields',
    diameterRangeKm: '80,100 - 160,000 km',
    massComparison: '25.1x - 90.0x Earth Mass',
    defenseSlots: 60,
    maxBuildingCapacity: 650,
    tacticalAdvantage: 'Virtually inexhaustible resource nodes; can harbor an entire civilization\'s armada and supreme megastructures.',
  },
];

// ==========================================
// MOON CLASSES A TO Z (SAMPLE SELECTION)
// ==========================================

export const MOON_CLASSES_A_TO_Z: MoonClassAZ[] = [
  {
    classCode: 'MON-A',
    className: 'Class Alpha: Barren Silicate Regolith',
    originType: 'collision_ejecta',
    densityGcm3: 3.34,
    surfaceGravityG: 0.16,
    fieldsMax: 85,
    lunarSizeRating: 4,
    specialFeature: 'Tidally locked with low seismic noise, ideal for high-precision Sensor Phalanxes.',
    phalanxEfficiency: 120,
    jumpGateSynergy: 100,
    description: 'Classic Luna-type satellite with ancient impact basins and basaltic mare plains.',
  },
  {
    classCode: 'MON-B',
    className: 'Class Beta: Ferrous Metallic Fragment',
    originType: 'captured_asteroid',
    densityGcm3: 5.8,
    surfaceGravityG: 0.28,
    fieldsMax: 70,
    lunarSizeRating: 3,
    specialFeature: 'Dense iron-nickel crust providing natural armor against orbital kinetic bombardment.',
    phalanxEfficiency: 100,
    jumpGateSynergy: 115,
    description: 'Differentiated core remnant of an ancient shattered planetoid, offering pure metal veins.',
  },
  {
    classCode: 'MON-C',
    className: 'Class Gamma: Cryo-Volcanic Methane Satellite',
    originType: 'co_accretion',
    densityGcm3: 1.88,
    surfaceGravityG: 0.14,
    fieldsMax: 95,
    lunarSizeRating: 5,
    specialFeature: 'High deuterium vapor geysers that replenish fleet fuel reserves during jump cooldowns.',
    phalanxEfficiency: 105,
    jumpGateSynergy: 125,
    description: 'Sub-zero satellite shrouded in liquid methane lakes and cryogenic nitrogen geysers.',
  },
  {
    classCode: 'MON-D',
    className: 'Class Delta: Tidally Kneaded Magma Moon',
    originType: 'co_accretion',
    densityGcm3: 3.52,
    surfaceGravityG: 0.18,
    fieldsMax: 75,
    lunarSizeRating: 3,
    specialFeature: 'Geothermal energy cores generate free electrical power for planetary shields.',
    phalanxEfficiency: 90,
    jumpGateSynergy: 110,
    description: 'Tidally flexed moon resembling Jupiter\'s Io, venting sulfur dioxide and molten lava.',
  },
  {
    classCode: 'MON-E',
    className: 'Class Epsilon: Subsurface Ocean Europan Shell',
    originType: 'co_accretion',
    densityGcm3: 3.01,
    surfaceGravityG: 0.13,
    fieldsMax: 105,
    lunarSizeRating: 6,
    specialFeature: 'Vast water ice shield absorbs radar sweeps, cloaking hidden fleet hangars.',
    phalanxEfficiency: 110,
    jumpGateSynergy: 130,
    description: 'Smooth white ice shell covering a 100km liquid ocean with rich isotopic concentrations.',
  },
  {
    classCode: 'MON-Z',
    className: 'Class Zeta: Hollow Ancient Forerunner Relic Moon',
    originType: 'ancient_construct',
    densityGcm3: 1.1,
    surfaceGravityG: 0.35,
    fieldsMax: 140,
    lunarSizeRating: 8,
    specialFeature: 'Ancient hyper-conduits double the speed of Jump Gate recharge cycles.',
    phalanxEfficiency: 180,
    jumpGateSynergy: 200,
    description: 'Artificial megastructure disguised as a natural moon, housing pre-built hangars and subspace arrays.',
  },
];

// ==========================================
// INTERSTELLAR OBJECTS & PHENOMENA
// ==========================================

export const INTERSTELLAR_OBJECTS: InterstellarCelestialObject[] = [
  {
    id: 'obj-1',
    name: 'Sirius Major (Spectral Class A1V)',
    category: 'star',
    spectralClass: 'Class A (White Hyperluminous)',
    luminosity: '25.4 Solar Luminosities',
    radiationIndex: 'High Ultraviolet',
    resourceYield: '+30% Solar Energy Satellite Output',
    tacticalEffect: 'Increases solar panel power by 35% on inner orbits.',
    coordinates: '[Galaxy 1 : Sector 04]',
    description: 'Bright binary stellar system casting brilliant white-blue radiation across orbiting colonies.',
  },
  {
    id: 'obj-2',
    name: 'Vela Pulsar PSR B0833-45',
    category: 'pulsar',
    spectralClass: 'Neutron Star (Rapid Rotator)',
    luminosity: 'High-Energy Gamma & Radio Beams',
    radiationIndex: 'Lethal Pulsed Synchrotron',
    resourceYield: '+50% Antimatter & Dark Energy Accumulation',
    tacticalEffect: 'Electromagnetic pulses scramble hostile long-range targeting sensors.',
    coordinates: '[Galaxy 2 : Sector 18]',
    description: 'Magnetized spinning neutron star emitting lighthouse-like beams of radiation every 89 milliseconds.',
  },
  {
    id: 'obj-3',
    name: 'Cygnus X-1 Singularity Core',
    category: 'black_hole',
    spectralClass: 'Stellar-Mass Black Hole',
    luminosity: 'Extreme X-Ray Accretion Disc',
    radiationIndex: 'Relativistic Relic Ray',
    resourceYield: '+100% Dark Matter Synthesis',
    tacticalEffect: 'Gravitational lens curves hyperspace jump trajectories, shortening transit by 40%.',
    coordinates: '[Galaxy 3 : Sector 99]',
    description: 'Supermassive gravitational abyss surrounded by a blinding swirl of superheated plasma matter.',
  },
  {
    id: 'obj-4',
    name: 'Tachyon Veil Mutara Nebula',
    category: 'nebula',
    spectralClass: 'Ionized Plasma Gas Cloud',
    luminosity: 'Ethereal Violet Emission',
    radiationIndex: 'Static Subspace Static',
    resourceYield: '+40% Deuterium Harvester Enrichment',
    tacticalEffect: 'Disables conventional fleet energy shields inside the gas cloud; forces armor-only kinetic combat.',
    coordinates: '[Galaxy 4 : Sector 12]',
    description: 'Vast interstellar nebula glowing in electromagnetic purples, concealing ambushing battle fleets.',
  },
  {
    id: 'obj-5',
    name: 'Sol-Alpha Dyson Swarm Array',
    category: 'dyson_swarm',
    spectralClass: 'Type-II Megastructure Node',
    luminosity: 'Absorbed 90% Stellar Flux',
    radiationIndex: 'Thermal Infrared Waste',
    resourceYield: '+100,000 Energy Units / Hour',
    tacticalEffect: 'Powers planet-cracking defensive beam grids across the entire system.',
    coordinates: '[Galaxy 5 : Sector 01]',
    description: 'Millions of automated solar collector mirrors encircling the host star in continuous orbit.',
  },
  {
    id: 'obj-6',
    name: 'Great Interstellar Jump Supergate',
    category: 'supergate',
    spectralClass: 'Precursor Ori-Class Megaconstruct',
    luminosity: 'Cherenkov Event Horizon Flare',
    radiationIndex: 'Zero-Point Subspace Wave',
    resourceYield: 'Instant Galaxy-To-Galaxy Fleet Conduit',
    tacticalEffect: 'Allows instantaneous passage of entire armada across galaxies without deuterium burn.',
    coordinates: '[Galaxy 9 : Sector 499]',
    description: 'A 400-meter ring constructed of 90 linked segment blocks powered by a micro-singularity.',
  },
];
