import { StoreItem, BattlePassTier, BattlePassQuest, BattlePassState, CosmeticRewardDetails, ResourceBonusDetails, BattlePassShopItem } from './types';

export const INITIAL_STORE_ITEMS: StoreItem[] = [
  // Officers & Staff
  {
    id: 'officer_commander',
    name: 'Supreme Fleet Commander',
    category: 'officer',
    description: 'Master tactician providing automated building queues, advanced empire overview, and instant fleet shortcuts.',
    icon: '🎖️',
    price: 500,
    currency: 'darkMatter',
    durationDays: 14,
    bonusEffect: '+2 Max Building Queues, +15% Empire Construction Speed',
    purchased: false,
  },
  {
    id: 'officer_geologist',
    name: 'Planetary Geologist',
    category: 'officer',
    description: 'Expert metallurgist optimizing mantle core extraction and deep crystal refining methods.',
    icon: '💎',
    price: 450,
    currency: 'darkMatter',
    durationDays: 14,
    bonusEffect: '+20% Natural Metal & Crystal Mine Production',
    purchased: false,
  },
  {
    id: 'officer_engineer',
    name: 'Chief Starbase Engineer',
    category: 'officer',
    description: 'Directs rapid shield regeneration and post-combat field repair of defenses and war vessels.',
    icon: '🔧',
    price: 450,
    currency: 'darkMatter',
    durationDays: 14,
    bonusEffect: '50% of Destroyed Defenses Auto-Rebuild, -25% Repair Costs',
    purchased: false,
  },
  {
    id: 'officer_admiral',
    name: 'Grand Fleet Admiral',
    category: 'officer',
    description: 'High military authority elevating armada coordination, hyperdrive routing, and fleet formations.',
    icon: '🚀',
    price: 400,
    currency: 'darkMatter',
    durationDays: 14,
    bonusEffect: '+2 Extra Fleet Dispatch Slots, +10% Fleet Sublight Speed',
    purchased: false,
  },
  {
    id: 'officer_technocrat',
    name: 'High Technocrat',
    category: 'officer',
    description: 'Cybernetic research director optimizing supercomputer nodes and subspace espionage arrays.',
    icon: '🔮',
    price: 450,
    currency: 'darkMatter',
    durationDays: 14,
    bonusEffect: '-25% Laboratory Research Time, +2 Espionage Tech Levels',
    purchased: false,
  },

  // Boosters & Overdrives
  {
    id: 'booster_metal_24h',
    name: 'Metal Mine Overdrive (24h)',
    category: 'booster',
    description: 'Infuses mining drill rigs with plasma thermal exciters to amplify metal output.',
    icon: '⚙️',
    price: 150,
    currency: 'darkMatter',
    durationDays: 1,
    bonusEffect: '+25% Metal Production for 24 Hours',
    quantityOwned: 1,
  },
  {
    id: 'booster_crystal_24h',
    name: 'Crystal Synthesis Surge (24h)',
    category: 'booster',
    description: 'Ion beam resonance accelerates silicate and crystal crystallization vats.',
    icon: '💠',
    price: 150,
    currency: 'darkMatter',
    durationDays: 1,
    bonusEffect: '+25% Crystal Production for 24 Hours',
    quantityOwned: 0,
  },
  {
    id: 'booster_deuterium_24h',
    name: 'Deuterium Cryo-Distiller (24h)',
    category: 'booster',
    description: 'Sub-zero cryo-centrifuges extract heavy isotopes from planetary hydrospheres.',
    icon: '🧪',
    price: 200,
    currency: 'darkMatter',
    durationDays: 1,
    bonusEffect: '+30% Deuterium Production for 24 Hours',
    quantityOwned: 1,
  },
  {
    id: 'energy_core_instant',
    name: 'Zero-Point Energy Cell (+10k)',
    category: 'booster',
    description: 'Subspace zero-point module providing an instantaneous surge of clean power.',
    icon: '⚡',
    price: 100,
    currency: 'darkMatter',
    bonusEffect: 'Instantly grants +10,000 Energy Units',
    quantityOwned: 2,
  },
  {
    id: 'naquadah_warp_cache',
    name: 'Imperial Naquadah Vault (+500k)',
    category: 'booster',
    description: 'High-density refined Naquadah ingots teleported straight into your planetary reserves.',
    icon: '🪙',
    price: 250,
    currency: 'darkMatter',
    bonusEffect: 'Instantly adds +500,000 Naquadah',
    quantityOwned: 0,
  },

  // Relics & Tokens
  {
    id: 'token_nanite_finisher',
    name: 'Nanite Swarm Fast-Forward',
    category: 'relic',
    description: 'Deploys millions of micro-constructors to instantly complete any active research or facility build.',
    icon: '⏱️',
    price: 350,
    currency: 'darkMatter',
    bonusEffect: 'Instantly completes current shipyard or lab queue item',
    quantityOwned: 3,
  },
  {
    id: 'token_planet_relocator',
    name: 'Stargate Colony Relocator',
    category: 'relic',
    description: 'Teleports an entire planetary settlement and orbital grid to new astronomical coordinates.',
    icon: '🌌',
    price: 800,
    currency: 'darkMatter',
    bonusEffect: 'Allows instantaneous coordinate relocation of 1 Colony',
    quantityOwned: 0,
  },
  {
    id: 'token_defcon_shield_bubble',
    name: 'DefCon-0 Temporal Aegis (48h)',
    category: 'relic',
    description: 'Envelops all sovereign worlds in a phased temporal field impervious to attacks or raids.',
    icon: '🛡️',
    price: 600,
    currency: 'darkMatter',
    durationDays: 2,
    bonusEffect: 'Complete attack & espionage immunity for 48 hours',
    quantityOwned: 0,
  },

  // Cosmetics & Skins
  {
    id: 'cosmetic_obsidian_hull',
    name: 'Obsidian Dreadnought Armor Plating',
    category: 'cosmetic',
    description: 'Radar-absorbing matte black crystalline coating with glowing violet energy conduits.',
    icon: '🛸',
    price: 1200,
    currency: 'darkMatter',
    bonusEffect: 'Cosmetic capital ship hull glow & +50 Glory Score',
    purchased: false,
  },
  {
    id: 'cosmetic_avatar_cyber_emperor',
    name: 'Ascended Cyber-Emperor Avatar',
    category: 'cosmetic',
    description: 'Exclusive commander visual hologram with floating neural crown and tachyon particle halo.',
    icon: '👑',
    price: 900,
    currency: 'darkMatter',
    bonusEffect: 'Unlocks exclusive Commander Title & Hologram Avatar',
    purchased: false,
  },
];

export const INITIAL_BATTLE_PASS_STATE: BattlePassState = {
  seasonNumber: 1,
  seasonName: 'Season 1: Awakening of the Void',
  daysRemaining: 42,
  currentLevel: 8,
  currentXp: 1850,
  xpToNextLevel: 2500,
  hasElitePass: false,
  totalXpEarned: 19350,
  battlePassPoints: 1250,
};

export const INITIAL_BATTLE_PASS_TIERS: BattlePassTier[] = [
  {
    level: 1,
    requiredXp: 1000,
    freeReward: {
      name: '50,000 Naquadah',
      type: 'resource',
      quantity: 50000,
      icon: '🪙',
      resourceBonus: { naquadah: 50000, energy: 500 },
    },
    eliteReward: {
      name: '250 Dark Matter',
      type: 'darkMatter',
      quantity: 250,
      icon: '🌌',
      resourceBonus: { darkMatter: 250 },
      cosmeticReward: {
        id: 'title_initiate',
        name: 'Cadet of the Stars',
        type: 'title',
        rarity: 'rare',
        icon: '🎖️',
        description: 'Early-access title awarded to all recruits embarking on the conquest track.',
        previewColor: '#3b82f6',
      },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 2,
    requiredXp: 1200,
    freeReward: {
      name: '20,000 Metal & 10k Crystal',
      type: 'resource',
      quantity: 30000,
      icon: '⚙️',
      resourceBonus: { metal: 20000, crystal: 10000 },
    },
    eliteReward: {
      name: 'Hologram: Starlight Orion Beacon',
      type: 'relic',
      quantity: 1,
      icon: '✨',
      resourceBonus: { attackTurns: 5 },
      cosmeticReward: {
        id: 'hologram_orion',
        name: 'Starlight Orion Beacon',
        type: 'hologram',
        rarity: 'rare',
        icon: '✨',
        description: 'Projects a celestial constellation marker above orbital defensive stations.',
        previewColor: '#60a5fa',
      },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 3,
    requiredXp: 1400,
    freeReward: {
      name: '10 Attack Turns & 5k Deuterium',
      type: 'resource',
      quantity: 10,
      icon: '🔄',
      resourceBonus: { attackTurns: 10, deuterium: 5000 },
    },
    eliteReward: {
      name: '300 Dark Matter',
      type: 'darkMatter',
      quantity: 300,
      icon: '🌌',
      resourceBonus: { darkMatter: 300 },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 4,
    requiredXp: 1600,
    freeReward: {
      name: '5x Heavy Cruisers',
      type: 'ship',
      quantity: 5,
      icon: '🚀',
      resourceBonus: { attackUnits: 150, metal: 30000 },
    },
    eliteReward: {
      name: 'Hull Skin: Obsidian Stealth Armor',
      type: 'titanShip',
      quantity: 1,
      icon: '🛸',
      resourceBonus: { darkMatter: 100 },
      cosmeticReward: {
        id: 'skin_obsidian_cruiser',
        name: 'Obsidian Stealth Hull Skin',
        type: 'skin',
        rarity: 'epic',
        icon: '🛸',
        description: 'Matte radar-absorbent composite coating concealing warship thermal signatures.',
        previewColor: '#1f2937',
      },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 5,
    requiredXp: 1800,
    freeReward: {
      name: '75,000 Naquadah & 1k Energy',
      type: 'resource',
      quantity: 75000,
      icon: '🪙',
      resourceBonus: { naquadah: 75000, energy: 1000 },
    },
    eliteReward: {
      name: 'Avatar: Cyborg Fleet Admiral',
      type: 'relic',
      quantity: 1,
      icon: '🤖',
      resourceBonus: { darkMatter: 150 },
      cosmeticReward: {
        id: 'avatar_cyborg_admiral',
        name: 'Cyborg Fleet Admiral',
        type: 'avatar',
        rarity: 'epic',
        icon: '🤖',
        description: 'Bionic neural cyberware avatar featuring glowing optical targeting telemetry.',
        previewColor: '#8b5cf6',
      },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 6,
    requiredXp: 2000,
    freeReward: {
      name: '15,000 Deuterium & 15k Crystal',
      type: 'resource',
      quantity: 15000,
      icon: '🧪',
      resourceBonus: { deuterium: 15000, crystal: 15000 },
    },
    eliteReward: {
      name: '400 Dark Matter',
      type: 'darkMatter',
      quantity: 400,
      icon: '🌌',
      resourceBonus: { darkMatter: 400 },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 7,
    requiredXp: 2200,
    freeReward: {
      name: '100 Elite Defense Units',
      type: 'resource',
      quantity: 100,
      icon: '🛡️',
      resourceBonus: { attackUnits: 200, metal: 25000 },
    },
    eliteReward: {
      name: 'Engine Trail: Void Plasma Glow',
      type: 'skin',
      quantity: 1,
      icon: '⚡',
      resourceBonus: { energy: 1500 },
      cosmeticReward: {
        id: 'trail_void_plasma',
        name: 'Void Plasma Engine Glow',
        type: 'engine_trail',
        rarity: 'epic',
        icon: '⚡',
        description: 'Supercharged ionized cyan trail left behind by sub-light hyperdrive thrusters.',
        previewColor: '#06b6d4',
      },
    },
    claimedFree: true,
    claimedElite: false,
  },
  {
    level: 8,
    requiredXp: 2500,
    freeReward: {
      name: '100,000 Naquadah & 500 Units',
      type: 'resource',
      quantity: 100000,
      icon: '🪙',
      resourceBonus: { naquadah: 100000, attackUnits: 500 },
    },
    eliteReward: {
      name: 'Hull Skin: Titan Chromatic Aegis',
      type: 'titanShip',
      quantity: 1,
      icon: '⭐',
      resourceBonus: { darkMatter: 250 },
      cosmeticReward: {
        id: 'skin_titan_chromatic',
        name: 'Titan Chromatic Aegis',
        type: 'skin',
        rarity: 'legendary',
        icon: '⭐',
        description: 'Iridescent crystalline reflective coating shielding colossal super-dreadnoughts.',
        previewColor: '#f59e0b',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 9,
    requiredXp: 2800,
    freeReward: {
      name: '25 Attack Turns & 50k Naquadah',
      type: 'resource',
      quantity: 25,
      icon: '🔄',
      resourceBonus: { attackTurns: 25, naquadah: 50000 },
    },
    eliteReward: {
      name: '500 Dark Matter & 20k Deuterium',
      type: 'darkMatter',
      quantity: 500,
      icon: '🌌',
      resourceBonus: { darkMatter: 500, deuterium: 20000 },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 10,
    requiredXp: 3000,
    freeReward: {
      name: '1x Zero-Point Energy Cell (3,000 Energy)',
      type: 'resource',
      quantity: 1,
      icon: '⚡',
      resourceBonus: { energy: 3000, naquadah: 150000 },
    },
    eliteReward: {
      name: 'Prestige Title: "Void Vanguard"',
      type: 'exclusiveTitle',
      quantity: 1,
      icon: '🎖️',
      resourceBonus: { darkMatter: 500 },
      cosmeticReward: {
        id: 'title_void_vanguard',
        name: 'Void Vanguard',
        type: 'title',
        rarity: 'legendary',
        icon: '🎖️',
        description: 'Awarded to front-line pathfinders braving deep galactic rim frontier sectors.',
        previewColor: '#d97706',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 11,
    requiredXp: 3200,
    freeReward: {
      name: '50,000 Metal & 30k Crystal',
      type: 'resource',
      quantity: 80000,
      icon: '⚙️',
      resourceBonus: { metal: 50000, crystal: 30000 },
    },
    eliteReward: {
      name: '600 Dark Matter',
      type: 'darkMatter',
      quantity: 600,
      icon: '🌌',
      resourceBonus: { darkMatter: 600, deuterium: 30000 },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 12,
    requiredXp: 3500,
    freeReward: {
      name: '10x Stealth Interceptors (300 Units)',
      type: 'ship',
      quantity: 10,
      icon: '🚀',
      resourceBonus: { attackUnits: 300, crystal: 40000 },
    },
    eliteReward: {
      name: 'Engine Trail: Singularity Hyperspace Wake',
      type: 'relic',
      quantity: 1,
      icon: '🌀',
      resourceBonus: { darkMatter: 350 },
      cosmeticReward: {
        id: 'trail_singularity_wake',
        name: 'Singularity Hyperspace Wake',
        type: 'engine_trail',
        rarity: 'legendary',
        icon: '🌀',
        description: 'Dark gravitational distortion wave trailing capital ships through hyperspace.',
        previewColor: '#9333ea',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 15,
    requiredXp: 4000,
    freeReward: {
      name: '200,000 Naquadah & 50k Deuterium',
      type: 'resource',
      quantity: 200000,
      icon: '🪙',
      resourceBonus: { naquadah: 200000, deuterium: 50000 },
    },
    eliteReward: {
      name: 'Avatar: Ascended Ancient Luminary',
      type: 'relic',
      quantity: 1,
      icon: '👑',
      resourceBonus: { darkMatter: 750 },
      cosmeticReward: {
        id: 'avatar_ascended_ancient',
        name: 'Ascended Ancient Luminary',
        type: 'avatar',
        rarity: 'legendary',
        icon: '🧙‍♂️',
        description: 'Transcendent pure-energy humanoid being composed of luminous zero-point radiation.',
        previewColor: '#eab308',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 20,
    requiredXp: 5000,
    freeReward: {
      name: '50 Attack Turns & 1,000 Units',
      type: 'resource',
      quantity: 50,
      icon: '🔄',
      resourceBonus: { attackTurns: 50, attackUnits: 1000, naquadah: 250000 },
    },
    eliteReward: {
      name: 'Hologram: Extinction Core Projection',
      type: 'titanShip',
      quantity: 1,
      icon: '💥',
      resourceBonus: { darkMatter: 1000 },
      cosmeticReward: {
        id: 'hologram_extinction_core',
        name: 'Extinction Core Projection',
        type: 'hologram',
        rarity: 'mythic',
        icon: '💥',
        description: 'Orbital holographic projector showing catastrophic planetary core breakdown simulations.',
        previewColor: '#ef4444',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 25,
    requiredXp: 6000,
    freeReward: {
      name: '500,000 Naquadah & 250k Crystal',
      type: 'resource',
      quantity: 500000,
      icon: '🪙',
      resourceBonus: { naquadah: 500000, crystal: 250000 },
    },
    eliteReward: {
      name: '1,500 Dark Matter',
      type: 'darkMatter',
      quantity: 1500,
      icon: '🌌',
      resourceBonus: { darkMatter: 1500, deuterium: 100000 },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 30,
    requiredXp: 7500,
    freeReward: {
      name: '100k Deuterium & 300k Metal',
      type: 'resource',
      quantity: 100000,
      icon: '🧪',
      resourceBonus: { deuterium: 100000, metal: 300000, attackUnits: 1500 },
    },
    eliteReward: {
      name: 'Legendary Title: "Master of Hyperspace"',
      type: 'exclusiveTitle',
      quantity: 1,
      icon: '🌟',
      resourceBonus: { darkMatter: 2000 },
      cosmeticReward: {
        id: 'title_master_hyperspace',
        name: 'Master of Hyperspace',
        type: 'title',
        rarity: 'mythic',
        icon: '🌟',
        description: 'Supreme honor demonstrating unmatched mastery over wormhole transit and fleet warp speed.',
        previewColor: '#ec4899',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 40,
    requiredXp: 9000,
    freeReward: {
      name: '1,000,000 Naquadah Reserves',
      type: 'resource',
      quantity: 1000000,
      icon: '🪙',
      resourceBonus: { naquadah: 1000000, metal: 500000, crystal: 500000 },
    },
    eliteReward: {
      name: 'Hull Skin: Star-Eater Dreadnought',
      type: 'relic',
      quantity: 1,
      icon: '🪐',
      resourceBonus: { darkMatter: 3000 },
      cosmeticReward: {
        id: 'skin_star_eater',
        name: 'Star-Eater Dreadnought Hull',
        type: 'skin',
        rarity: 'mythic',
        icon: '🪐',
        description: 'Forged from stellar furnace remnants, pulsating with coronal plasma conduits.',
        previewColor: '#f97316',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
  {
    level: 50,
    requiredXp: 12000,
    freeReward: {
      name: 'Cosmic Grand Cache (2.5M Naq, 100 Ships)',
      type: 'resource',
      quantity: 2500000,
      icon: '🏆',
      resourceBonus: {
        naquadah: 2500000,
        crystal: 1000000,
        metal: 1000000,
        attackTurns: 100,
        attackUnits: 5000,
        darkMatter: 500,
      },
    },
    eliteReward: {
      name: 'Auric Skin: Primordial Ascension & 5,000 DM',
      type: 'exclusiveTitle',
      quantity: 5000,
      icon: '🌠',
      resourceBonus: { darkMatter: 5000, naquadah: 5000000 },
      cosmeticReward: {
        id: 'skin_primordial_ascension',
        name: 'Primordial Ascension Auric Skin',
        type: 'skin',
        rarity: 'mythic',
        icon: '🌠',
        description: 'The pinnacle of interstellar prestige: Pure golden resonant alloys with zero-point distortion halo.',
        previewColor: '#eab308',
      },
    },
    claimedFree: false,
    claimedElite: false,
  },
];

export const INITIAL_COSMETICS_CATALOG: CosmeticRewardDetails[] = [
  {
    id: 'cat_title_initiate',
    name: 'Cadet of the Stars',
    type: 'title',
    rarity: 'rare',
    icon: '🎖️',
    description: 'Early-access title awarded to all recruits embarking on the conquest track.',
    previewColor: '#3b82f6',
    equipped: true,
  },
  {
    id: 'cat_hologram_orion',
    name: 'Starlight Orion Beacon',
    type: 'hologram',
    rarity: 'rare',
    icon: '✨',
    description: 'Projects a celestial constellation marker above orbital defensive stations.',
    previewColor: '#60a5fa',
    equipped: false,
  },
  {
    id: 'cat_skin_obsidian_cruiser',
    name: 'Obsidian Stealth Hull Skin',
    type: 'skin',
    rarity: 'epic',
    icon: '🛸',
    description: 'Matte radar-absorbent composite coating concealing warship thermal signatures.',
    previewColor: '#1f2937',
    equipped: false,
  },
  {
    id: 'cat_avatar_cyborg_admiral',
    name: 'Cyborg Fleet Admiral',
    type: 'avatar',
    rarity: 'epic',
    icon: '🤖',
    description: 'Bionic neural cyberware avatar featuring glowing optical targeting telemetry.',
    previewColor: '#8b5cf6',
    equipped: false,
  },
  {
    id: 'cat_trail_void_plasma',
    name: 'Void Plasma Engine Glow',
    type: 'engine_trail',
    rarity: 'epic',
    icon: '⚡',
    description: 'Supercharged ionized cyan trail left behind by sub-light hyperdrive thrusters.',
    previewColor: '#06b6d4',
    equipped: false,
  },
  {
    id: 'cat_skin_titan_chromatic',
    name: 'Titan Chromatic Aegis',
    type: 'skin',
    rarity: 'legendary',
    icon: '⭐',
    description: 'Iridescent crystalline reflective coating shielding colossal super-dreadnoughts.',
    previewColor: '#f59e0b',
    equipped: false,
  },
  {
    id: 'cat_title_void_vanguard',
    name: 'Void Vanguard',
    type: 'title',
    rarity: 'legendary',
    icon: '🎖️',
    description: 'Awarded to front-line pathfinders braving deep galactic rim frontier sectors.',
    previewColor: '#d97706',
    equipped: false,
  },
  {
    id: 'cat_trail_singularity_wake',
    name: 'Singularity Hyperspace Wake',
    type: 'engine_trail',
    rarity: 'legendary',
    icon: '🌀',
    description: 'Dark gravitational distortion wave trailing capital ships through hyperspace.',
    previewColor: '#9333ea',
    equipped: false,
  },
  {
    id: 'cat_avatar_ascended_ancient',
    name: 'Ascended Ancient Luminary',
    type: 'avatar',
    rarity: 'legendary',
    icon: '🧙‍♂️',
    description: 'Transcendent pure-energy humanoid being composed of luminous zero-point radiation.',
    previewColor: '#eab308',
    equipped: false,
  },
  {
    id: 'cat_hologram_extinction_core',
    name: 'Extinction Core Projection',
    type: 'hologram',
    rarity: 'mythic',
    icon: '💥',
    description: 'Orbital holographic projector showing catastrophic planetary core breakdown simulations.',
    previewColor: '#ef4444',
    equipped: false,
  },
  {
    id: 'cat_title_master_hyperspace',
    name: 'Master of Hyperspace',
    type: 'title',
    rarity: 'mythic',
    icon: '🌟',
    description: 'Supreme honor demonstrating unmatched mastery over wormhole transit and fleet warp speed.',
    previewColor: '#ec4899',
    equipped: false,
  },
  {
    id: 'cat_skin_star_eater',
    name: 'Star-Eater Dreadnought Hull',
    type: 'skin',
    rarity: 'mythic',
    icon: '🪐',
    description: 'Forged from stellar furnace remnants, pulsating with coronal plasma conduits.',
    previewColor: '#f97316',
    equipped: false,
  },
  {
    id: 'cat_skin_primordial_ascension',
    name: 'Primordial Ascension Auric Skin',
    type: 'skin',
    rarity: 'mythic',
    icon: '🌠',
    description: 'The pinnacle of interstellar prestige: Pure golden resonant alloys with zero-point distortion halo.',
    previewColor: '#eab308',
    equipped: false,
  },
];

export const INITIAL_BATTLE_PASS_QUESTS: BattlePassQuest[] = [
  {
    id: 'quest_turns',
    title: 'Process 12 Turn Cycles',
    description: 'Advance empire turn simulations to harvest resource increments and population growth.',
    type: 'daily',
    targetCount: 12,
    currentCount: 8,
    xpReward: 350,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_mine_metal',
    title: 'Mine 100,000 Metal',
    description: 'Extract raw industrial alloys from planetary surface and asteroid strip-mines.',
    type: 'daily',
    targetCount: 100000,
    currentCount: 85000,
    xpReward: 400,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_spy_probe',
    title: 'Launch 3 Espionage Probes',
    description: 'Dispatch reconnaissance sensor drones into rival systems to gather tactical data.',
    type: 'daily',
    targetCount: 3,
    currentCount: 3,
    xpReward: 450,
    completed: true,
    claimed: false,
  },
  {
    id: 'quest_expedition',
    title: 'Conduct Deep Space Expedition',
    description: 'Send a scout fleet into uncharted deep-space sectors to discover relics or dark matter.',
    type: 'daily',
    targetCount: 1,
    currentCount: 1,
    xpReward: 500,
    completed: true,
    claimed: true,
  },
  {
    id: 'quest_weekly_combat',
    title: 'Achieve 5 Combat Victories',
    description: 'Raid rival warlords, pirate strongholds, or planetary colonies with triumphant outcomes.',
    type: 'weekly',
    targetCount: 5,
    currentCount: 3,
    xpReward: 1200,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_weekly_shipyard',
    title: 'Construct 25 Warships in Shipyard',
    description: 'Assemble battle fleets, cruisers, or interceptors in orbital drydocks.',
    type: 'weekly',
    targetCount: 25,
    currentCount: 14,
    xpReward: 1500,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_weekly_recycle',
    title: 'Harvest Debris Field with Recyclers',
    description: 'Scavenge shattered ship wreckage from orbit using specialized recycler vessels.',
    type: 'weekly',
    targetCount: 50000,
    currentCount: 22000,
    xpReward: 1400,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_milestone_moon',
    title: 'Discover or Fortify a Lunar Base',
    description: 'Establish high-tier subterranean moon bases or calibrate deep-space sensor phalanxes.',
    type: 'milestone',
    targetCount: 1,
    currentCount: 1,
    xpReward: 2500,
    completed: true,
    claimed: false,
  },
];

export const INITIAL_BATTLE_PASS_SHOP_ITEMS: BattlePassShopItem[] = [
  // ==========================================
  // EXCLUSIVE COSMETIC UNIT SKINS
  // ==========================================
  {
    id: 'bp_skin_f302_ghost',
    name: 'F-302 Hyperspace Stealth Ghost',
    category: 'unit_skin',
    description: 'Matte carbon-weave aerogel plating with anti-radar microwave absorption coating and sapphire sublight ion contrails.',
    pricePoints: 400,
    icon: '✈️',
    rarity: 'epic',
    unitTarget: 'F-302 Interceptor & Light Fighters',
    previewColor: '#1e1e24',
    accentColor: '#38bdf8',
    bonusEffect: '+120 Unit Prestige, Void-Black Stealth Hull & Sapphire Engine Plume',
    cosmeticDetails: {
      id: 'skin_f302_ghost',
      name: 'F-302 Stealth Ghost',
      type: 'skin',
      rarity: 'epic',
      icon: '✈️',
      description: 'Void-black radar absorbing stealth livery for F-302 space interceptors.',
      previewColor: '#1e1e24',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_bc304_prometheus',
    name: "BC-304 'Prometheus Reborn' Trinium Gold",
    category: 'unit_skin',
    description: 'Gleaming golden trinium alloy armor hull etched with Ancient protection runes and high-yield Asgard beam emitter conduits.',
    pricePoints: 650,
    icon: '🛸',
    rarity: 'legendary',
    unitTarget: 'BC-304 Battlecruisers & Heavy Cruisers',
    previewColor: '#ca8a04',
    accentColor: '#fde047',
    bonusEffect: '+250 Flagship Glory, Radiant Golden Trinium Shroud & Asgard Pulse Conduits',
    cosmeticDetails: {
      id: 'skin_bc304_prometheus',
      name: "BC-304 'Prometheus Reborn'",
      type: 'skin',
      rarity: 'legendary',
      icon: '🛸',
      description: 'Honored golden trinium standard with Ancient rune engravings.',
      previewColor: '#ca8a04',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_hatak_solar',
    name: "Ha'tak Solar Flare Imperial Standard",
    category: 'unit_skin',
    description: 'Ceremonial Ra imperial pyramid hull, embellished with ruby pyrites and molten gold hieroglyphic thermal cooling radiators.',
    pricePoints: 600,
    icon: '🔱',
    rarity: 'legendary',
    unitTarget: "Goa'uld Ha'tak Flagships & Pyramids",
    previewColor: '#b91c1c',
    accentColor: '#f59e0b',
    bonusEffect: '+220 System Lord Authority, Molten Crimson Glow & Golden Plasma Conduits',
    cosmeticDetails: {
      id: 'skin_hatak_solar',
      name: "Ha'tak Solar Flare",
      type: 'skin',
      rarity: 'legendary',
      icon: '🔱',
      description: 'Imperial ceremonial pyramid livery bathed in radiant solar plasma.',
      previewColor: '#b91c1c',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_oneill_bifrost',
    name: "O'Neill Battleship 'Bifrost Convergence'",
    category: 'unit_skin',
    description: 'Translucent neutronium-infused crystal lattice refracting subatomic light into an ethereal chromatic particle aura.',
    pricePoints: 750,
    icon: '💎',
    rarity: 'mythic',
    unitTarget: "Asgard O'Neill & Valhalla Battleships",
    previewColor: '#06b6d4',
    accentColor: '#a855f7',
    bonusEffect: '+350 Technological Splendor, Chromatic Refractive Aura & Prismatic Core',
    cosmeticDetails: {
      id: 'skin_oneill_bifrost',
      name: "O'Neill Bifrost Convergence",
      type: 'skin',
      rarity: 'mythic',
      icon: '💎',
      description: 'Refractive neutronium crystal lattice dispersing chromatic subatomic light.',
      previewColor: '#06b6d4',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_wraith_hades',
    name: "Wraith Hive 'Hades Royal Bioweave'",
    category: 'unit_skin',
    description: 'Chitinous biomechanical hull overgrown with pulsating bioluminescent violet neural tendrils and cellular regeneration cysts.',
    pricePoints: 550,
    icon: '👾',
    rarity: 'epic',
    unitTarget: 'Wraith Hive Ships & Cruisers',
    previewColor: '#581c87',
    accentColor: '#c084fc',
    bonusEffect: '+180 Bio-Dominance, Bioluminescent Purple Veins & Cellular Pulse',
    cosmeticDetails: {
      id: 'skin_wraith_hades',
      name: 'Wraith Royal Bioweave',
      type: 'skin',
      rarity: 'epic',
      icon: '👾',
      description: 'Royal hive-queen bioweave hull pulsing with organic violet radiance.',
      previewColor: '#581c87',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_aurora_atlantis',
    name: "Aurora Warship 'Pride of Atlantis'",
    category: 'unit_skin',
    description: 'Immaculately restored Lantean titanium-silver hull displaying cyan zero-point conduits and glowing drone launch tubes.',
    pricePoints: 850,
    icon: '⚡',
    rarity: 'mythic',
    unitTarget: 'Lantean Aurora Battleships & Dreadnoughts',
    previewColor: '#e2e8f0',
    accentColor: '#14b8a6',
    bonusEffect: '+400 Ancient Legacy, Lantean Turquoise Energy Grid & Drone Silo Glow',
    cosmeticDetails: {
      id: 'skin_aurora_atlantis',
      name: 'Aurora Pride of Atlantis',
      type: 'skin',
      rarity: 'mythic',
      icon: '⚡',
      description: 'Pristine Lantean silver hull with active turquoise zero-point circuitry.',
      previewColor: '#e2e8f0',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_glider_dakara',
    name: "Death Glider 'Blood of Dakara'",
    category: 'unit_skin',
    description: 'High-contrast scarlet and black ceremonial livery celebrating the liberation of the Free Jaffa Nation at the temple of Dakara.',
    pricePoints: 350,
    icon: '⚔️',
    rarity: 'rare',
    unitTarget: 'Jaffa Death Gliders & Scout Flits',
    previewColor: '#991b1b',
    accentColor: '#f87171',
    bonusEffect: '+80 Rebellion Honor, High-Visibility Crimson Wings & Staff Emitters',
    cosmeticDetails: {
      id: 'skin_glider_dakara',
      name: 'Death Glider Dakara',
      type: 'skin',
      rarity: 'rare',
      icon: '⚔️',
      description: 'Liberation war markings from the uprising on holy Dakara.',
      previewColor: '#991b1b',
      equipped: false,
    },
    purchased: false,
  },
  {
    id: 'bp_skin_replicator_quicksilver',
    name: "Nanite Cruiser 'Liquid Quicksilver'",
    category: 'unit_skin',
    description: 'Polygonal nanite building blocks constantly undulating in liquid mercury reflections, distorting tactical sensor scans.',
    pricePoints: 700,
    icon: '🪞',
    rarity: 'legendary',
    unitTarget: 'Replicator Nanite Swarms & Cruisers',
    previewColor: '#64748b',
    accentColor: '#38bdf8',
    bonusEffect: '+300 Nanite Cohesion, Morphing Liquid Mercury Geometry',
    cosmeticDetails: {
      id: 'skin_replicator_quicksilver',
      name: 'Nanite Liquid Quicksilver',
      type: 'skin',
      rarity: 'legendary',
      icon: '🪞',
      description: 'Ever-shifting chrome nanite blocks with fluid mirror reflections.',
      previewColor: '#64748b',
      equipped: false,
    },
    purchased: false,
  },

  // ==========================================
  // UNIQUE STARTING RESOURCE BUNDLES
  // ==========================================
  {
    id: 'bp_bundle_pioneer_starter',
    name: 'Pioneer Colony Starter Requisition',
    category: 'resource_bundle',
    description: 'A comprehensive starter cache packed with liquid Naquadah, primary metals, and exploration attack turns to colonize new worlds.',
    pricePoints: 350,
    icon: '📦',
    rarity: 'rare',
    previewColor: '#3b82f6',
    accentColor: '#93c5fd',
    bonusEffect: '+500k Naquadah, +300k Metal, +150k Crystal, +5k Energy, +20 Turns',
    resourceBonus: {
      naquadah: 500000,
      metal: 300000,
      crystal: 150000,
      energy: 5000,
      attackTurns: 20,
    },
    purchaseCount: 0,
  },
  {
    id: 'bp_bundle_fleet_vanguard',
    name: 'Deep Space Vanguard Fleet Cache',
    category: 'resource_bundle',
    description: 'Pre-commissioned military provisions packed with Deuterium warp propellant, heavy ordnance alloys, and veteran attack troops.',
    pricePoints: 650,
    icon: '🚀',
    rarity: 'epic',
    previewColor: '#8b5cf6',
    accentColor: '#c084fc',
    bonusEffect: '+1.2M Naquadah, +600k Metal, +400k Crystal, +250k Deuterium, +120 Troops, +40 Turns',
    resourceBonus: {
      naquadah: 1200000,
      metal: 600000,
      crystal: 400000,
      deuterium: 250000,
      attackUnits: 120,
      attackTurns: 40,
    },
    purchaseCount: 0,
  },
  {
    id: 'bp_bundle_zpm_jumpstart',
    name: 'Ancient ZPM Core Jumpstart Pack',
    category: 'resource_bundle',
    description: 'Salvaged Zero-Point Module micro-containment cell supplying vast clean energy, Dark Matter catalysts, and enriched Deuterium.',
    pricePoints: 800,
    icon: '⚡',
    rarity: 'legendary',
    previewColor: '#eab308',
    accentColor: '#fef08a',
    bonusEffect: '+25k Energy, +350 Dark Matter, +1.5M Naquadah, +350k Deuterium, +50 Turns',
    resourceBonus: {
      energy: 25000,
      darkMatter: 350,
      naquadah: 1500000,
      deuterium: 350000,
      attackTurns: 50,
    },
    purchaseCount: 0,
  },
  {
    id: 'bp_bundle_titan_industrial',
    name: 'Titan Industrialist Planetary Megacrate',
    category: 'resource_bundle',
    description: 'Massive empire industrial supply drop engineered to fast-track planetary mines, orbital megastructures, and capital ship fleets.',
    pricePoints: 1100,
    icon: '🏗️',
    rarity: 'mythic',
    previewColor: '#ec4899',
    accentColor: '#f472b6',
    bonusEffect: '+3.0M Naquadah, +2.0M Metal, +1.2M Crystal, +600k Deuterium, +30k Energy, +75 Turns',
    resourceBonus: {
      naquadah: 3000000,
      metal: 2000000,
      crystal: 1200000,
      deuterium: 600000,
      energy: 30000,
      attackTurns: 75,
    },
    purchaseCount: 0,
  },
  {
    id: 'bp_bundle_spec_ops',
    name: 'Stargate Special Ops Infiltration Crate',
    category: 'resource_bundle',
    description: 'Covert off-world kit containing Stargate dialing credentials, trained special forces soldiers, and Dark Matter research funds.',
    pricePoints: 500,
    icon: '🎯',
    rarity: 'epic',
    previewColor: '#059669',
    accentColor: '#34d399',
    bonusEffect: '+45 Attack Turns, +250 Elite Troops, +250 Dark Matter, +800k Naquadah',
    resourceBonus: {
      attackTurns: 45,
      attackUnits: 250,
      darkMatter: 250,
      naquadah: 800000,
    },
    purchaseCount: 0,
  },
  {
    id: 'bp_bundle_nanite_matrix',
    name: 'Nanite Matrix Rapid Synthesis Kit',
    category: 'resource_bundle',
    description: 'High-purity crystalline matrices and refined alloys for instantaneous factory retooling and rapid research queue completion.',
    pricePoints: 450,
    icon: '⚙️',
    rarity: 'rare',
    previewColor: '#0ea5e9',
    accentColor: '#7dd3fc',
    bonusEffect: '+500k Metal, +350k Crystal, +8k Energy, +25 Attack Turns',
    resourceBonus: {
      metal: 500000,
      crystal: 350000,
      energy: 8000,
      attackTurns: 25,
    },
    purchaseCount: 0,
  },
];
