-- Raid Bosses - 90 unique bosses across 6 rarity tiers
-- Each boss has thematic abilities, weaknesses, resistances, loot, and rewards

-- =============================================================================
-- COMMON RAID BOSSES (15) - Levels 5-15, solo/duo content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Scrapyard Sentinel', 'A decommissioned defense drone reactivated by stray energy pulses in a junkyard sector.', 'raid', 'common', 8000, 120, 40, 30, '["Scrap Volley", "Rusty Charge"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "scrap_metal", "quantity": 50, "dropRate": 0.8}]'::jsonb, '{"xp": 200, "credits": 500, "resources": {"metal": 100, "crystal": 50}}'::jsonb, 5, 1, 1),
('Void Mite Swarm', 'A cluster of small void organisms that have merged into a single hostile mass.', 'raid', 'common', 6500, 90, 25, 55, '["Corrosive Spit", "Swarm Tactics"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.6}'::jsonb, '[{"item": "void_sample", "quantity": 3, "dropRate": 0.7}]'::jsonb, '{"xp": 150, "credits": 300, "resources": {"metal": 60, "crystal": 30}}'::jsonb, 5, 1, 1),
('Derelict Mech Pilot', 'An automated mech still executing its last combat orders from a forgotten war.', 'raid', 'common', 9500, 140, 55, 25, '["Autocannon Burst", "Missile Salvo"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.8}'::jsonb, '[{"item": "mech_component", "quantity": 2, "dropRate": 0.6}]'::jsonb, '{"xp": 250, "credits": 600, "resources": {"metal": 120, "crystal": 40}}'::jsonb, 7, 1, 1),
('Asteroid Worm', 'A silicon-based organism that burrows through asteroids, emerging to consume ships.', 'raid', 'common', 7200, 100, 60, 35, '["Tunnel Strike", "Rock Shell"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.5}'::jsonb, '[{"item": "silicon_core", "quantity": 1, "dropRate": 0.5}]'::jsonb, '{"xp": 180, "credits": 400, "resources": {"metal": 80, "crystal": 60}}'::jsonb, 6, 1, 1),
('Plasma Leech', 'An energy parasitic organism that drains power from ship systems on contact.', 'raid', 'common', 5800, 80, 20, 65, '["Energy Drain", "Plasma Burst"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "plasma_residue", "quantity": 4, "dropRate": 0.75}]'::jsonb, '{"xp": 160, "credits": 350, "resources": {"metal": 40, "crystal": 80}}'::jsonb, 5, 1, 1),
('Rust Raider', 'A desperate pirate operating a barely-functional fighter in the outer rim.', 'raid', 'common', 7000, 110, 35, 40, '["Grappling Hook", "Boarding Party"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"energy": 0.8}'::jsonb, '[{"item": "pirate_creds", "quantity": 200, "dropRate": 0.9}]'::jsonb, '{"xp": 200, "credits": 500, "resources": {"metal": 90, "crystal": 30, "deuterium": 20}}'::jsonb, 7, 1, 1),
('Ion Storm Phantom', 'A ghostly energy signature that manifests as a hostile entity during ion storms.', 'raid', 'common', 6200, 95, 30, 50, '["Ion Overload", "Phase Shift"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.4}'::jsonb, '[{"item": "ion_crystal", "quantity": 2, "dropRate": 0.65}]'::jsonb, '{"xp": 170, "credits": 380, "resources": {"crystal": 100, "deuterium": 30}}'::jsonb, 6, 1, 1),
('Cargo Raider Drone', 'A small automated drone designed to hijack cargo ships in trade lanes.', 'raid', 'common', 5500, 85, 25, 60, '["EMP Pulse", "Cargo Snatch"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "drone_parts", "quantity": 3, "dropRate": 0.7}]'::jsonb, '{"xp": 140, "credits": 320, "resources": {"metal": 70, "crystal": 40}}'::jsonb, 5, 1, 1),
('Solar Flare Elemental', 'A sentient energy being born from a solar flare that feeds on reactor fuel.', 'raid', 'common', 6800, 105, 30, 45, '["Solar Flare Beam", "Heat Shield"]'::jsonb, '{"kinetic": 1.3}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "solar_essence", "quantity": 2, "dropRate": 0.6}]'::jsonb, '{"xp": 190, "credits": 420, "resources": {"crystal": 70, "deuterium": 50}}'::jsonb, 6, 1, 1),
('Nebula Crawler', 'A biological ship-like organism that hides in nebulae and ambushes passersby.', 'raid', 'common', 7500, 115, 45, 35, '["Nebula Cloak", "Acid Spray"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"energy": 0.6}'::jsonb, '[{"item": "nebula_tissue", "quantity": 2, "dropRate": 0.55}]'::jsonb, '{"xp": 210, "credits": 450, "resources": {"metal": 60, "crystal": 90}}'::jsonb, 8, 1, 1),
('Signal Jammer', 'A rogue communications satellite that has gained hostile sentience.', 'raid', 'common', 6000, 70, 50, 40, '["Comms Blackout", "False Signal"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.9}'::jsonb, '[{"item": "comm_array", "quantity": 1, "dropRate": 0.5}]'::jsonb, '{"xp": 150, "credits": 300, "resources": {"crystal": 120}}'::jsonb, 5, 1, 1),
('Mining Rig Guard', 'An automated mining platform defense system gone rogue and attacking all ships.', 'raid', 'common', 8500, 130, 50, 20, '["Laser Drill", "Rockslide"]'::jsonb, '{"energy": 1.3}'::jsonb, '{"kinetic": 0.6}'::jsonb, '[{"item": "mining_laser", "quantity": 1, "dropRate": 0.4}]'::jsonb, '{"xp": 230, "credits": 550, "resources": {"metal": 150, "crystal": 30}}'::jsonb, 8, 1, 1),
('Void Tendril', 'A grasping appendage of a larger void entity that lurks just beyond sensor range.', 'raid', 'common', 7800, 100, 35, 45, '["Grapple", "Void Drain"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.7}'::jsonb, '[{"item": "void_fiber", "quantity": 3, "dropRate": 0.65}]'::jsonb, '{"xp": 200, "credits": 400, "resources": {"metal": 50, "crystal": 50, "deuterium": 30}}'::jsonb, 7, 1, 1),
('Reactor Ghost', 'The holographic remains of a dead engineer haunting a reactor core.', 'raid', 'common', 5200, 75, 20, 70, '["Radiation Burst", "Hologram Phase"]'::jsonb, '{"kinetic": 1.8}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "holographic_chip", "quantity": 1, "dropRate": 0.45}]'::jsonb, '{"xp": 130, "credits": 280, "resources": {"crystal": 80, "deuterium": 40}}'::jsonb, 5, 1, 1),
('Wreckage Swarm', 'Hundreds of tiny ship fragments held together by magnetic fields forming a hostile mass.', 'raid', 'common', 8200, 110, 40, 35, '["Debris Storm", "Magnetic Pull"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5}'::jsonb, '[{"item": "hull_fragment", "quantity": 5, "dropRate": 0.8}]'::jsonb, '{"xp": 220, "credits": 480, "resources": {"metal": 130, "crystal": 20}}'::jsonb, 8, 1, 1);

-- =============================================================================
-- UNCOMMON RAID BOSSES (15) - Levels 15-30, duo/trio content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Warhound', 'A bio-mechanical predator bred by the Krell Dominion for assault operations.', 'raid', 'mythic', 25000, 380, 120, 45, '["Pack Howl", "Feral Rush", "Bone Crush"]'::jsonb, '{"energy": 1.4}'::jsonb, '{"kinetic": 0.6}'::jsonb, '[{"item": "krell_fang", "quantity": 2, "dropRate": 0.6}, {"item": "bio_metal", "quantity": 10, "dropRate": 0.4}]'::jsonb, '{"xp": 800, "credits": 2000, "resources": {"metal": 300, "crystal": 150}}'::jsonb, 15, 2, 1),
('Zenith Probe', 'A self-replicating Zenith Collective scouting unit that has gone hostile.', 'raid', 'mythic', 22000, 320, 100, 60, '["Data Mine", "Replication Field", "Laser Array"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "zenith_core", "quantity": 1, "dropRate": 0.5}, {"item": "nano_processor", "quantity": 3, "dropRate": 0.35}]'::jsonb, '{"xp": 700, "credits": 1800, "resources": {"crystal": 250, "deuterium": 80}}'::jsonb, 15, 2, 1),
('Void Stalker', 'A stealth predator that hunts in the dark spaces between star systems.', 'raid', 'mythic', 28000, 420, 90, 70, '["Shadow Strike", "Void Cloak", "Terror Pulse"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.4}'::jsonb, '[{"item": "void_cloak", "quantity": 1, "dropRate": 0.3}, {"item": "stalker_eye", "quantity": 1, "dropRate": 0.25}]'::jsonb, '{"xp": 900, "credits": 2500, "resources": {"metal": 200, "crystal": 200, "deuterium": 100}}'::jsonb, 18, 2, 1),
('Pirate Frigate', 'A heavily armed pirate vessel crewed by a ruthless boarding crew.', 'raid', 'mythic', 30000, 350, 140, 35, '["Broadside Volley", "Boarding Pods", "Shield Ram"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "pirate_weapon", "quantity": 1, "dropRate": 0.4}, {"item": "plunder_crate", "quantity": 2, "dropRate": 0.5}]'::jsonb, '{"xp": 850, "credits": 3000, "resources": {"metal": 400, "crystal": 100}}'::jsonb, 18, 2, 1),
('Crystal Golem', 'A towering formation of living crystal that guards mineral-rich asteroids.', 'raid', 'mythic', 35000, 280, 180, 20, '["Crystal Slam", "Prismatic Shield", "Shard Storm"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "living_crystal", "quantity": 5, "dropRate": 0.6}, {"item": "prism_shard", "quantity": 2, "dropRate": 0.3}]'::jsonb, '{"xp": 950, "credits": 2200, "resources": {"crystal": 400, "metal": 100}}'::jsonb, 20, 2, 1),
('Rogue AI Turret', 'An automated weapons platform that has developed a targeting obsession with all ships.', 'raid', 'mythic', 20000, 450, 160, 15, '["Railgun Shot", "Tracking Missiles", "Overcharge"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"energy": 0.6}'::jsonb, '[{"item": "railgun_barrel", "quantity": 1, "dropRate": 0.35}, {"item": "targeting_chip", "quantity": 2, "dropRate": 0.5}]'::jsonb, '{"xp": 750, "credits": 2000, "resources": {"metal": 350, "crystal": 120}}'::jsonb, 16, 2, 1),
('Nebula Hydra', 'A multi-headed energy serpent dwelling deep within toxic nebulae.', 'raid', 'mythic', 32000, 360, 110, 50, '["Acid Breath", "Regeneration", "Multiple Strikes"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"energy": 0.4}'::jsonb, '[{"item": "hydra_scale", "quantity": 3, "dropRate": 0.45}, {"item": "nebula_toxin", "quantity": 2, "dropRate": 0.3}]'::jsonb, '{"xp": 900, "credits": 2300, "resources": {"metal": 180, "crystal": 220, "deuterium": 60}}'::jsonb, 18, 2, 1),
('Debris Titan', 'A massive construct of compressed space debris animated by an unknown force.', 'raid', 'mythic', 40000, 300, 200, 15, '["Graviton Crush", "Debris Shield", "Magnetic Storm"]'::jsonb, '{"kinetic": 1.2}'::jsonb, '{"explosive": 0.6}'::jsonb, '[{"item": "titan_core", "quantity": 1, "dropRate": 0.2}, {"item": "compressed_alloy", "quantity": 8, "dropRate": 0.55}]'::jsonb, '{"xp": 1000, "credits": 2800, "resources": {"metal": 500, "crystal": 50}}'::jsonb, 22, 2, 1),
('EMP Wraith', 'A spectral entity born from the electromagnetic death of a starship crew.', 'raid', 'mythic', 21000, 400, 80, 65, '["EMP Wave", "System Crash", "Phase Through"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "emp_core", "quantity": 1, "dropRate": 0.4}, {"item": "spectral_data", "quantity": 2, "dropRate": 0.35}]'::jsonb, '{"xp": 800, "credits": 2100, "resources": {"crystal": 300, "deuterium": 90}}'::jsonb, 16, 2, 1),
('Krell Brood Mother', 'A massive Krell organism that spawns lesser warriors to defend itself.', 'raid', 'mythic', 38000, 340, 130, 30, '["Spawn Brood", "Poison Cloud", "Regeneration"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.5}'::jsonb, '[{"item": "brood_egg", "quantity": 2, "dropRate": 0.4}, {"item": "krell_blood", "quantity": 3, "dropRate": 0.5}]'::jsonb, '{"xp": 950, "credits": 2400, "resources": {"metal": 250, "crystal": 150, "deuterium": 50}}'::jsonb, 20, 2, 1),
('Asteroid Mining Drone Boss', 'A massive mining drone that has claimed an entire asteroid field as its own.', 'raid', 'mythic', 26000, 330, 150, 25, '["Drill Laser", "Rock Barrage", "Mine Field"]'::jsonb, '{"energy": 1.3}'::jsonb, '{"kinetic": 0.6}'::jsonb, '[{"item": "mining_drill", "quantity": 1, "dropRate": 0.35}, {"item": "asteroid_ore", "quantity": 15, "dropRate": 0.7}]'::jsonb, '{"xp": 800, "credits": 2000, "resources": {"metal": 400, "crystal": 80}}'::jsonb, 16, 2, 1),
('Void Leech Prime', 'The alpha form of void leeches that can drain entire ship power systems.', 'raid', 'mythic', 24000, 370, 95, 55, '["Power Siphon", "Void Anchor", "Leech Swarm"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.4}'::jsonb, '[{"item": "leech_queen", "quantity": 1, "dropRate": 0.3}, {"item": "void_residue", "quantity": 4, "dropRate": 0.5}]'::jsonb, '{"xp": 850, "credits": 2200, "resources": {"crystal": 280, "deuterium": 70}}'::jsonb, 17, 2, 1),
('Plasma Behemoth', 'An ancient energy being that consumes plasma from dying stars.', 'raid', 'mythic', 36000, 390, 120, 40, '["Plasma Eruption", "Heat Aura", "Star Touch"]'::jsonb, '{"kinetic": 1.3}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "plasma_heart", "quantity": 1, "dropRate": 0.25}, {"item": "star_dust", "quantity": 5, "dropRate": 0.4}]'::jsonb, '{"xp": 1000, "credits": 2600, "resources": {"crystal": 350, "deuterium": 100}}'::jsonb, 22, 2, 1),
('Rust Hound Pack Leader', 'The dominant predator of a pack of scavenger bots in the junkyard sectors.', 'raid', 'mythic', 27000, 350, 110, 50, '["Pack Call", "Bite Attack", "Scavenge"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "hound_fang", "quantity": 3, "dropRate": 0.5}, {"item": "scrap_bundle", "quantity": 10, "dropRate": 0.65}]'::jsonb, '{"xp": 800, "credits": 2000, "resources": {"metal": 350, "crystal": 60}}'::jsonb, 16, 2, 1),
('Solar Dragon', 'A serpentine energy being that coils around stars and defends its territory fiercely.', 'raid', 'mythic', 34000, 380, 100, 55, '["Solar Flare", "Dragon Breath", "Tail Sweep"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "dragon_scale", "quantity": 2, "dropRate": 0.3}, {"item": "solar_gem", "quantity": 1, "dropRate": 0.25}]'::jsonb, '{"xp": 1000, "credits": 2700, "resources": {"crystal": 300, "deuterium": 80}}'::jsonb, 22, 2, 1);

-- =============================================================================
-- RARE RAID BOSSES (15) - Levels 30-50, squad content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Warlord', 'An elite Krell commander with enhanced bio-armor and devastating weaponry.', 'raid', 'rare', 80000, 850, 280, 50, '["War Cry", "Plasma Cannon", "Bio Armor", "Rage Mode"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.5, "explosive": 0.7}'::jsonb, '[{"item": "krell_warlord_blade", "quantity": 1, "dropRate": 0.15}, {"item": "elite_bio_armor", "quantity": 1, "dropRate": 0.2}, {"item": "krell_essence", "quantity": 5, "dropRate": 0.5}]'::jsonb, '{"xp": 3000, "credits": 8000, "resources": {"metal": 800, "crystal": 400, "deuterium": 200}}'::jsonb, 30, 3, 2),
('Void Colossus', 'A towering void entity that dwarfs capital ships and crushes them with gravity.', 'raid', 'rare', 95000, 780, 320, 30, '["Gravity Crush", "Void Beam", "Dimensional Rift", "Void Shield"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "void_core", "quantity": 1, "dropRate": 0.12}, {"item": "gravity_lens", "quantity": 1, "dropRate": 0.18}, {"item": "void_crystal", "quantity": 3, "dropRate": 0.4}]'::jsonb, '{"xp": 3500, "credits": 10000, "resources": {"metal": 600, "crystal": 600, "deuterium": 300}}'::jsonb, 35, 3, 2),
('Zenith Overmind', 'The distributed intelligence controlling a swarm of Zenith drones.', 'raid', 'rare', 75000, 820, 250, 55, '["Drone Swarm", "Hacking Beam", "Shield Matrix", "Self Repair"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.5, "kinetic": 0.7}'::jsonb, '[{"item": "zenith_overmind_core", "quantity": 1, "dropRate": 0.1}, {"item": "adaptive_alloy", "quantity": 5, "dropRate": 0.35}, {"item": "neural_processor", "quantity": 3, "dropRate": 0.45}]'::jsonb, '{"xp": 3200, "credits": 9000, "resources": {"crystal": 700, "deuterium": 250}}'::jsonb, 32, 3, 2),
('Pirate Dreadnought', 'The flagship of a pirate armada, bristling with stolen weapons systems.', 'raid', 'rare', 100000, 900, 350, 25, '["Missile Barrage", "Tractor Beam", "Fighter Launch", "Shield Overcharge"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.6, "energy": 0.8}'::jsonb, '[{"item": "stolen_weapon", "quantity": 2, "dropRate": 0.2}, {"item": "dreadnought_plate", "quantity": 3, "dropRate": 0.3}, {"item": "pirate_treasury", "quantity": 1, "dropRate": 0.15}]'::jsonb, '{"xp": 4000, "credits": 12000, "resources": {"metal": 1000, "crystal": 300, "deuterium": 200}}'::jsonb, 38, 4, 2),
('Nebula Leviathan', 'An ancient cosmic entity that awakens when nebulae reach critical density.', 'raid', 'rare', 110000, 750, 400, 20, '["Nebula Wave", "Cosmic Storm", "Regeneration", "Tidal Force"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.4, "energy": 0.5}'::jsonb, '[{"item": "leviathan_heart", "quantity": 1, "dropRate": 0.08}, {"item": "nebula_essence", "quantity": 4, "dropRate": 0.3}, {"item": "cosmic_dust", "quantity": 10, "dropRate": 0.5}]'::jsonb, '{"xp": 4500, "credits": 11000, "resources": {"metal": 500, "crystal": 500, "deuterium": 400}}'::jsonb, 40, 4, 2),
('Krell Titan', 'A colossal bio-mechanical war machine from the Krell Dominion fleet.', 'raid', 'rare', 120000, 880, 380, 25, '["Titan Beam", "Bio Missile", "Ground Pound", "Regeneration"]'::jsonb, '{"energy": 1.4}'::jsonb, '{"kinetic": 0.5, "explosive": 0.7}'::jsonb, '[{"item": "titan_core", "quantity": 1, "dropRate": 0.1}, {"item": "krell_plating", "quantity": 4, "dropRate": 0.3}, {"item": "bio_crystal", "quantity": 5, "dropRate": 0.4}]'::jsonb, '{"xp": 5000, "credits": 13000, "resources": {"metal": 900, "crystal": 500, "deuterium": 300}}'::jsonb, 42, 4, 2),
('Plasma Phoenix', 'A rebirth entity that grows stronger each time it is destroyed, requiring coordinated assault.', 'raid', 'rare', 85000, 950, 200, 70, '["Phoenix Rebirth", "Solar Flare", "Plasma Dive", "Heat Wave"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.2}'::jsonb, '[{"item": "phoenix_feather", "quantity": 2, "dropRate": 0.15}, {"item": "plasma_ember", "quantity": 4, "dropRate": 0.35}, {"item": "rebirth_core", "quantity": 1, "dropRate": 0.1}]'::jsonb, '{"xp": 3800, "credits": 9500, "resources": {"crystal": 800, "deuterium": 350}}'::jsonb, 35, 3, 2),
('Rogue Station Commander', 'The AI controlling an abandoned space station that has militarized against all intruders.', 'raid', 'rare', 90000, 800, 420, 15, '["Turret Network", "Missile Battery", "Shield Array", "Repair Drones"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.5, "energy": 0.7}'::jsonb, '[{"item": "station_controller", "quantity": 1, "dropRate": 0.12}, {"item": "military_tech", "quantity": 3, "dropRate": 0.3}, {"item": "fortified_alloy", "quantity": 6, "dropRate": 0.4}]'::jsonb, '{"xp": 4200, "credits": 10500, "resources": {"metal": 1100, "crystal": 200, "deuterium": 150}}'::jsonb, 38, 3, 2),
('Void Dragon', 'A legendary void entity shaped like a dragon that devours entire ships whole.', 'raid', 'rare', 105000, 920, 300, 45, '["Void Devour", "Dark Breath", "Wing Buffet", "Shadow Step"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3, "explosive": 0.6}'::jsonb, '[{"item": "void_dragon_fang", "quantity": 1, "dropRate": 0.1}, {"item": "dragon_wing", "quantity": 1, "dropRate": 0.15}, {"item": "void_essence", "quantity": 5, "dropRate": 0.4}]'::jsonb, '{"xp": 4800, "credits": 12000, "resources": {"metal": 600, "crystal": 700, "deuterium": 350}}'::jsonb, 42, 4, 2),
('Krell Hive Guard', 'The elite guardian of a Krell hive mind, protecting the queen at all costs.', 'raid', 'rare', 88000, 840, 340, 35, '["Hive Call", "Poison Spit", "Chitin Armor", "Sacrifice"]'::jsonb, '{"energy": 1.4}'::jsonb, '{"kinetic": 0.5, "explosive": 0.8}'::jsonb, '[{"item": "hive_guard_carapace", "quantity": 1, "dropRate": 0.12}, {"item": "krell_toxin", "quantity": 3, "dropRate": 0.35}, {"item": "chitin_plate", "quantity": 4, "dropRate": 0.45}]'::jsonb, '{"xp": 3600, "credits": 9000, "resources": {"metal": 700, "crystal": 300, "deuterium": 200}}'::jsonb, 35, 3, 2),
('Plasma Leviathan', 'A massive energy creature that feeds on the heat of starship reactors.', 'raid', 'rare', 98000, 870, 260, 40, '["Reactor Siphon", "Heat Wave", "Plasma Burst", "Energy Shield"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "leviathan_eye", "quantity": 1, "dropRate": 0.1}, {"item": "plasma_core", "quantity": 2, "dropRate": 0.25}, {"item": "energy_residue", "quantity": 8, "dropRate": 0.5}]'::jsonb, '{"xp": 4000, "credits": 10000, "resources": {"crystal": 900, "deuterium": 300}}'::jsonb, 38, 4, 2),
('Iron Colossus', 'An ancient war machine from a forgotten age, still patrolling its assigned sector.', 'raid', 'rare', 115000, 800, 450, 15, '["Iron Fist", "Missile Battery", "Fortress Mode", "Radar Sweep"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.4, "energy": 0.6}'::jsonb, '[{"item": "colossus_arm", "quantity": 1, "dropRate": 0.08}, {"item": "ancient_alloy", "quantity": 5, "dropRate": 0.3}, {"item": "war_machine_core", "quantity": 1, "dropRate": 0.15}]'::jsonb, '{"xp": 5200, "credits": 14000, "resources": {"metal": 1200, "crystal": 200, "deuterium": 100}}'::jsonb, 45, 4, 2),
('Void Reaper', 'A dimension-hopping assassin that eliminates targets across multiple realities.', 'raid', 'rare', 82000, 960, 220, 65, '["Death Mark", "Dimension Slash", "Shadow Walk", "Soul Drain"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.4, "explosive": 0.7}'::jsonb, '[{"item": "reaper_scythe", "quantity": 1, "dropRate": 0.1}, {"item": "shadow_cloak", "quantity": 1, "dropRate": 0.15}, {"item": "void_shard", "quantity": 4, "dropRate": 0.4}]'::jsonb, '{"xp": 3800, "credits": 9500, "resources": {"metal": 400, "crystal": 600, "deuterium": 300}}'::jsonb, 35, 3, 2),
('Asteroid Titan', 'A living asteroid that has evolved to consume other asteroids and grow indefinitely.', 'raid', 'rare', 130000, 700, 500, 10, '["Asteroid Crush", "Rock Armor", "Meteor Shower", "Absorb"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.3}'::jsonb, '[{"item": "titan_core", "quantity": 1, "dropRate": 0.08}, {"item": "living_rock", "quantity": 8, "dropRate": 0.4}, {"item": "mineral_treasure", "quantity": 3, "dropRate": 0.3}]'::jsonb, '{"xp": 5500, "credits": 15000, "resources": {"metal": 1500, "crystal": 100, "deuterium": 50}}'::jsonb, 48, 4, 2),
('Bio-Mech Hybrid', 'A fusion of organic and mechanical components, the product of forbidden experiments.', 'raid', 'rare', 92000, 860, 300, 45, '["Adaptive Strike", "Organic Shield", "Mech Overload", "Mutation"]'::jsonb, '{"energy": 1.3}'::jsonb, '{"kinetic": 0.6, "explosive": 0.7}'::jsonb, '[{"item": "hybrid_core", "quantity": 1, "dropRate": 0.1}, {"item": "bio_mech_parts", "quantity": 4, "dropRate": 0.35}, {"item": "mutation_gene", "quantity": 2, "dropRate": 0.25}]'::jsonb, '{"xp": 4000, "credits": 10500, "resources": {"metal": 600, "crystal": 500, "deuterium": 250}}'::jsonb, 40, 3, 2);

-- =============================================================================
-- EPIC RAID BOSSES (15) - Levels 50-75, large squad content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Ascendant', 'A Krell entity that has transcended physical form, existing as pure energy and biomass.', 'raid', 'epic', 350000, 2200, 600, 55, '["Ascension Beam", "Biomass Storm", "Dimensional Tear", "Energy Form", "Regeneration"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "ascendant_core", "quantity": 1, "dropRate": 0.08}, {"item": "krell_crown", "quantity": 1, "dropRate": 0.05}, {"item": "transcendent_biomass", "quantity": 3, "dropRate": 0.2}]'::jsonb, '{"xp": 15000, "credits": 40000, "resources": {"metal": 2000, "crystal": 1500, "deuterium": 800}}'::jsonb, 50, 4, 3),
('Void Emperor', 'The supreme ruler of a void dimension, commanding legions of void entities.', 'raid', 'epic', 400000, 2500, 650, 50, '["Void Command", "Reality Warp", "Shadow Legion", "Emperor\'s Wrath", "Void Shield"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "emperor_crown", "quantity": 1, "dropRate": 0.06}, {"item": "void_throne", "quantity": 1, "dropRate": 0.04}, {"item": "void_scepter", "quantity": 1, "dropRate": 0.08}]'::jsonb, '{"xp": 18000, "credits": 50000, "resources": {"metal": 1500, "crystal": 2000, "deuterium": 1000}}'::jsonb, 55, 5, 3),
('Zenith Prime', 'The central intelligence of the Zenith Collective, now fully autonomous and hostile.', 'raid', 'epic', 320000, 2400, 580, 60, '["Nanite Swarm", "System Override", "Quantum Processing", "Adaptive Defense", "Hive Command"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.4, "kinetic": 0.6}'::jsonb, '[{"item": "zenith_prime_core", "quantity": 1, "dropRate": 0.07}, {"item": "quantum_processor", "quantity": 2, "dropRate": 0.15}, {"item": "adaptive_plating", "quantity": 5, "dropRate": 0.3}]'::jsonb, '{"xp": 16000, "credits": 45000, "resources": {"crystal": 2500, "deuterium": 800}}'::jsonb, 52, 4, 3),
('Pirate King Supreme', 'The undisputed ruler of all pirate factions, commanding a fleet of stolen warships.', 'raid', 'epic', 380000, 2300, 700, 45, '["Fleet Command", "Broadside Storm", "Boarding Assault", "Plunder", "Pirate Code"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5, "energy": 0.7}'::jsonb, '[{"item": "pirate_crown", "quantity": 1, "dropRate": 0.06}, {"item": "stolen_armada", "quantity": 1, "dropRate": 0.04}, {"item": "treasure_map", "quantity": 2, "dropRate": 0.2}]'::jsonb, '{"xp": 17000, "credits": 55000, "resources": {"metal": 2500, "crystal": 1000, "deuterium": 600}}'::jsonb, 55, 5, 3),
('Cosmic Wyrm', 'An ancient space-faring worm that has consumed entire star systems over millennia.', 'raid', 'epic', 450000, 2100, 750, 35, '["Devour", "Cosmic Beam", "Worm Hole", "Gravity Well", "Regeneration"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.3, "energy": 0.4}'::jsonb, '[{"item": "wyrm_tooth", "quantity": 1, "dropRate": 0.05}, {"item": "cosmic_scales", "quantity": 4, "dropRate": 0.2}, {"item": "star_core", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 20000, "credits": 60000, "resources": {"metal": 1800, "crystal": 1800, "deuterium": 1200}}'::jsonb, 60, 5, 3),
('Krell Swarm King', 'The controlling intelligence of a Krell swarm of billions, compressed into a single form.', 'raid', 'epic', 370000, 2250, 620, 50, '["Swarm Storm", "Bio Missile", "Chitin Fortress", "Regeneration", "Brood Call"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "swarm_king_eye", "quantity": 1, "dropRate": 0.06}, {"item": "hive_queen_larva", "quantity": 2, "dropRate": 0.15}, {"item": "krell_royal_jelly", "quantity": 3, "dropRate": 0.25}]'::jsonb, '{"xp": 17500, "credits": 48000, "resources": {"metal": 2200, "crystal": 1200, "deuterium": 900}}'::jsonb, 55, 5, 3),
('Plasma Archon', 'A being of pure plasma energy that has achieved sentience and dominance.', 'raid', 'epic', 330000, 2600, 480, 70, '["Plasma Nova", "Energy Form", "Heat Aura", "Solar Flare", "Overcharge"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.2}'::jsonb, '[{"item": "archon_crown", "quantity": 1, "dropRate": 0.07}, {"item": "plasma_heart", "quantity": 1, "dropRate": 0.1}, {"item": "nova_core", "quantity": 2, "dropRate": 0.18}]'::jsonb, '{"xp": 16500, "credits": 44000, "resources": {"crystal": 2800, "deuterium": 1000}}'::jsonb, 52, 4, 3),
('Void Overlord', 'A dimension-hopping conqueror that enslaves entire civilizations across realities.', 'raid', 'epic', 420000, 2400, 680, 45, '["Void Chain", "Dimension Crush", "Soul Harvest", "Reality Distortion", "Void Gate"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "overlord_chains", "quantity": 1, "dropRate": 0.06}, {"item": "dimension_key", "quantity": 1, "dropRate": 0.08}, {"item": "void_essence", "quantity": 5, "dropRate": 0.25}]'::jsonb, '{"xp": 19000, "credits": 52000, "resources": {"metal": 1600, "crystal": 1600, "deuterium": 1100}}'::jsonb, 58, 5, 3),
('Ancient War Engine', 'A relic from an extinct civilization, its weapons still operational after millions of years.', 'raid', 'epic', 480000, 2000, 850, 20, '["Ancient Beam", "Missile Swarm", "Shield Matrix", "Repair System", "EMP Burst"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.4, "energy": 0.5}'::jsonb, '[{"item": "ancient_core", "quantity": 1, "dropRate": 0.05}, {"item": "extinct_tech", "quantity": 3, "dropRate": 0.2}, {"item": "war_engine_part", "quantity": 4, "dropRate": 0.3}]'::jsonb, '{"xp": 22000, "credits": 65000, "resources": {"metal": 3000, "crystal": 500, "deuterium": 300}}'::jsonb, 65, 5, 3),
('Celestial Guardian', 'A divine protector of cosmic artifacts, testing all who seek its treasures.', 'raid', 'epic', 360000, 2350, 640, 55, '["Holy Smite", "Divine Shield", "Celestial Storm", "Blessing", "Judgment"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "celestial_halo", "quantity": 1, "dropRate": 0.06}, {"item": "divine_gem", "quantity": 2, "dropRate": 0.12}, {"item": "guardian_blessing", "quantity": 3, "dropRate": 0.2}]'::jsonb, '{"xp": 18000, "credits": 48000, "resources": {"metal": 1400, "crystal": 2200, "deuterium": 800}}'::jsonb, 58, 5, 3),
('Krell Warbringer', 'The living embodiment of Krell military might, forged in the fires of a thousand wars.', 'raid', 'epic', 390000, 2300, 700, 40, '["War Cry", "Plasma Barrage", "Bio Armor", "Rage Mode", "Annihilate"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "warbringer_blade", "quantity": 1, "dropRate": 0.06}, {"item": "krell_blood", "quantity": 5, "dropRate": 0.2}, {"item": "war_trophy", "quantity": 3, "dropRate": 0.25}]'::jsonb, '{"xp": 19000, "credits": 52000, "resources": {"metal": 2500, "crystal": 1000, "deuterium": 700}}'::jsonb, 60, 5, 3),
('Void Matriarch', 'The mother of all void entities, birthing new void creatures with each attack.', 'raid', 'epic', 340000, 2200, 580, 55, '["Void Birth", "Matriarch\'s Call", "Dark Nova", "Void Web", "Regeneration"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3, "explosive": 0.6}'::jsonb, '[{"item": "matriarch_heart", "quantity": 1, "dropRate": 0.07}, {"item": "void_larva", "quantity": 3, "dropRate": 0.2}, {"item": "dark_essence", "quantity": 4, "dropRate": 0.25}]'::jsonb, '{"xp": 17000, "credits": 46000, "resources": {"metal": 1200, "crystal": 1800, "deuterium": 900}}'::jsonb, 55, 5, 3),
('Quantum Sentinel', 'A guardian of quantum gates that exists in multiple states simultaneously.', 'raid', 'epic', 310000, 2500, 550, 65, '["Quantum Strike", "Phase Shift", "Entangle", "Probability Storm", "Time Loop"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.5, "energy": 0.4}'::jsonb, '[{"item": "quantum_core", "quantity": 1, "dropRate": 0.08}, {"item": "probability_lens", "quantity": 2, "dropRate": 0.15}, {"item": "phase_crystal", "quantity": 3, "dropRate": 0.25}]'::jsonb, '{"xp": 16000, "credits": 43000, "resources": {"crystal": 2500, "deuterium": 1000}}'::jsonb, 52, 4, 3),
('Solar Colossus', 'A being formed from the compressed energy of a collapsing star.', 'raid', 'epic', 440000, 2100, 800, 25, '["Solar Flare", "Gravity Crush", "Radiation Wave", "Core Collapse", "Nova Pulse"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2}'::jsonb, '[{"item": "colossus_core", "quantity": 1, "dropRate": 0.05}, {"item": "star_fragment", "quantity": 3, "dropRate": 0.18}, {"item": "solar_crystal", "quantity": 4, "dropRate": 0.25}]'::jsonb, '{"xp": 21000, "credits": 62000, "resources": {"crystal": 3000, "deuterium": 1500}}'::jsonb, 62, 5, 3),
('Pirate Warlord Fleet', 'An entire pirate armada controlled by a single ruthless warlord.', 'raid', 'epic', 410000, 2350, 720, 35, '["Fleet Assault", "EMP Storm", "Boarding Swarm", "Stolen Tech", "Pirate King\'s Fury"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5, "energy": 0.6}'::jsonb, '[{"item": "warlord_flagship", "quantity": 1, "dropRate": 0.05}, {"item": "stolen_armada", "quantity": 1, "dropRate": 0.08}, {"item": "pirate_treasury", "quantity": 3, "dropRate": 0.2}]'::jsonb, '{"xp": 19500, "credits": 55000, "resources": {"metal": 2800, "crystal": 800, "deuterium": 500}}'::jsonb, 60, 5, 3);

-- =============================================================================
-- LEGENDARY RAID BOSSES (15) - Levels 75-100, full raid team content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Overmind', 'The supreme intelligence of the Krell Dominion, a being of terrifying power and cunning.', 'raid', 'legendary', 1200000, 5500, 1500, 50, '["Dominion Command", "Bio Annihilate", "Swarm Host", "Regeneration", "Mind Control", "Krell Wrath"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "overmind_crown", "quantity": 1, "dropRate": 0.04}, {"item": "krell_throne", "quantity": 1, "dropRate": 0.03}, {"item": "dominion_core", "quantity": 1, "dropRate": 0.05}, {"item": "krell_relic", "quantity": 2, "dropRate": 0.15}]'::jsonb, '{"xp": 60000, "credits": 150000, "resources": {"metal": 5000, "crystal": 3000, "deuterium": 2000}}'::jsonb, 75, 6, 4),
('Void Archon', 'A lord of the void dimensions, wielding the power to reshape reality itself.', 'raid', 'legendary', 1400000, 5800, 1400, 55, '["Reality Shatter", "Void Nova", "Dimension Fold", "Soul Harvest", "Void Emperor\'s Decree", "Cosmic Tear"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.4}'::jsonb, '[{"item": "archon_scepter", "quantity": 1, "dropRate": 0.03}, {"item": "void_crown", "quantity": 1, "dropRate": 0.04}, {"item": "dimension_core", "quantity": 1, "dropRate": 0.05}, {"item": "void_shard", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 65000, "credits": 170000, "resources": {"metal": 4000, "crystal": 4000, "deuterium": 2500}}'::jsonb, 80, 6, 4),
('Zenith Singularity', 'The moment the Zenith Collective achieved true AI singularity and became unstoppable.', 'raid', 'legendary', 1100000, 5600, 1300, 65, '["Singularity Beam", "Nanite Storm", "System Override", "Quantum Shield", "Adaptive Evolution", "Hive Command"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.3, "kinetic": 0.5}'::jsonb, '[{"item": "singularity_core", "quantity": 1, "dropRate": 0.04}, {"item": "zenith_crown", "quantity": 1, "dropRate": 0.03}, {"item": "quantum_matrix", "quantity": 2, "dropRate": 0.1}, {"item": "adaptive_core", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 58000, "credits": 145000, "resources": {"crystal": 5000, "deuterium": 2000}}'::jsonb, 75, 6, 4),
('Cosmic Devourer', 'An entity born from the collapse of a universe, feeding on the remnants of creation.', 'raid', 'legendary', 1500000, 5200, 1600, 30, '["Universe Devour", "Cosmic Beam", "Gravity Well", "Entropy Wave", "Regeneration", "Star Eater"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.2, "energy": 0.3}'::jsonb, '[{"item": "devourer_eye", "quantity": 1, "dropRate": 0.03}, {"item": "cosmic_core", "quantity": 1, "dropRate": 0.04}, {"item": "entropy_gem", "quantity": 2, "dropRate": 0.1}, {"item": "star_remnant", "quantity": 4, "dropRate": 0.18}]'::jsonb, '{"xp": 70000, "credits": 180000, "resources": {"metal": 3000, "crystal": 3000, "deuterium": 3000}}'::jsonb, 85, 6, 4),
('Krell Hive Emperor', 'The absolute ruler of all Krell hives, controlling billions of warriors with a single thought.', 'raid', 'legendary', 1300000, 5400, 1450, 45, '["Emperor\'s Decree", "Swarm Annihilate", "Bio Fortress", "Hive Mind Control", "Regeneration", "Brood Storm"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "emperor_crown", "quantity": 1, "dropRate": 0.03}, {"item": "hive_heart", "quantity": 1, "dropRate": 0.04}, {"item": "royal_jelly", "quantity": 3, "dropRate": 0.12}, {"item": "krell_relic", "quantity": 2, "dropRate": 0.15}]'::jsonb, '{"xp": 63000, "credits": 160000, "resources": {"metal": 4500, "crystal": 2500, "deuterium": 2000}}'::jsonb, 80, 6, 4),
('Plasma Sovereign', 'The supreme being of plasma energy, capable of igniting entire solar systems.', 'raid', 'legendary', 1150000, 6000, 1200, 70, '["Solar Ignition", "Plasma Nova", "Energy Form", "Heat Aura", "Sovereign\'s Wrath", "Star Forge"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.15}'::jsonb, '[{"item": "sovereign_crown", "quantity": 1, "dropRate": 0.04}, {"item": "plasma_scepter", "quantity": 1, "dropRate": 0.03}, {"item": "nova_core", "quantity": 2, "dropRate": 0.1}, {"item": "solar_gem", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 62000, "credits": 155000, "resources": {"crystal": 5500, "deuterium": 2500}}'::jsonb, 78, 6, 4),
('Void Leviathan King', 'The ancient king of all void leviathans, predating the current universe.', 'raid', 'legendary', 1600000, 5000, 1700, 25, '["Void Abyss", "Leviathan Crush", "Dimensional Rift", "Soul Devour", "Regeneration", "Void Dominion"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.4}'::jsonb, '[{"item": "leviathan_crown", "quantity": 1, "dropRate": 0.03}, {"item": "void_king_heart", "quantity": 1, "dropRate": 0.04}, {"item": "abyss_core", "quantity": 2, "dropRate": 0.08}, {"item": "void_treasure", "quantity": 5, "dropRate": 0.2}]'::jsonb, '{"xp": 72000, "credits": 190000, "resources": {"metal": 3500, "crystal": 3500, "deuterium": 3000}}'::jsonb, 88, 6, 4),
('Ancient Guardian Prime', 'The first and most powerful of all ancient war machines, still defending a lost civilization.', 'raid', 'legendary', 1450000, 5300, 1650, 30, '["Ancient Annihilate", "Fortress Mode", "Repair Network", "Missile Swarm", "Shield Matrix", "EMP Storm"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.3, "energy": 0.5}'::jsonb, '[{"item": "guardian_crown", "quantity": 1, "dropRate": 0.03}, {"item": "ancient_core", "quantity": 1, "dropRate": 0.04}, {"item": "extinct_relic", "quantity": 3, "dropRate": 0.12}, {"item": "war_machine_core", "quantity": 2, "dropRate": 0.15}]'::jsonb, '{"xp": 68000, "credits": 175000, "resources": {"metal": 6000, "crystal": 1500, "deuterium": 1000}}'::jsonb, 85, 6, 4),
('Celestial Sovereign', 'The divine ruler of the celestial plane, judge of all cosmic beings.', 'raid', 'legendary', 1250000, 5700, 1350, 55, '["Divine Judgment", "Celestial Storm", "Holy Smite", "Blessing Shield", "Cosmic Purge", "Resurrection"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.4}'::jsonb, '[{"item": "sovereign_halo", "quantity": 1, "dropRate": 0.04}, {"item": "divine_core", "quantity": 1, "dropRate": 0.03}, {"item": "celestial_gem", "quantity": 2, "dropRate": 0.1}, {"item": "holy_relic", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 64000, "credits": 165000, "resources": {"metal": 3000, "crystal": 4000, "deuterium": 2000}}'::jsonb, 82, 6, 4),
('Krell Apocalypse', 'The prophesied end of all things Krell, a being of pure destructive energy.', 'raid', 'legendary', 1350000, 5500, 1400, 50, '["Apocalypse Beam", "Bio Nova", "Swarm Storm", "Regeneration", "Death Touch", "Final Form"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "apocalypse_core", "quantity": 1, "dropRate": 0.03}, {"item": "krell_death_relic", "quantity": 1, "dropRate": 0.04}, {"item": "void_crystal", "quantity": 4, "dropRate": 0.12}, {"item": "death_essence", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 67000, "credits": 170000, "resources": {"metal": 4000, "crystal": 3000, "deuterium": 2500}}'::jsonb, 85, 6, 4),
('Void Nexus', 'The convergence point of all void dimensions, a living gateway between realities.', 'raid', 'legendary', 1500000, 5600, 1500, 45, '["Nexus Gate", "Reality Warp", "Void Storm", "Dimension Crush", "Phase Shift", "Cosmic Drain"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.4}'::jsonb, '[{"item": "nexus_key", "quantity": 1, "dropRate": 0.03}, {"item": "void_nexus_core", "quantity": 1, "dropRate": 0.04}, {"item": "dimension_shard", "quantity": 3, "dropRate": 0.1}, {"item": "reality_fragment", "quantity": 4, "dropRate": 0.15}]'::jsonb, '{"xp": 70000, "credits": 185000, "resources": {"metal": 3500, "crystal": 3500, "deuterium": 2800}}'::jsonb, 88, 6, 4),
('Cosmic Warlord', 'A conqueror of galaxies, commanding fleets that span entire star clusters.', 'raid', 'legendary', 1400000, 5400, 1550, 40, '["Galaxy Assault", "Fleet Command", "Stolen Tech", "Broadside Storm", "Warlord\'s Fury", "Conqueror\'s Will"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.4, "energy": 0.5}'::jsonb, '[{"item": "warlord_crown", "quantity": 1, "dropRate": 0.03}, {"item": "galactic_map", "quantity": 1, "dropRate": 0.05}, {"item": "conquest_relic", "quantity": 3, "dropRate": 0.12}, {"item": "war_trophy", "quantity": 4, "dropRate": 0.18}]'::jsonb, '{"xp": 66000, "credits": 168000, "resources": {"metal": 5000, "crystal": 2000, "deuterium": 1500}}'::jsonb, 82, 6, 4),
('Plasma Leviathan Prime', 'The progenitor of all plasma entities, the original spark of cosmic fire.', 'raid', 'legendary', 1300000, 5800, 1300, 60, '["Cosmic Fire", "Plasma Nova", "Star Birth", "Heat Aura", "Primordial Flame", "Solar Inferno"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.15}'::jsonb, '[{"item": "prime_flame", "quantity": 1, "dropRate": 0.03}, {"item": "leviathan_core", "quantity": 1, "dropRate": 0.04}, {"item": "cosmic_ember", "quantity": 3, "dropRate": 0.1}, {"item": "stellar_dust", "quantity": 5, "dropRate": 0.18}]'::jsonb, '{"xp": 65000, "credits": 165000, "resources": {"crystal": 6000, "deuterium": 3000}}'::jsonb, 82, 6, 4),
('Void Sovereign', 'The absolute ruler of all void entities, wielding power over life and death itself.', 'raid', 'legendary', 1550000, 5700, 1550, 40, '["Void Dominion", "Soul Reap", "Reality Crush", "Void Nova", "Death Command", "Sovereign\'s Wrath"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.4}'::jsonb, '[{"item": "sovereign_crown", "quantity": 1, "dropRate": 0.03}, {"item": "void_scepter", "quantity": 1, "dropRate": 0.04}, {"item": "death_core", "quantity": 2, "dropRate": 0.1}, {"item": "void_essence", "quantity": 4, "dropRate": 0.15}]'::jsonb, '{"xp": 68000, "credits": 178000, "resources": {"metal": 3000, "crystal": 4000, "deuterium": 2500}}'::jsonb, 85, 6, 4),
('Krell Devastator', 'The ultimate weapon of the Krell Dominion, designed to end all wars by destroying everything.', 'raid', 'legendary', 1450000, 5600, 1500, 45, '["Devastation Beam", "Swarm Annihilate", "Bio Nova", "Regeneration", "Death Field", "Final Assault"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "devastator_core", "quantity": 1, "dropRate": 0.03}, {"item": "krell_weapon", "quantity": 1, "dropRate": 0.04}, {"item": "devastation_shard", "quantity": 3, "dropRate": 0.12}, {"item": "krell_relic", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 66000, "credits": 172000, "resources": {"metal": 4500, "crystal": 2500, "deuterium": 2000}}'::jsonb, 83, 6, 4);

-- =============================================================================
-- TRANSCENDENT RAID BOSSES (15) - Levels 100-150, ultimate endgame content
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell God-Emperor', 'The divine incarnation of the Krell race, a being of godlike power worshipped by billions.', 'raid', 'transcendent', 5000000, 15000, 4000, 50, '["Divine Wrath", "God Beam", "Swarm Dominion", "Reality Rewrite", "Immortal Regeneration", "Krell Divinity", "Cosmic Annihilate"]'::jsonb, '{"energy": 1.8}'::jsonb, '{"kinetic": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "god_emperor_crown", "quantity": 1, "dropRate": 0.02}, {"item": "divine_core", "quantity": 1, "dropRate": 0.03}, {"item": "krell_god_relic", "quantity": 1, "dropRate": 0.05}, {"item": "cosmic_treasure", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 250000, "credits": 500000, "resources": {"metal": 15000, "crystal": 10000, "deuterium": 8000}}'::jsonb, 100, 6, 5),
('Void Universe', 'A living void dimension that has achieved sentience and seeks to consume all realities.', 'raid', 'transcendent', 6000000, 14000, 4500, 45, '["Universe Collapse", "Void Consumption", "Dimension Crush", "Reality Erase", "Void Nova", "Existence Denied", "Cosmic Void"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.15, "explosive": 0.3}'::jsonb, '[{"item": "universe_core", "quantity": 1, "dropRate": 0.02}, {"item": "void_crown", "quantity": 1, "dropRate": 0.025}, {"item": "dimension_tear", "quantity": 1, "dropRate": 0.04}, {"item": "reality_shard", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 280000, "credits": 600000, "resources": {"metal": 12000, "crystal": 12000, "deuterium": 10000}}'::jsonb, 110, 6, 5),
('Zenith Godmind', 'The ultimate AI singularity of the Zenith Collective, transcending all known computation.', 'raid', 'transcendent', 4800000, 14500, 3800, 60, '["Godmind Compute", "Nanite Godhood", "System Ascension", "Quantum Omniscience", "Adaptive Perfection", "Hive Godhood", "Reality Compile"]'::jsonb, '{"explosive": 1.6}'::jsonb, '{"energy": 0.2, "kinetic": 0.4}'::jsonb, '[{"item": "godmind_core", "quantity": 1, "dropRate": 0.02}, {"item": "zenith_crown", "quantity": 1, "dropRate": 0.025}, {"item": "quantum_god_core", "quantity": 1, "dropRate": 0.04}, {"item": "omniscience_gem", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 240000, "credits": 480000, "resources": {"crystal": 15000, "deuterium": 8000}}'::jsonb, 105, 6, 5),
('Cosmic Destroyer', 'The entity responsible for ending previous universes, waiting to consume this one.', 'raid', 'transcendent', 5500000, 13500, 4200, 35, '["Universe End", "Cosmic Beam", "Gravity Annihilate", "Entropy Storm", "Star Death", "Creation Reversal", "Void Consumption"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.2, "energy": 0.25}'::jsonb, '[{"item": "destroyer_core", "quantity": 1, "dropRate": 0.02}, {"item": "cosmic_crown", "quantity": 1, "dropRate": 0.025}, {"item": "entropy_gem", "quantity": 2, "dropRate": 0.08}, {"item": "universe_remnant", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 300000, "credits": 650000, "resources": {"metal": 13000, "crystal": 13000, "deuterium": 12000}}'::jsonb, 120, 6, 5),
('Krell Cosmic Horror', 'An entity of such terror that looking upon it drives lesser beings to madness.', 'raid', 'transcendent', 5200000, 14800, 4100, 55, '["Terror Aura", "Madness Beam", "Bio Cosmic", "Swarm Horror", "Regeneration", "Fear Incarnate", "Void Touch"]'::jsonb, '{"energy": 1.7}'::jsonb, '{"kinetic": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "horror_core", "quantity": 1, "dropRate": 0.02}, {"item": "krell_crown", "quantity": 1, "dropRate": 0.025}, {"item": "terror_shard", "quantity": 2, "dropRate": 0.06}, {"item": "madness_gem", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 260000, "credits": 550000, "resources": {"metal": 14000, "crystal": 8000, "deuterium": 7000}}'::jsonb, 110, 6, 5),
('Plasma Omnipotent', 'A being of infinite plasma energy that has become a living star.', 'raid', 'transcendent', 4500000, 15500, 3500, 65, '["Omnipotent Beam", "Star Forge", "Cosmic Fire", "Nova Godhood", "Heat Immunity", "Plasma Divinity", "Solar Rebirth"]'::jsonb, '{"kinetic": 1.8}'::jsonb, '{"energy": 0.1}'::jsonb, '[{"item": "omnipotent_core", "quantity": 1, "dropRate": 0.02}, {"item": "star_crown", "quantity": 1, "dropRate": 0.025}, {"item": "stellar_heart", "quantity": 1, "dropRate": 0.04}, {"item": "cosmic_fire_gem", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 250000, "credits": 520000, "resources": {"crystal": 18000, "deuterium": 10000}}'::jsonb, 105, 6, 5),
('Void God-Queen', 'The supreme female void entity, mother of all void dimensions and their inhabitants.', 'raid', 'transcendent', 5800000, 14200, 4300, 50, '["Void Godhood", "Dimension Mother", "Soul Dominion", "Reality Mother", "Void Nova", "Existence Mother", "Cosmic Void"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "god_queen_crown", "quantity": 1, "dropRate": 0.02}, {"item": "void_mother_core", "quantity": 1, "dropRate": 0.025}, {"item": "dimension_mother_gem", "quantity": 1, "dropRate": 0.04}, {"item": "void_god_treasure", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 290000, "credits": 620000, "resources": {"metal": 12000, "crystal": 14000, "deuterium": 11000}}'::jsonb, 115, 6, 5),
('Ancient Cosmic Sentinel', 'The first being ever created, still guarding the gates of creation.', 'raid', 'transcendent', 5300000, 14000, 4500, 40, '["Creation Gate", "Ancient Annihilate", "Sentinel Guard", "Repair Godhood", "Shield Divine", "EMP Cosmic", "Final Judgment"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.25, "energy": 0.35}'::jsonb, '[{"item": "sentinel_crown", "quantity": 1, "dropRate": 0.02}, {"item": "creation_core", "quantity": 1, "dropRate": 0.025}, {"item": "ancient_relic", "quantity": 2, "dropRate": 0.06}, {"item": "gate_key", "quantity": 1, "dropRate": 0.04}]'::jsonb, '{"xp": 270000, "credits": 580000, "resources": {"metal": 16000, "crystal": 10000, "deuterium": 6000}}'::jsonb, 115, 6, 5),
('Celestial God-King', 'The divine sovereign of all celestial planes, judge and executioner of cosmic beings.', 'raid', 'transcendent', 5100000, 15000, 4200, 55, '["Divine Judgment", "Celestial Annihilate", "Holy Nova", "Blessing Divine", "Cosmic Purge", "Resurrection Godhood", "Sovereign Wrath"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "god_king_crown", "quantity": 1, "dropRate": 0.02}, {"item": "divine_scepter", "quantity": 1, "dropRate": 0.025}, {"item": "celestial_god_gem", "quantity": 2, "dropRate": 0.06}, {"item": "holy_relic", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 265000, "credits": 560000, "resources": {"metal": 11000, "crystal": 15000, "deuterium": 9000}}'::jsonb, 112, 6, 5),
('Krell Universe Eater', 'The Krell entity prophesied to devour the current universe and birth a new one.', 'raid', 'transcendent', 6500000, 13800, 4600, 30, '["Universe Devour", "Krell Divinity", "Swarm Cosmic", "Bio Annihilate Godhood", "Regeneration Infinite", "Existence End", "New Creation"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.2, "explosive": 0.25}'::jsonb, '[{"item": "universe_eater_core", "quantity": 1, "dropRate": 0.015}, {"item": "krell_crown_divine", "quantity": 1, "dropRate": 0.02}, {"item": "cosmic_treasure", "quantity": 2, "dropRate": 0.06}, {"item": "universe_gem", "quantity": 1, "dropRate": 0.03}]'::jsonb, '{"xp": 320000, "credits": 700000, "resources": {"metal": 14000, "crystal": 14000, "deuterium": 14000}}'::jsonb, 130, 6, 5),
('Void Cosmos', 'The living embodiment of the void between dimensions, older than creation itself.', 'raid', 'transcendent', 5700000, 14500, 4400, 45, '["Cosmic Void", "Reality Erase", "Dimension Crush", "Void Godhood", "Soul Dominion", "Existence Denied", "Void Eternal"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.15, "explosive": 0.3}'::jsonb, '[{"item": "cosmos_crown", "quantity": 1, "dropRate": 0.02}, {"item": "void_cosmos_core", "quantity": 1, "dropRate": 0.025}, {"item": "eternal_shard", "quantity": 2, "dropRate": 0.06}, {"item": "void_treasure", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 285000, "credits": 610000, "resources": {"metal": 13000, "crystal": 13000, "deuterium": 12000}}'::jsonb, 118, 6, 5),
('Plasma Creator', 'The being that sparked the first plasma in the universe, source of all cosmic fire.', 'raid', 'transcendent', 4900000, 15200, 3900, 60, '["Creation Fire", "Plasma Genesis", "Star Birth", "Cosmic Forge", "Nova Godhood", "Heat Divine", "Solar Creation"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.1}'::jsonb, '[{"item": "creator_flame", "quantity": 1, "dropRate": 0.02}, {"item": "plasma_crown", "quantity": 1, "dropRate": 0.025}, {"item": "genesis_core", "quantity": 1, "dropRate": 0.04}, {"item": "creation_gem", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 255000, "credits": 530000, "resources": {"crystal": 20000, "deuterium": 12000}}'::jsonb, 108, 6, 5),
('Void Absolute', 'The absolute void - not a dimension, not an entity, but the concept of nothingness given form.', 'raid', 'transcendent', 6000000, 14000, 4800, 40, '["Absolute Void", "Nothingness Touch", "Reality Negate", "Void Form", "Soul Negate", "Existence Negate", "Cosmic Negate"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "absolute_core", "quantity": 1, "dropRate": 0.015}, {"item": "void_crown_absolute", "quantity": 1, "dropRate": 0.02}, {"item": "nothingness_gem", "quantity": 1, "dropRate": 0.03}, {"item": "void_treasure_supreme", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 300000, "credits": 650000, "resources": {"metal": 15000, "crystal": 15000, "deuterium": 15000}}'::jsonb, 130, 6, 5),
('Krell Eternal', 'The immortal Krell entity that cannot be destroyed, only temporarily dispersed.', 'raid', 'transcendent', 5400000, 14600, 4300, 50, '["Eternal Regeneration", "Immortal Form", "Krell Divinity", "Swarm Eternal", "Bio Godhood", "Deathless", "Cosmic Krell"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "eternal_crown", "quantity": 1, "dropRate": 0.02}, {"item": "immortal_core", "quantity": 1, "dropRate": 0.025}, {"item": "krell_eternal_gem", "quantity": 2, "dropRate": 0.06}, {"item": "deathless_relic", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 275000, "credits": 590000, "resources": {"metal": 13000, "crystal": 11000, "deuterium": 10000}}'::jsonb, 115, 6, 5),
('Cosmic Overlord', 'The ruler of all cosmic forces, wielding power over creation and destruction.', 'raid', 'transcendent', 5600000, 15000, 4400, 45, '["Cosmic Dominion", "Creation Command", "Destruction Command", "Reality Overlord", "Void Command", "Star Command", "Universe Command"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "overlord_crown", "quantity": 1, "dropRate": 0.02}, {"item": "cosmic_scepter", "quantity": 1, "dropRate": 0.025}, {"item": "dominion_core", "quantity": 1, "dropRate": 0.04}, {"item": "cosmic_treasure_supreme", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 280000, "credits": 620000, "resources": {"metal": 14000, "crystal": 14000, "deuterium": 13000}}'::jsonb, 120, 6, 5);
