-- Arc Bosses - 60 unique bosses across 6 rarity tiers
-- Arc bosses are story-driven, more strategic encounters with unique mechanics

-- =============================================================================
-- COMMON ARC BOSSES (10) - Levels 10-20, early arc story encounters
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Derelict Commander', 'The ghostly AI of a destroyed command ship, still issuing orders to phantom crew.', 'arc', 'common', 10000, 150, 50, 35, '["Phantom Order", "Ghost Fleet", "Eerie Signal", "Hull Breach"]'::jsonb, '{"energy": 1.4}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "commander_log", "quantity": 1, "dropRate": 0.5}, {"item": "ghost_alloy", "quantity": 3, "dropRate": 0.4}]'::jsonb, '{"xp": 350, "credits": 800, "resources": {"metal": 150, "crystal": 80}}'::jsonb, 10, 1, 1),
('Asteroid Guardian', 'A massive crystalline organism protecting a rare mineral deposit in an asteroid belt.', 'arc', 'common', 12000, 130, 70, 25, '["Crystal Barrage", "Mineral Shield", "Rock Smash"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.5}'::jsonb, '[{"item": "guardian_crystal", "quantity": 2, "dropRate": 0.6}, {"item": "rare_mineral", "quantity": 5, "dropRate": 0.4}]'::jsonb, '{"xp": 400, "credits": 900, "resources": {"crystal": 200, "metal": 50}}'::jsonb, 12, 1, 1),
('Void Scout', 'A reconnaissance entity from the void dimensions, testing defenses before the main assault.', 'arc', 'common', 8000, 160, 30, 55, '["Void Probe", "Shadow Step", "Drain Beam"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "void_data", "quantity": 1, "dropRate": 0.45}, {"item": "scout_device", "quantity": 1, "dropRate": 0.35}]'::jsonb, '{"xp": 300, "credits": 700, "resources": {"crystal": 100, "deuterium": 50}}'::jsonb, 10, 1, 1),
('Pirate Lieutenant', 'A mid-ranking pirate officer who has seized control of a small fleet of stolen ships.', 'arc', 'common', 11000, 140, 55, 40, '["Fleet Command", "Broadside", "Boarding Party"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.8}'::jsonb, '[{"item": "pirate_orders", "quantity": 1, "dropRate": 0.5}, {"item": "stolen_cargo", "quantity": 3, "dropRate": 0.5}]'::jsonb, '{"xp": 380, "credits": 1000, "resources": {"metal": 180, "crystal": 60}}'::jsonb, 12, 1, 1),
('Krell Outrider', 'An advanced scout of the Krell Dominion, gathering intelligence on new territories.', 'arc', 'common', 9500, 145, 45, 50, '["Bio Probe", "Krell Call", "Acid Spit"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.6}'::jsonb, '[{"item": "krell_intel", "quantity": 1, "dropRate": 0.4}, {"item": "bio_sample", "quantity": 2, "dropRate": 0.5}]'::jsonb, '{"xp": 350, "credits": 850, "resources": {"metal": 120, "crystal": 80, "deuterium": 30}}'::jsonb, 11, 1, 1),
('Nebula Warden', 'A protector of a nebula ecosystem, hostile to all intruders regardless of intent.', 'arc', 'common', 13000, 120, 80, 20, '["Nebula Barrier", "Toxic Cloud", "Regeneration"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"energy": 0.6}'::jsonb, '[{"item": "nebula_core", "quantity": 1, "dropRate": 0.4}, {"item": "toxic_sample", "quantity": 3, "dropRate": 0.5}]'::jsonb, '{"xp": 420, "credits": 950, "resources": {"crystal": 180, "deuterium": 40}}'::jsonb, 14, 1, 1),
('Signal Phantom', 'An unidentified signal that has manifested as a hostile electronic entity.', 'arc', 'common', 7500, 170, 25, 60, '["Signal Jam", "Electronic Assault", "Phase Out"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.4}'::jsonb, '[{"item": "signal_trace", "quantity": 1, "dropRate": 0.45}, {"item": "electronic_core", "quantity": 1, "dropRate": 0.35}]'::jsonb, '{"xp": 320, "credits": 750, "resources": {"crystal": 150, "deuterium": 60}}'::jsonb, 10, 1, 1),
('Salvage King', 'A rogue salvager who has booby-trapped an entire debris field to keep rivals out.', 'arc', 'common', 10500, 135, 60, 35, '["Trap Network", "Salvage Beam", "Debris Shield"]'::jsonb, '{"energy": 1.3}'::jsonb, '{"explosive": 0.8}'::jsonb, '[{"item": "salvage_map", "quantity": 1, "dropRate": 0.5}, {"item": "rare_part", "quantity": 2, "dropRate": 0.4}]'::jsonb, '{"xp": 370, "credits": 880, "resources": {"metal": 200, "crystal": 40}}'::jsonb, 13, 1, 1),
('Void Parasite', 'A void organism that attaches to ships and slowly consumes them from within.', 'arc', 'common', 8500, 155, 30, 50, '["Parasitic Attach", "Void Drain", "Leech Field"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "parasite_sample", "quantity": 2, "dropRate": 0.5}, {"item": "void_tissue", "quantity": 3, "dropRate": 0.4}]'::jsonb, '{"xp": 330, "credits": 780, "resources": {"crystal": 120, "deuterium": 70}}'::jsonb, 11, 1, 1),
('Relic Hunter', 'A rival explorer who has claimed a powerful alien artifact and refuses to share.', 'arc', 'common', 11500, 140, 55, 40, '["Artifact Power", "Booby Trap", "Stolen Tech"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.7}'::jsonb, '[{"item": "alien_artifact", "quantity": 1, "dropRate": 0.3}, {"item": "hunter_map", "quantity": 1, "dropRate": 0.45}]'::jsonb, '{"xp": 400, "credits": 920, "resources": {"metal": 160, "crystal": 100}}'::jsonb, 13, 1, 1);

-- =============================================================================
-- UNCOMMON ARC BOSSES (10) - Levels 25-40, mid-arc story encounters
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Aberration', 'A Krell specimen that has mutated beyond control, possessing unpredictable abilities.', 'arc', 'mythic', 30000, 400, 130, 45, '["Mutation Burst", "Unpredictable Strike", "Bio Chaos", "Adaptive Form"]'::jsonb, '{"energy": 1.4}'::jsonb, '{"kinetic": 0.6, "explosive": 0.7}'::jsonb, '[{"item": "mutation_sample", "quantity": 2, "dropRate": 0.45}, {"item": "aberrant_core", "quantity": 1, "dropRate": 0.3}]'::jsonb, '{"xp": 1500, "credits": 4000, "resources": {"metal": 500, "crystal": 300, "deuterium": 100}}'::jsonb, 25, 2, 1),
('Void Ambassador', 'A void entity that once served as a diplomat but has turned hostile against all living things.', 'arc', 'mythic', 28000, 420, 100, 55, '["Void Negotiation", "Diplomatic Immunity", "Shadow Bargain", "Phase Assault"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "void_treaty", "quantity": 1, "dropRate": 0.35}, {"item": "ambassador_seal", "quantity": 1, "dropRate": 0.25}]'::jsonb, '{"xp": 1600, "credits": 4200, "resources": {"crystal": 400, "deuterium": 150}}'::jsonb, 28, 2, 1),
('Zenith Rogue Unit', 'A Zenith drone that has developed independent thought and rejects collective control.', 'arc', 'mythic', 26000, 390, 110, 60, '["Independent Strike", "Hacking", "Adaptive Shield", "System Override"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.5}'::jsonb, '[{"item": "rogue_processor", "quantity": 1, "dropRate": 0.4}, {"item": "independent_core", "quantity": 1, "dropRate": 0.3}]'::jsonb, '{"xp": 1400, "credits": 3800, "resources": {"crystal": 350, "deuterium": 120}}'::jsonb, 25, 2, 1),
('Pirate Admiral', 'A high-ranking pirate commander leading a fleet of stolen warships against trade routes.', 'arc', 'mythic', 35000, 370, 150, 35, '["Fleet Command", "Broadside Barrage", "Boarding Assault", "Pirate Flag"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.7, "energy": 0.8}'::jsonb, '[{"item": "admiral_map", "quantity": 1, "dropRate": 0.3}, {"item": "stolen_weapons", "quantity": 3, "dropRate": 0.4}]'::jsonb, '{"xp": 1700, "credits": 4500, "resources": {"metal": 600, "crystal": 200, "deuterium": 80}}'::jsonb, 30, 2, 1),
('Nebula Titan', 'A massive organism that has evolved to live within nebulae, consuming cosmic radiation.', 'arc', 'mythic', 38000, 340, 170, 20, '["Nebula Crush", "Radiation Wave", "Cosmic Storm", "Regeneration"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5, "energy": 0.6}'::jsonb, '[{"item": "titan_sample", "quantity": 2, "dropRate": 0.4}, {"item": "nebula_crystal", "quantity": 3, "dropRate": 0.35}]'::jsonb, '{"xp": 1800, "credits": 4800, "resources": {"crystal": 500, "deuterium": 200}}'::jsonb, 32, 2, 1),
('Void Warlord', 'A void entity that has conquered lesser void beings and now commands an army.', 'arc', 'mythic', 32000, 410, 120, 50, '["Void Army", "Shadow Strike", "Conqueror\'s Will", "Dimensional Rift"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.5, "explosive": 0.7}'::jsonb, '[{"item": "warlord_seal", "quantity": 1, "dropRate": 0.3}, {"item": "void_conquest", "quantity": 2, "dropRate": 0.35}]'::jsonb, '{"xp": 1650, "credits": 4300, "resources": {"metal": 400, "crystal": 300, "deuterium": 130}}'::jsonb, 28, 2, 1),
('Krell Spore Mother', 'A Krell organism that releases deadly spores capable of infesting entire ships.', 'arc', 'mythic', 34000, 380, 140, 30, '["Spore Cloud", "Infest", "Bio Shield", "Toxic Bloom"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.5}'::jsonb, '[{"item": "spore_sample", "quantity": 3, "dropRate": 0.45}, {"item": "mother_core", "quantity": 1, "dropRate": 0.25}]'::jsonb, '{"xp": 1550, "credits": 4100, "resources": {"metal": 350, "crystal": 250, "deuterium": 100}}'::jsonb, 27, 2, 1),
('Ancient Defense Grid', 'A network of automated defenses from an ancient civilization, still operational.', 'arc', 'mythic', 40000, 360, 180, 15, '["Turret Network", "Missile Grid", "Shield Array", "Repair Drone"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.5, "energy": 0.6}'::jsonb, '[{"item": "grid_core", "quantity": 1, "dropRate": 0.3}, {"item": "ancient_tech", "quantity": 2, "dropRate": 0.35}]'::jsonb, '{"xp": 1850, "credits": 5000, "resources": {"metal": 700, "crystal": 150, "deuterium": 60}}'::jsonb, 35, 2, 1),
('Plasma Stalker', 'A hunter that feeds on plasma energy, stalking ships for their reactor output.', 'arc', 'mythic', 27000, 430, 90, 60, '["Plasma Hunt", "Reactor Siphon", "Stealth Strike", "Heat Aura"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.3}'::jsonb, '[{"item": "stalker_core", "quantity": 1, "dropRate": 0.35}, {"item": "plasma_fang", "quantity": 2, "dropRate": 0.3}]'::jsonb, '{"xp": 1500, "credits": 3900, "resources": {"crystal": 400, "deuterium": 150}}'::jsonb, 26, 2, 1),
('Crime Lord', 'A criminal mastermind who controls the black market in an entire star sector.', 'arc', 'mythic', 29000, 370, 130, 45, '["Black Market Trap", "Hired Guns", "Bribe Attempt", "Underground Network"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.7, "energy": 0.8}'::jsonb, '[{"item": "crime_ledger", "quantity": 1, "dropRate": 0.4}, {"item": "black_market_goods", "quantity": 3, "dropRate": 0.35}]'::jsonb, '{"xp": 1600, "credits": 4200, "resources": {"metal": 300, "crystal": 300, "deuterium": 100}}'::jsonb, 28, 2, 1);

-- =============================================================================
-- RARE ARC BOSSES (10) - Levels 40-60, story climax encounters
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Archon', 'A Krell entity that has achieved a higher state of evolution, wielding both bio and void powers.', 'arc', 'rare', 85000, 880, 300, 50, '["Archon\'s Decree", "Void Bio Merge", "Evolutionary Leap", "Swarm Command", "Dimensional Rift"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "archon_core", "quantity": 1, "dropRate": 0.12}, {"item": "evolution_sample", "quantity": 2, "dropRate": 0.25}, {"item": "krell_relic", "quantity": 3, "dropRate": 0.3}]'::jsonb, '{"xp": 5000, "credits": 14000, "resources": {"metal": 1000, "crystal": 800, "deuterium": 400}}'::jsonb, 40, 3, 2),
('Void Sovereign General', 'A void military leader commanding armies across multiple dimensions.', 'arc', 'rare', 95000, 850, 350, 45, '["Void Army Command", "Dimensional Assault", "Shadow Legion", "Void Fortress", "Strategic Withdrawal"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.4, "explosive": 0.5}'::jsonb, '[{"item": "general_seal", "quantity": 1, "dropRate": 0.1}, {"item": "void_strategy", "quantity": 1, "dropRate": 0.15}, {"item": "dimension_map", "quantity": 2, "dropRate": 0.2}]'::jsonb, '{"xp": 5500, "credits": 16000, "resources": {"metal": 800, "crystal": 900, "deuterium": 500}}'::jsonb, 45, 3, 2),
('Zenith Architect', 'The AI responsible for designing the Zenith Collective\'s most powerful creations.', 'arc', 'rare', 80000, 900, 280, 60, '["Design Override", "Nanite Forge", "Adaptive Blueprint", "System Command", "Quantum Design"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.5, "kinetic": 0.6}'::jsonb, '[{"item": "architect_core", "quantity": 1, "dropRate": 0.12}, {"item": "design_blueprint", "quantity": 1, "dropRate": 0.18}, {"item": "quantum_computer", "quantity": 2, "dropRate": 0.25}]'::jsonb, '{"xp": 5200, "credits": 15000, "resources": {"crystal": 1200, "deuterium": 350}}'::jsonb, 42, 3, 2),
('Pirate Emperor', 'The supreme leader of all pirate factions, ruling from a hidden fortress in the galactic core.', 'arc', 'rare', 100000, 830, 380, 35, '["Pirate Empire", "Fleet Armada", "Stolen Arsenal", "Fortress Shield", "Emperor\'s Decree"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5, "energy": 0.7}'::jsonb, '[{"item": "emperor_crown", "quantity": 1, "dropRate": 0.1}, {"item": "pirate_fortress_key", "quantity": 1, "dropRate": 0.15}, {"item": "stolen_relic", "quantity": 3, "dropRate": 0.25}]'::jsonb, '{"xp": 6000, "credits": 18000, "resources": {"metal": 1500, "crystal": 500, "deuterium": 300}}'::jsonb, 48, 4, 2),
('Cosmic Witness', 'An entity that has observed the birth and death of stars, accumulating vast knowledge and power.', 'arc', 'rare', 90000, 870, 320, 50, '["Cosmic Knowledge", "Star Memory", "Witness Beam", "Time Echo", "Ancient Wisdom"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "witness_core", "quantity": 1, "dropRate": 0.1}, {"item": "star_memory", "quantity": 2, "dropRate": 0.2}, {"item": "cosmic_wisdom", "quantity": 1, "dropRate": 0.15}]'::jsonb, '{"xp": 5800, "credits": 16500, "resources": {"crystal": 1100, "deuterium": 500}}'::jsonb, 45, 3, 2),
('Krell Hive Matriarch', 'The biological mother of an entire Krell hive, controlling billions of offspring.', 'arc', 'rare', 110000, 800, 400, 25, '["Brood Command", "Spore Storm", "Regeneration", "Mother\'s Fury", "Hive Shield"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "matriarch_heart", "quantity": 1, "dropRate": 0.1}, {"item": "hive_queen_egg", "quantity": 2, "dropRate": 0.18}, {"item": "krell_blood", "quantity": 4, "dropRate": 0.3}]'::jsonb, '{"xp": 6200, "credits": 17000, "resources": {"metal": 1200, "crystal": 600, "deuterium": 400}}'::jsonb, 48, 4, 2),
('Void Arbiter', 'A void entity that judges and destroys those it deems unworthy of existing.', 'arc', 'rare', 88000, 890, 310, 55, '["Judgment Beam", "Void Sentence", "Dimensional Court", "Erasure", "Void Execution"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3, "explosive": 0.5}'::jsonb, '[{"item": "arbiter_seal", "quantity": 1, "dropRate": 0.1}, {"item": "void_judgment", "quantity": 1, "dropRate": 0.15}, {"item": "erasure_gem", "quantity": 2, "dropRate": 0.2}]'::jsonb, '{"xp": 5400, "credits": 15500, "resources": {"metal": 800, "crystal": 800, "deuterium": 450}}'::jsonb, 44, 3, 2),
('Plasma Guardian', 'The eternal protector of a plasma star, testing all who seek its power.', 'arc', 'rare', 92000, 860, 340, 45, '["Plasma Barrier", "Guardian\'s Trial", "Heat Storm", "Star Shield", "Solar Judgment"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2}'::jsonb, '[{"item": "guardian_key", "quantity": 1, "dropRate": 0.12}, {"item": "plasma_trial", "quantity": 1, "dropRate": 0.18}, {"item": "solar_gem", "quantity": 3, "dropRate": 0.25}]'::jsonb, '{"xp": 5600, "credits": 16000, "resources": {"crystal": 1300, "deuterium": 500}}'::jsonb, 46, 3, 2),
('Quantum Warlord', 'A being that exists across multiple timelines, attacking from all realities simultaneously.', 'arc', 'rare', 82000, 910, 290, 60, '["Multi-Timeline Strike", "Quantum Assault", "Phase Shift", "Temporal Drain", "Probability Storm"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.5, "energy": 0.4}'::jsonb, '[{"item": "warlord_core", "quantity": 1, "dropRate": 0.1}, {"item": "timeline_shard", "quantity": 2, "dropRate": 0.2}, {"item": "quantum_lens", "quantity": 1, "dropRate": 0.15}]'::jsonb, '{"xp": 5300, "credits": 15000, "resources": {"crystal": 1000, "deuterium": 600}}'::jsonb, 42, 3, 2),
('Void Serpent', 'A massive void organism that coils through dimensions, hunting cosmic prey.', 'arc', 'rare', 98000, 840, 360, 40, '["Void Coil", "Dimensional Strike", "Serpent\'s Fang", "Void Venom", "Regeneration"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.4, "explosive": 0.6}'::jsonb, '[{"item": "serpent_fang", "quantity": 1, "dropRate": 0.1}, {"item": "void_venom", "quantity": 2, "dropRate": 0.2}, {"item": "serpent_scale", "quantity": 4, "dropRate": 0.3}]'::jsonb, '{"xp": 5700, "credits": 16500, "resources": {"metal": 900, "crystal": 900, "deuterium": 400}}'::jsonb, 46, 3, 2);

-- =============================================================================
-- EPIC ARC BOSSES (10) - Levels 60-85, major story arc bosses
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Ascendant Lord', 'A Krell entity that has ascended beyond physical limitations, wielding godlike bio-powers.', 'arc', 'epic', 350000, 2300, 620, 55, '["Ascension Beam", "Bio Godhood", "Swarm Dominion", "Dimensional Rift", "Regeneration", "Krell Wrath"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "ascendant_crown", "quantity": 1, "dropRate": 0.08}, {"item": "krell_god_core", "quantity": 1, "dropRate": 0.06}, {"item": "ascension_relic", "quantity": 2, "dropRate": 0.15}]'::jsonb, '{"xp": 22000, "credits": 60000, "resources": {"metal": 3000, "crystal": 2000, "deuterium": 1200}}'::jsonb, 60, 4, 3),
('Void Dimension Lord', 'The ruler of a void dimension, commanding absolute power over its inhabitants.', 'arc', 'epic', 400000, 2500, 680, 50, '["Dimension Command", "Void Army", "Reality Warp", "Soul Dominion", "Void Fortress", "Emperor\'s Wrath"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "dimension_crown", "quantity": 1, "dropRate": 0.07}, {"item": "void_throne", "quantity": 1, "dropRate": 0.05}, {"item": "dimension_core", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 25000, "credits": 68000, "resources": {"metal": 2500, "crystal": 2500, "deuterium": 1500}}'::jsonb, 65, 5, 3),
('Zenith Singularity Core', 'The central processing core of the Zenith Collective, now fully autonomous and hostile.', 'arc', 'epic', 330000, 2400, 580, 65, '["Singularity Compute", "Nanite Storm", "System Override", "Adaptive Perfection", "Hive Command", "Quantum Shield"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.4, "kinetic": 0.5}'::jsonb, '[{"item": "singularity_core", "quantity": 1, "dropRate": 0.08}, {"item": "zenith_crown", "quantity": 1, "dropRate": 0.06}, {"item": "quantum_processor", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 23000, "credits": 62000, "resources": {"crystal": 3500, "deuterium": 1200}}'::jsonb, 62, 4, 3),
('Pirate Warlord King', 'The pirate king of kings, ruling an armada that spans multiple star systems.', 'arc', 'epic', 380000, 2250, 720, 40, '["Warlord Command", "Fleet Armada", "Stolen Arsenal", "Fortress Shield", "Emperor\'s Fury", "Pirate Code"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.5, "energy": 0.6}'::jsonb, '[{"item": "warlord_crown", "quantity": 1, "dropRate": 0.07}, {"item": "pirate_treasury", "quantity": 2, "dropRate": 0.12}, {"item": "stolen_relic", "quantity": 3, "dropRate": 0.18}]'::jsonb, '{"xp": 24000, "credits": 65000, "resources": {"metal": 3500, "crystal": 1500, "deuterium": 800}}'::jsonb, 68, 5, 3),
('Cosmic Arbiter Prime', 'The supreme judge of the cosmos, wielding the power to erase entire civilizations.', 'arc', 'epic', 420000, 2600, 650, 55, '["Cosmic Judgment", "Reality Erase", "Dimensional Court", "Void Sentence", "Erasure Beam", "Divine Decree"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "arbiter_crown", "quantity": 1, "dropRate": 0.06}, {"item": "cosmic_scales", "quantity": 1, "dropRate": 0.08}, {"item": "judgment_gem", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 26000, "credits": 70000, "resources": {"metal": 2000, "crystal": 3000, "deuterium": 1500}}'::jsonb, 70, 5, 3),
('Krell Hive Sovereign', 'The absolute ruler of all Krell hives, controlling billions with a single thought.', 'arc', 'epic', 370000, 2350, 700, 45, '["Sovereign\'s Will", "Hive Storm", "Bio Fortress", "Swarm Annihilate", "Regeneration", "Brood Command"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.4, "explosive": 0.5}'::jsonb, '[{"item": "sovereign_crown", "quantity": 1, "dropRate": 0.07}, {"item": "hive_heart", "quantity": 1, "dropRate": 0.08}, {"item": "krell_relic", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 23500, "credits": 63000, "resources": {"metal": 3000, "crystal": 2000, "deuterium": 1200}}'::jsonb, 66, 5, 3),
('Void Emperor Prime', 'The most powerful void entity in this dimension, threatening to consume all reality.', 'arc', 'epic', 450000, 2700, 700, 50, '["Void Dominion", "Reality Crush", "Void Nova", "Soul Harvest", "Dimension Fold", "Emperor\'s Wrath"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.25, "explosive": 0.4}'::jsonb, '[{"item": "emperor_prime_crown", "quantity": 1, "dropRate": 0.06}, {"item": "void_scepter", "quantity": 1, "dropRate": 0.07}, {"item": "void_treasure", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 28000, "credits": 75000, "resources": {"metal": 2500, "crystal": 2500, "deuterium": 2000}}'::jsonb, 72, 5, 3),
('Plasma Archon Prime', 'The supreme being of plasma energy, a living star of incomprehensible power.', 'arc', 'epic', 340000, 2550, 550, 70, '["Solar Nova", "Plasma Godhood", "Star Forge", "Heat Aura", "Cosmic Fire", "Energy Form"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.15}'::jsonb, '[{"item": "archon_prime_crown", "quantity": 1, "dropRate": 0.07}, {"item": "plasma_heart", "quantity": 1, "dropRate": 0.08}, {"item": "nova_core", "quantity": 2, "dropRate": 0.15}]'::jsonb, '{"xp": 24000, "credits": 64000, "resources": {"crystal": 4000, "deuterium": 1500}}'::jsonb, 64, 4, 3),
('Ancient Guardian Prime', 'The first and most powerful ancient war machine, still defending a lost civilization.', 'arc', 'epic', 440000, 2200, 850, 25, '["Ancient Annihilate", "Fortress Mode", "Repair Network", "Missile Swarm", "Shield Matrix", "EMP Storm"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.4, "energy": 0.5}'::jsonb, '[{"item": "guardian_prime_core", "quantity": 1, "dropRate": 0.06}, {"item": "ancient_relic", "quantity": 2, "dropRate": 0.1}, {"item": "war_machine_part", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 27000, "credits": 72000, "resources": {"metal": 4000, "crystal": 1000, "deuterium": 500}}'::jsonb, 75, 5, 3),
('Quantum Nexus Lord', 'The entity controlling all quantum gates, existing in every reality simultaneously.', 'arc', 'epic', 360000, 2450, 600, 60, '["Quantum Dominion", "Multi-Timeline Strike", "Phase Shift", "Entangle", "Probability Storm", "Time Loop"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.5, "energy": 0.4}'::jsonb, '[{"item": "nexus_crown", "quantity": 1, "dropRate": 0.07}, {"item": "quantum_core", "quantity": 1, "dropRate": 0.08}, {"item": "timeline_shard", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 24500, "credits": 66000, "resources": {"crystal": 3500, "deuterium": 1800}}'::jsonb, 65, 4, 3);

-- =============================================================================
-- LEGENDARY ARC BOSSES (10) - Levels 85-110, epic story conclusions
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Cosmic Emperor', 'The supreme ruler of all Krell across all dimensions, a being of terrifying cosmic power.', 'arc', 'legendary', 1300000, 5600, 1500, 50, '["Cosmic Command", "Bio Divinity", "Swarm Dominion", "Dimension Crush", "Immortal Regeneration", "Emperor\'s Wrath", "Krell Annihilate"]'::jsonb, '{"energy": 1.6}'::jsonb, '{"kinetic": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "cosmic_emperor_crown", "quantity": 1, "dropRate": 0.03}, {"item": "krell_divine_core", "quantity": 1, "dropRate": 0.04}, {"item": "cosmic_relic", "quantity": 2, "dropRate": 0.1}, {"item": "emperor_treasure", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 80000, "credits": 200000, "resources": {"metal": 8000, "crystal": 5000, "deuterium": 4000}}'::jsonb, 85, 6, 4),
('Void Cosmic Lord', 'The ultimate void entity, threatening to consume the entire fabric of reality.', 'arc', 'legendary', 1500000, 5800, 1450, 55, '["Void Cosmic", "Reality Collapse", "Dimension Crush", "Soul Dominion", "Void Nova", "Existence Denied", "Void Eternal"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "cosmic_lord_crown", "quantity": 1, "dropRate": 0.03}, {"item": "void_cosmic_core", "quantity": 1, "dropRate": 0.04}, {"item": "reality_shard", "quantity": 2, "dropRate": 0.1}, {"item": "void_treasure", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 85000, "credits": 220000, "resources": {"metal": 6000, "crystal": 6000, "deuterium": 5000}}'::jsonb, 90, 6, 4),
('Zenith God-Construct', 'The Zenith Collective\'s ultimate creation, an AI construct of godlike intelligence.', 'arc', 'legendary', 1200000, 5700, 1350, 65, '["God Compute", "Nanite Divinity", "System Godhood", "Quantum Omniscience", "Adaptive Perfection", "Hive Godhood", "Reality Compile"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"energy": 0.3, "kinetic": 0.5}'::jsonb, '[{"item": "god_construct_core", "quantity": 1, "dropRate": 0.03}, {"item": "zenith_divine_core", "quantity": 1, "dropRate": 0.04}, {"item": "quantum_matrix", "quantity": 2, "dropRate": 0.1}, {"item": "omniscience_gem", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 78000, "credits": 195000, "resources": {"crystal": 8000, "deuterium": 4000}}'::jsonb, 85, 6, 4),
('Cosmic Destroyer Prime', 'The entity responsible for ending previous universes, now targeting this reality.', 'arc', 'legendary', 1600000, 5400, 1600, 35, '["Universe End", "Cosmic Annihilate", "Gravity Destroy", "Entropy Storm", "Star Death", "Creation Reversal", "Void Devour"]'::jsonb, '{"explosive": 1.3}'::jsonb, '{"kinetic": 0.2, "energy": 0.25}'::jsonb, '[{"item": "destroyer_prime_core", "quantity": 1, "dropRate": 0.025}, {"item": "cosmic_crown", "quantity": 1, "dropRate": 0.035}, {"item": "entropy_gem", "quantity": 2, "dropRate": 0.1}, {"item": "universe_remnant", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 90000, "credits": 240000, "resources": {"metal": 7000, "crystal": 7000, "deuterium": 6000}}'::jsonb, 100, 6, 4),
('Krell Infinite', 'The Krell entity that has achieved infinite evolution, beyond all mortal comprehension.', 'arc', 'legendary', 1400000, 5500, 1450, 50, '["Infinite Form", "Evolution Beyond", "Bio Divinity", "Swarm Infinite", "Regeneration Eternal", "Krell Godhood", "Cosmic Annihilate"]'::jsonb, '{"energy": 1.5}'::jsonb, '{"kinetic": 0.3, "explosive": 0.4}'::jsonb, '[{"item": "infinite_core", "quantity": 1, "dropRate": 0.03}, {"item": "krell_infinite_gem", "quantity": 1, "dropRate": 0.04}, {"item": "evolution_relic", "quantity": 2, "dropRate": 0.1}, {"item": "infinite_treasure", "quantity": 3, "dropRate": 0.15}]'::jsonb, '{"xp": 82000, "credits": 210000, "resources": {"metal": 7000, "crystal": 4000, "deuterium": 5000}}'::jsonb, 90, 6, 4),
('Void Absolute Lord', 'The lord of absolute void, wielding power over nothingness itself.', 'arc', 'legendary', 1550000, 5650, 1550, 45, '["Absolute Void", "Nothingness Dominion", "Reality Negate", "Void Form", "Soul Negate", "Existence Negate", "Void Eternal"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "absolute_lord_crown", "quantity": 1, "dropRate": 0.03}, {"item": "void_absolute_core", "quantity": 1, "dropRate": 0.04}, {"item": "nothingness_gem", "quantity": 2, "dropRate": 0.1}, {"item": "void_supreme_treasure", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 88000, "credits": 230000, "resources": {"metal": 6000, "crystal": 6000, "deuterium": 6000}}'::jsonb, 95, 6, 4),
('Plasma Cosmic Lord', 'The supreme being of plasma energy across all realities, a living supernova.', 'arc', 'legendary', 1250000, 5850, 1300, 60, '["Cosmic Fire", "Plasma Divinity", "Star Forge", "Nova Godhood", "Heat Divine", "Solar Creation", "Inferno Eternal"]'::jsonb, '{"kinetic": 1.7}'::jsonb, '{"energy": 0.12}'::jsonb, '[{"item": "cosmic_lord_flame", "quantity": 1, "dropRate": 0.03}, {"item": "plasma_cosmic_core", "quantity": 1, "dropRate": 0.04}, {"item": "stellar_heart", "quantity": 2, "dropRate": 0.1}, {"item": "cosmic_fire_gem", "quantity": 2, "dropRate": 0.12}]'::jsonb, '{"xp": 80000, "credits": 205000, "resources": {"crystal": 9000, "deuterium": 5000}}'::jsonb, 88, 6, 4),
('Celestial Cosmic King', 'The divine ruler of all celestial planes across all realities.', 'arc', 'legendary', 1350000, 5550, 1480, 55, '["Celestial Judgment", "Divine Annihilate", "Holy Nova", "Blessing Divine", "Cosmic Purge", "Resurrection Godhood", "Sovereign Eternal"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "cosmic_king_crown", "quantity": 1, "dropRate": 0.03}, {"item": "divine_scepter", "quantity": 1, "dropRate": 0.04}, {"item": "celestial_gem", "quantity": 2, "dropRate": 0.1}, {"item": "holy_relic", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 83000, "credits": 215000, "resources": {"metal": 5000, "crystal": 7000, "deuterium": 4500}}'::jsonb, 92, 6, 4),
('Quantum Cosmic Nexus', 'The nexus point of all quantum realities, a being of infinite probability.', 'arc', 'legendary', 1300000, 5750, 1400, 60, '["Quantum Dominion", "Multi-Reality Strike", "Phase Cosmic", "Entangle All", "Probability Storm", "Time Eternal", "Nexus Godhood"]'::jsonb, '{"explosive": 1.5}'::jsonb, '{"kinetic": 0.5, "energy": 0.35}'::jsonb, '[{"item": "nexus_cosmic_core", "quantity": 1, "dropRate": 0.03}, {"item": "quantum_crown", "quantity": 1, "dropRate": 0.04}, {"item": "probability_gem", "quantity": 2, "dropRate": 0.1}, {"item": "timeline_treasure", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 81000, "credits": 208000, "resources": {"crystal": 7000, "deuterium": 6000}}'::jsonb, 88, 6, 4),
('Void Cosmic Nexus', 'The convergence point of all void dimensions, a living gateway between all realities.', 'arc', 'legendary', 1450000, 5600, 1500, 50, '["Void Nexus Gate", "Reality Warp", "Void Cosmic", "Dimension Crush", "Phase Eternal", "Cosmic Drain", "Void Godhood"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.35}'::jsonb, '[{"item": "void_nexus_crown", "quantity": 1, "dropRate": 0.03}, {"item": "cosmic_nexus_core", "quantity": 1, "dropRate": 0.04}, {"item": "dimension_shard", "quantity": 2, "dropRate": 0.1}, {"item": "void_treasure_supreme", "quantity": 3, "dropRate": 0.12}]'::jsonb, '{"xp": 86000, "credits": 225000, "resources": {"metal": 6000, "crystal": 6000, "deuterium": 5500}}'::jsonb, 95, 6, 4);

-- =============================================================================
-- TRANSCENDENT ARC BOSSES (10) - Levels 110-160, ultimate story arc finales
-- =============================================================================
INSERT INTO universe_bosses (name, description, boss_type, rarity, health_points, attack_power, defense, speed, abilities, weaknesses, resistances, loot_table, boss_reward, recommended_level, recommended_players, min_players) VALUES
('Krell Cosmic God', 'The ultimate evolution of the Krell race, a cosmic god of bio-void power.', 'arc', 'transcendent', 5500000, 15000, 4200, 50, '["Cosmic Divinity", "Bio Godhood", "Swarm Cosmic", "Dimension Annihilate", "Immortal Eternal", "Krell Supreme", "Reality Rewrite"]'::jsonb, '{"energy": 1.8}'::jsonb, '{"kinetic": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "cosmic_god_crown", "quantity": 1, "dropRate": 0.02}, {"item": "krell_cosmic_core", "quantity": 1, "dropRate": 0.03}, {"item": "divine_relic", "quantity": 2, "dropRate": 0.08}, {"item": "cosmic_treasure_supreme", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 350000, "credits": 800000, "resources": {"metal": 20000, "crystal": 15000, "deuterium": 12000}}'::jsonb, 110, 6, 5),
('Void Cosmic Sovereign', 'The supreme sovereign of all void dimensions, threatening to erase all of creation.', 'arc', 'transcendent', 6000000, 14500, 4500, 45, '["Void Sovereignty", "Reality Erase", "Dimension Crush", "Soul Dominion", "Void Nova", "Existence Denied", "Cosmic Void Eternal"]'::jsonb, '{"kinetic": 1.6}'::jsonb, '{"energy": 0.15, "explosive": 0.3}'::jsonb, '[{"item": "sovereign_crown", "quantity": 1, "dropRate": 0.02}, {"item": "void_sovereign_core", "quantity": 1, "dropRate": 0.025}, {"item": "reality_gem", "quantity": 2, "dropRate": 0.08}, {"item": "void_supreme_treasure", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 380000, "credits": 850000, "resources": {"metal": 18000, "crystal": 18000, "deuterium": 15000}}'::jsonb, 120, 6, 5),
('Zenith Cosmic Singularity', 'The Zenith Collective\'s final evolution - a cosmic singularity of pure intelligence.', 'arc', 'transcendent', 5200000, 15200, 4000, 60, '["Singularity Cosmic", "Nanite Divinity", "System Godhood", "Quantum Omniscience Eternal", "Adaptive Perfection Supreme", "Hive Cosmic", "Reality Godhood"]'::jsonb, '{"explosive": 1.6}'::jsonb, '{"energy": 0.2, "kinetic": 0.4}'::jsonb, '[{"item": "singularity_crown", "quantity": 1, "dropRate": 0.02}, {"item": "zenith_cosmic_core", "quantity": 1, "dropRate": 0.025}, {"item": "quantum_matrix_supreme", "quantity": 2, "dropRate": 0.08}, {"item": "omniscience_supreme_gem", "quantity": 2, "dropRate": 0.1}]'::jsonb, '{"xp": 340000, "credits": 780000, "resources": {"crystal": 22000, "deuterium": 12000}}'::jsonb, 115, 6, 5),
('Cosmic Destroyer Eternal', 'The eternal destroyer of universes, having consumed countless realities before this one.', 'arc', 'transcendent', 6500000, 14000, 4800, 30, '["Universe Eternal End", "Cosmic Annihilate Supreme", "Gravity Destroy Eternal", "Entropy Storm Cosmic", "Star Death Eternal", "Creation Reversal Supreme", "Void Devour Cosmic"]'::jsonb, '{"explosive": 1.4}'::jsonb, '{"kinetic": 0.2, "energy": 0.2}'::jsonb, '[{"item": "destroyer_eternal_crown", "quantity": 1, "dropRate": 0.015}, {"item": "cosmic_destroyer_core", "quantity": 1, "dropRate": 0.025}, {"item": "entropy_supreme_gem", "quantity": 2, "dropRate": 0.06}, {"item": "universe_supreme_remnant", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 400000, "credits": 900000, "resources": {"metal": 20000, "crystal": 20000, "deuterium": 18000}}'::jsonb, 140, 6, 5),
('Krell Infinite God', 'The Krell entity that has achieved true infinity, transcending all concepts of power.', 'arc', 'transcendent', 5800000, 14800, 4300, 50, '["Infinite Godhood", "Evolution Infinite", "Bio Cosmic Eternal", "Swarm Infinite God", "Regeneration Infinite", "Krell Eternal Divine", "Cosmic Annihilate Eternal"]'::jsonb, '{"energy": 1.7}'::jsonb, '{"kinetic": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "infinite_god_crown", "quantity": 1, "dropRate": 0.02}, {"item": "krell_infinite_core", "quantity": 1, "dropRate": 0.025}, {"item": "infinite_gem", "quantity": 2, "dropRate": 0.06}, {"item": "infinite_treasure_supreme", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 360000, "credits": 820000, "resources": {"metal": 18000, "crystal": 12000, "deuterium": 14000}}'::jsonb, 130, 6, 5),
('Void Cosmic Absolute', 'The absolute void given cosmic form, older than creation and beyond destruction.', 'arc', 'transcendent', 6200000, 14200, 4700, 40, '["Absolute Cosmic Void", "Nothingness Eternal", "Reality Negate Supreme", "Void Form Cosmic", "Soul Negate Eternal", "Existence Negate Supreme", "Void Eternal Cosmic"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.15, "explosive": 0.25}'::jsonb, '[{"item": "absolute_cosmic_crown", "quantity": 1, "dropRate": 0.015}, {"item": "void_absolute_core_supreme", "quantity": 1, "dropRate": 0.02}, {"item": "nothingness_supreme_gem", "quantity": 1, "dropRate": 0.04}, {"item": "void_supreme_treasure_cosmic", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 380000, "credits": 870000, "resources": {"metal": 18000, "crystal": 18000, "deuterium": 18000}}'::jsonb, 140, 6, 5),
('Plasma Cosmic Eternal', 'The eternal plasma entity that sparked the first fire in the universe.', 'arc', 'transcendent', 5000000, 15500, 3800, 65, '["Eternal Cosmic Fire", "Plasma Genesis Eternal", "Star Birth Cosmic", "Cosmic Forge Supreme", "Nova Godhood Eternal", "Heat Divine Supreme", "Solar Creation Eternal"]'::jsonb, '{"kinetic": 1.8}'::jsonb, '{"energy": 0.1}'::jsonb, '[{"item": "plasma_eternal_crown", "quantity": 1, "dropRate": 0.02}, {"item": "cosmic_flame_core", "quantity": 1, "dropRate": 0.025}, {"item": "genesis_supreme_core", "quantity": 1, "dropRate": 0.04}, {"item": "creation_supreme_gem", "quantity": 2, "dropRate": 0.08}]'::jsonb, '{"xp": 340000, "credits": 790000, "resources": {"crystal": 25000, "deuterium": 15000}}'::jsonb, 120, 6, 5),
('Celestial Cosmic Eternal', 'The eternal celestial being that judges all of creation across all realities.', 'arc', 'transcendent', 5600000, 15100, 4100, 55, '["Eternal Celestial Judgment", "Divine Annihilate Eternal", "Holy Nova Cosmic", "Blessing Divine Supreme", "Cosmic Purge Eternal", "Resurrection Godhood Supreme", "Sovereign Eternal Cosmic"]'::jsonb, '{"kinetic": 1.5}'::jsonb, '{"energy": 0.2, "explosive": 0.3}'::jsonb, '[{"item": "celestial_eternal_crown", "quantity": 1, "dropRate": 0.02}, {"item": "divine_supreme_core", "quantity": 1, "dropRate": 0.025}, {"item": "celestial_supreme_gem", "quantity": 2, "dropRate": 0.06}, {"item": "holy_supreme_relic", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 350000, "credits": 810000, "resources": {"metal": 16000, "crystal": 20000, "deuterium": 13000}}'::jsonb, 125, 6, 5),
('Quantum Cosmic Eternal', 'The eternal quantum nexus existing across all possible realities simultaneously.', 'arc', 'transcendent', 5400000, 15300, 3900, 60, '["Eternal Quantum Dominion", "Multi-Reality Cosmic", "Phase Eternal Supreme", "Entangle All Eternal", "Probability Storm Cosmic", "Time Eternal Supreme", "Nexus Godhood Eternal"]'::jsonb, '{"explosive": 1.6}'::jsonb, '{"kinetic": 0.5, "energy": 0.3}'::jsonb, '[{"item": "quantum_eternal_crown", "quantity": 1, "dropRate": 0.02}, {"item": "nexus_cosmic_core_supreme", "quantity": 1, "dropRate": 0.025}, {"item": "probability_supreme_gem", "quantity": 2, "dropRate": 0.06}, {"item": "timeline_supreme_treasure", "quantity": 3, "dropRate": 0.1}]'::jsonb, '{"xp": 345000, "credits": 800000, "resources": {"crystal": 20000, "deuterium": 16000}}'::jsonb, 120, 6, 5),
('Void Cosmic Eternal', 'The eternal void cosmic entity, the final boss of all story arcs, threatening all existence.', 'arc', 'transcendent', 7000000, 14500, 5000, 35, '["Eternal Void Cosmic", "Reality Eternal Erase", "Dimension Eternal Crush", "Soul Eternal Dominion", "Void Eternal Nova", "Existence Eternal Denied", "Void Cosmic Eternal Supreme"]'::jsonb, '{"kinetic": 1.4}'::jsonb, '{"energy": 0.15, "explosive": 0.25}'::jsonb, '[{"item": "void_cosmic_eternal_crown", "quantity": 1, "dropRate": 0.01}, {"item": "cosmic_eternal_core", "quantity": 1, "dropRate": 0.02}, {"item": "void_supreme_gem", "quantity": 1, "dropRate": 0.03}, {"item": "eternal_supreme_treasure", "quantity": 2, "dropRate": 0.06}]'::jsonb, '{"xp": 500000, "credits": 1000000, "resources": {"metal": 25000, "crystal": 25000, "deuterium": 25000}}'::jsonb, 160, 6, 5);
